// =========================================================
// 雅思核心词包 · 第4批（IELTS Batch 4）—— 高频词大幅扩容
// 目标：尽量覆盖雅思 6000 中的高频（基础日常 + 通用进阶）部分。
// 后续仍按 words_ielts5.js … 继续，加载方式不变，自动去重。
// =========================================================
WORDS.push(
  // ---------- 高频动词 / 名词（通用） ----------
  {word:"account", ipa:"/əˈkaʊnt/", pos:"n./v.", zh:"账户；说明", def:"an arrangement with a bank; a report or explanation", example:"I put the money into my bank ___.", pack:"ielts4", level:1},
  {word:"address", ipa:"/əˈdres/", pos:"n./v.", zh:"地址；处理", def:"the place where you live; to deal with a problem", example:"What is your home ___?", pack:"ielts4", level:1},
  {word:"belong", ipa:"/bɪˈlɔːŋ/", pos:"v.", zh:"属于", def:"to be owned by someone or part of a group", example:"This book ___s to me.", pack:"ielts4", level:1},
  {word:"bend", ipa:"/bend/", pos:"v.", zh:"弯曲", def:"to move part of your body or an object into a curve", example:"You need to ___ your knees to lift it.", pack:"ielts4", level:1},
  {word:"cheer", ipa:"/tʃɪr/", pos:"v./n.", zh:"欢呼；加油", def:"to shout to show support or happiness", example:"The fans ___ed for their team.", pack:"ielts4", level:1},
  {word:"command", ipa:"/kəˈmænd/", pos:"v./n.", zh:"命令", def:"to order someone to do something", example:"The captain ___ed the ship to stop.", pack:"ielts4", level:2},
  {word:"compete", ipa:"/kəmˈpiːt/", pos:"v.", zh:"竞争", def:"to try to win against others", example:"Two teams will ___ for the cup.", pack:"ielts4", level:2},
  {word:"concern", ipa:"/kənˈsɜːrn/", pos:"v./n.", zh:"担心；涉及", def:"to worry someone; something you worry about", example:"The news ___ed all the parents.", pack:"ielts4", level:2},
  {word:"conduct", ipa:"/kənˈdʌkt/", pos:"v.", zh:"进行；指挥", def:"to organize and do something; to lead", example:"They ___ed a survey about shopping.", pack:"ielts4", level:2},
  {word:"cook", ipa:"/kʊk/", pos:"v.", zh:"烹饪", def:"to prepare food by heating it", example:"He ___s dinner for the family.", pack:"ielts4", level:1},
  {word:"correct", ipa:"/kəˈrekt/", pos:"v./adj.", zh:"改正；正确的", def:"to fix mistakes; right", example:"Please ___ the wrong answers.", pack:"ielts4", level:1},
  {word:"cross", ipa:"/krɔːs/", pos:"v.", zh:"穿过", def:"to go from one side to the other", example:"Be careful when you ___ the street.", pack:"ielts4", level:1},
  {word:"declare", ipa:"/dɪˈkler/", pos:"v.", zh:"宣布", def:"to say something officially", example:"The country ___d independence.", pack:"ielts4", level:2},
  {word:"decorate", ipa:"/ˈdekəreɪt/", pos:"v.", zh:"装饰", def:"to make something look nice with colors or objects", example:"We ___d the room for the party.", pack:"ielts4", level:2},
  {word:"defeat", ipa:"/dɪˈfiːt/", pos:"v./n.", zh:"打败；失败", def:"to win against someone", example:"Our team ___ed the champions.", pack:"ielts4", level:2},
  {word:"defend", ipa:"/dɪˈfend/", pos:"v.", zh:"保卫；辩护", def:"to protect someone or something", example:"Soldiers ___ the city walls.", pack:"ielts4", level:2},
  {word:"design", ipa:"/dɪˈzaɪn/", pos:"v./n.", zh:"设计", def:"to plan how something will look or work", example:"She ___ed the new logo.", pack:"ielts4", level:1},
  {word:"enjoy", ipa:"/ɪnˈdʒɔɪ/", pos:"v.", zh:"享受", def:"to get pleasure from something", example:"I really ___ reading.", pack:"ielts4", level:1},
  {word:"entertain", ipa:"/ˌentərˈteɪn/", pos:"v.", zh:"娱乐；招待", def:"to make people laugh or enjoy themselves", example:"The clown ___ed the children.", pack:"ielts4", level:2},
  {word:"explore", ipa:"/ɪkˈsplɔːr/", pos:"v.", zh:"探索", def:"to travel around to find out about a place", example:"We ___d the old city on foot.", pack:"ielts4", level:2},
  {word:"fail", ipa:"/feɪl/", pos:"v.", zh:"失败", def:"to not succeed", example:"He ___ed the driving test twice.", pack:"ielts4", level:1},
  {word:"feed", ipa:"/fiːd/", pos:"v.", zh:"喂养", def:"to give food to someone or an animal", example:"She ___s the cat every morning.", pack:"ielts4", level:1},
  {word:"fight", ipa:"/faɪt/", pos:"v./n.", zh:"打架；斗争", def:"to use force against someone; a battle", example:"The two boys ___ over the ball.", pack:"ielts4", level:1},
  {word:"figure", ipa:"/ˈfɪɡjər/", pos:"n./v.", zh:"数字；人物；弄明白", def:"a number; a person; to work something out", example:"I can't ___ out this puzzle.", pack:"ielts4", level:2},
  {word:"fill", ipa:"/fɪl/", pos:"v.", zh:"填满", def:"to make something full", example:"Please ___ the glass with water.", pack:"ielts4", level:1},
  {word:"fix", ipa:"/fɪks/", pos:"v.", zh:"修理；固定", def:"to repair something; to make something stay in place", example:"Dad ___ed my bike.", pack:"ielts4", level:1},
  {word:"follow", ipa:"/ˈfɑːloʊ/", pos:"v.", zh:"跟随", def:"to go after someone; to understand", example:"The dog ___ed me home.", pack:"ielts4", level:1},
  {word:"force", ipa:"/fɔːrs/", pos:"v./n.", zh:"强迫；力量", def:"to make someone do something", example:"They ___d the door open.", pack:"ielts4", level:2},
  {word:"gain", ipa:"/ɡeɪn/", pos:"v.", zh:"获得", def:"to get something useful or good", example:"She ___ed weight over the winter.", pack:"ielts4", level:2},
  {word:"gather", ipa:"/ˈɡæðər/", pos:"v.", zh:"聚集", def:"to come together in a group", example:"Crowds ___ed to watch the show.", pack:"ielts4", level:2},
  {word:"guard", ipa:"/ɡɑːrd/", pos:"v./n.", zh:"守卫", def:"to protect a person or place", example:"Dogs ___ the house at night.", pack:"ielts4", level:2},
  {word:"handle", ipa:"/ˈhændl/", pos:"v.", zh:"处理", def:"to deal with a situation or thing", example:"She can ___ difficult customers.", pack:"ielts4", level:2},
  {word:"happen", ipa:"/ˈhæpən/", pos:"v.", zh:"发生", def:"to take place", example:"What ___ed at the party?", pack:"ielts4", level:1},
  {word:"help", ipa:"/help/", pos:"v./n.", zh:"帮助", def:"to make something easier for someone", example:"Can you ___ me carry this box?", pack:"ielts4", level:1},
  {word:"hide", ipa:"/haɪd/", pos:"v.", zh:"隐藏", def:"to put something where it cannot be seen", example:"The cat ___ under the bed.", pack:"ielts4", level:1},
  {word:"hurry", ipa:"/ˈhɜːri/", pos:"v.", zh:"赶紧", def:"to move or do something quickly", example:"We must ___ or we'll be late.", pack:"ielts4", level:1},
  {word:"imagine", ipa:"/ɪˈmædʒɪn/", pos:"v.", zh:"想象", def:"to form a picture in your mind", example:"Can you ___ living on the moon?", pack:"ielts4", level:1},
  {word:"inform", ipa:"/ɪnˈfɔːrm/", pos:"v.", zh:"通知", def:"to tell someone facts", example:"Please ___ us of any changes.", pack:"ielts4", level:2},
  {word:"insist", ipa:"/ɪnˈsɪst/", pos:"v.", zh:"坚持", def:"to say firmly that something is true or must happen", example:"He ___s on paying for dinner.", pack:"ielts4", level:2},
  {word:"invent", ipa:"/ɪnˈvent/", pos:"v.", zh:"发明", def:"to make something new that did not exist before", example:"Who ___ed the telephone?", pack:"ielts4", level:2},
  {word:"invite", ipa:"/ɪnˈvaɪt/", pos:"v.", zh:"邀请", def:"to ask someone to come to an event", example:"They ___d us to the wedding.", pack:"ielts4", level:1},
  {word:"join", ipa:"/dʒɔɪn/", pos:"v.", zh:"加入；连接", def:"to become a member; to connect parts", example:"I want to ___ the music club.", pack:"ielts4", level:1},
  {word:"keep", ipa:"/kiːp/", pos:"v.", zh:"保持；保存", def:"to continue to have or do something", example:"Please ___ the change.", pack:"ielts4", level:1},
  {word:"kill", ipa:"/kɪl/", pos:"v.", zh:"杀死", def:"to make a person or animal die", example:"The cold weather ___ed the plants.", pack:"ielts4", level:1},
  {word:"knock", ipa:"/nɑːk/", pos:"v.", zh:"敲", def:"to hit a door to make a sound", example:"Please ___ before you come in.", pack:"ielts4", level:1},
  {word:"lay", ipa:"/leɪ/", pos:"v.", zh:"放置", def:"to put something down flat", example:"___ the books on the table.", pack:"ielts4", level:2},
  {word:"lead", ipa:"/liːd/", pos:"v.", zh:"带领", def:"to go in front of a group", example:"She ___s the research team.", pack:"ielts4", level:2},
  {word:"learn", ipa:"/lɜːrn/", pos:"v.", zh:"学习", def:"to get knowledge or a skill", example:"Children ___ fast.", pack:"ielts4", level:1},
  {word:"lift", ipa:"/lɪft/", pos:"v.", zh:"举起", def:"to raise something up", example:"He ___ed the heavy box easily.", pack:"ielts4", level:1},
  {word:"limit", ipa:"/ˈlɪmɪt/", pos:"v./n.", zh:"限制", def:"to stop something from going over a point", example:"Speed is ___ed on this road.", pack:"ielts4", level:2},
  {word:"locate", ipa:"/ˈloʊkeɪt/", pos:"v.", zh:"找到位置", def:"to find where something is", example:"I can't ___ the hotel on the map.", pack:"ielts4", level:3},
  {word:"match", ipa:"/mætʃ/", pos:"v./n.", zh:"匹配；比赛", def:"to be the same as something; a game", example:"The socks don't ___ each other.", pack:"ielts4", level:1},
  {word:"measure", ipa:"/ˈmeʒər/", pos:"v.", zh:"测量", def:"to find the size or amount of something", example:"We ___d the room before buying the carpet.", pack:"ielts4", level:2},
  {word:"mix", ipa:"/mɪks/", pos:"v.", zh:"混合", def:"to put different things together", example:"___ the paint with water.", pack:"ielts4", level:1},
  {word:"move", ipa:"/muːv/", pos:"v.", zh:"移动", def:"to change place or position", example:"Please ___ your car.", pack:"ielts4", level:1},
  {word:"notice", ipa:"/ˈnoʊtɪs/", pos:"v./n.", zh:"注意到；通知", def:"to see and pay attention to something", example:"I didn't ___ the sign.", pack:"ielts4", level:2},
  {word:"obey", ipa:"/əˈbeɪ/", pos:"v.", zh:"服从", def:"to do what someone tells you", example:"Drivers must ___ the traffic rules.", pack:"ielts4", level:2},
  {word:"observe", ipa:"/əbˈzɜːrv/", pos:"v.", zh:"观察", def:"to watch something carefully", example:"Scientists ___ the birds all day.", pack:"ielts4", level:2},
  {word:"order", ipa:"/ˈɔːrdər/", pos:"v./n.", zh:"点餐；命令；顺序", def:"to ask for food in a restaurant; to command", example:"Let's ___ two coffees.", pack:"ielts4", level:1},
  {word:"organize", ipa:"/ˈɔːrɡənaɪz/", pos:"v.", zh:"组织", def:"to plan and arrange something", example:"She ___d a party for her mother.", pack:"ielts4", level:2},
  {word:"overcome", ipa:"/ˌoʊvərˈkʌm/", pos:"v.", zh:"克服", def:"to succeed in dealing with a problem", example:"He ___ his fear of flying.", pack:"ielts4", level:3},
  {word:"perform", ipa:"/pərˈfɔːrm/", pos:"v.", zh:"表演；执行", def:"to act, sing or play in front of people", example:"She ___ed a song on stage.", pack:"ielts4", level:2},
  {word:"persuade", ipa:"/pərˈsweɪd/", pos:"v.", zh:"说服", def:"to make someone agree by giving reasons", example:"He ___d me to stay longer.", pack:"ielts4", level:3},
  {word:"place", ipa:"/pleɪs/", pos:"v./n.", zh:"放置；地方", def:"to put something somewhere", example:"___ the cup on the table.", pack:"ielts4", level:1},
  {word:"plan", ipa:"/plæn/", pos:"v./n.", zh:"计划", def:"to decide what you will do", example:"We are planning a trip to the coast.", pack:"ielts4", level:1},
  {word:"prefer", ipa:"/prɪˈfɜːr/", pos:"v.", zh:"更喜欢", def:"to like one thing more than another", example:"I ___ tea to coffee.", pack:"ielts4", level:1},
  {word:"prepare", ipa:"/prɪˈper/", pos:"v.", zh:"准备", def:"to make something ready", example:"She is preparing for the exam.", pack:"ielts4", level:1},
  {word:"present", ipa:"/prɪˈzent/", pos:"v.", zh:"展示；赠送", def:"to show or give something officially", example:"He ___ed his ideas to the team.", pack:"ielts4", level:2},
  {word:"pretend", ipa:"/prɪˈtend/", pos:"v.", zh:"假装", def:"to act as if something is true when it is not", example:"Don't ___ to be sick.", pack:"ielts4", level:2},
  {word:"produce", ipa:"/prəˈduːs/", pos:"v.", zh:"生产", def:"to make or grow something", example:"The farm ___s fresh milk.", pack:"ielts4", level:1},
  {word:"promise", ipa:"/ˈprɑːmɪs/", pos:"v./n.", zh:"承诺", def:"to say you will definitely do something", example:"He ___d to call me back.", pack:"ielts4", level:1},
  {word:"pronounce", ipa:"/prəˈnaʊns/", pos:"v.", zh:"发音", def:"to say a word or letter in a certain way", example:"How do you ___ this word?", pack:"ielts4", level:2},
  {word:"prove", ipa:"/pruːv/", pos:"v.", zh:"证明", def:"to show that something is true", example:"Can you ___ that you were here?", pack:"ielts4", level:2},
  {word:"publish", ipa:"/ˈpʌblɪʃ/", pos:"v.", zh:"出版", def:"to print a book or article for people to read", example:"She ___ed her first novel at 30.", pack:"ielts4", level:3},
  {word:"pull", ipa:"/pʊl/", pos:"v.", zh:"拉", def:"to move something towards you", example:"___ the door to open it.", pack:"ielts4", level:1},
  {word:"punish", ipa:"/ˈpʌnɪʃ/", pos:"v.", zh:"惩罚", def:"to make someone suffer for doing wrong", example:"The teacher ___ed the late students.", pack:"ielts4", level:2},
  {word:"push", ipa:"/pʊʃ/", pos:"v.", zh:"推", def:"to move something away from you", example:"___ the button to start.", pack:"ielts4", level:1},
  {word:"raise", ipa:"/reɪz/", pos:"v.", zh:"举起；提高；抚养", def:"to lift up; to increase; to bring up children", example:"They ___d prices last week.", pack:"ielts4", level:1},
  {word:"reach", ipa:"/riːtʃ/", pos:"v.", zh:"到达；够到", def:"to arrive at a place", example:"We ___ed the station at six.", pack:"ielts4", level:1},
  {word:"realize", ipa:"/ˈriːəlaɪz/", pos:"v.", zh:"意识到", def:"to understand something suddenly", example:"I didn't ___ how late it was.", pack:"ielts4", level:2},
  {word:"receive", ipa:"/rɪˈsiːv/", pos:"v.", zh:"收到", def:"to get something given or sent to you", example:"I ___d your letter yesterday.", pack:"ielts4", level:1},
  {word:"recommend", ipa:"/ˌrekəˈmend/", pos:"v.", zh:"推荐", def:"to suggest that something is good", example:"I ___ this restaurant.", pack:"ielts4", level:2},
  {word:"record", ipa:"/rɪˈkɔːrd/", pos:"v./n.", zh:"记录", def:"to write or save information; a stored piece of data", example:"She ___ed the meeting on her phone.", pack:"ielts4", level:1},
  {word:"refer", ipa:"/rɪˈfɜːr/", pos:"v.", zh:"提到；参考", def:"to mention something; to look at information", example:"Please ___ to page ten.", pack:"ielts4", level:2},
  {word:"refuse", ipa:"/rɪˈfjuːz/", pos:"v.", zh:"拒绝", def:"to say no to something", example:"She ___d to sign the paper.", pack:"ielts4", level:1},
  {word:"regard", ipa:"/rɪˈɡɑːrd/", pos:"v.", zh:"看待", def:"to think of someone or something in a certain way", example:"He is ___ed as a genius.", pack:"ielts4", level:3},
  {word:"register", ipa:"/ˈredʒɪstər/", pos:"v.", zh:"注册；登记", def:"to put your name on an official list", example:"Please ___ for the course online.", pack:"ielts4", level:2},
  {word:"relate", ipa:"/rɪˈleɪt/", pos:"v.", zh:"相关", def:"to have a connection with something", example:"These facts ___ to our problem.", pack:"ielts4", level:2},
  {word:"release", ipa:"/rɪˈliːs/", pos:"v.", zh:"发布；释放", def:"to let someone go free; to make public", example:"The company ___d a new app.", pack:"ielts4", level:2},
  {word:"remain", ipa:"/rɪˈmeɪn/", pos:"v.", zh:"保持；留下", def:"to stay in the same state or place", example:"The door ___ed closed.", pack:"ielts4", level:2},
  {word:"remove", ipa:"/rɪˈmuːv/", pos:"v.", zh:"移除", def:"to take something away", example:"Please ___ your shoes at the door.", pack:"ielts4", level:1},
  {word:"repeat", ipa:"/rɪˈpiːt/", pos:"v.", zh:"重复", def:"to say or do something again", example:"Could you ___ the question?", pack:"ielts4", level:1},
  {word:"replace", ipa:"/rɪˈpleɪs/", pos:"v.", zh:"替换", def:"to put something new in the place of old", example:"We ___d the broken window.", pack:"ielts4", level:2},
  {word:"reply", ipa:"/rɪˈplaɪ/", pos:"v./n.", zh:"回复", def:"to answer someone", example:"She hasn't ___ed to my message.", pack:"ielts4", level:1},
  {word:"report", ipa:"/rɪˈpɔːrt/", pos:"v./n.", zh:"报告", def:"to tell people about news or facts", example:"The news ___ed a big storm.", pack:"ielts4", level:1},
  {word:"respect", ipa:"/rɪˈspekt/", pos:"v./n.", zh:"尊重", def:"to admire someone and treat them well", example:"Students should ___ their teachers.", pack:"ielts4", level:1},
  {word:"respond", ipa:"/rɪˈspɑːnd/", pos:"v.", zh:"回应", def:"to answer or react", example:"He ___ed to the news with a smile.", pack:"ielts4", level:2},
  {word:"rest", ipa:"/rest/", pos:"v./n.", zh:"休息", def:"to stop working or moving to relax", example:"You should ___ after the long trip.", pack:"ielts4", level:1},
  {word:"review", ipa:"/rɪˈvjuː/", pos:"v./n.", zh:"复习；评论", def:"to study again; to give an opinion of something", example:"Let's ___ today's words.", pack:"ielts4", level:1},
  {word:"reward", ipa:"/rɪˈwɔːrd/", pos:"n./v.", zh:"奖励", def:"something given for good work", example:"Hard work brings its own ___.", pack:"ielts4", level:2},
  {word:"ruin", ipa:"/ˈruːɪn/", pos:"v.", zh:"毁掉", def:"to spoil or destroy something", example:"The rain ___ed our picnic.", pack:"ielts4", level:2},
  {word:"satisfy", ipa:"/ˈsætɪsfaɪ/", pos:"v.", zh:"使满意", def:"to make someone happy or pleased", example:"The meal ___ed all the guests.", pack:"ielts4", level:2},
  {word:"save", ipa:"/seɪv/", pos:"v.", zh:"节省；拯救", def:"to keep money; to rescue someone", example:"She ___s money for a new bike.", pack:"ielts4", level:1},
  {word:"search", ipa:"/sɜːrtʃ/", pos:"v./n.", zh:"搜寻", def:"to look carefully for something", example:"They ___ed the room for the key.", pack:"ielts4", level:1},
  {word:"select", ipa:"/sɪˈlekt/", pos:"v.", zh:"选择", def:"to choose carefully from a group", example:"Please ___ a color from the list.", pack:"ielts4", level:2},
  {word:"serve", ipa:"/sɜːrv/", pos:"v.", zh:"服务；端上", def:"to give food or help to people", example:"They ___ dinner at seven.", pack:"ielts4", level:2},
  {word:"shout", ipa:"/ʃaʊt/", pos:"v.", zh:"喊叫", def:"to speak very loudly", example:"Don't ___ at the children.", pack:"ielts4", level:1},
  {word:"show", ipa:"/ʃoʊ/", pos:"v.", zh:"展示", def:"to let someone see something", example:"Can you ___ me the way?", pack:"ielts4", level:1},
  {word:"solve", ipa:"/sɑːlv/", pos:"v.", zh:"解决", def:"to find the answer to a problem", example:"We solved the puzzle together.", pack:"ielts4", level:1},
  {word:"support", ipa:"/səˈpɔːrt/", pos:"v./n.", zh:"支持", def:"to help someone or something", example:"My family ___s my decision.", pack:"ielts4", level:2},
  {word:"survive", ipa:"/sərˈvaɪv/", pos:"v.", zh:"存活", def:"to continue to live after danger", example:"Only a few plants ___d the winter.", pack:"ielts4", level:3},
  {word:"suspect", ipa:"/səˈspekt/", pos:"v.", zh:"怀疑", def:"to think something is probably true or wrong", example:"I ___ he is lying.", pack:"ielts4", level:3},
  {word:"teach", ipa:"/tiːtʃ/", pos:"v.", zh:"教", def:"to help someone learn something", example:"She ___es math at a school.", pack:"ielts4", level:1},
  {word:"translate", ipa:"/trænzˈleɪt/", pos:"v.", zh:"翻译", def:"to change words into another language", example:"Can you ___ this into English?", pack:"ielts4", level:2},
  {word:"trust", ipa:"/trʌst/", pos:"v./n.", zh:"信任", def:"to believe that someone is good and honest", example:"I ___ her completely.", pack:"ielts4", level:2},
  {word:"understand", ipa:"/ˌʌndərˈstænd/", pos:"v.", zh:"理解", def:"to know the meaning of something", example:"Now I ___ the problem.", pack:"ielts4", level:1},
  {word:"urge", ipa:"/ɜːrdʒ/", pos:"v.", zh:"力劝", def:"to strongly advise someone to do something", example:"Doctors ___ people to exercise.", pack:"ielts4", level:3},
  {word:"value", ipa:"/ˈvæljuː/", pos:"v./n.", zh:"重视；价值", def:"to think something is important", example:"We ___ our customers.", pack:"ielts4", level:1},
  {word:"warn", ipa:"/wɔːrn/", pos:"v.", zh:"警告", def:"to tell someone about danger", example:"They ___ed us about the icy road.", pack:"ielts4", level:2},
  {word:"wear", ipa:"/wer/", pos:"v.", zh:"穿；戴", def:"to have clothes on your body", example:"She always ___s a red coat.", pack:"ielts4", level:1},
  {word:"wonder", ipa:"/ˈwʌndər/", pos:"v.", zh:"想知道；惊讶", def:"to want to know something", example:"I ___ where she went.", pack:"ielts4", level:1},
  {word:"worry", ipa:"/ˈwɜːri/", pos:"v./n.", zh:"担心", def:"to feel upset because of problems", example:"Don't ___ about small things.", pack:"ielts4", level:1},
  {word:"ability", ipa:"/əˈbɪləti/", pos:"n.", zh:"能力", def:"the skill or power to do something", example:"She has the ___ to lead people.", pack:"ielts4", level:1},
  {word:"accident", ipa:"/ˈæksɪdənt/", pos:"n.", zh:"事故", def:"a bad event that happens by chance", example:"He had a car ___ on the highway.", pack:"ielts4", level:1},
  {word:"advertisement", ipa:"/ˌædvərˈtaɪzmənt/", pos:"n.", zh:"广告", def:"a notice that tells people about a product", example:"The ___ was on every website.", pack:"ielts4", level:2},
  {word:"agreement", ipa:"/əˈɡriːmənt/", pos:"n.", zh:"协议；同意", def:"an arrangement that people accept", example:"Both sides signed the ___.", pack:"ielts4", level:2},
  {word:"ambition", ipa:"/æmˈbɪʃn/", pos:"n.", zh:"抱负", def:"a strong wish to succeed", example:"Her ___ is to become a doctor.", pack:"ielts4", level:2},
  {word:"ancestor", ipa:"/ˈænsestər/", pos:"n.", zh:"祖先", def:"a family member from long ago", example:"Our ___s came from the north.", pack:"ielts4", level:3},
  {word:"anger", ipa:"/ˈæŋɡər/", pos:"n.", zh:"愤怒", def:"the strong feeling you have when something is unfair", example:"He couldn't hide his ___.", pack:"ielts4", level:1},
  {word:"appetite", ipa:"/ˈæpɪtaɪt/", pos:"n.", zh:"食欲", def:"the wish to eat food", example:"Exercise gives me a good ___.", pack:"ielts4", level:2},
  {word:"arrival", ipa:"/əˈraɪvl/", pos:"n.", zh:"到达", def:"the act of reaching a place", example:"Her ___ was a big surprise.", pack:"ielts4", level:2},
  {word:"attention", ipa:"/əˈtenʃn/", pos:"n.", zh:"注意", def:"the act of watching or listening carefully", example:"Please pay ___ to the screen.", pack:"ielts4", level:1},
  {word:"background", ipa:"/ˈbækɡraʊnd/", pos:"n.", zh:"背景", def:"the things behind a person or situation", example:"She comes from a poor ___.", pack:"ielts4", level:2},
  {word:"behavior", ipa:"/bɪˈheɪvjər/", pos:"n.", zh:"行为", def:"the way a person acts", example:"His ___ in class improved.", pack:"ielts4", level:1},
  {word:"belief", ipa:"/bɪˈliːf/", pos:"n.", zh:"信念", def:"a strong feeling that something is true", example:"Her ___ in hard work never changed.", pack:"ielts4", level:2},
  {word:"billion", ipa:"/ˈbɪljən/", pos:"num.", zh:"十亿", def:"the number 1,000,000,000", example:"The world has over eight ___ people.", pack:"ielts4", level:2},
  {word:"birth", ipa:"/bɜːrθ/", pos:"n.", zh:"出生", def:"the time when a baby comes out of its mother", example:"She has celebrated her ___day today.", pack:"ielts4", level:1},
  {word:"brain", ipa:"/breɪn/", pos:"n.", zh:"大脑", def:"the organ in your head that thinks", example:"The ___ needs sleep to work well.", pack:"ielts4", level:1},
  {word:"branch", ipa:"/bræntʃ/", pos:"n.", zh:"树枝；分部", def:"a part of a tree or an organization", example:"The bank has a ___ in town.", pack:"ielts4", level:2},
  {word:"breath", ipa:"/breθ/", pos:"n.", zh:"呼吸", def:"the air you take in and out", example:"Take a deep ___ before you speak.", pack:"ielts4", level:1},
  {word:"brotherhood", ipa:"/ˈbrʌðərhʊd/", pos:"n.", zh:"兄弟情谊", def:"the feeling of friendship between people", example:"They built a strong ___.", pack:"ielts4", level:3},
  {word:"burden", ipa:"/ˈbɜːrdn/", pos:"n.", zh:"负担", def:"something heavy or difficult to carry or deal with", example:"Debt became a huge ___ for him.", pack:"ielts4", level:3},
  {word:"camp", ipa:"/kæmp/", pos:"n./v.", zh:"营地；露营", def:"a place with tents; to stay in tents", example:"We ___ed by the lake.", pack:"ielts4", level:1},
  {word:"capital", ipa:"/ˈkæpɪtl/", pos:"n./adj.", zh:"首都；资金", def:"the main city of a country; money for business", example:"Beijing is the ___ of China.", pack:"ielts4", level:1},
  {word:"case", ipa:"/keɪs/", pos:"n.", zh:"情况；案例", def:"an example of something; a situation", example:"In this ___, we should wait.", pack:"ielts4", level:1},
  {word:"century", ipa:"/ˈsentʃəri/", pos:"n.", zh:"世纪", def:"a period of one hundred years", example:"The building is from the 19th ___.", pack:"ielts4", level:1},
  {word:"ceremony", ipa:"/ˈserəmoʊni/", pos:"n.", zh:"典礼", def:"a formal event to celebrate something", example:"The opening ___ starts at nine.", pack:"ielts4", level:2},
  {word:"character", ipa:"/ˈkærəktər/", pos:"n.", zh:"性格；角色", def:"the personality of a person; a person in a story", example:"She is a kind ___.", pack:"ielts4", level:2},
  {word:"choice", ipa:"/tʃɔɪs/", pos:"n.", zh:"选择", def:"the act of picking one thing", example:"You have a ___: tea or coffee?", pack:"ielts4", level:1},
  {word:"citizenry", ipa:"/ˈsɪtɪzənri/", pos:"n.", zh:"全体公民", def:"all the citizens of a place", example:"The ___ voted for change.", pack:"ielts4", level:4},
  {word:"companion", ipa:"/kəmˈpænjən/", pos:"n.", zh:"同伴", def:"a person who goes with you", example:"My dog is my best ___.", pack:"ielts4", level:3},
  {word:"connection", ipa:"/kəˈnekʃn/", pos:"n.", zh:"联系", def:"the state of being joined or related", example:"There is a ___ between diet and health.", pack:"ielts4", level:2},
  {word:"cooperation", ipa:"/koʊˌɑːpəˈreɪʃn/", pos:"n.", zh:"合作", def:"working together for a goal", example:"The project needs everyone's ___.", pack:"ielts4", level:3},
  {word:"creation", ipa:"/kriˈeɪʃn/", pos:"n.", zh:"创造", def:"the act of making something new", example:"The ___ of the app took two years.", pack:"ielts4", level:3},
  {word:"danger", ipa:"/ˈdeɪndʒər/", pos:"n.", zh:"危险", def:"the possibility of harm or death", example:"The sign warns of ___.", pack:"ielts4", level:1},
  {word:"decision", ipa:"/dɪˈsɪʒn/", pos:"n.", zh:"决定", def:"a choice you make after thinking", example:"It was a difficult ___.", pack:"ielts4", level:1},
  {word:"description", ipa:"/dɪˈskrɪpʃn/", pos:"n.", zh:"描述", def:"words that say what something is like", example:"Give me a ___ of the thief.", pack:"ielts4", level:2},
  {word:"detail", ipa:"/ˈdiːteɪl/", pos:"n.", zh:"细节", def:"a small piece of information", example:"Please tell me every ___.", pack:"ielts4", level:1},
  {word:"development", ipa:"/dɪˈveləpmənt/", pos:"n.", zh:"发展", def:"the process of growing or improving", example:"The ___ of the city took decades.", pack:"ielts4", level:2},
  {word:"difference", ipa:"/ˈdɪfrəns/", pos:"n.", zh:"差别", def:"the way things are not the same", example:"There is a big ___ in price.", pack:"ielts4", level:1},
  {word:"difficulty", ipa:"/ˈdɪfɪkəlti/", pos:"n.", zh:"困难", def:"a problem that is hard to deal with", example:"They had ___, but they succeeded.", pack:"ielts4", level:1},
  {word:"direction", ipa:"/dəˈrekʃn/", pos:"n.", zh:"方向", def:"the way someone or something moves or points", example:"We walked in the wrong ___.", pack:"ielts4", level:1},
  {word:"discovery", ipa:"/dɪˈskʌvəri/", pos:"n.", zh:"发现", def:"the act of finding something new", example:"The ___ of the cave amazed everyone.", pack:"ielts4", level:3},
  {word:"discussion", ipa:"/dɪˈskʌʃn/", pos:"n.", zh:"讨论", def:"a talk about a topic", example:"We had a long ___ about the plan.", pack:"ielts4", level:2},
  {word:"duty", ipa:"/ˈduːti/", pos:"n.", zh:"责任", def:"something you must do", example:"It is my ___ to help you.", pack:"ielts4", level:2},
  {word:"education", ipa:"/ˌedʒuˈkeɪʃn/", pos:"n.", zh:"教育", def:"the process of teaching and learning", example:"___ opens many doors.", pack:"ielts4", level:1},
  {word:"emergency", ipa:"/ɪˈmɜːrdʒənsi/", pos:"n.", zh:"紧急情况", def:"a sudden dangerous situation", example:"Call 911 in an ___.", pack:"ielts4", level:2},
  {word:"enemy", ipa:"/ˈenəmi/", pos:"n.", zh:"敌人", def:"a person who hates or fights you", example:"The two countries were ___.", pack:"ielts4", level:1},
  {word:"equipment", ipa:"/ɪˈkwɪpmənt/", pos:"n.", zh:"设备", def:"the tools and machines needed for a task", example:"The gym has modern ___.", pack:"ielts4", level:3},
  {word:"example", ipa:"/ɪɡˈzæmpl/", pos:"n.", zh:"例子", def:"something that shows how a thing is done", example:"Give me an ___ of a mammal.", pack:"ielts4", level:1},
  {word:"excellence", ipa:"/ˈeksələns/", pos:"n.", zh:"卓越", def:"the quality of being very good", example:"The school prizes ___.", pack:"ielts4", level:4},
  {word:"expert", ipa:"/ˈekspɜːrt/", pos:"n.", zh:"专家", def:"a person with great knowledge of a subject", example:"He is an ___ on birds.", pack:"ielts4", level:2},
  {word:"failure", ipa:"/ˈfeɪljər/", pos:"n.", zh:"失败", def:"the state of not succeeding", example:"___ taught him to work harder.", pack:"ielts4", level:2},
  {word:"fame", ipa:"/feɪm/", pos:"n.", zh:"名声", def:"the state of being known by many people", example:"The singer found ___ overnight.", pack:"ielts4", level:2},
  {word:"feature", ipa:"/ˈfiːtʃər/", pos:"n.", zh:"特点；功能", def:"an important part or quality of something", example:"The phone has a new safety ___.", pack:"ielts4", level:2},
  {word:"feeling", ipa:"/ˈfiːlɪŋ/", pos:"n.", zh:"感觉", def:"an emotion or the sense of touch", example:"I have a good ___ about this.", pack:"ielts4", level:1},
  {word:"fiction", ipa:"/ˈfɪkʃn/", pos:"n.", zh:"小说（虚构）", def:"stories about imagined events", example:"She prefers reading ___ to news.", pack:"ielts4", level:2},
  {word:"field", ipa:"/fiːld/", pos:"n.", zh:"田野；领域", def:"an open area of land; an area of study", example:"She works in the ___ of medicine.", pack:"ielts4", level:1},
  {word:"freedom", ipa:"/ˈfriːdəm/", pos:"n.", zh:"自由", def:"the state of being free", example:"People fought for their ___.", pack:"ielts4", level:1},
  {word:"friendship", ipa:"/ˈfrendʃɪp/", pos:"n.", zh:"友谊", def:"the state of being friends", example:"Their ___ lasted for years.", pack:"ielts4", level:1},
  {word:"future", ipa:"/ˈfjuːtʃər/", pos:"n.", zh:"未来", def:"the time that will come after now", example:"We should plan for the ___.", pack:"ielts4", level:1},
  {word:"gender", ipa:"/ˈdʒendər/", pos:"n.", zh:"性别", def:"being male or female", example:"The form asks about your ___.", pack:"ielts4", level:3},
  {word:"goal", ipa:"/ɡoʊl/", pos:"n.", zh:"目标", def:"something you want to achieve", example:"My ___ is to finish the book.", pack:"ielts4", level:1},
  {word:"growth", ipa:"/ɡroʊθ/", pos:"n.", zh:"增长；成长", def:"the process of growing", example:"The city saw fast ___.", pack:"ielts4", level:2},
  {word:"happiness", ipa:"/ˈhæpinəs/", pos:"n.", zh:"幸福", def:"the feeling of being happy", example:"Money cannot buy ___.", pack:"ielts4", level:1},
  {word:"health", ipa:"/helθ/", pos:"n.", zh:"健康", def:"the condition of your body and mind", example:"Exercise is good for your ___.", pack:"ielts4", level:1},
  {word:"history", ipa:"/ˈhɪstri/", pos:"n.", zh:"历史", def:"all past events", example:"She teaches world ___.", pack:"ielts4", level:1},
  {word:"honesty", ipa:"/ˈɑːnəsti/", pos:"n.", zh:"诚实", def:"the quality of telling the truth", example:"___ is the best policy.", pack:"ielts4", level:2},
  {word:"honor", ipa:"/ˈɑːnər/", pos:"n.", zh:"荣誉", def:"great respect for something good", example:"It is an ___ to meet you.", pack:"ielts4", level:2},
  {word:"hope", ipa:"/hoʊp/", pos:"v./n.", zh:"希望", def:"the feeling that good things will happen", example:"There is always ___.", pack:"ielts4", level:1},
  {word:"idea", ipa:"/aɪˈdiːə/", pos:"n.", zh:"主意", def:"a thought or plan", example:"That's a great ___.", pack:"ielts4", level:1},
  {word:"identity", ipa:"/aɪˈdentəti/", pos:"n.", zh:"身份", def:"who you are", example:"He kept his ___ secret.", pack:"ielts4", level:3},
  {word:"illness", ipa:"/ˈɪlnəs/", pos:"n.", zh:"疾病", def:"a state of being sick", example:"She missed school because of ___.", pack:"ielts4", level:1},
  {word:"image", ipa:"/ˈɪmɪdʒ/", pos:"n.", zh:"形象；图像", def:"a picture or the way people see you", example:"He cared about his public ___.", pack:"ielts4", level:2},
  {word:"imagination", ipa:"/ɪˌmædʒɪˈneɪʃn/", pos:"n.", zh:"想象力", def:"the power to see new things in your mind", example:"Children have rich ___.", pack:"ielts4", level:2},
  {word:"importance", ipa:"/ɪmˈpɔːrtns/", pos:"n.", zh:"重要性", def:"the quality of being important", example:"She stressed the ___ of sleep.", pack:"ielts4", level:2},
  {word:"improvement", ipa:"/ɪmˈpruːvmənt/", pos:"n.", zh:"改进", def:"a change that makes something better", example:"We saw a big ___ in sales.", pack:"ielts4", level:2},
  {word:"independence", ipa:"/ˌɪndɪˈpendəns/", pos:"n.", zh:"独立", def:"the state of not needing others", example:"Teens want more ___.", pack:"ielts4", level:3},
  {word:"industry", ipa:"/ˈɪndəstri/", pos:"n.", zh:"工业；行业", def:"the production of goods; a type of business", example:"The car ___ is huge.", pack:"ielts4", level:2},
  {word:"instruction", ipa:"/ɪnˈstrʌkʃn/", pos:"n.", zh:"指示；说明", def:"a direction telling you what to do", example:"Read the ___s before use.", pack:"ielts4", level:2},
  {word:"intelligence", ipa:"/ɪnˈtelɪdʒəns/", pos:"n.", zh:"智力；情报", def:"the ability to learn and think", example:"Dogs show high ___.", pack:"ielts4", level:3},
  {word:"interest", ipa:"/ˈɪntrəst/", pos:"n.", zh:"兴趣；利息", def:"a thing you like; money paid for a loan", example:"Her main ___ is music.", pack:"ielts4", level:1},
  {word:"language", ipa:"/ˈlæŋɡwɪdʒ/", pos:"n.", zh:"语言", def:"words people use to talk or write", example:"She speaks three ___.", pack:"ielts4", level:1},
  {word:"leadership", ipa:"/ˈliːdərʃɪp/", pos:"n.", zh:"领导力", def:"the ability to lead a group", example:"She showed strong ___ in the crisis.", pack:"ielts4", level:3},
  {word:"level", ipa:"/ˈlevl/", pos:"n.", zh:"水平；等级", def:"the amount or degree of something", example:"The water ___ rose quickly.", pack:"ielts4", level:1},
  {word:"luck", ipa:"/lʌk/", pos:"n.", zh:"运气", def:"good or bad chance", example:"Good ___ on your test!", pack:"ielts4", level:1},
  {word:"meaning", ipa:"/ˈmiːnɪŋ/", pos:"n.", zh:"意思", def:"what a word or action means", example:"What is the ___ of this word?", pack:"ielts4", level:1},
  {word:"memory", ipa:"/ˈmeməri/", pos:"n.", zh:"记忆", def:"the power to remember things", example:"This song brings back old ___.", pack:"ielts4", level:1},
  {word:"middle", ipa:"/ˈmɪdl/", pos:"n.", zh:"中间", def:"the center part", example:"He sat in the ___ of the row.", pack:"ielts4", level:1},
  {word:"mind", ipa:"/maɪnd/", pos:"n.", zh:"头脑", def:"the part of you that thinks", example:"A healthy body has a healthy ___.", pack:"ielts4", level:1},
  {word:"mistake", ipa:"/mɪˈsteɪk/", pos:"n.", zh:"错误", def:"something done wrong", example:"Everyone makes ___.", pack:"ielts4", level:1},
  {word:"moment", ipa:"/ˈmoʊmənt/", pos:"n.", zh:"时刻", def:"a very short time", example:"Wait a ___, please.", pack:"ielts4", level:1},
  {word:"movement", ipa:"/ˈmuːvmənt/", pos:"n.", zh:"运动；活动", def:"the act of moving; a group working for change", example:"The peace ___ grew larger.", pack:"ielts4", level:2},
  {word:"nature", ipa:"/ˈneɪtʃər/", pos:"n.", zh:"大自然", def:"all living things and the world outside", example:"We love walking in ___.", pack:"ielts4", level:1},
  {word:"necessity", ipa:"/nəˈsesəti/", pos:"n.", zh:"必需品；必要", def:"something you must have", example:"Water is a ___.", pack:"ielts4", level:3},
  {word:"neighborhood", ipa:"/ˈneɪbərhʊd/", pos:"n.", zh:"街区；邻里", def:"the area where you live", example:"We moved to a quiet ___.", pack:"ielts4", level:2},
  {word:"novel", ipa:"/ˈnɑːvl/", pos:"n.", zh:"小说", def:"a long story book", example:"She wrote her first ___ at twenty.", pack:"ielts4", level:2},
  {word:"number", ipa:"/ˈnʌmbər/", pos:"n.", zh:"数字；数量", def:"a word or sign for a count", example:"What is your phone ___?", pack:"ielts4", level:1},
  {word:"object", ipa:"/ˈɑːbdʒekt/", pos:"n.", zh:"物体", def:"a thing you can see and touch", example:"What is that shiny ___?", pack:"ielts4", level:1},
  {word:"opinion", ipa:"/əˈpɪnjən/", pos:"n.", zh:"意见", def:"what you think about something", example:"In my ___, this is a good idea.", pack:"ielts4", level:1},
  {word:"organization", ipa:"/ˌɔːrɡənəˈzeɪʃn/", pos:"n.", zh:"组织", def:"a group with a purpose", example:"She works for a charity ___.", pack:"ielts4", level:2},
  {word:"origin", ipa:"/ˈɔːrɪdʒɪn/", pos:"n.", zh:"起源", def:"the place where something begins", example:"This dish has its ___ in the south.", pack:"ielts4", level:3},
  {word:"pace", ipa:"/peɪs/", pos:"n.", zh:"速度；步伐", def:"the speed of walking or doing something", example:"He walks at a fast ___.", pack:"ielts4", level:2},
  {word:"partnership", ipa:"/ˈpɑːrtnərʃɪp/", pos:"n.", zh:"伙伴关系", def:"two people or groups working together", example:"They formed a ___ to build the bridge.", pack:"ielts4", level:3},
  {word:"passion", ipa:"/ˈpæʃn/", pos:"n.", zh:"热情", def:"a very strong feeling of love for something", example:"She has a ___ for cooking.", pack:"ielts4", level:2},
  {word:"past", ipa:"/pæst/", pos:"n.", zh:"过去", def:"the time before now", example:"We can learn from the ___.", pack:"ielts4", level:1},
  {word:"pattern", ipa:"/ˈpætərn/", pos:"n.", zh:"模式；图案", def:"a repeated shape or way", example:"Sleep has a natural ___.", pack:"ielts4", level:2},
  {word:"peace", ipa:"/piːs/", pos:"n.", zh:"和平；宁静", def:"a time without war or noise", example:"Everyone wants ___ in the world.", pack:"ielts4", level:1},
  {word:"pity", ipa:"/ˈpɪti/", pos:"n.", zh:"怜悯；可惜", def:"a feeling of sadness for someone", example:"It is a ___ that you missed the show.", pack:"ielts4", level:2},
  {word:"pleasure", ipa:"/ˈpleʒər/", pos:"n.", zh:"快乐", def:"a happy feeling", example:"Reading gives me great ___.", pack:"ielts4", level:1},
  {word:"position", ipa:"/pəˈzɪʃn/", pos:"n.", zh:"位置；职位", def:"a place or a job", example:"She applied for the ___ of manager.", pack:"ielts4", level:1},
  {word:"possession", ipa:"/pəˈzeʃn/", pos:"n.", zh:"财产", def:"something you own", example:"He packed his few ___.", pack:"ielts4", level:3},
  {word:"possibility", ipa:"/ˌpɑːsəˈbɪləti/", pos:"n.", zh:"可能性", def:"a chance that something may happen", example:"There is a ___ of snow tonight.", pack:"ielts4", level:2},
  {word:"power", ipa:"/ˈpaʊər/", pos:"n.", zh:"力量；权力", def:"energy; the ability to control", example:"The storm cut off the ___.", pack:"ielts4", level:1},
  {word:"preference", ipa:"/ˈprefrəns/", pos:"n.", zh:"偏好", def:"the thing you like more", example:"My ___ is tea over coffee.", pack:"ielts4", level:3},
  {word:"pressure", ipa:"/ˈpreʃər/", pos:"n.", zh:"压力", def:"the force of pushing; stress", example:"She works well under ___.", pack:"ielts4", level:2},
  {word:"pride", ipa:"/praɪd/", pos:"n.", zh:"自豪", def:"the happy feeling when you do well", example:"He took ___ in his work.", pack:"ielts4", level:2},
  {word:"process", ipa:"/ˈprɑːses/", pos:"n.", zh:"过程", def:"a series of steps to do something", example:"Learning is a slow ___.", pack:"ielts4", level:2},
  {word:"product", ipa:"/ˈprɑːdʌkt/", pos:"n.", zh:"产品", def:"something made to be sold", example:"The store sells fresh ___.", pack:"ielts4", level:1},
  {word:"project", ipa:"/ˈprɑːdʒekt/", pos:"n.", zh:"项目", def:"a planned piece of work", example:"Our science ___ won first prize.", pack:"ielts4", level:1},
  {word:"protection", ipa:"/prəˈtekʃn/", pos:"n.", zh:"保护", def:"the act of keeping something safe", example:"Sunscreen offers ___.", pack:"ielts4", level:2},
  {word:"quality", ipa:"/ˈkwɑːləti/", pos:"n.", zh:"质量", def:"how good something is", example:"This shop sells high-___ goods.", pack:"ielts4", level:1},
  {word:"question", ipa:"/ˈkwestʃən/", pos:"n.", zh:"问题", def:"something you ask", example:"May I ask a ___?", pack:"ielts4", level:1},
  {word:"reality", ipa:"/riˈæləti/", pos:"n.", zh:"现实", def:"the true state of things", example:"His dream became ___.", pack:"ielts4", level:2},
  {word:"reason", ipa:"/ˈriːzn/", pos:"n.", zh:"原因", def:"why something happens", example:"The ___ for the delay was traffic.", pack:"ielts4", level:1},
  {word:"requirement", ipa:"/rɪˈkwaɪərmənt/", pos:"n.", zh:"要求；必要条件", def:"something you must have or do", example:"English is a ___ for the job.", pack:"ielts4", level:3},
  {word:"risk", ipa:"/rɪsk/", pos:"n.", zh:"风险", def:"the chance of something bad", example:"Smoking is a health ___.", pack:"ielts4", level:1},
  {word:"role", ipa:"/roʊl/", pos:"n.", zh:"角色；作用", def:"the job someone does; a part in a play", example:"Parents play a key ___.", pack:"ielts4", level:2},
  {word:"safety", ipa:"/ˈseɪfti/", pos:"n.", zh:"安全", def:"the state of being safe", example:"Workers should follow ___ rules.", pack:"ielts4", level:1},
  {word:"science", ipa:"/ˈsaɪəns/", pos:"n.", zh:"科学", def:"the study of nature and the world", example:"___ explains how things work.", pack:"ielts4", level:1},
  {word:"security", ipa:"/sɪˈkjʊrəti/", pos:"n.", zh:"安全；保障", def:"the state of being protected", example:"The airport has strong ___.", pack:"ielts4", level:2},
  {word:"solution", ipa:"/səˈluːʃn/", pos:"n.", zh:"解决方案", def:"the answer to a problem", example:"We found a ___ to the issue.", pack:"ielts4", level:2},
  {word:"soul", ipa:"/soʊl/", pos:"n.", zh:"灵魂", def:"the spiritual part of a person", example:"Music touches the ___.", pack:"ielts4", level:2},
  {word:"space", ipa:"/speɪs/", pos:"n.", zh:"空间；太空", def:"empty area; the universe beyond earth", example:"This car has little ___.", pack:"ielts4", level:1},
  {word:"standard", ipa:"/ˈstændərd/", pos:"n.", zh:"标准", def:"a level of quality", example:"The work meets our high ___.", pack:"ielts4", level:2},
  {word:"strength", ipa:"/streŋkθ/", pos:"n.", zh:"力量；强项", def:"the quality of being strong", example:"Patience is her ___.", pack:"ielts4", level:1},
  {word:"structure", ipa:"/ˈstrʌktʃər/", pos:"n.", zh:"结构", def:"the way parts are arranged", example:"The ___ of the building is old.", pack:"ielts4", level:2},
  {word:"success", ipa:"/səkˈses/", pos:"n.", zh:"成功", def:"the state of doing well", example:"Hard work brings ___.", pack:"ielts4", level:1},
  {word:"supply", ipa:"/səˈplaɪ/", pos:"n./v.", zh:"供应", def:"the amount available; to provide", example:"Food ___ ran low in winter.", pack:"ielts4", level:2},
  {word:"surprise", ipa:"/sərˈpraɪz/", pos:"n.", zh:"惊喜", def:"an unexpected event", example:"The gift was a nice ___.", pack:"ielts4", level:1},
  {word:"system", ipa:"/ˈsɪstəm/", pos:"n.", zh:"系统", def:"parts working together", example:"The traffic ___ needs upgrading.", pack:"ielts4", level:2},
  {word:"task", ipa:"/tæsk/", pos:"n.", zh:"任务", def:"a piece of work to do", example:"Finish the ___ before noon.", pack:"ielts4", level:2},
  {word:"team", ipa:"/tiːm/", pos:"n.", zh:"团队", def:"a group working together", example:"Our ___ won the match.", pack:"ielts4", level:1},
  {word:"thought", ipa:"/θɔːt/", pos:"n.", zh:"想法", def:"an idea in your mind", example:"I had a sudden ___.", pack:"ielts4", level:1},
  {word:"trouble", ipa:"/ˈtrʌbl/", pos:"n.", zh:"麻烦", def:"a problem or difficulty", example:"The car is giving me ___.", pack:"ielts4", level:1},
  {word:"truth", ipa:"/truːθ/", pos:"n.", zh:"真相", def:"what is real and true", example:"Always tell the ___.", pack:"ielts4", level:1},
  {word:"type", ipa:"/taɪp/", pos:"n.", zh:"类型", def:"a kind of thing", example:"What ___ of music do you like?", pack:"ielts4", level:1},
  {word:"understanding", ipa:"/ˌʌndərˈstændɪŋ/", pos:"n.", zh:"理解；了解", def:"the ability to know what something means", example:"She has a deep ___ of art.", pack:"ielts4", level:2},
  {word:"variety", ipa:"/vəˈraɪəti/", pos:"n.", zh:"多样性", def:"many different types", example:"Eat a ___ of vegetables.", pack:"ielts4", level:2},
  {word:"victory", ipa:"/ˈvɪktəri/", pos:"n.", zh:"胜利", def:"success in a fight or game", example:"The team celebrated their ___.", pack:"ielts4", level:2},
  {word:"way", ipa:"/weɪ/", pos:"n.", zh:"方法；路", def:"a method; a road", example:"This is the best ___ to learn.", pack:"ielts4", level:1},
  {word:"wealth", ipa:"/welθ/", pos:"n.", zh:"财富", def:"a large amount of money or things", example:"He built his ___ slowly.", pack:"ielts4", level:2},
  {word:"wisdom", ipa:"/ˈwɪzdəm/", pos:"n.", zh:"智慧", def:"the ability to make good choices", example:"Grandma shared her ___.", pack:"ielts4", level:2},
  {word:"work", ipa:"/wɜːrk/", pos:"n./v.", zh:"工作", def:"a job; to do a job", example:"She goes to ___ by bus.", pack:"ielts4", level:1},
  {word:"able", ipa:"/ˈeɪbl/", pos:"adj.", zh:"有能力的", def:"having the power or skill to do something", example:"She is ___ to swim very fast.", pack:"ielts4", level:1},
  {word:"active", ipa:"/ˈæktɪv/", pos:"adj.", zh:"活跃的", def:"always moving or doing things", example:"He leads an ___ life.", pack:"ielts4", level:1},
  {word:"actual", ipa:"/ˈæktʃuəl/", pos:"adj.", zh:"实际的", def:"real, not imagined", example:"The ___ cost was higher than expected.", pack:"ielts4", level:2},
  {word:"afraid", ipa:"/əˈfreɪd/", pos:"adj.", zh:"害怕的", def:"feeling fear", example:"She is ___ of spiders.", pack:"ielts4", level:1},
  {word:"angry", ipa:"/ˈæŋɡri/", pos:"adj.", zh:"生气的", def:"feeling strong displeasure", example:"He was ___ about the noise.", pack:"ielts4", level:1},
  {word:"available", ipa:"/əˈveɪləbl/", pos:"adj.", zh:"可用的；有空的", def:"able to be used or reached", example:"The doctor is ___ now.", pack:"ielts4", level:2},
  {word:"awful", ipa:"/ˈɔːfl/", pos:"adj.", zh:"糟糕的", def:"very bad", example:"The weather was ___.", pack:"ielts4", level:1},
  {word:"beautiful", ipa:"/ˈbjuːtɪfl/", pos:"adj.", zh:"美丽的", def:"very pleasing to look at", example:"What a ___ sunset!", pack:"ielts4", level:1},
  {word:"brave", ipa:"/breɪv/", pos:"adj.", zh:"勇敢的", def:"showing no fear", example:"The firefighter was very ___.", pack:"ielts4", level:1},
  {word:"bright", ipa:"/braɪt/", pos:"adj.", zh:"明亮的；聪明的", def:"full of light; smart", example:"The room is very ___.", pack:"ielts4", level:1},
  {word:"busy", ipa:"/ˈbɪzi/", pos:"adj.", zh:"忙碌的", def:"having a lot to do", example:"She is ___ with work today.", pack:"ielts4", level:1},
  {word:"calm", ipa:"/kɑːm/", pos:"adj.", zh:"平静的", def:"peaceful and quiet", example:"Keep ___ during the test.", pack:"ielts4", level:1},
  {word:"careful", ipa:"/ˈkerfl/", pos:"adj.", zh:"小心的", def:"giving attention to avoid danger", example:"Be ___ with the hot water.", pack:"ielts4", level:1},
  {word:"cheap", ipa:"/tʃiːp/", pos:"adj.", zh:"便宜的", def:"low in price", example:"The tickets were quite ___.", pack:"ielts4", level:1},
  {word:"clean", ipa:"/kliːn/", pos:"adj.", zh:"干净的", def:"free from dirt", example:"Keep your hands ___.", pack:"ielts4", level:1},
  {word:"clever", ipa:"/ˈklevər/", pos:"adj.", zh:"聪明的", def:"quick at learning and understanding", example:"The fox is a ___ animal.", pack:"ielts4", level:1},
  {word:"complex", ipa:"/kəmˈpleks/", pos:"adj.", zh:"复杂的", def:"made of many parts; not simple", example:"This is a ___ problem.", pack:"ielts4", level:3},
  {word:"dangerous", ipa:"/ˈdeɪndʒərəs/", pos:"adj.", zh:"危险的", def:"able to hurt you", example:"Driving in fog is ___.", pack:"ielts4", level:1},
  {word:"different", ipa:"/ˈdɪfrənt/", pos:"adj.", zh:"不同的", def:"not the same", example:"We come from ___ countries.", pack:"ielts4", level:1},
  {word:"difficult", ipa:"/ˈdɪfɪkəlt/", pos:"adj.", zh:"困难的", def:"not easy", example:"The test was ___.", pack:"ielts4", level:1},
  {word:"distant", ipa:"/ˈdɪstənt/", pos:"adj.", zh:"遥远的", def:"far away in space or time", example:"They live in a ___ village.", pack:"ielts4", level:2},
  {word:"early", ipa:"/ˈɜːrli/", pos:"adj.", zh:"早的", def:"before the usual time", example:"We caught an ___ train.", pack:"ielts4", level:1},
  {word:"empty", ipa:"/ˈempti/", pos:"adj.", zh:"空的", def:"having nothing inside", example:"The bottle is ___.", pack:"ielts4", level:1},
  {word:"equal", ipa:"/ˈiːkwəl/", pos:"adj.", zh:"平等的；相等的", def:"the same in size or value", example:"All people are ___.", pack:"ielts4", level:2},
  {word:"exact", ipa:"/ɪɡˈzækt/", pos:"adj.", zh:"精确的", def:"completely correct", example:"Tell me the ___ time.", pack:"ielts4", level:2},
  {word:"excellent", ipa:"/ˈeksələnt/", pos:"adj.", zh:"极好的", def:"very good", example:"She did an ___ job.", pack:"ielts4", level:1},
  {word:"fair", ipa:"/fer/", pos:"adj.", zh:"公平的", def:"treating everyone the same", example:"The referee was ___.", pack:"ielts4", level:1},
  {word:"famous", ipa:"/ˈfeɪməs/", pos:"adj.", zh:"著名的", def:"known by many people", example:"The city is ___ for its food.", pack:"ielts4", level:1},
  {word:"fast", ipa:"/fæst/", pos:"adj.", zh:"快的", def:"moving at high speed", example:"He is a ___ runner.", pack:"ielts4", level:1},
  {word:"final", ipa:"/ˈfaɪnl/", pos:"adj.", zh:"最后的", def:"coming at the end", example:"This is my ___ decision.", pack:"ielts4", level:1},
  {word:"foreign", ipa:"/ˈfɔːrən/", pos:"adj.", zh:"外国的", def:"from another country", example:"She enjoys learning ___ languages.", pack:"ielts4", level:1},
  {word:"formal", ipa:"/ˈfɔːrml/", pos:"adj.", zh:"正式的", def:"serious and following rules", example:"Wear ___ clothes to the meeting.", pack:"ielts4", level:2},
  {word:"full", ipa:"/fʊl/", pos:"adj.", zh:"满的", def:"having no empty space", example:"The bus is ___.", pack:"ielts4", level:1},
  {word:"funny", ipa:"/ˈfʌni/", pos:"adj.", zh:"好笑的", def:"making you laugh", example:"He told a ___ story.", pack:"ielts4", level:1},
  {word:"gentle", ipa:"/ˈdʒentl/", pos:"adj.", zh:"温和的", def:"kind and soft", example:"She has a ___ voice.", pack:"ielts4", level:1},
  {word:"glad", ipa:"/ɡlæd/", pos:"adj.", zh:"高兴的", def:"happy about something", example:"I'm ___ you came.", pack:"ielts4", level:1},
  {word:"great", ipa:"/ɡreɪt/", pos:"adj.", zh:"极好的；大的", def:"very good; large", example:"We had a ___ time.", pack:"ielts4", level:1},
  {word:"happy", ipa:"/ˈhæpi/", pos:"adj.", zh:"快乐的", def:"feeling pleasure", example:"The children look ___.", pack:"ielts4", level:1},
  {word:"hard", ipa:"/hɑːrd/", pos:"adj.", zh:"硬的；难的", def:"difficult; not soft", example:"The question was too ___.", pack:"ielts4", level:1},
  {word:"healthy", ipa:"/ˈhelθi/", pos:"adj.", zh:"健康的", def:"strong and well", example:"Eat ___ food every day.", pack:"ielts4", level:1},
  {word:"heavy", ipa:"/ˈhevi/", pos:"adj.", zh:"重的", def:"weighing a lot", example:"This box is too ___.", pack:"ielts4", level:1},
  {word:"high", ipa:"/haɪ/", pos:"adj.", zh:"高的", def:"tall or far above the ground", example:"The mountain is very ___.", pack:"ielts4", level:1},
  {word:"huge", ipa:"/hjuːdʒ/", pos:"adj.", zh:"巨大的", def:"very big", example:"An elephant is a ___ animal.", pack:"ielts4", level:1},
  {word:"important", ipa:"/ɪmˈpɔːrtnt/", pos:"adj.", zh:"重要的", def:"mattering a lot", example:"Sleep is ___.", pack:"ielts4", level:1},
  {word:"interesting", ipa:"/ˈɪntrəstɪŋ/", pos:"adj.", zh:"有趣的", def:"holding your attention", example:"The book is quite ___.", pack:"ielts4", level:1},
  {word:"international", ipa:"/ˌɪntərˈnæʃnəl/", pos:"adj.", zh:"国际的", def:"involving many countries", example:"She works for an ___ company.", pack:"ielts4", level:2},
  {word:"large", ipa:"/lɑːrdʒ/", pos:"adj.", zh:"大的", def:"big in size or amount", example:"We need a ___ table.", pack:"ielts4", level:1},
  {word:"late", ipa:"/leɪt/", pos:"adj.", zh:"迟的", def:"after the expected time", example:"The train is ___ again.", pack:"ielts4", level:1},
  {word:"lazy", ipa:"/ˈleɪzi/", pos:"adj.", zh:"懒惰的", def:"not wanting to work", example:"He is too ___ to help.", pack:"ielts4", level:1},
  {word:"light", ipa:"/laɪt/", pos:"adj.", zh:"轻的；明亮的", def:"not heavy; not dark", example:"The bag is very ___.", pack:"ielts4", level:1},
  {word:"likely", ipa:"/ˈlaɪkli/", pos:"adj.", zh:"可能的", def:"probably going to happen", example:"It is ___ to rain.", pack:"ielts4", level:2},
  {word:"loud", ipa:"/laʊd/", pos:"adj.", zh:"大声的", def:"making a strong sound", example:"The music is too ___.", pack:"ielts4", level:1},
  {word:"lucky", ipa:"/ˈlʌki/", pos:"adj.", zh:"幸运的", def:"having good luck", example:"You are ___ to have this chance.", pack:"ielts4", level:1},
  {word:"main", ipa:"/meɪn/", pos:"adj.", zh:"主要的", def:"most important", example:"What is the ___ idea?", pack:"ielts4", level:1},
  {word:"modern", ipa:"/ˈmɑːdərn/", pos:"adj.", zh:"现代的", def:"new and up to date", example:"They live in a ___ house.", pack:"ielts4", level:1},
  {word:"natural", ipa:"/ˈnætʃrəl/", pos:"adj.", zh:"自然的", def:"from nature, not made by people", example:"This drink has ___ sugar.", pack:"ielts4", level:1},
  {word:"normal", ipa:"/ˈnɔːrml/", pos:"adj.", zh:"正常的", def:"usual or expected", example:"It is ___ to feel nervous.", pack:"ielts4", level:2},
  {word:"obvious", ipa:"/ˈɑːbviəs/", pos:"adj.", zh:"明显的", def:"easy to see or understand", example:"The answer is ___.", pack:"ielts4", level:3},
  {word:"old-fashioned", ipa:"/ˌoʊld ˈfæʃnd/", pos:"adj.", zh:"过时的", def:"no longer modern", example:"His ideas are ___.", pack:"ielts4", level:3},
  {word:"open", ipa:"/ˈoʊpən/", pos:"adj.", zh:"开放的", def:"not closed; willing to new ideas", example:"The store is ___ till ten.", pack:"ielts4", level:1},
  {word:"patient", ipa:"/ˈpeɪʃnt/", pos:"adj.", zh:"耐心的", def:"able to wait calmly", example:"Be ___ with beginners.", pack:"ielts4", level:2},
  {word:"perfect", ipa:"/ˈpɜːrfɪkt/", pos:"adj.", zh:"完美的", def:"without any mistakes", example:"Her English is ___.", pack:"ielts4", level:1},
  {word:"personal", ipa:"/ˈpɜːrsənl/", pos:"adj.", zh:"个人的", def:"belonging to one person", example:"This is my ___ opinion.", pack:"ielts4", level:2},
  {word:"pleasant", ipa:"/ˈpleznt/", pos:"adj.", zh:"令人愉快的", def:"nice and enjoyable", example:"We had a ___ evening.", pack:"ielts4", level:2},
  {word:"poor", ipa:"/pʊr/", pos:"adj.", zh:"贫穷的；差的", def:"having little money; not good", example:"Many ___ families need help.", pack:"ielts4", level:1},
  {word:"positive", ipa:"/ˈpɑːzətɪv/", pos:"adj.", zh:"积极的", def:"hopeful and confident", example:"Keep a ___ attitude.", pack:"ielts4", level:2},
  {word:"powerful", ipa:"/ˈpaʊərfl/", pos:"adj.", zh:"强大的", def:"very strong", example:"The engine is very ___.", pack:"ielts4", level:2},
  {word:"practical", ipa:"/ˈpræktɪkl/", pos:"adj.", zh:"实用的", def:"useful in real situations", example:"She has ___ experience.", pack:"ielts4", level:3},
  {word:"private", ipa:"/ˈpraɪvət/", pos:"adj.", zh:"私人的", def:"not for the public", example:"This is a ___ room.", pack:"ielts4", level:2},
  {word:"quick", ipa:"/kwɪk/", pos:"adj.", zh:"快速的", def:"fast", example:"She gave a ___ answer.", pack:"ielts4", level:1},
  {word:"quiet", ipa:"/ˈkwaɪət/", pos:"adj.", zh:"安静的", def:"making little noise", example:"The library is ___.", pack:"ielts4", level:1},
  {word:"rare", ipa:"/rer/", pos:"adj.", zh:"稀有的", def:"not happening or seen often", example:"Snow is ___ here.", pack:"ielts4", level:2},
  {word:"real", ipa:"/ˈriːəl/", pos:"adj.", zh:"真实的", def:"actually existing", example:"Is this story ___.", pack:"ielts4", level:1},
  {word:"recent", ipa:"/ˈriːsnt/", pos:"adj.", zh:"最近的", def:"happening not long ago", example:"Have you seen the ___ news?", pack:"ielts4", level:2},
  {word:"rich", ipa:"/rɪtʃ/", pos:"adj.", zh:"富有的", def:"having a lot of money", example:"He became ___ through trade.", pack:"ielts4", level:1},
  {word:"right", ipa:"/raɪt/", pos:"adj.", zh:"正确的", def:"correct", example:"Your answer is ___.", pack:"ielts4", level:1},
  {word:"serious", ipa:"/ˈsɪriəs/", pos:"adj.", zh:"严肃的；严重的", def:"not joking; very important", example:"This is a ___ problem.", pack:"ielts4", level:2},
  {word:"similar", ipa:"/ˈsɪmələr/", pos:"adj.", zh:"相似的", def:"almost the same", example:"Our bags are ___.", pack:"ielts4", level:2},
  {word:"simple", ipa:"/ˈsɪmpl/", pos:"adj.", zh:"简单的", def:"easy to do or understand", example:"The rules are ___.", pack:"ielts4", level:1},
  {word:"small", ipa:"/smɔːl/", pos:"adj.", zh:"小的", def:"little in size", example:"She lives in a ___ flat.", pack:"ielts4", level:1},
  {word:"smooth", ipa:"/smuːð/", pos:"adj.", zh:"光滑的", def:"flat and even, without bumps", example:"The road is very ___.", pack:"ielts4", level:1},
  {word:"social", ipa:"/ˈsoʊʃl/", pos:"adj.", zh:"社会的；社交的", def:"related to people in groups", example:"He has good ___ skills.", pack:"ielts4", level:2},
  {word:"special", ipa:"/ˈspeʃl/", pos:"adj.", zh:"特别的", def:"different and better than usual", example:"Today is a ___ day.", pack:"ielts4", level:1},
  {word:"strange", ipa:"/streɪndʒ/", pos:"adj.", zh:"奇怪的", def:"unusual and surprising", example:"I heard a ___ sound.", pack:"ielts4", level:1},
  {word:"strict", ipa:"/strɪkt/", pos:"adj.", zh:"严格的", def:"demanding exact rules", example:"Our teacher is very ___.", pack:"ielts4", level:2},
  {word:"strong", ipa:"/strɔːŋ/", pos:"adj.", zh:"强壮的", def:"having power in the body", example:"He is strong enough to lift it.", pack:"ielts4", level:1},
  {word:"successful", ipa:"/səkˈsesfl/", pos:"adj.", zh:"成功的", def:"achieving success", example:"She runs a ___ business.", pack:"ielts4", level:2},
  {word:"sure", ipa:"/ʃʊr/", pos:"adj.", zh:"确定的", def:"certain", example:"Are you ___ about that?", pack:"ielts4", level:1},
  {word:"terrible", ipa:"/ˈterəbl/", pos:"adj.", zh:"可怕的；糟糕的", def:"very bad", example:"The food was ___.", pack:"ielts4", level:1},
  {word:"usual", ipa:"/ˈjuːʒuəl/", pos:"adj.", zh:"通常的", def:"happening most of the time", example:"I took my ___ bus.", pack:"ielts4", level:2},
  {word:"various", ipa:"/ˈveriəs/", pos:"adj.", zh:"各种各样的", def:"many different kinds", example:"The store sells ___ items.", pack:"ielts4", level:3},
  {word:"weak", ipa:"/wiːk/", pos:"adj.", zh:"虚弱的", def:"not strong", example:"He felt ___ after the illness.", pack:"ielts4", level:1},
  {word:"whole", ipa:"/hoʊl/", pos:"adj.", zh:"整个的", def:"complete, with nothing missing", example:"I ate the ___ cake.", pack:"ielts4", level:1},
  {word:"wide", ipa:"/waɪd/", pos:"adj.", zh:"宽的", def:"large from side to side", example:"The river is very ___.", pack:"ielts4", level:1},
  {word:"wrong", ipa:"/rɔːŋ/", pos:"adj.", zh:"错误的", def:"not correct", example:"Your answer was ___.", pack:"ielts4", level:1},
  {word:"young", ipa:"/jʌŋ/", pos:"adj.", zh:"年轻的", def:"not old", example:"She is too ___ to drive.", pack:"ielts4", level:1},
  {word:"immediately", ipa:"/ɪˈmiːdiətli/", pos:"adv.", zh:"立刻", def:"now, without delay", example:"Please come ___.", pack:"ielts4", level:2},
  {word:"together", ipa:"/təˈɡeðər/", pos:"adv.", zh:"一起", def:"with each other", example:"We study ___.", pack:"ielts4", level:1},
  {word:"perhaps", ipa:"/pərˈhæps/", pos:"adv.", zh:"也许", def:"maybe", example:"___ we can meet tomorrow.", pack:"ielts4", level:2},
  {word:"probably", ipa:"/ˈprɑːbəbli/", pos:"adv.", zh:"很可能", def:"almost certainly", example:"It will ___ rain.", pack:"ielts4", level:2},
  {word:"actually", ipa:"/ˈæktʃuəli/", pos:"adv.", zh:"实际上", def:"really; in fact", example:"I ___ liked the movie.", pack:"ielts4", level:2},
  {word:"almost", ipa:"/ˈɔːlmoʊst/", pos:"adv.", zh:"几乎", def:"nearly but not completely", example:"It is ___ dark outside.", pack:"ielts4", level:2},
  {word:"sometimes", ipa:"/ˈsʌmtaɪmz/", pos:"adv.", zh:"有时", def:"not always", example:"___ I walk to school.", pack:"ielts4", level:1},
  {word:"always", ipa:"/ˈɔːlweɪz/", pos:"adv.", zh:"总是", def:"every time", example:"She ___ arrives early.", pack:"ielts4", level:1},
  {word:"often", ipa:"/ˈɔːfn/", pos:"adv.", zh:"经常", def:"many times", example:"We ___ eat out on Fridays.", pack:"ielts4", level:1},
  {word:"usually", ipa:"/ˈjuːʒuəli/", pos:"adv.", zh:"通常", def:"most of the time", example:"I ___ get up at seven.", pack:"ielts4", level:1},
  {word:"besides", ipa:"/bɪˈsaɪdz/", pos:"adv.", zh:"此外", def:"also; in addition", example:"___, we need more time.", pack:"ielts4", level:3},
  {word:"therefore", ipa:"/ˈðerfɔːr/", pos:"adv.", zh:"因此", def:"for that reason", example:"It rained; ___, we stayed in.", pack:"ielts4", level:3},
  {word:"however", ipa:"/haʊˈevər/", pos:"adv.", zh:"然而", def:"but", example:"I like it; ___, it is pricey.", pack:"ielts4", level:2},
  {word:"although", ipa:"/ɔːlˈðoʊ/", pos:"conj.", zh:"虽然", def:"even though", example:"___ it was cold, we went out.", pack:"ielts4", level:2},
  {word:"through", ipa:"/θruː/", pos:"prep.", zh:"穿过", def:"from one side to the other", example:"We walked ___ the forest.", pack:"ielts4", level:1},
  {word:"within", ipa:"/wɪˈðɪn/", pos:"prep.", zh:"在…之内", def:"inside a period or area", example:"Finish it ___ an hour.", pack:"ielts4", level:2},
  {word:"beyond", ipa:"/biˈjɑːnd/", pos:"prep.", zh:"超出", def:"on the other side of; more than", example:"The village is ___ the hills.", pack:"ielts4", level:3},
  // ===BATCH-C-END===
);
