// =========================================================
// 雅思核心词包 · 第9批（IELTS Batch 9）—— 继续补高频/进阶
// =========================================================
WORDS.push(
  {word:"wake", ipa:"/weɪk/", pos:"v.", zh:"醒来", def:"to stop sleeping", example:"I ___ up at seven every day.", pack:"ielts9", level:1},
  {word:"sleep", ipa:"/sliːp/", pos:"v./n.", zh:"睡觉", def:"to rest with your eyes closed", example:"Babies need a lot of ___.", pack:"ielts9", level:1},
  {word:"alarm", ipa:"/əˈlɑːrm/", pos:"n.", zh:"闹钟；警报", def:"a thing that wakes you or warns of danger", example:"My ___ rang at six.", pack:"ielts9", level:1},
  {word:"already", ipa:"/ɔːlˈredi/", pos:"adv.", zh:"已经", def:"before now", example:"I have ___ eaten.", pack:"ielts9", level:1},
  {word:"apartment", ipa:"/əˈpɑːrtmənt/", pos:"n.", zh:"公寓", def:"a flat; a set of rooms to live in", example:"They rent a small ___.", pack:"ielts9", level:1},
  {word:"area", ipa:"/ˈeriə/", pos:"n.", zh:"地区；面积", def:"a part of a place; the size of a space", example:"This ___ is famous for food.", pack:"ielts9", level:1},
  {word:"army", ipa:"/ˈɑːrmi/", pos:"n.", zh:"军队", def:"a large group of soldiers", example:"He joined the ___ at twenty.", pack:"ielts9", level:2},
  {word:"assistant", ipa:"/əˈsɪstənt/", pos:"n.", zh:"助手", def:"a person who helps someone", example:"She works as a shop ___.", pack:"ielts9", level:2},
  {word:"blow", ipa:"/bloʊ/", pos:"v.", zh:"吹", def:"to move air; the wind moves something", example:"The wind ___ my hat away.", pack:"ielts9", level:1},
  {word:"board", ipa:"/bɔːrd/", pos:"n./v.", zh:"板；登机；董事会", def:"a flat piece of wood; to get on a plane", example:"Passengers should ___ now.", pack:"ielts9", level:1},
  {word:"bottom", ipa:"/ˈbɑːtəm/", pos:"n.", zh:"底部", def:"the lowest part", example:"Look at the ___ of the page.", pack:"ielts9", level:1},
  {word:"brake", ipa:"/breɪk/", pos:"n.", zh:"刹车", def:"the part that stops a vehicle", example:"Push the ___ to slow down.", pack:"ielts9", level:2},
  {word:"burst", ipa:"/bɜːrst/", pos:"v.", zh:"爆裂", def:"to break open suddenly", example:"The balloon ___t.", pack:"ielts9", level:2},
  {word:"buy", ipa:"/baɪ/", pos:"v.", zh:"买", def:"to get something by paying money", example:"I want to ___ a new phone.", pack:"ielts9", level:1},
  {word:"camera", ipa:"/ˈkæmərə/", pos:"n.", zh:"相机", def:"a device that takes photos", example:"He took photos with his ___.", pack:"ielts9", level:1},
  {word:"careless", ipa:"/ˈkerləs/", pos:"adj.", zh:"粗心的", def:"not paying enough attention", example:"A ___ driver caused the accident.", root:"care(小心)+less(无)→不小心", pack:"ielts9", level:2},
  {word:"center", ipa:"/ˈsentər/", pos:"n.", zh:"中心", def:"the middle of something", example:"The shop is in the city ___.", pack:"ielts9", level:1},
  {word:"change", ipa:"/tʃeɪndʒ/", pos:"v./n.", zh:"改变；零钱", def:"to become different; coins", example:"Here is your ___.", pack:"ielts9", level:1},
  {word:"cheerful", ipa:"/ˈtʃɪrfl/", pos:"adj.", zh:"快乐的", def:"happy and positive", example:"She is always ___.", pack:"ielts9", level:2},
  {word:"child", ipa:"/tʃaɪld/", pos:"n.", zh:"孩子", def:"a young person", example:"The ___ plays in the yard.", pack:"ielts9", level:1},
  {word:"classify", ipa:"/ˈklæsɪfaɪ/", pos:"v.", zh:"分类", def:"to put things into groups", example:"Librarians ___ books by subject.", pack:"ielts9", level:3},
  {word:"completely", ipa:"/kəmˈpliːtli/", pos:"adv.", zh:"完全地", def:"totally", example:"The work is ___ done.", pack:"ielts9", level:2},
  {word:"confuse", ipa:"/kənˈfjuːz/", pos:"v.", zh:"使困惑", def:"to make someone unable to understand", example:"The map ___d me.", pack:"ielts9", level:2},
  {word:"copy", ipa:"/ˈkɑːpi/", pos:"v./n.", zh:"复制；副本", def:"to make something like another", example:"Please ___ this file.", pack:"ielts9", level:1},
  {word:"correctly", ipa:"/kəˈrektli/", pos:"adv.", zh:"正确地", def:"in the right way", example:"Answer the question ___.", pack:"ielts9", level:1},
  {word:"course", ipa:"/kɔːrs/", pos:"n.", zh:"课程；一道菜", def:"a class; one part of a meal", example:"She takes an English ___.", pack:"ielts9", level:1},
  {word:"crazy", ipa:"/ˈkreɪzi/", pos:"adj.", zh:"疯狂的", def:"very silly or excited", example:"You must be ___ to try that.", pack:"ielts9", level:1},
  {word:"desk", ipa:"/desk/", pos:"n.", zh:"书桌", def:"a table for writing or work", example:"She sits at the front ___.", pack:"ielts9", level:1},
  {word:"dirty", ipa:"/ˈdɜːrti/", pos:"adj.", zh:"脏的", def:"not clean", example:"Your hands are ___.", pack:"ielts9", level:1},
  {word:"draw", ipa:"/drɔː/", pos:"v.", zh:"画画；拉", def:"to make a picture with a pen", example:"She likes to ___ animals.", pack:"ielts9", level:1},
  {word:"either", ipa:"/ˈaɪðər/", pos:"conj.", zh:"或者", def:"one of two", example:"You can have ___ one.", pack:"ielts9", level:1},
  {word:"engine", ipa:"/ˈendʒɪn/", pos:"n.", zh:"发动机", def:"the machine that makes a car move", example:"The ___ is very quiet.", pack:"ielts9", level:2},
  {word:"entrance", ipa:"/ˈentrəns/", pos:"n.", zh:"入口", def:"the door you go in through", example:"The ___ is on the left.", root:"enter(进入)+ance→入口", pack:"ielts9", level:2},
  {word:"envy", ipa:"/ˈenvi/", pos:"v.", zh:"羡慕", def:"to wish you had what someone has", example:"I ___ her success.", syn:["jealousy"], pack:"ielts9", level:3},
  {word:"except", ipa:"/ɪkˈsept/", pos:"prep.", zh:"除了", def:"not including", example:"Everyone came ___ Tom.", pack:"ielts9", level:2},
  {word:"excited", ipa:"/ɪkˈsaɪtɪd/", pos:"adj.", zh:"兴奋的", def:"very happy and eager", example:"The kids were ___ about the trip.", pack:"ielts9", level:1},
  {word:"exercise", ipa:"/ˈeksərsaɪz/", pos:"n./v.", zh:"锻炼", def:"physical activity to stay healthy", example:"Do ___ every day.", pack:"ielts9", level:1},
  {word:"exit", ipa:"/ˈeɡzɪt/", pos:"n.", zh:"出口", def:"the way out", example:"Use the side ___.", root:"ex(出)+it(走)→出口", pack:"ielts9", level:2},
  {word:"fashion", ipa:"/ˈfæʃn/", pos:"n.", zh:"时尚", def:"the popular style of clothes", example:"She follows the latest ___.", pack:"ielts9", level:2},
  {word:"fear", ipa:"/fɪr/", pos:"n.", zh:"恐惧", def:"the feeling of being afraid", example:"She has a ___ of heights.", pack:"ielts9", level:1},
  {word:"find", ipa:"/faɪnd/", pos:"v.", zh:"找到", def:"to discover after looking", example:"I can't ___ my keys.", pack:"ielts9", level:1},
  {word:"finish", ipa:"/ˈfɪnɪʃ/", pos:"v.", zh:"完成", def:"to bring to an end", example:"I ___ed my homework.", pack:"ielts9", level:1},
  {word:"garden", ipa:"/ˈɡɑːrdn/", pos:"n.", zh:"花园", def:"land where flowers or vegetables grow", example:"We grow tomatoes in the ___.", pack:"ielts9", level:1},
  {word:"gold", ipa:"/ɡoʊld/", pos:"n.", zh:"黄金", def:"a valuable yellow metal", example:"The ring is made of ___.", pack:"ielts9", level:1},
  {word:"highly", ipa:"/ˈhaɪli/", pos:"adv.", zh:"高度地", def:"very; to a high degree", example:"She is ___ respected.", pack:"ielts9", level:2},
  {word:"hold", ipa:"/hoʊld/", pos:"v.", zh:"握住；举行", def:"to have in your hand; to organize", example:"She ___s a baby in her arms.", pack:"ielts9", level:1},
  {word:"inside", ipa:"/ˌɪnˈsaɪd/", pos:"prep.", zh:"在…里面", def:"in the inner part", example:"Come ___ the house.", pack:"ielts9", level:1},
  {word:"instead", ipa:"/ɪnˈsted/", pos:"adv.", zh:"代替", def:"in place of something", example:"Let's walk ___ of driving.", pack:"ielts9", level:2},
  {word:"introduce", ipa:"/ˌɪntrəˈduːs/", pos:"v.", zh:"介绍", def:"to make people know each other", example:"Let me ___ my friend.", pack:"ielts9", level:2},
  {word:"keyboard", ipa:"/ˈkiːbɔːrd/", pos:"n.", zh:"键盘", def:"the keys you type on", example:"Clean the ___ carefully.", pack:"ielts9", level:2},
  {word:"leave", ipa:"/liːv/", pos:"v.", zh:"离开", def:"to go away from a place", example:"The train ___s at six.", pack:"ielts9", level:1},
  {word:"letter", ipa:"/ˈletər/", pos:"n.", zh:"信；字母", def:"a written message; a character of alphabet", example:"I sent her a long ___.", pack:"ielts9", level:1},
  {word:"maybe", ipa:"/ˈmeɪbi/", pos:"adv.", zh:"也许", def:"perhaps", example:"___ it will snow.", pack:"ielts9", level:1},
  {word:"medical", ipa:"/ˈmedɪkl/", pos:"adj.", zh:"医学的", def:"related to medicine", example:"She needs ___ help.", pack:"ielts9", level:2},
  {word:"might", ipa:"/maɪt/", pos:"modal", zh:"可能", def:"may; perhaps", example:"It ___ rain later.", pack:"ielts9", level:1},
  {word:"million", ipa:"/ˈmɪljən/", pos:"num.", zh:"百万", def:"the number 1,000,000", example:"A ___ people live here.", pack:"ielts9", level:1},
  {word:"neither", ipa:"/ˈnaɪðər/", pos:"conj.", zh:"两者都不", def:"not one and not the other", example:"___ answer is correct.", pack:"ielts9", level:3},
  {word:"noise", ipa:"/nɔɪz/", pos:"n.", zh:"噪音", def:"unwanted sound", example:"The ___ kept me awake.", pack:"ielts9", level:1},
  {word:"opposite", ipa:"/ˈɑːpəzɪt/", pos:"adj.", zh:"相反的", def:"completely different; facing", example:"The bank is ___ the park.", pack:"ielts9", level:2},
  {word:"paint", ipa:"/peɪnt/", pos:"v./n.", zh:"绘画；油漆", def:"to cover with color; colored liquid", example:"We ___ed the wall blue.", pack:"ielts9", level:1},
  {word:"pair", ipa:"/per/", pos:"n.", zh:"一对", def:"two things used together", example:"I need a new ___ of shoes.", pack:"ielts9", level:1},
  {word:"paper", ipa:"/ˈpeɪpər/", pos:"n.", zh:"纸；论文", def:"thin sheets for writing; an academic essay", example:"Write it on a piece of ___.", pack:"ielts9", level:1},
  {word:"pass", ipa:"/pæs/", pos:"v.", zh:"通过；传递", def:"to go past; to give to someone", example:"Please ___ the salt.", pack:"ielts9", level:1},
  {word:"picture", ipa:"/ˈpɪktʃər/", pos:"n.", zh:"图片", def:"a drawing or photo", example:"Look at the ___ on page two.", pack:"ielts9", level:1},
  {word:"please", ipa:"/pliːz/", pos:"interj.", zh:"请", def:"a polite word when asking", example:"___ open the window.", pack:"ielts9", level:1},
  {word:"point", ipa:"/pɔɪnt/", pos:"v./n.", zh:"指向；点", def:"to show with a finger; an idea", example:"Good ___! I agree.", pack:"ielts9", level:1},
  {word:"postcard", ipa:"/ˈpoʊstkɑːrd/", pos:"n.", zh:"明信片", def:"a card sent with a picture on it", example:"She sent a ___ from Paris.", pack:"ielts9", level:2},
  {word:"problem", ipa:"/ˈprɑːbləm/", pos:"n.", zh:"问题", def:"something hard to deal with", example:"We solved the ___.", pack:"ielts9", level:1},
  {word:"quite", ipa:"/kwaɪt/", pos:"adv.", zh:"相当", def:"fairly; to some degree", example:"The movie was ___ good.", pack:"ielts9", level:2},
  {word:"ready", ipa:"/ˈredi/", pos:"adj.", zh:"准备好的", def:"prepared to do something", example:"Are you ___ to go?", pack:"ielts9", level:1},
  {word:"relax", ipa:"/rɪˈlæks/", pos:"v.", zh:"放松", def:"to rest and feel calm", example:"___ on the sofa for a while.", pack:"ielts9", level:2},
  {word:"rise", ipa:"/raɪz/", pos:"v.", zh:"上升", def:"to go up", example:"The sun ___s early.", pack:"ielts9", level:1},
  {word:"sick", ipa:"/sɪk/", pos:"adj.", zh:"生病的", def:"not well", example:"She is ___ today.", pack:"ielts9", level:1},
  {word:"signal", ipa:"/ˈsɪɡnəl/", pos:"n.", zh:"信号", def:"a sign that carries information", example:"The traffic ___ turned green.", pack:"ielts9", level:2},
  {word:"since", ipa:"/sɪns/", pos:"prep.", zh:"自从", def:"from a past time until now", example:"I have lived here ___ 2020.", pack:"ielts9", level:1},
  {word:"single", ipa:"/ˈsɪŋɡl/", pos:"adj.", zh:"单一的；单身的", def:"only one; not married", example:"A ___ ticket, please.", pack:"ielts9", level:1},
  {word:"smart", ipa:"/smɑːrt/", pos:"adj.", zh:"聪明的；智能的", def:"clever; intelligent", example:"She is a ___ student.", pack:"ielts9", level:1},
  {word:"somewhere", ipa:"/ˈsʌmwer/", pos:"adv.", zh:"某处", def:"in or to some place", example:"Let's go ___ warm.", pack:"ielts9", level:1},
  {word:"sorry", ipa:"/ˈsɑːri/", pos:"adj.", zh:"抱歉的", def:"feeling regret", example:"I'm ___ for being late.", pack:"ielts9", level:1},
  {word:"spirit", ipa:"/ˈspɪrɪt/", pos:"n.", zh:"精神；情绪", def:"the energy or mood of a person", example:"Team ___ is high.", pack:"ielts9", level:3},
  {word:"stay", ipa:"/steɪ/", pos:"v.", zh:"停留", def:"to remain in a place", example:"We ___ed at a hotel.", pack:"ielts9", level:1},
  {word:"still", ipa:"/stɪl/", pos:"adv.", zh:"仍然", def:"continuing until now", example:"He is ___ sleeping.", pack:"ielts9", level:1},
  {word:"story", ipa:"/ˈstɔːri/", pos:"n.", zh:"故事", def:"a tale about events", example:"Grandpa told us a ___.", pack:"ielts9", level:1},
  {word:"study", ipa:"/ˈstʌdi/", pos:"v.", zh:"学习；研究", def:"to learn about a subject", example:"She ___s medicine.", pack:"ielts9", level:1},
  {word:"such", ipa:"/sʌtʃ/", pos:"adj.", zh:"这样的", def:"of that kind", example:"I've never seen ___ a view.", pack:"ielts9", level:2},
  {word:"suddenly", ipa:"/ˈsʌdənli/", pos:"adv.", zh:"突然", def:"quickly and unexpectedly", example:"The lights ___ went out.", pack:"ielts9", level:2},
  {word:"though", ipa:"/ðoʊ/", pos:"adv.", zh:"虽然；不过", def:"however; although", example:"It's hard, ___ it's worth it.", pack:"ielts9", level:2},
  {word:"traffic", ipa:"/ˈtræfɪk/", pos:"n.", zh:"交通", def:"cars and people moving on roads", example:"___ is heavy in the morning.", pack:"ielts9", level:1},
  {word:"trip", ipa:"/trɪp/", pos:"n.", zh:"旅行", def:"a short journey", example:"We took a day ___.", pack:"ielts9", level:1},
  {word:"true", ipa:"/truː/", pos:"adj.", zh:"真的", def:"real and correct", example:"Is the story ___.", pack:"ielts9", level:1},
  {word:"try", ipa:"/traɪ/", pos:"v.", zh:"尝试", def:"to attempt", example:"___ your best.", pack:"ielts9", level:1},
  {word:"view", ipa:"/vjuː/", pos:"n.", zh:"景色；观点", def:"what you can see; an opinion", example:"The room has a sea ___.", pack:"ielts9", level:1},
  {word:"weight", ipa:"/weɪt/", pos:"n.", zh:"重量", def:"how heavy something is", example:"What is your ___.", pack:"ielts9", level:2},
  {word:"welcome", ipa:"/ˈwelkəm/", pos:"v.", zh:"欢迎", def:"to greet someone happily", example:"They ___d us warmly.", pack:"ielts9", level:1},
  {word:"wish", ipa:"/wɪʃ/", pos:"v.", zh:"希望", def:"to want something", example:"I ___ you good luck.", pack:"ielts9", level:1},
  {word:"word", ipa:"/wɜːrd/", pos:"n.", zh:"单词", def:"a unit of language with meaning", example:"What does this ___ mean?", pack:"ielts9", level:1},
  {word:"workplace", ipa:"/ˈwɜːrkpleɪs/", pos:"n.", zh:"工作场所", def:"the place where you work", example:"Safety rules apply in the ___.", pack:"ielts9", level:2},
  {word:"world", ipa:"/wɜːrld/", pos:"n.", zh:"世界", def:"the earth and everything on it", example:"She traveled around the ___.", pack:"ielts9", level:1},
  {word:"worried", ipa:"/ˈwɜːrid/", pos:"adj.", zh:"担心的", def:"feeling uneasy", example:"She was ___ about the test.", pack:"ielts9", level:1},
  {word:"yesterday", ipa:"/ˈjestərdeɪ/", pos:"n.", zh:"昨天", def:"the day before today", example:"We met ___.", pack:"ielts9", level:1},
  // ===BATCH-A-END===
);
