// =========================================================
// 雅思核心词包 · 第5批（IELTS Batch 5）—— 学术/拓展扩容
// 目标：补 level2~4 学术与主题词，向 6000 继续推进。
// 加载方式不变，自动去重。
// =========================================================
WORDS.push(
  // ---------- 学术动词 / 抽象名词 ----------
  {word:"accommodate", ipa:"/əˈkɑːmədeɪt/", pos:"v.", zh:"容纳；适应", def:"to have space for; to help by changing", example:"The hall can ___ five hundred people.", pack:"ielts5", level:4},
  {word:"administer", ipa:"/ədˈmɪnɪstər/", pos:"v.", zh:"管理；执行", def:"to manage; to give out something officially", example:"She ___s the scholarship program.", pack:"ielts5", level:4},
  {word:"affect", ipa:"/əˈfekt/", pos:"v.", zh:"影响", def:"to change or influence someone or something", example:"Noise can ___ your sleep.", pack:"ielts5", level:2},
  {word:"annual", ipa:"/ˈænjuəl/", pos:"adj.", zh:"每年的", def:"happening once a year", example:"The company holds an ___ meeting.", pack:"ielts5", level:3},
  {word:"authorize", ipa:"/ˈɔːθəraɪz/", pos:"v.", zh:"授权", def:"to officially allow something", example:"Only the manager can ___ payment.", pack:"ielts5", level:4},
  {word:"automate", ipa:"/ˈɔːtəmeɪt/", pos:"v.", zh:"使自动化", def:"to make a process run by machines", example:"The factory ___d its packing line.", pack:"ielts5", level:4},
  {word:"category", ipa:"/ˈkætəɡɔːri/", pos:"n.", zh:"类别", def:"a group of things of the same type", example:"Files are stored by ___.", pack:"ielts5", level:3},
  {word:"chapter", ipa:"/ˈtʃæptər/", pos:"n.", zh:"章节", def:"a part of a book", example:"Read chapter three tonight.", pack:"ielts5", level:1},
  {word:"clarity", ipa:"/ˈklærəti/", pos:"n.", zh:"清晰", def:"the quality of being clear and easy to understand", example:"The essay lacks ___.", pack:"ielts5", level:3},
  {word:"commentary", ipa:"/ˈkɑːmənteri/", pos:"n.", zh:"评论", def:"spoken or written explanation of an event", example:"The ___ explained the match.", pack:"ielts5", level:3},
  {word:"compose", ipa:"/kəmˈpoʊz/", pos:"v.", zh:"组成；作曲", def:"to be made of parts; to write music", example:"The committee is ___d of ten members.", pack:"ielts5", level:4},
  {word:"consecutive", ipa:"/kənˈsekjətɪv/", pos:"adj.", zh:"连续的", def:"following one after another", example:"It rained for five ___ days.", pack:"ielts5", level:4},
  {word:"contemporary", ipa:"/kənˈtempəreri/", pos:"adj.", zh:"当代的", def:"existing at the present time", example:"___ art is very popular.", pack:"ielts5", level:4},
  {word:"conventional", ipa:"/kənˈvenʃənl/", pos:"adj.", zh:"传统的", def:"following usual customs", example:"___ farming uses chemicals.", pack:"ielts5", level:4},
  {word:"conviction", ipa:"/kənˈvɪkʃn/", pos:"n.", zh:"信念；定罪", def:"a firm belief; a guilty decision in court", example:"She spoke with ___.", pack:"ielts5", level:4},
  {word:"correlate", ipa:"/ˈkɔːrəleɪt/", pos:"v.", zh:"相关", def:"to have a connection between two things", example:"Sleep ___s with health.", pack:"ielts5", level:4},
  {word:"decade", ipa:"/ˈdekeɪd/", pos:"n.", zh:"十年", def:"a period of ten years", example:"Prices rose over the past ___.", pack:"ielts5", level:2},
  {word:"dedicate", ipa:"/ˈdedɪkeɪt/", pos:"v.", zh:"奉献", def:"to give your time and energy to something", example:"She ___d her life to teaching.", pack:"ielts5", level:3},
  {word:"definite", ipa:"/ˈdefɪnət/", pos:"adj.", zh:"明确的", def:"clear and certain", example:"We need a ___ answer.", pack:"ielts5", level:2},
  {word:"deliberate", ipa:"/dɪˈlɪbərət/", pos:"adj.", zh:"故意的", def:"done on purpose", example:"It was a ___ insult.", pack:"ielts5", level:4},
  {word:"deny", ipa:"/dɪˈnaɪ/", pos:"v.", zh:"否认", def:"to say something is not true", example:"He ___ed stealing the money.", pack:"ielts5", level:2},
  {word:"deprive", ipa:"/dɪˈpraɪv/", pos:"v.", zh:"剥夺", def:"to take something important away from someone", example:"The storm ___d them of power.", pack:"ielts5", level:4},
  {word:"discern", ipa:"/dɪˈsɜːrn/", pos:"v.", zh:"分辨", def:"to notice something that is not easy to see", example:"It is hard to ___ the difference.", pack:"ielts5", level:4},
  {word:"domestic", ipa:"/dəˈmestɪk/", pos:"adj.", zh:"国内的；家庭的", def:"related to home or one's own country", example:"___ flights are cheap.", pack:"ielts5", level:3},
  {word:"dominant", ipa:"/ˈdɑːmɪnənt/", pos:"adj.", zh:"主导的", def:"stronger or more important than others", example:"Blue is the ___ color here.", pack:"ielts5", level:4},
  {word:"economical", ipa:"/ˌiːkəˈnɑːmɪkl/", pos:"adj.", zh:"节约的", def:"cheap and using little money or fuel", example:"This car is very ___.", pack:"ielts5", level:3},
  {word:"element", ipa:"/ˈelɪmənt/", pos:"n.", zh:"元素；要素", def:"one basic part of something", example:"Trust is a key ___ of friendship.", pack:"ielts5", level:2},
  {word:"embody", ipa:"/ɪmˈbɑːdi/", pos:"v.", zh:"体现", def:"to be a clear example of an idea", example:"She ___s hard work.", pack:"ielts5", level:4},
  {word:"emphasis", ipa:"/ˈemfəsɪs/", pos:"n.", zh:"强调", def:"special importance given to something", example:"The school puts ___ on sports.", pack:"ielts5", level:3},
  {word:"era", ipa:"/ˈerə/", pos:"n.", zh:"时代", def:"a long period of history", example:"We live in a digital ___.", pack:"ielts5", level:2},
  {word:"exhibit", ipa:"/ɪɡˈzɪbɪt/", pos:"v.", zh:"展示", def:"to show something in public", example:"The museum ___s ancient coins.", pack:"ielts5", level:3},
  {word:"expire", ipa:"/ɪkˈspaɪər/", pos:"v.", zh:"到期", def:"to end after a period of time", example:"My passport ___s next month.", pack:"ielts5", level:3},
  {word:"formula", ipa:"/ˈfɔːrmjələ/", pos:"n.", zh:"公式", def:"a set of numbers or rules for solving a problem", example:"We used a simple ___.", pack:"ielts5", level:4},
  {word:"identical", ipa:"/aɪˈdentɪkl/", pos:"adj.", zh:"完全相同的", def:"exactly the same", example:"The twins look ___.", pack:"ielts5", level:3},
  {word:"ignore", ipa:"/ɪɡˈnɔːr/", pos:"v.", zh:"忽视", def:"to pay no attention to something", example:"He ___d my warning.", pack:"ielts5", level:2},
  {word:"incident", ipa:"/ˈɪnsɪdənt/", pos:"n.", zh:"事件", def:"something that happens, especially something bad", example:"Police reported the ___.", pack:"ielts5", level:3},
  {word:"inquiry", ipa:"/ɪnˈkwaɪəri/", pos:"n.", zh:"调查；询问", def:"the act of asking or investigating", example:"The police opened an ___.", pack:"ielts5", level:3},
  {word:"inspect", ipa:"/ɪnˈspekt/", pos:"v.", zh:"检查", def:"to look at something carefully", example:"The officer ___ed our bags.", pack:"ielts5", level:3},
  {word:"interval", ipa:"/ˈɪntərvl/", pos:"n.", zh:"间隔", example:"There is an ___ between classes.", pack:"ielts5", level:3},
  {word:"intuition", ipa:"/ˌɪntuˈɪʃn/", pos:"n.", zh:"直觉", def:"the ability to know without reasoning", example:"Her ___ told her not to go.", pack:"ielts5", level:4},
  {word:"largely", ipa:"/ˈlɑːrdʒli/", pos:"adv.", zh:"大部分", def:"mostly", example:"The result was ___ positive.", pack:"ielts5", level:3},
  {word:"major", ipa:"/ˈmeɪdʒər/", pos:"adj.", zh:"主要的", def:"very important or large", example:"Traffic is a ___ problem.", pack:"ielts5", level:1},
  {word:"mature", ipa:"/məˈtʃʊr/", pos:"adj.", zh:"成熟的", def:"fully grown or developed", example:"The market is ___.", pack:"ielts5", level:3},
  {word:"medium", ipa:"/ˈmiːdiəm/", pos:"n.", zh:"媒介；中间", def:"a way of communicating; the middle", example:"Film is a popular ___.", pack:"ielts5", level:2},
  {word:"merely", ipa:"/ˈmɪrli/", pos:"adv.", zh:"仅仅", def:"only, just", example:"It is ___ a suggestion.", pack:"ielts5", level:3},
  {word:"minimize", ipa:"/ˈmɪnɪmaɪz/", pos:"v.", zh:"最小化", def:"to make something as small as possible", example:"Wear gloves to ___ the risk.", pack:"ielts5", level:3},
  {word:"moderate", ipa:"/ˈmɑːdərət/", pos:"adj.", zh:"适度的", def:"average, not extreme", example:"Do ___ exercise each day.", pack:"ielts5", level:3},
  {word:"motivate", ipa:"/ˈmoʊtɪveɪt/", pos:"v.", zh:"激励", def:"to make someone want to do something", example:"Praise ___s students.", pack:"ielts5", level:3},
  {word:"offend", ipa:"/əˈfend/", pos:"v.", zh:"冒犯", def:"to make someone feel upset or angry", example:"I didn't mean to ___ you.", pack:"ielts5", level:2},
  {word:"operate", ipa:"/ˈɑːpəreɪt/", pos:"v.", zh:"操作；运转", def:"to work or run a machine or business", example:"She ___s a small farm.", pack:"ielts5", level:2},
  {word:"option", ipa:"/ˈɑːpʃn/", pos:"n.", zh:"选项", def:"one of the choices available", example:"We have two ___.", pack:"ielts5", level:2},
  {word:"parallel", ipa:"/ˈpærəlel/", pos:"adj.", zh:"平行的", def:"running side by side without meeting", example:"The two roads are ___.", pack:"ielts5", level:3},
  {word:"peculiar", ipa:"/pɪˈkjuːliər/", pos:"adj.", zh:"奇怪的", def:"strange or unusual", example:"There is a ___ smell here.", pack:"ielts5", level:3},
  {word:"period", ipa:"/ˈpɪriəd/", pos:"n.", zh:"时期", def:"a length of time", example:"The castle dates from that ___.", pack:"ielts5", level:1},
  {word:"persistent", ipa:"/pərˈsɪstənt/", pos:"adj.", zh:"持续的；坚持的", def:"continuing firmly; lasting a long time", example:"His ___ cough worried us.", pack:"ielts5", level:4},
  {word:"portion", ipa:"/ˈpɔːrʃn/", pos:"n.", zh:"一部分", def:"a part of something", example:"A large ___ of the budget is for housing.", pack:"ielts5", level:3},
  {word:"primary", ipa:"/ˈpraɪmeri/", pos:"adj.", zh:"主要的", def:"most important", example:"Our ___ goal is safety.", pack:"ielts5", level:3},
  {word:"proclaim", ipa:"/prəˈkleɪm/", pos:"v.", zh:"宣告", def:"to announce officially", example:"The king ___ed a holiday.", pack:"ielts5", level:4},
  {word:"profile", ipa:"/ˈproʊfaɪl/", pos:"n.", zh:"简介；侧面", def:"a short description of a person; a side view", example:"Read her ___ on the site.", pack:"ielts5", level:3},
  {word:"prolong", ipa:"/prəˈlɔːŋ/", pos:"v.", zh:"延长", def:"to make something last longer", example:"We ___ed our stay by two days.", pack:"ielts5", level:4},
  {word:"prosper", ipa:"/ˈprɑːspər/", pos:"v.", zh:"繁荣", def:"to become successful and rich", example:"The town ___ed after the railway came.", pack:"ielts5", level:3},
  {word:"random", ipa:"/ˈrændəm/", pos:"adj.", zh:"随机的", def:"chosen without a plan or pattern", example:"Pick a ___ number.", pack:"ielts5", level:3},
  {word:"range", ipa:"/reɪndʒ/", pos:"n.", zh:"范围", def:"the area between limits", example:"The price ___ is wide.", pack:"ielts5", level:2},
  {word:"react", ipa:"/riˈækt/", pos:"v.", zh:"反应", def:"to act in response to something", example:"How did she ___ to the news?", pack:"ielts5", level:2},
  {word:"recover", ipa:"/rɪˈkʌvər/", pos:"v.", zh:"恢复", def:"to get better after illness or loss", example:"He ___ed from the flu.", pack:"ielts5", level:2},
  {word:"regulate", ipa:"/ˈreɡjuleɪt/", pos:"v.", zh:"监管", def:"to control by rules or laws", example:"The market is tightly __d.", pack:"ielts5", level:4},
  {word:"resemble", ipa:"/rɪˈzembl/", pos:"v.", zh:"像", def:"to look or be similar to someone", example:"She ___s her mother.", pack:"ielts5", level:4},
  {word:"reserve", ipa:"/rɪˈzɜːrv/", pos:"v./n.", zh:"预订；储备", def:"to keep for later use; to book", example:"I ___d a table for two.", pack:"ielts5", level:2},
  {word:"resist", ipa:"/rɪˈzɪst/", pos:"v.", zh:"抵抗", def:"to fight against or refuse to accept", example:"I can't ___ chocolate.", pack:"ielts5", level:3},
  {word:"resolution", ipa:"/ˌrezəˈluːʃn/", pos:"n.", zh:"决心；决议", def:"a firm decision; an official agreement", example:"Her New Year's ___ was to exercise.", pack:"ielts5", level:4},
  {word:"reverse", ipa:"/rɪˈvɜːrs/", pos:"v.", zh:"逆转", def:"to change to the opposite direction", example:"The decision was ___d.", pack:"ielts5", level:3},
  {word:"rival", ipa:"/ˈraɪvl/", pos:"n.", zh:"对手", def:"a person or group you compete with", example:"The two firms are old ___.", pack:"ielts5", level:3},
  {word:"scheme", ipa:"/skiːm/", pos:"n.", zh:"计划；方案", def:"an organized plan, often for a purpose", example:"The city has a recycling ___.", pack:"ielts5", level:3},
  {word:"scope", ipa:"/skoʊp/", pos:"n.", zh:"范围", def:"the amount or area that something covers", example:"The task is outside my ___.", pack:"ielts5", level:4},
  {word:"settle", ipa:"/ˈsetl/", pos:"v.", zh:"解决；定居", def:"to end an argument; to live in a place", example:"They ___d the dispute.", pack:"ielts5", level:2},
  {word:"severe", ipa:"/sɪˈvɪr/", pos:"adj.", zh:"严重的", def:"very bad or serious", example:"The storm caused ___ damage.", pack:"ielts5", level:3},
  {word:"shift", ipa:"/ʃɪft/", pos:"v./n.", zh:"转移；轮班", def:"to move or change position", example:"The focus ___ed to costs.", pack:"ielts5", level:2},
  {word:"solely", ipa:"/ˈsoʊlli/", pos:"adv.", zh:"仅仅", def:"only; without others", example:"You are ___ responsible.", pack:"ielts5", level:3},
  {word:"stable", ipa:"/ˈsteɪbl/", pos:"adj.", zh:"稳定的", def:"not changing or moving suddenly", example:"Keep the boat ___.", pack:"ielts5", level:2},
  {word:"stimulate", ipa:"/ˈstɪmjuleɪt/", pos:"v.", zh:"刺激；激发", def:"to encourage activity or growth", example:"Coffee ___s the brain.", pack:"ielts5", level:4},
  {word:"strive", ipa:"/straɪv/", pos:"v.", zh:"努力", def:"to try very hard to achieve something", example:"We ___ to improve quality.", pack:"ielts5", level:4},
  {word:"substitute", ipa:"/ˈsʌbstɪtuːt/", pos:"v./n.", zh:"代替", def:"to use something instead of another", example:"Honey can ___ sugar.", pack:"ielts5", level:3},
  {word:"summarize", ipa:"/ˈsʌməraɪz/", pos:"v.", zh:"总结", def:"to give the main points briefly", example:"___ the article in two lines.", pack:"ielts5", level:3},
  {word:"surge", ipa:"/sɜːrdʒ/", pos:"n.", zh:"激增", def:"a sudden large increase", example:"There was a ___ in demand.", pack:"ielts5", level:3},
  {word:"tackle", ipa:"/ˈtækl/", pos:"v.", zh:"处理（难题）", def:"to deal with a hard problem", example:"We must ___ the housing issue.", pack:"ielts5", level:3},
  {word:"temporary", ipa:"/ˈtempəreri/", pos:"adj.", zh:"临时的", def:"lasting only for a short time", example:"He took a ___ job.", pack:"ielts5", level:2},
  {word:"tension", ipa:"/ˈtenʃn/", pos:"n.", zh:"紧张", def:"a feeling of nervous worry", example:"There is ___ between the teams.", pack:"ielts5", level:3},
  {word:"terminal", ipa:"/ˈtɜːrmɪnl/", pos:"adj.", zh:"末期的；终端的", def:"at the end; causing death", example:"The patient is in a ___ illness.", pack:"ielts5", level:4},
  {word:"territory", ipa:"/ˈterətɔːri/", pos:"n.", zh:"领土", def:"land controlled by a country", example:"The bird guards its ___.", pack:"ielts5", level:3},
  {word:"tolerate", ipa:"/ˈtɑːləreɪt/", pos:"v.", zh:"忍受", def:"to accept something unpleasant", example:"She can't ___ noise.", pack:"ielts5", level:3},
  {word:"transfer", ipa:"/trænsˈfɜːr/", pos:"v.", zh:"转移", def:"to move from one place to another", example:"She ___red to a new school.", pack:"ielts5", level:2},
  {word:"universal", ipa:"/ˌjuːnɪˈvɜːrsl/", pos:"adj.", zh:"普遍的", def:"true for everyone or everywhere", example:"Music is a ___ language.", pack:"ielts5", level:3},
  {word:"vague", ipa:"/veɪɡ/", pos:"adj.", zh:"模糊的", def:"not clear or exact", example:"He gave a ___ answer.", pack:"ielts5", level:3},
  {word:"vanish", ipa:"/ˈvænɪʃ/", pos:"v.", zh:"消失", def:"to disappear suddenly", example:"The ship ___ed in the fog.", pack:"ielts5", level:3},
  {word:"via", ipa:"/ˈvaɪə/", pos:"prep.", zh:"经由", def:"by way of", example:"We flew to Rome ___ Dubai.", pack:"ielts5", level:2},
  {word:"virtue", ipa:"/ˈvɜːrtʃuː/", pos:"n.", zh:"美德", def:"a good quality in a person", example:"Patience is a ___.", pack:"ielts5", level:3},
  {word:"visual", ipa:"/ˈvɪʒuəl/", pos:"adj.", zh:"视觉的", def:"related to seeing", example:"The lesson used ___ aids.", pack:"ielts5", level:3},
  {word:"vital", ipa:"/ˈvaɪtl/", pos:"adj.", zh:"至关重要的", def:"extremely important", example:"Water is ___ for life.", pack:"ielts5", level:3},
  {word:"vivid", ipa:"/ˈvɪvɪd/", pos:"adj.", zh:"生动的", def:"producing clear and strong pictures in the mind", example:"She has a ___ imagination.", pack:"ielts5", level:3},
  {word:"yield", ipa:"/jiːld/", pos:"v./n.", zh:"产生；产量", def:"to produce something; the amount produced", example:"The field ___s rich crops.", pack:"ielts5", level:4}
  // ===BATCH-B-END===
);
