// =========================================================
// 雅思核心词包 · 第8批（IELTS Batch 8）—— 通用主题扩展
// 部分词条已带扩展字段：syn 同义词[]、root 词根拆解（展示架子已支持）。
// =========================================================
WORDS.push(
  {word:"absorb", ipa:"/əbˈzɔːrb/", pos:"v.", zh:"吸收；理解", def:"to take in liquid, heat or information", example:"Paper ___s water quickly.", root:"ab(去)+sorb(吸)→吸收", syn:["take in","soak up"], pack:"ielts8", level:3},
  {word:"accomplish", ipa:"/əˈkɑːmplɪʃ/", pos:"v.", zh:"完成", def:"to finish something successfully", example:"We ___ed the task on time.", syn:["achieve","complete"], pack:"ielts8", level:3},
  {word:"across", ipa:"/əˈkrɔːs/", pos:"prep.", zh:"穿过；横跨", def:"from one side to the other", example:"We swam ___ the lake.", pack:"ielts8", level:1},
  {word:"addition", ipa:"/əˈdɪʃn/", pos:"n.", zh:"增加；加法", def:"something added; the act of adding", example:"In ___ to tea, we had cake.", pack:"ielts8", level:2},
  {word:"affection", ipa:"/əˈfekʃn/", pos:"n.", zh:"喜爱", def:"a warm feeling of liking someone", example:"She showed ___ for her old dog.", syn:["fondness","love"], pack:"ielts8", level:3},
  {word:"agenda", ipa:"/əˈdʒendə/", pos:"n.", zh:"议程", def:"a list of things to discuss", example:"The first item on the ___ is safety.", root:"ag(做)+enda→要做的事→议程", pack:"ielts8", level:3},
  {word:"alert", ipa:"/əˈlɜːrt/", pos:"adj./n.", zh:"警觉的；警报", def:"quick to notice; a warning", example:"Stay ___ while driving.", pack:"ielts8", level:2},
  {word:"allowance", ipa:"/əˈlaʊəns/", pos:"n.", zh:"零花钱；津贴", def:"money given regularly to someone", example:"The kids get a weekly ___.", pack:"ielts8", level:2},
  {word:"alternative", ipa:"/ɔːlˈtɜːrnətɪv/", pos:"n./adj.", zh:"替代方案", def:"another choice", example:"We need an ___ plan.", root:"alter(其他)+native→别的→替代", syn:["option","choice"], pack:"ielts8", level:3},
  {word:"amuse", ipa:"/əˈmjuːz/", pos:"v.", zh:"逗乐", def:"to make someone laugh or have fun", example:"The clown ___d the kids.", syn:["entertain"], pack:"ielts8", level:2},
  {word:"anniversary", ipa:"/ˌænɪˈvɜːrsəri/", pos:"n.", zh:"周年纪念", def:"the yearly date of an event", example:"They celebrated their tenth ___.", root:"anni(年)+vers(转)+ary→一年一转→周年", pack:"ielts8", level:3},
  {word:"applause", ipa:"/əˈplɔːz/", pos:"n.", zh:"掌声", def:"the sound of clapping hands", example:"The singer got loud ___.", pack:"ielts8", level:3},
  {word:"application", ipa:"/ˌæplɪˈkeɪʃn/", pos:"n.", zh:"申请；应用", def:"a formal request; a use", example:"She sent an ___ for the job.", pack:"ielts8", level:3},
  {word:"appreciate", ipa:"/əˈpriːʃieɪt/", pos:"v.", zh:"感激；欣赏", def:"to be thankful for; to value", example:"I really ___ your help.", root:"ap+preci(价值)+ate→看到价值→欣赏", syn:["value","be grateful for"], pack:"ielts8", level:3},
  {word:"approve", ipa:"/əˈpruːv/", pos:"v.", zh:"批准；赞成", def:"to agree officially or to like", example:"The plan was ___d.", root:"ap+prove(证明)→验证通过→批准", pack:"ielts8", level:2},
  {word:"article", ipa:"/ˈɑːrtɪkl/", pos:"n.", zh:"文章；物品", def:"a piece of writing; a thing", example:"She wrote an ___ about travel.", pack:"ielts8", level:1},
  {word:"awake", ipa:"/əˈweɪk/", pos:"adj.", zh:"醒着的", def:"not sleeping", example:"The baby is still ___.", pack:"ielts8", level:2},
  {word:"bother", ipa:"/ˈbɑːðər/", pos:"v.", zh:"打扰；费心", def:"to trouble someone", example:"Sorry to ___ you so late.", pack:"ielts8", level:2},
  {word:"candidate", ipa:"/ˈkændɪdət/", pos:"n.", zh:"候选人", def:"a person trying to get a job or position", example:"There are five ___s for the role.", pack:"ielts8", level:3},
  {word:"cheat", ipa:"/tʃiːt/", pos:"v.", zh:"作弊；欺骗", def:"to act dishonestly to win", example:"Never ___ in an exam.", syn:["trick"], pack:"ielts8", level:2},
  {word:"check", ipa:"/tʃek/", pos:"v.", zh:"检查", def:"to look at to make sure something is right", example:"___ your answers again.", pack:"ielts8", level:1},
  {word:"client", ipa:"/ˈklaɪənt/", pos:"n.", zh:"客户", def:"a person who pays for a service", example:"She meets her ___s on Fridays.", syn:["customer"], pack:"ielts8", level:3},
  {word:"college", ipa:"/ˈkɑːlɪdʒ/", pos:"n.", zh:"学院；大学", def:"a school after high school", example:"He studies art at ___.", pack:"ielts8", level:1},
  {word:"comment", ipa:"/ˈkɑːment/", pos:"n./v.", zh:"评论", def:"an opinion in words", example:"She left a nice ___ on my photo.", pack:"ielts8", level:2},
  {word:"commercial", ipa:"/kəˈmɜːrʃl/", pos:"adj.", zh:"商业的", def:"related to business and selling", example:"The area has many ___ buildings.", root:"com+merc(贸易)+ial→商业的", pack:"ielts8", level:3},
  {word:"company", ipa:"/ˈkʌmpəni/", pos:"n.", zh:"公司；陪伴", def:"a business; being with someone", example:"He works for a big ___.", pack:"ielts8", level:1},
  {word:"complaint", ipa:"/kəmˈpleɪnt/", pos:"n.", zh:"投诉", def:"words that say you are unhappy", example:"She made a ___ about the noise.", pack:"ielts8", level:3},
  {word:"concert", ipa:"/ˈkɑːnsərt/", pos:"n.", zh:"音乐会", def:"a live music show", example:"We went to a rock ___.", pack:"ielts8", level:1},
  {word:"costume", ipa:"/ˈkɑːstuːm/", pos:"n.", zh:"戏服", def:"clothes worn for a play or party", example:"He wore a dragon ___.", pack:"ielts8", level:2},
  {word:"crowd", ipa:"/kraʊd/", pos:"n.", zh:"人群", def:"a large group of people", example:"A big ___ watched the show.", pack:"ielts8", level:1},
  {word:"delight", ipa:"/dɪˈlaɪt/", pos:"n.", zh:"高兴", def:"great pleasure", example:"The gift filled her with ___.", pack:"ielts8", level:3},
  {word:"depart", ipa:"/dɪˈpɑːrt/", pos:"v.", zh:"出发", def:"to leave a place", example:"The train ___s at nine.", root:"de(离开)+part(分)→分开→出发", syn:["leave"], pack:"ielts8", level:3},
  {word:"dialogue", ipa:"/ˈdaɪəlɔːɡ/", pos:"n.", zh:"对话", def:"a conversation between people", example:"The film has funny ___.", root:"dia(对)+logue(话)→对话", pack:"ielts8", level:2},
  {word:"differ", ipa:"/ˈdɪfər/", pos:"v.", zh:"不同", def:"to be not the same", example:"The twins ___ in character.", root:"dif(分开)+fer(拿)→各拿各的→不同", pack:"ielts8", level:2},
  {word:"digest", ipa:"/daɪˈdʒest/", pos:"v.", zh:"消化", def:"to change food in the body so you can use it", example:"It takes time to ___ heavy food.", root:"di(分开)+gest(携带)→运走→消化", pack:"ielts8", level:3},
  {word:"direct", ipa:"/dəˈrekt/", pos:"adj./v.", zh:"直接的；指挥", def:"straight; to lead", example:"This is a ___ flight.", pack:"ielts8", level:2},
  {word:"double", ipa:"/ˈdʌbl/", pos:"adj.", zh:"两倍的", def:"twice as much or many", example:"I ordered a ___ coffee.", pack:"ielts8", level:1},
  {word:"downtown", ipa:"/ˌdaʊnˈtaʊn/", pos:"n.", zh:"市中心", def:"the main business area of a city", example:"We had lunch ___.", pack:"ielts8", level:2},
  {word:"eager", ipa:"/ˈiːɡər/", pos:"adj.", zh:"热切的", def:"wanting very much to do something", example:"The kids were ___ to go outside.", syn:["keen","excited"], pack:"ielts8", level:3},
  {word:"enough", ipa:"/ɪˈnʌf/", pos:"adj.", zh:"足够的", def:"as much as needed", example:"We have ___ time.", pack:"ielts8", level:1},
  {word:"enter", ipa:"/ˈentər/", pos:"v.", zh:"进入", def:"to go into a place", example:"Please ___ the room quietly.", pack:"ielts8", level:1},
  {word:"excuse", ipa:"/ɪkˈskjuːs/", pos:"n.", zh:"借口", def:"a reason given for a mistake", example:"He made an ___ for being late.", pack:"ielts8", level:2},
  {word:"extra", ipa:"/ˈekstrə/", pos:"adj.", zh:"额外的", def:"more than usual", example:"We need ___ chairs.", pack:"ielts8", level:1},
  {word:"faith", ipa:"/feɪθ/", pos:"n.", zh:"信念", def:"strong trust in something", example:"She has ___ in her team.", syn:["belief"], pack:"ielts8", level:3},
  {word:"favorite", ipa:"/ˈfeɪvərɪt/", pos:"adj.", zh:"最喜爱的", def:"liked the most", example:"Blue is my ___ color.", pack:"ielts8", level:1},
  {word:"firm", ipa:"/fɜːrm/", pos:"adj./n.", zh:"坚固的；公司", def:"not soft; a business", example:"The mattress is ___.", pack:"ielts8", level:2},
  {word:"further", ipa:"/ˈfɜːrðər/", pos:"adj./adv.", zh:"更远的；进一步的", def:"more; at a greater distance", example:"Do you have any ___ questions?", pack:"ielts8", level:2},
  {word:"global", ipa:"/ˈɡloʊbl/", pos:"adj.", zh:"全球的", def:"relating to the whole world", example:"___ warming is a real issue.", pack:"ielts8", level:2},
  {word:"grade", ipa:"/ɡreɪd/", pos:"n.", zh:"成绩；年级", def:"a mark at school; a level", example:"She got a good ___ in math.", pack:"ielts8", level:1},
  {word:"happily", ipa:"/ˈhæpɪli/", pos:"adv.", zh:"快乐地", def:"in a happy way", example:"The kids played ___.", pack:"ielts8", level:1},
  {word:"harm", ipa:"/hɑːrm/", pos:"v./n.", zh:"伤害", def:"to hurt someone or something", example:"Smoking ___s your health.", syn:["damage","hurt"], pack:"ielts8", level:2},
  {word:"immediate", ipa:"/ɪˈmiːdiət/", pos:"adj.", zh:"立即的", def:"happening at once", example:"We need ___ action.", root:"im(无)+medi(中间)+ate→没有间隔→立即", pack:"ielts8", level:3},
  {word:"impress", ipa:"/ɪmˈpres/", pos:"v.", zh:"给…深刻印象", def:"to make someone admire you", example:"Her speech ___ed everyone.", root:"im(往里)+press(压)→压进心里→印象深刻", pack:"ielts8", level:3},
  {word:"intend", ipa:"/ɪnˈtend/", pos:"v.", zh:"打算", def:"to plan to do something", example:"I ___ to visit you soon.", root:"in+tend(伸)→伸手向→打算", pack:"ielts8", level:2},
  {word:"joy", ipa:"/dʒɔɪ/", pos:"n.", zh:"快乐", def:"great happiness", example:"The news brought her ___.", pack:"ielts8", level:2},
  {word:"keen", ipa:"/kiːn/", pos:"adj.", zh:"热衷的", def:"very interested in something", example:"She is ___ on music.", syn:["eager"], pack:"ielts8", level:3},
  {word:"kindness", ipa:"/ˈkaɪndnəs/", pos:"n.", zh:"善良", def:"the quality of being kind", example:"Thank you for your ___.", pack:"ielts8", level:2},
  {word:"local", ipa:"/ˈloʊkl/", pos:"adj.", zh:"当地的", def:"related to a nearby area", example:"Ask the ___ people for help.", pack:"ielts8", level:2},
  {word:"lovely", ipa:"/ˈlʌvli/", pos:"adj.", zh:"可爱的", def:"very nice or pleasant", example:"What a ___ day!", pack:"ielts8", level:1},
  {word:"message", ipa:"/ˈmesɪdʒ/", pos:"n.", zh:"信息", def:"a short written or spoken communication", example:"Leave a ___ for me.", pack:"ielts8", level:1},
  {word:"national", ipa:"/ˈnæʃnəl/", pos:"adj.", zh:"国家的", def:"relating to a country", example:"Today is a ___ holiday.", pack:"ielts8", level:2},
  {word:"native", ipa:"/ˈneɪtɪv/", pos:"adj./n.", zh:"本地的", def:"born in a place; original", example:"English is her ___ language.", pack:"ielts8", level:2},
  {word:"official", ipa:"/əˈfɪʃl/", pos:"adj.", zh:"官方的", def:"approved by an authority", example:"This is the ___ report.", pack:"ielts8", level:2},
  {word:"ordinary", ipa:"/ˈɔːrdneri/", pos:"adj.", zh:"普通的", def:"normal, not special", example:"It was an ___ day.", syn:["common","normal"], pack:"ielts8", level:2},
  {word:"peaceful", ipa:"/ˈpiːsfl/", pos:"adj.", zh:"平静的", def:"quiet and calm", example:"The lake looks ___.", pack:"ielts8", level:2},
  {word:"possible", ipa:"/ˈpɑːsəbl/", pos:"adj.", zh:"可能的", def:"able to happen", example:"It is ___ to walk there.", pack:"ielts8", level:1},
  {word:"regular", ipa:"/ˈreɡjələr/", pos:"adj.", zh:"规律的；定期的", def:"happening at equal times", example:"He does ___ exercise.", pack:"ielts8", level:2},
  {word:"relative", ipa:"/ˈrelətɪv/", pos:"n.", zh:"亲戚", def:"a person in your family", example:"All her ___s came to the wedding.", pack:"ielts8", level:2},
  {word:"spread", ipa:"/spred/", pos:"v.", zh:"传播；铺开", def:"to open wider or reach more people", example:"News ___ quickly online.", pack:"ielts8", level:2},
  {word:"stranger", ipa:"/ˈstreɪndʒər/", pos:"n.", zh:"陌生人", def:"a person you do not know", example:"Don't trust ___.", pack:"ielts8", level:2},
  {word:"suffer", ipa:"/ˈsʌfər/", pos:"v.", zh:"遭受", def:"to feel pain or experience something bad", example:"He ___s from headaches.", pack:"ielts8", level:2},
  {word:"suppose", ipa:"/səˈpoʊz/", pos:"v.", zh:"猜想", def:"to think something is true", example:"I ___ you are right.", pack:"ielts8", level:2},
  {word:"surround", ipa:"/səˈraʊnd/", pos:"v.", zh:"环绕", def:"to be all around something", example:"Trees ___ the lake.", pack:"ielts8", level:3},
  {word:"talent", ipa:"/ˈtælənt/", pos:"n.", zh:"天赋", def:"a natural ability", example:"She has a ___ for music.", pack:"ielts8", level:3},
  {word:"thousand", ipa:"/ˈθaʊznd/", pos:"num.", zh:"千", def:"the number 1,000", example:"The hall holds a ___ people.", pack:"ielts8", level:1},
  {word:"truly", ipa:"/ˈtruːli/", pos:"adv.", zh:"真正地", def:"really", example:"I am ___ grateful.", pack:"ielts8", level:2},
  {word:"unusual", ipa:"/ʌnˈjuːʒuəl/", pos:"adj.", zh:"不寻常的", def:"not common or normal", example:"She has an ___ hobby.", root:"un(不)+usual(通常)→不寻常", syn:["strange","rare"], pack:"ielts8", level:2},
  // ===BATCH-A-END===
);
