// ============================================================
// 单词库（可自由增删，按同样格式加一行即可）
// 字段说明：
//   word    英文单词
//   ipa     美式音标
//   pos     词性（n.名词 v.动词 adj.形容词 adv.副词 prep.介词 conj.连词）
//   zh      中文释义（写英文单词时的提示）
//   def     英文释义（学习模式用）
//   example 例句，目标词用 "___" 挖空（句子填空模式用）
//   level   难度 1=基础 2=进阶 3=高阶 4=学术
// ============================================================
const WORDS = [
  // ---------- Level 1 基础（日常高频） ----------
  {word:"abandon", ipa:"/əˈbændən/", pos:"v.", zh:"放弃；抛弃", def:"to leave someone or something completely and permanently", example:"The sailors had to ___ the sinking ship.", level:1},
  {word:"achieve", ipa:"/əˈtʃiːv/", pos:"v.", zh:"实现；达到", def:"to succeed in doing or getting something after effort", example:"She worked hard to ___ her goal.", level:1},
  {word:"advice", ipa:"/ədˈvaɪs/", pos:"n.", zh:"建议；忠告", def:"an opinion you give someone about what they should do", example:"Can you give me some ___ on this problem?", level:1},
  {word:"afford", ipa:"/əˈfɔːrd/", pos:"v.", zh:"负担得起", def:"to have enough money or time to do something", example:"We can't ___ to buy a new car this year.", level:1},
  {word:"agree", ipa:"/əˈɡriː/", pos:"v.", zh:"同意", def:"to have the same opinion as someone else", example:"I ___ with you completely.", level:1},
  {word:"allow", ipa:"/əˈlaʊ/", pos:"v.", zh:"允许", def:"to let someone do something", example:"My parents don't ___ me to stay out late.", level:1},
  {word:"ancient", ipa:"/ˈeɪnʃənt/", pos:"adj.", zh:"古代的；古老的", def:"very old, from a long time ago", example:"They discovered an ___ city under the desert.", level:1},
  {word:"appear", ipa:"/əˈpɪr/", pos:"v.", zh:"出现；似乎", def:"to become visible; to seem", example:"The sun began to ___ over the hill.", level:1},
  {word:"arrange", ipa:"/əˈreɪndʒ/", pos:"v.", zh:"安排；整理", def:"to plan or organize something", example:"I need to ___ a meeting for next week.", level:1},
  {word:"arrive", ipa:"/əˈraɪv/", pos:"v.", zh:"到达", def:"to reach a place", example:"The train will ___ at noon.", level:1},
  {word:"attend", ipa:"/əˈtend/", pos:"v.", zh:"参加；出席", def:"to be present at an event or place", example:"Will you ___ the meeting tomorrow?", level:1},
  {word:"avoid", ipa:"/əˈvɔɪd/", pos:"v.", zh:"避免；避开", def:"to stay away from something", example:"Try to ___ making the same mistake again.", level:1},
  {word:"basic", ipa:"/ˈbeɪsɪk/", pos:"adj.", zh:"基本的；基础的", def:"forming the simplest and most important part of something", example:"This course teaches ___ computer skills.", level:1},
  {word:"borrow", ipa:"/ˈbɑːroʊ/", pos:"v.", zh:"借入", def:"to take something and return it later", example:"Can I ___ your pen for a minute?", level:1},
  {word:"certain", ipa:"/ˈsɜːrtn/", pos:"adj.", zh:"确定的；某些", def:"sure; particular but not named", example:"I'm ___ that he will come.", level:1},
  {word:"choose", ipa:"/tʃuːz/", pos:"v.", zh:"选择", def:"to pick one thing from several", example:"You must ___ between the two options.", level:1},
  {word:"common", ipa:"/ˈkɑːmən/", pos:"adj.", zh:"常见的；共同的", def:"happening often or shared by many", example:"It's a ___ mistake among beginners.", level:1},
  {word:"compare", ipa:"/kəmˈper/", pos:"v.", zh:"比较", def:"to examine differences and similarities", example:"Let's ___ the two prices before buying.", level:1},
  {word:"complete", ipa:"/kəmˈpliːt/", pos:"v.", zh:"完成", def:"to finish something", example:"Please ___ the form and sign it.", level:1},
  {word:"consider", ipa:"/kənˈsɪdər/", pos:"v.", zh:"考虑；认为", def:"to think about something carefully", example:"We should ___ all the options first.", level:1},
  {word:"continue", ipa:"/kənˈtɪnjuː/", pos:"v.", zh:"继续", def:"to keep doing something", example:"Let's ___ our discussion after lunch.", level:1},
  {word:"create", ipa:"/kriˈeɪt/", pos:"v.", zh:"创造；创建", def:"to make something new", example:"The artist wants to ___ something original.", level:1},
  {word:"decide", ipa:"/dɪˈsaɪd/", pos:"v.", zh:"决定", def:"to make a choice about something", example:"We need to ___ where to go on vacation.", level:1},
  {word:"describe", ipa:"/dɪˈskraɪb/", pos:"v.", zh:"描述", def:"to say what something is like", example:"Can you ___ the man you saw?", level:1},
  {word:"develop", ipa:"/dɪˈveləp/", pos:"v.", zh:"发展；开发", def:"to grow or make something more advanced", example:"The company plans to ___ a new app.", level:1},
  {word:"discuss", ipa:"/dɪˈskʌs/", pos:"v.", zh:"讨论", def:"to talk about something with others", example:"Let's ___ the plan in detail.", level:1},
  {word:"effect", ipa:"/ɪˈfekt/", pos:"n.", zh:"效果；影响", def:"a change caused by something", example:"The new law had a positive ___ on the city.", level:1},
  {word:"effort", ipa:"/ˈefərt/", pos:"n.", zh:"努力", def:"the physical or mental energy used to do something", example:"Success requires a lot of ___ .", level:1},
  {word:"encourage", ipa:"/ɪnˈkɜːrɪdʒ/", pos:"v.", zh:"鼓励", def:"to give someone confidence to do something", example:"Teachers should ___ students to ask questions.", level:1},
  {word:"environment", ipa:"/ɪnˈvaɪrənmənt/", pos:"n.", zh:"环境", def:"the natural world, or the conditions around you", example:"We must protect the ___ from pollution.", level:1},
  {word:"especially", ipa:"/ɪˈspeʃəli/", pos:"adv.", zh:"尤其；特别", def:"more than usual or more than others", example:"I love fruit, ___ apples.", level:1},
  {word:"experience", ipa:"/ɪkˈspɪriəns/", pos:"n.", zh:"经验；经历", def:"knowledge or skill gained from doing something", example:"She has years of ___ in teaching.", level:1},
  {word:"explain", ipa:"/ɪkˈspleɪn/", pos:"v.", zh:"解释", def:"to make something clear to understand", example:"Could you ___ this rule to me?", level:1},
  {word:"familiar", ipa:"/fəˈmɪliər/", pos:"adj.", zh:"熟悉的", def:"well known or easy to recognize", example:"That song sounds ___ to me.", level:1},
  {word:"focus", ipa:"/ˈfoʊkəs/", pos:"v.", zh:"集中；专注", def:"to give attention to one thing", example:"Try to ___ on your studies.", level:1},
  {word:"improve", ipa:"/ɪmˈpruːv/", pos:"v.", zh:"改善；提高", def:"to make something better", example:"Practice will ___ your English.", level:1},
  {word:"include", ipa:"/ɪnˈkluːd/", pos:"v.", zh:"包括；包含", def:"to have something as a part", example:"The price doesn't ___ tax.", level:1},
  {word:"increase", ipa:"/ɪnˈkriːs/", pos:"v.", zh:"增加", def:"to become larger in number or amount", example:"The price will ___ next month.", level:1},
  {word:"influence", ipa:"/ˈɪnfluəns/", pos:"n.", zh:"影响", def:"the power to change how someone thinks or acts", example:"Parents have a big ___ on their children.", level:1},
  {word:"involve", ipa:"/ɪnˈvɑːlv/", pos:"v.", zh:"涉及；包含", def:"to include or require something", example:"The job will ___ a lot of travel.", level:1},
  {word:"issue", ipa:"/ˈɪʃuː/", pos:"n.", zh:"问题；议题", def:"an important topic or problem", example:"Climate change is a serious ___ .", level:1},
  {word:"method", ipa:"/ˈmeθəd/", pos:"n.", zh:"方法", def:"a way of doing something", example:"This is the best ___ to solve it.", level:1},
  {word:"offer", ipa:"/ˈɔːfər/", pos:"v.", zh:"提供", def:"to give or present something", example:"They ___ me a good job.", level:1},
  {word:"opportunity", ipa:"/ˌɑːpərˈtuːnəti/", pos:"n.", zh:"机会", def:"a chance to do something", example:"This is a great ___ to learn.", level:1},
  {word:"provide", ipa:"/prəˈvaɪd/", pos:"v.", zh:"提供", def:"to give something that is needed", example:"The hotel will ___ breakfast.", level:1},
  {word:"reduce", ipa:"/rɪˈduːs/", pos:"v.", zh:"减少；降低", def:"to make something smaller or less", example:"We need to ___ our spending.", level:1},
  {word:"require", ipa:"/rɪˈkwaɪər/", pos:"v.", zh:"需要；要求", def:"to need something", example:"This job will ___ a lot of patience.", level:1},
  {word:"result", ipa:"/rɪˈzʌlt/", pos:"n.", zh:"结果", def:"what happens at the end of an action", example:"The exam ___ will come out tomorrow.", level:1},
  {word:"situation", ipa:"/ˌsɪtʃuˈeɪʃn/", pos:"n.", zh:"情况；形势", def:"the conditions that exist at a particular time", example:"We are in a difficult ___ .", level:1},
  {word:"suggest", ipa:"/səˈdʒest/", pos:"v.", zh:"建议；暗示", def:"to give an idea or plan for someone to consider", example:"I ___ that we leave early.", level:1},

  // ---------- Level 2 进阶（写作/学术常用） ----------
  {word:"abundant", ipa:"/əˈbʌndənt/", pos:"adj.", zh:"丰富的；充裕的", def:"existing in large quantities", example:"The region has ___ natural resources.", level:2},
  {word:"access", ipa:"/ˈækses/", pos:"n.", zh:"进入；使用权", def:"the right or ability to use or enter something", example:"Students have free ___ to the library.", level:2},
  {word:"accurate", ipa:"/ˈækjərət/", pos:"adj.", zh:"准确的", def:"correct and exact", example:"The report must be ___ and clear.", level:2},
  {word:"adapt", ipa:"/əˈdæpt/", pos:"v.", zh:"适应；改编", def:"to change to fit a new situation", example:"Animals must ___ to survive.", level:2},
  {word:"adequate", ipa:"/ˈædɪkwət/", pos:"adj.", zh:"足够的；适当的", def:"enough for a particular purpose", example:"Make sure you get ___ sleep.", level:2},
  {word:"analyze", ipa:"/ˈænəlaɪz/", pos:"v.", zh:"分析", def:"to study something carefully in detail", example:"Scientists will ___ the data.", level:2},
  {word:"approach", ipa:"/əˈproʊtʃ/", pos:"n.", zh:"方法；途径", def:"a way of dealing with something", example:"We need a new ___ to this problem.", level:2},
  {word:"appropriate", ipa:"/əˈproʊpriət/", pos:"adj.", zh:"恰当的；合适的", def:"suitable or right for a situation", example:"Wear clothing ___ for the occasion.", level:2},
  {word:"benefit", ipa:"/ˈbenɪfɪt/", pos:"n.", zh:"好处；利益", def:"an advantage or helpful effect", example:"Exercise has many health ___ .", level:2},
  {word:"capacity", ipa:"/kəˈpæsəti/", pos:"n.", zh:"能力；容量", def:"the ability or amount something can hold", example:"The stadium has a ___ of 50,000.", level:2},
  {word:"challenge", ipa:"/ˈtʃælɪndʒ/", pos:"n.", zh:"挑战", def:"a difficult task that tests your ability", example:"Learning a language is a real ___ .", level:2},
  {word:"consequence", ipa:"/ˈkɑːnsɪkwens/", pos:"n.", zh:"后果；结果", def:"a result of an action, often bad", example:"You must accept the ___ of your choice.", level:2},
  {word:"consume", ipa:"/kənˈsuːm/", pos:"v.", zh:"消耗；消费", def:"to use up or eat and drink", example:"Cars ___ a lot of fuel.", level:2},
  {word:"contribute", ipa:"/kənˈtrɪbjuːt/", pos:"v.", zh:"贡献；促成", def:"to give or add something to help", example:"Everyone can ___ to the team's success.", level:2},
  {word:"crucial", ipa:"/ˈkruːʃl/", pos:"adj.", zh:"关键的；至关重要的", def:"extremely important", example:"Timing is ___ to the plan.", level:2},
  {word:"decline", ipa:"/dɪˈklaɪn/", pos:"v.", zh:"下降；衰退", def:"to become smaller, weaker, or worse", example:"Sales began to ___ last year.", level:2},
  {word:"demonstrate", ipa:"/ˈdemənstreɪt/", pos:"v.", zh:"证明；演示", def:"to show clearly that something is true", example:"The results ___ the theory.", level:2},
  {word:"derive", ipa:"/dɪˈraɪv/", pos:"v.", zh:"获得；源于", def:"to get something from a source", example:"Many words ___ from Latin.", level:2},
  {word:"distinguish", ipa:"/dɪˈstɪŋɡwɪʃ/", pos:"v.", zh:"区分；辨别", def:"to see the difference between things", example:"Can you ___ right from wrong?", level:2},
  {word:"efficient", ipa:"/ɪˈfɪʃnt/", pos:"adj.", zh:"高效的", def:"working well without wasting time or energy", example:"This is a more ___ way to work.", level:2},
  {word:"emerge", ipa:"/ɪˈmɜːrdʒ/", pos:"v.", zh:"出现；浮现", def:"to come out or appear", example:"New problems began to ___ .", level:2},
  {word:"establish", ipa:"/ɪˈstæblɪʃ/", pos:"v.", zh:"建立；确立", def:"to start or create something that lasts", example:"They plan to ___ a new company.", level:2},
  {word:"estimate", ipa:"/ˈestɪmeɪt/", pos:"v.", zh:"估计；估算", def:"to guess an amount or size roughly", example:"We ___ the cost at 100 dollars.", level:2},
  {word:"evaluate", ipa:"/ɪˈvæljueɪt/", pos:"v.", zh:"评估；评价", def:"to judge the value or quality of something", example:"Teachers ___ students' progress.", level:2},
  {word:"evidence", ipa:"/ˈevɪdəns/", pos:"n.", zh:"证据", def:"facts that show something is true", example:"There is no ___ to support the claim.", level:2},
  {word:"factor", ipa:"/ˈfæktər/", pos:"n.", zh:"因素", def:"one thing that affects a result", example:"Price is an important ___ .", level:2},
  {word:"generate", ipa:"/ˈdʒenəreɪt/", pos:"v.", zh:"产生；生成", def:"to produce or create something", example:"The panels ___ electricity from sunlight.", level:2},
  {word:"identify", ipa:"/aɪˈdentɪfaɪ/", pos:"v.", zh:"识别；确认", def:"to recognize or find out what something is", example:"Can you ___ the problem?", level:2},
  {word:"impact", ipa:"/ˈɪmpækt/", pos:"n.", zh:"影响；冲击", def:"a strong effect on something", example:"The news had a big ___ on him.", level:2},
  {word:"imply", ipa:"/ɪmˈplaɪ/", pos:"v.", zh:"暗示；意味着", def:"to suggest something without saying it directly", example:"His words ___ that he was unhappy.", level:2},
  {word:"indicate", ipa:"/ˈɪndɪkeɪt/", pos:"v.", zh:"表明；指出", def:"to show or point out something", example:"The results ___ a clear trend.", level:2},
  {word:"interpret", ipa:"/ɪnˈtɜːrprɪt/", pos:"v.", zh:"解释；理解", def:"to explain the meaning of something", example:"How do you ___ this poem?", level:2},
  {word:"maintain", ipa:"/meɪnˈteɪn/", pos:"v.", zh:"维持；保养", def:"to keep something in good condition", example:"It's hard to ___ a healthy diet.", level:2},
  {word:"occur", ipa:"/əˈkɜːr/", pos:"v.", zh:"发生", def:"to happen", example:"The accident ___ at midnight.", level:2},
  {word:"obtain", ipa:"/əbˈteɪn/", pos:"v.", zh:"获得", def:"to get something, especially by effort", example:"You must ___ a license first.", level:2},
  {word:"significant", ipa:"/sɪɡˈnɪfɪkənt/", pos:"adj.", zh:"重要的；显著的", def:"large or important enough to notice", example:"There was a ___ increase in sales.", level:2},
  {word:"source", ipa:"/sɔːrs/", pos:"n.", zh:"来源；源头", def:"the place something comes from", example:"What is the ___ of this information?", level:2},
  {word:"specific", ipa:"/spəˈsɪfɪk/", pos:"adj.", zh:"具体的；特定的", def:"clear and exact, not general", example:"Give me a ___ example.", level:2},
  {word:"strategy", ipa:"/ˈstrætədʒi/", pos:"n.", zh:"策略；战略", def:"a plan to achieve a goal", example:"We need a new marketing ___ .", level:2},
  {word:"sufficient", ipa:"/səˈfɪʃnt/", pos:"adj.", zh:"足够的", def:"enough for what is needed", example:"We have ___ food for everyone.", level:2},
  {word:"tend", ipa:"/tend/", pos:"v.", zh:"倾向于；往往会", def:"to be likely to do something", example:"People ___ to eat more in winter.", level:2},
  {word:"vary", ipa:"/ˈveri/", pos:"v.", zh:"变化；不同", def:"to change or be different", example:"Prices ___ from shop to shop.", level:2},

  // ---------- Level 3 高阶 ----------
  {word:"ambiguous", ipa:"/æmˈbɪɡjuəs/", pos:"adj.", zh:"模棱两可的；含糊的", def:"having more than one possible meaning", example:"The question was ___ and confused everyone.", level:3},
  {word:"arbitrary", ipa:"/ˈɑːrbɪtreri/", pos:"adj.", zh:"任意的；武断的", def:"based on chance or personal choice, not reason", example:"The choice seemed completely ___ .", level:3},
  {word:"coherent", ipa:"/koʊˈhɪrənt/", pos:"adj.", zh:"连贯的；条理清晰的", def:"logical and well organized", example:"She gave a ___ explanation of the plan.", level:3},
  {word:"compensate", ipa:"/ˈkɑːmpenseɪt/", pos:"v.", zh:"补偿；弥补", def:"to make up for a loss or mistake", example:"The company will ___ you for the delay.", level:3},
  {word:"comprehensive", ipa:"/ˌkɑːmprɪˈhensɪv/", pos:"adj.", zh:"全面的；综合的", def:"complete and including everything", example:"This is a ___ guide to the city.", level:3},
  {word:"contradict", ipa:"/ˌkɑːntrəˈdɪkt/", pos:"v.", zh:"反驳；与…矛盾", def:"to say the opposite of something", example:"His actions ___ his words.", level:3},
  {word:"controversial", ipa:"/ˌkɑːntrəˈvɜːrʃl/", pos:"adj.", zh:"有争议的", def:"causing strong disagreement", example:"It's a ___ topic in politics.", level:3},
  {word:"criteria", ipa:"/kraɪˈtɪriə/", pos:"n.", zh:"标准；准则", def:"standards used to judge something", example:"What are the ___ for selection?", level:3},
  {word:"diminish", ipa:"/dɪˈmɪnɪʃ/", pos:"v.", zh:"减少；削弱", def:"to become or make smaller or weaker", example:"His influence began to ___ over time.", level:3},
  {word:"diverse", ipa:"/daɪˈvɜːrs/", pos:"adj.", zh:"多样的；不同的", def:"very different from each other", example:"The city has a ___ population.", level:3},
  {word:"eliminate", ipa:"/ɪˈlɪmɪneɪt/", pos:"v.", zh:"消除；淘汰", def:"to completely remove something", example:"We must ___ all errors from the code.", level:3},
  {word:"emphasize", ipa:"/ˈemfəsaɪz/", pos:"v.", zh:"强调", def:"to give special importance to something", example:"The teacher ___ the importance of practice.", level:3},
  {word:"enhance", ipa:"/ɪnˈhæns/", pos:"v.", zh:"增强；提高", def:"to improve the quality or value of something", example:"Good lighting will ___ the photo.", level:3},
  {word:"explicit", ipa:"/ɪkˈsplɪsɪt/", pos:"adj.", zh:"明确的；清楚的", def:"clear and exact", example:"He gave ___ instructions.", level:3},
  {word:"fundamental", ipa:"/ˌfʌndəˈmentl/", pos:"adj.", zh:"基本的；根本的", def:"forming the base of something", example:"This is a ___ principle of physics.", level:3},
  {word:"hypothesis", ipa:"/haɪˈpɑːθəsɪs/", pos:"n.", zh:"假设；假说", def:"an idea that explains something and can be tested", example:"The experiment tested the ___ .", level:3},
  {word:"inevitable", ipa:"/ɪnˈevɪtəbl/", pos:"adj.", zh:"不可避免的", def:"certain to happen and cannot be avoided", example:"Change is ___ .", level:3},
  {word:"integrate", ipa:"/ˈɪntɪɡreɪt/", pos:"v.", zh:"整合；融合", def:"to combine two things into one whole", example:"We should ___ the two systems.", level:3},
  {word:"justify", ipa:"/ˈdʒʌstɪfaɪ/", pos:"v.", zh:"证明…有理；为…辩护", def:"to give a good reason for something", example:"How do you ___ this decision?", level:3},
  {word:"legitimate", ipa:"/lɪˈdʒɪtɪmət/", pos:"adj.", zh:"合法的；正当的", def:"allowed by law or fair and reasonable", example:"That's a ___ reason to refuse.", level:3},
  {word:"manipulate", ipa:"/məˈnɪpjuleɪt/", pos:"v.", zh:"操纵；操作", def:"to control something or someone cleverly", example:"Don't try to ___ the results.", level:3},
  {word:"mechanism", ipa:"/ˈmekənɪzəm/", pos:"n.", zh:"机制；机械装置", def:"a system or process that makes something work", example:"The body has a natural defense ___ .", level:3},
  {word:"notion", ipa:"/ˈnoʊʃn/", pos:"n.", zh:"概念；想法", def:"an idea or belief about something", example:"He has a strange ___ of success.", level:3},
  {word:"perspective", ipa:"/pərˈspektɪv/", pos:"n.", zh:"视角；观点", def:"a way of thinking about something", example:"Try to see it from my ___ .", level:3},
  {word:"phenomenon", ipa:"/fəˈnɑːmɪnən/", pos:"n.", zh:"现象", def:"something that exists and can be observed", example:"This is a common natural ___ .", level:3},
  {word:"preliminary", ipa:"/prɪˈlɪmɪneri/", pos:"adj.", zh:"初步的；预备的", def:"happening before the main part", example:"These are just ___ results.", level:3},
  {word:"prominent", ipa:"/ˈprɑːmɪnənt/", pos:"adj.", zh:"突出的；著名的", def:"important, well-known, or easy to notice", example:"He is a ___ scientist.", level:3},
  {word:"profound", ipa:"/prəˈfaʊnd/", pos:"adj.", zh:"深刻的；深远的", def:"very great or deep", example:"The book had a ___ effect on me.", level:3},
  {word:"reinforce", ipa:"/ˌriːɪnˈfɔːrs/", pos:"v.", zh:"加强；强化", def:"to make something stronger", example:"This will ___ the bridge.", level:3},
  {word:"relevant", ipa:"/ˈreləvənt/", pos:"adj.", zh:"相关的；切题的", def:"connected with what is being discussed", example:"Please keep your answer ___ to the question.", level:3},
  {word:"simultaneous", ipa:"/ˌsaɪmlˈteɪniəs/", pos:"adj.", zh:"同时发生的", def:"happening at the same time", example:"The two events were ___ .", level:3},
  {word:"sophisticated", ipa:"/səˈfɪstɪkeɪtɪd/", pos:"adj.", zh:"复杂的；精密的；老练的", def:"complicated and advanced, or having good taste", example:"This is a very ___ piece of software.", level:3},
  {word:"subsequent", ipa:"/ˈsʌbsɪkwənt/", pos:"adj.", zh:"随后的；后来的", def:"happening after something else", example:"___ events proved him right.", level:3},
  {word:"subtle", ipa:"/ˈsʌtl/", pos:"adj.", zh:"微妙的；细微的", def:"not obvious and hard to notice", example:"There's a ___ difference between them.", level:3},
  {word:"undergo", ipa:"/ˌʌndərˈɡoʊ/", pos:"v.", zh:"经历；经受", def:"to experience something, especially a change", example:"The building will ___ repairs.", level:3},

  // ---------- Level 4 学术（AWL/雅思核心） ----------
  {word:"accumulate", ipa:"/əˈkjuːmjəleɪt/", pos:"v.", zh:"积累；累积", def:"to gather or grow gradually over time", example:"Dust began to ___ on the shelf.", level:4},
  {word:"acknowledge", ipa:"/əkˈnɑːlɪdʒ/", pos:"v.", zh:"承认；致谢", def:"to accept that something is true", example:"He refused to ___ his mistake.", level:4},
  {word:"allocate", ipa:"/ˈæləkeɪt/", pos:"v.", zh:"分配；拨给", def:"to give resources for a specific purpose", example:"The team will ___ more time to testing.", level:4},
  {word:"coincide", ipa:"/ˌkoʊɪnˈsaɪd/", pos:"v.", zh:"同时发生；一致", def:"to happen at the same time or agree", example:"The meeting ___ with my vacation.", level:4},
  {word:"commodity", ipa:"/kəˈmɑːdəti/", pos:"n.", zh:"商品；货物", def:"a product that can be bought and sold", example:"Oil is a valuable ___ .", level:4},
  {word:"constitute", ipa:"/ˈkɑːnstɪtuːt/", pos:"v.", zh:"构成；组成", def:"to be the parts that form something", example:"Women ___ half of the workforce.", level:4},
  {word:"constrain", ipa:"/kənˈstreɪn/", pos:"v.", zh:"限制；约束", def:"to limit or restrict something", example:"Budget cuts will ___ our plans.", level:4},
  {word:"contemplate", ipa:"/ˈkɑːntəmpleɪt/", pos:"v.", zh:"考虑；沉思", def:"to think about something deeply", example:"She sat quietly to ___ her future.", level:4},
  {word:"converge", ipa:"/kənˈvɜːrdʒ/", pos:"v.", zh:"汇聚；趋同", def:"to move toward the same point", example:"The two roads ___ in the town center.", level:4},
  {word:"dimension", ipa:"/daɪˈmenʃn/", pos:"n.", zh:"维度；尺寸", def:"a measurement or an aspect of something", example:"We must consider the social ___ of the problem.", level:4},
  {word:"discrepancy", ipa:"/dɪsˈkrepənsi/", pos:"n.", zh:"差异；不一致", def:"a difference between things that should be the same", example:"There is a ___ in the two reports.", level:4},
  {word:"dismantle", ipa:"/dɪsˈmæntl/", pos:"v.", zh:"拆除；拆卸", def:"to take something apart", example:"Workers will ___ the old machine.", level:4},
  {word:"empirical", ipa:"/ɪmˈpɪrɪkl/", pos:"adj.", zh:"经验主义的；实证的", def:"based on experiment and observation, not theory", example:"The theory needs ___ support.", level:4},
  {word:"feasible", ipa:"/ˈfiːzəbl/", pos:"adj.", zh:"可行的", def:"possible to do successfully", example:"Is this plan ___ in one month?", level:4},
  {word:"fluctuate", ipa:"/ˈflʌktʃueɪt/", pos:"v.", zh:"波动；起伏", def:"to change frequently in level or amount", example:"Prices ___ with the seasons.", level:4},
  {word:"hierarchy", ipa:"/ˈhaɪərɑːrki/", pos:"n.", zh:"等级制度；层级", def:"a system where people are ranked by importance", example:"The company has a strict ___ .", level:4},
  {word:"implicit", ipa:"/ɪmˈplɪsɪt/", pos:"adj.", zh:"含蓄的；隐含的", def:"suggested but not directly expressed", example:"There was an ___ threat in his words.", level:4},
  {word:"indispensable", ipa:"/ˌɪndɪˈspensəbl/", pos:"adj.", zh:"不可或缺的", def:"absolutely necessary", example:"Water is ___ to life.", level:4},
  {word:"inherent", ipa:"/ɪnˈhɪrənt/", pos:"adj.", zh:"固有的；内在的", def:"existing as a natural part of something", example:"Risk is ___ in investment.", level:4},
  {word:"inhibit", ipa:"/ɪnˈhɪbɪt/", pos:"v.", zh:"抑制；阻碍", def:"to prevent or slow down something", example:"Fear can ___ learning.", level:4},
  {word:"paradigm", ipa:"/ˈpærədaɪm/", pos:"n.", zh:"范式；典范", def:"a typical example or model of something", example:"This discovery changed the scientific ___ .", level:4},
  {word:"parameter", ipa:"/pəˈræmɪtər/", pos:"n.", zh:"参数；界限", def:"a factor that limits or defines something", example:"The test has many ___ .", level:4},
  {word:"predominant", ipa:"/prɪˈdɑːmɪnənt/", pos:"adj.", zh:"占主导地位的", def:"the most common or important", example:"English is the ___ language here.", level:4},
  {word:"premise", ipa:"/ˈpremɪs/", pos:"n.", zh:"前提；假设", def:"an idea that forms the base of an argument", example:"The whole argument rests on a false ___ .", level:4},
  {word:"prohibit", ipa:"/prəˈhɪbɪt/", pos:"v.", zh:"禁止", def:"to officially forbid something", example:"The law will ___ smoking in public.", level:4},
  {word:"proportion", ipa:"/prəˈpɔːrʃn/", pos:"n.", zh:"比例；部分", def:"a part of a whole, or the relation between parts", example:"A large ___ of students passed.", level:4},
  {word:"rationale", ipa:"/ˌræʃəˈnæl/", pos:"n.", zh:"理由；逻辑依据", def:"the reasons behind a decision", example:"Explain the ___ for your choice.", level:4},
  {word:"refine", ipa:"/rɪˈfaɪn/", pos:"v.", zh:"精炼；改进", def:"to improve something by making small changes", example:"We need to ___ our approach.", level:4},
  {word:"reliance", ipa:"/rɪˈlaɪəns/", pos:"n.", zh:"依赖；信赖", def:"the state of depending on something", example:"Our ___ on oil must decrease.", level:4},
  {word:"rigorous", ipa:"/ˈrɪɡərəs/", pos:"adj.", zh:"严格的；严谨的", def:"careful, thorough, and exact", example:"The study used ___ methods.", level:4},
  {word:"subsidy", ipa:"/ˈsʌbsədi/", pos:"n.", zh:"补贴；津贴", def:"money given by the government to reduce costs", example:"Farmers receive a government ___ .", level:4},
  {word:"tentative", ipa:"/ˈtentətɪv/", pos:"adj.", zh:"试探性的；暂定的", def:"not final or certain", example:"We made a ___ plan for the trip.", level:4},
  {word:"undermine", ipa:"/ˌʌndərˈmaɪn/", pos:"v.", zh:"削弱；逐渐损害", def:"to weaken something gradually", example:"Rumors can ___ trust.", level:4},
  {word:"viable", ipa:"/ˈvaɪəbl/", pos:"adj.", zh:"切实可行的", def:"able to work successfully", example:"This is a ___ solution.", level:4},
  {word:"widespread", ipa:"/ˈwaɪdspred/", pos:"adj.", zh:"广泛的；普遍的", def:"existing in many places", example:"The disease is ___ in this region.", level:4},

  // ---------- Level 1 基础（扩充） ----------
  {word:"accept", ipa:"/əkˈsept/", pos:"v.", zh:"接受", def:"to agree to take something", example:"I decided to ___ the offer.", level:1},
  {word:"admire", ipa:"/ədˈmaɪər/", pos:"v.", zh:"钦佩；欣赏", def:"to respect and like someone or something", example:"I really ___ her courage.", level:1},
  {word:"admit", ipa:"/ədˈmɪt/", pos:"v.", zh:"承认", def:"to agree that something is true", example:"He had to ___ his mistake.", level:1},
  {word:"advance", ipa:"/ədˈvæns/", pos:"v.", zh:"前进；推进", def:"to move forward", example:"The army began to ___ at dawn.", level:1},
  {word:"advantage", ipa:"/ədˈvæntɪdʒ/", pos:"n.", zh:"优势", def:"something that helps you succeed", example:"Speaking English is a big ___ .", level:1},
  {word:"amount", ipa:"/əˈmaʊnt/", pos:"n.", zh:"数量", def:"a quantity of something", example:"A large ___ of money was spent.", level:1},
  {word:"announce", ipa:"/əˈnaʊns/", pos:"v.", zh:"宣布", def:"to tell people officially", example:"They will ___ the winner soon.", level:1},
  {word:"apart", ipa:"/əˈpɑːrt/", pos:"adv.", zh:"分开；相隔", def:"separated by distance", example:"The two towns are far ___ .", level:1},
  {word:"apologize", ipa:"/əˈpɑːlədʒaɪz/", pos:"v.", zh:"道歉", def:"to say sorry", example:"You should ___ for being late.", level:1},
  {word:"argue", ipa:"/ˈɑːrɡjuː/", pos:"v.", zh:"争论；争吵", def:"to disagree with someone", example:"They often ___ about money.", level:1},
  {word:"aspect", ipa:"/ˈæspekt/", pos:"n.", zh:"方面", def:"one part of a situation or subject", example:"We considered every ___ of the plan.", level:1},
  {word:"assist", ipa:"/əˈsɪst/", pos:"v.", zh:"帮助；协助", def:"to help someone", example:"Can you ___ me with this task?", level:1},
  {word:"assume", ipa:"/əˈsuːm/", pos:"v.", zh:"假设；假定", def:"to think something is true without proof", example:"Don't ___ he will agree.", level:1},
  {word:"attach", ipa:"/əˈtætʃ/", pos:"v.", zh:"附上；系上", def:"to fasten or join one thing to another", example:"Please ___ the file to the email.", level:1},
  {word:"attempt", ipa:"/əˈtempt/", pos:"v.", zh:"尝试；企图", def:"to try to do something", example:"He will ___ the exam again.", level:1},
  {word:"attract", ipa:"/əˈtrækt/", pos:"v.", zh:"吸引", def:"to make someone interested", example:"The show will ___ many visitors.", level:1},
  {word:"average", ipa:"/ˈævərɪdʒ/", pos:"adj.", zh:"平均的；普通的", def:"typical or in the middle", example:"The ___ temperature is 20 degrees.", level:1},
  {word:"aware", ipa:"/əˈwer/", pos:"adj.", zh:"意识到的；知道的", def:"knowing about something", example:"Are you ___ of the risk?", level:1},
  {word:"balance", ipa:"/ˈbæləns/", pos:"n.", zh:"平衡", def:"a state where things are equal", example:"Keep a ___ between work and rest.", level:1},
  {word:"base", ipa:"/beɪs/", pos:"n.", zh:"基础；底部", def:"the bottom part of something", example:"The tower has a strong ___ .", level:1},
  {word:"behave", ipa:"/bɪˈheɪv/", pos:"v.", zh:"表现；举止", def:"to act in a certain way", example:"The children ___ well in class.", level:1},
  {word:"blame", ipa:"/bleɪm/", pos:"v.", zh:"责备；归咎于", def:"to say someone caused a problem", example:"Don't ___ me for your mistake.", level:1},
  {word:"border", ipa:"/ˈbɔːrdər/", pos:"n.", zh:"边界；边境", def:"the line between two areas", example:"We crossed the ___ at night.", level:1},
  {word:"brief", ipa:"/briːf/", pos:"adj.", zh:"简短的", def:"short in time or length", example:"He gave a ___ introduction.", level:1},
  {word:"broad", ipa:"/brɔːd/", pos:"adj.", zh:"宽阔的", def:"wide", example:"The river is very ___ here.", level:1},
  {word:"calculate", ipa:"/ˈkælkjuleɪt/", pos:"v.", zh:"计算", def:"to find an answer using math", example:"Can you ___ the total cost?", level:1},
  {word:"cancel", ipa:"/ˈkænsl/", pos:"v.", zh:"取消", def:"to stop something from happening", example:"The flight was ___ .", level:1},
  {word:"capable", ipa:"/ˈkeɪpəbl/", pos:"adj.", zh:"有能力的", def:"able to do something", example:"She is ___ of great things.", level:1},
  {word:"cause", ipa:"/kɔːz/", pos:"v.", zh:"导致；引起", def:"to make something happen", example:"Smoking can ___ health problems.", level:1},
  {word:"celebrate", ipa:"/ˈselɪbreɪt/", pos:"v.", zh:"庆祝", def:"to do something enjoyable for a special event", example:"We will ___ her birthday.", level:1},
  {word:"chance", ipa:"/tʃæns/", pos:"n.", zh:"机会；可能性", def:"a possibility that something will happen", example:"There's a good ___ of rain.", level:1},
  {word:"charge", ipa:"/tʃɑːrdʒ/", pos:"v.", zh:"收费", def:"to ask for payment", example:"They ___ ten dollars for delivery.", level:1},
  {word:"claim", ipa:"/kleɪm/", pos:"v.", zh:"声称；主张", def:"to say something is true", example:"He ___ to know the answer.", level:1},
  {word:"collect", ipa:"/kəˈlekt/", pos:"v.", zh:"收集", def:"to gather things together", example:"She likes to ___ stamps.", level:1},
  {word:"combine", ipa:"/kəmˈbaɪn/", pos:"v.", zh:"结合；合并", def:"to join things together", example:"___ the two ideas into one.", level:1},
  {word:"comfort", ipa:"/ˈkʌmfərt/", pos:"n.", zh:"舒适；安慰", def:"a pleasant feeling of relaxation", example:"I miss the ___ of home.", level:1},
  {word:"communicate", ipa:"/kəˈmjuːnɪkeɪt/", pos:"v.", zh:"交流；沟通", def:"to share information with someone", example:"We ___ by email.", level:1},
  {word:"community", ipa:"/kəˈmjuːnəti/", pos:"n.", zh:"社区；团体", def:"a group of people living together", example:"The ___ came together to help.", level:1},
  {word:"complain", ipa:"/kəmˈpleɪn/", pos:"v.", zh:"抱怨", def:"to say you are unhappy about something", example:"He always ___ about the weather.", level:1},
  {word:"concentrate", ipa:"/ˈkɑːnsntreɪt/", pos:"v.", zh:"集中注意力", def:"to focus your attention on something", example:"I can't ___ with all this noise.", level:1},
  {word:"condition", ipa:"/kənˈdɪʃn/", pos:"n.", zh:"条件；状况", def:"the state of something", example:"The car is in good ___ .", level:1},
  {word:"connect", ipa:"/kəˈnekt/", pos:"v.", zh:"连接；联系", def:"to join things together", example:"The bridge will ___ the two islands.", level:1},
  {word:"consist", ipa:"/kənˈsɪst/", pos:"v.", zh:"由…组成", def:"to be made of particular parts", example:"The team ___ of five people.", level:1},
  {word:"contact", ipa:"/ˈkɑːntækt/", pos:"v.", zh:"联系；接触", def:"to communicate with someone", example:"Please ___ me by phone.", level:1},
  {word:"contain", ipa:"/kənˈteɪn/", pos:"v.", zh:"包含；容纳", def:"to have something inside", example:"The box ___ old photos.", level:1},
  {word:"control", ipa:"/kənˈtroʊl/", pos:"v.", zh:"控制", def:"to make something do what you want", example:"She can ___ her temper.", level:1},
  {word:"convenient", ipa:"/kənˈviːniənt/", pos:"adj.", zh:"方便的", def:"easy to use or reach", example:"The location is very ___ .", level:1},
  {word:"convince", ipa:"/kənˈvɪns/", pos:"v.", zh:"说服；使相信", def:"to make someone believe something", example:"He tried to ___ me to stay.", level:1},
  {word:"count", ipa:"/kaʊnt/", pos:"v.", zh:"数；计算", def:"to find the total number", example:"Let's ___ the votes.", level:1},
  {word:"courage", ipa:"/ˈkɜːrɪdʒ/", pos:"n.", zh:"勇气", def:"the ability to face danger", example:"It takes ___ to speak up.", level:1},
  {word:"cover", ipa:"/ˈkʌvər/", pos:"v.", zh:"覆盖", def:"to put something over another", example:"Snow will ___ the ground.", level:1},
  {word:"damage", ipa:"/ˈdæmɪdʒ/", pos:"v.", zh:"损害；破坏", def:"to harm something", example:"The storm will ___ the crops.", level:1},
  {word:"deal", ipa:"/diːl/", pos:"v.", zh:"处理；应对", def:"to handle a situation", example:"How do you ___ with stress?", level:1},
  {word:"define", ipa:"/dɪˈfaɪn/", pos:"v.", zh:"定义；界定", def:"to explain the meaning of something", example:"Can you ___ this word?", level:1},
  {word:"degree", ipa:"/dɪˈɡriː/", pos:"n.", zh:"程度；学位", def:"a level or amount of something", example:"I agree to a certain ___ .", level:1},
  {word:"delay", ipa:"/dɪˈleɪ/", pos:"v.", zh:"推迟；耽搁", def:"to make something happen later", example:"The rain will ___ the game.", level:1},
  {word:"deliver", ipa:"/dɪˈlɪvər/", pos:"v.", zh:"递送；交付", def:"to take something to a place", example:"They will ___ the package today.", level:1},
  {word:"demand", ipa:"/dɪˈmænd/", pos:"v.", zh:"要求", def:"to ask for something firmly", example:"Workers ___ higher pay.", level:1},
  {word:"depend", ipa:"/dɪˈpend/", pos:"v.", zh:"依赖；取决于", def:"to rely on something", example:"Children ___ on their parents.", level:1},
  {word:"desire", ipa:"/dɪˈzaɪər/", pos:"n.", zh:"渴望；欲望", def:"a strong wish for something", example:"He has a strong ___ to succeed.", level:1},
  {word:"destroy", ipa:"/dɪˈstrɔɪ/", pos:"v.", zh:"摧毁；破坏", def:"to damage something completely", example:"The fire will ___ the forest.", level:1},
  {word:"determine", ipa:"/dɪˈtɜːrmɪn/", pos:"v.", zh:"决定；确定", def:"to decide or find out", example:"Tests will ___ the cause.", level:1},
  {word:"disappear", ipa:"/ˌdɪsəˈpɪr/", pos:"v.", zh:"消失", def:"to stop being visible", example:"The sun will ___ behind clouds.", level:1},
  {word:"discover", ipa:"/dɪˈskʌvər/", pos:"v.", zh:"发现", def:"to find something for the first time", example:"They ___ a new planet.", level:1},
  {word:"distance", ipa:"/ˈdɪstəns/", pos:"n.", zh:"距离", def:"the space between two things", example:"The ___ is about 5 miles.", level:1},
  {word:"divide", ipa:"/dɪˈvaɪd/", pos:"v.", zh:"分开；划分", def:"to split into parts", example:"___ the cake into eight pieces.", level:1},
  {word:"doubt", ipa:"/daʊt/", pos:"v.", zh:"怀疑", def:"to not believe something", example:"I ___ his story.", level:1},
  {word:"earn", ipa:"/ɜːrn/", pos:"v.", zh:"赚取；赢得", def:"to get money for work", example:"He ___ a good salary.", level:1},
  {word:"educate", ipa:"/ˈedʒukeɪt/", pos:"v.", zh:"教育", def:"to teach someone", example:"Schools ___ children.", level:1},
  {word:"emotion", ipa:"/ɪˈmoʊʃn/", pos:"n.", zh:"情感；情绪", def:"a strong feeling", example:"He hid his ___ .", level:1},
  {word:"employ", ipa:"/ɪmˈplɔɪ/", pos:"v.", zh:"雇用", def:"to give someone a job", example:"The factory will ___ more workers.", level:1},
  {word:"enable", ipa:"/ɪˈneɪbl/", pos:"v.", zh:"使能够", def:"to make it possible for someone to do something", example:"The money will ___ us to travel.", level:1},
  {word:"energy", ipa:"/ˈenərdʒi/", pos:"n.", zh:"能量；精力", def:"the power to do things", example:"The sun gives us ___ .", level:1},
  {word:"engage", ipa:"/ɪnˈɡeɪdʒ/", pos:"v.", zh:"参与；从事", def:"to take part in something", example:"Students should ___ in class activities.", level:1},
  {word:"escape", ipa:"/ɪˈskeɪp/", pos:"v.", zh:"逃跑；逃避", def:"to get away from a place", example:"The bird managed to ___ .", level:1},
  {word:"essential", ipa:"/ɪˈsenʃl/", pos:"adj.", zh:"必不可少的", def:"completely necessary", example:"Water is ___ to life.", level:1},
  {word:"examine", ipa:"/ɪɡˈzæmɪn/", pos:"v.", zh:"检查；审查", def:"to look at something carefully", example:"The doctor will ___ the patient.", level:1},
  {word:"exchange", ipa:"/ɪksˈtʃeɪndʒ/", pos:"v.", zh:"交换", def:"to give something and receive another", example:"We ___ gifts at the party.", level:1},
  {word:"exist", ipa:"/ɪɡˈzɪst/", pos:"v.", zh:"存在", def:"to be real or present", example:"Do ghosts really ___ ?", level:1},
  {word:"expand", ipa:"/ɪkˈspænd/", pos:"v.", zh:"扩大；扩张", def:"to become larger", example:"The company plans to ___ overseas.", level:1},
  {word:"express", ipa:"/ɪkˈspres/", pos:"v.", zh:"表达", def:"to show your feelings or ideas", example:"It's hard to ___ my feelings.", level:1},

  // ---------- Level 2 进阶（扩充） ----------
  {word:"acquire", ipa:"/əˈkwaɪər/", pos:"v.", zh:"获得；习得", def:"to gain or obtain something", example:"You can ___ new skills by practicing.", level:2},
  {word:"adjust", ipa:"/əˈdʒʌst/", pos:"v.", zh:"调整；适应", def:"to change something slightly", example:"Please ___ the volume.", level:2},
  {word:"advocate", ipa:"/ˈædvəkeɪt/", pos:"v.", zh:"提倡；主张", def:"to publicly support an idea", example:"Many doctors ___ a healthy diet.", level:2},
  {word:"alter", ipa:"/ˈɔːltər/", pos:"v.", zh:"改变；更改", def:"to change something", example:"We had to ___ our plans.", level:2},
  {word:"anticipate", ipa:"/ænˈtɪsɪpeɪt/", pos:"v.", zh:"预期；预料", def:"to expect something to happen", example:"We ___ a rise in prices.", level:2},
  {word:"apparent", ipa:"/əˈpærənt/", pos:"adj.", zh:"明显的；显然的", def:"easy to see or understand", example:"It was ___ that he was tired.", level:2},
  {word:"assess", ipa:"/əˈses/", pos:"v.", zh:"评估；评价", def:"to judge the quality of something", example:"Teachers ___ students' work.", level:2},
  {word:"assign", ipa:"/əˈsaɪn/", pos:"v.", zh:"分配；指派", def:"to give someone a task", example:"The manager will ___ the work.", level:2},
  {word:"attribute", ipa:"/əˈtrɪbjuːt/", pos:"v.", zh:"归因于", def:"to say something is caused by", example:"She ___ her success to hard work.", level:2},
  {word:"circumstance", ipa:"/ˈsɜːrkəmstæns/", pos:"n.", zh:"情况；环境", def:"a condition that affects a situation", example:"Under no ___ should you lie.", level:2},
  {word:"cite", ipa:"/saɪt/", pos:"v.", zh:"引用；引证", def:"to mention something as evidence", example:"He ___ several studies.", level:2},
  {word:"clarify", ipa:"/ˈklærəfaɪ/", pos:"v.", zh:"澄清；阐明", def:"to make something clearer", example:"Could you ___ your point?", level:2},
  {word:"collapse", ipa:"/kəˈlæps/", pos:"v.", zh:"倒塌；崩溃", def:"to fall down suddenly", example:"The bridge could ___ .", level:2},
  {word:"commence", ipa:"/kəˈmens/", pos:"v.", zh:"开始", def:"to begin", example:"The meeting will ___ at nine.", level:2},
  {word:"commit", ipa:"/kəˈmɪt/", pos:"v.", zh:"承诺；犯(错)", def:"to promise, or to do something wrong", example:"He ___ a serious error.", level:2},
  {word:"competent", ipa:"/ˈkɑːmpɪtənt/", pos:"adj.", zh:"有能力的；胜任的", def:"able to do something well", example:"She is a ___ manager.", level:2},
  {word:"component", ipa:"/kəmˈpoʊnənt/", pos:"n.", zh:"组成部分；部件", def:"a part of a larger whole", example:"This is a key ___ of the system.", level:2},
  {word:"comprise", ipa:"/kəmˈpraɪz/", pos:"v.", zh:"包含；由…组成", def:"to consist of", example:"The team ___ ten members.", level:2},
  {word:"concept", ipa:"/ˈkɑːnsept/", pos:"n.", zh:"概念；观念", def:"an idea or principle", example:"This is a difficult ___ .", level:2},
  {word:"conclude", ipa:"/kənˈkluːd/", pos:"v.", zh:"得出结论；结束", def:"to decide something after thinking", example:"We can ___ that he was wrong.", level:2},
  {word:"confirm", ipa:"/kənˈfɜːrm/", pos:"v.", zh:"确认；证实", def:"to show that something is true", example:"Please ___ your booking.", level:2},
  {word:"conflict", ipa:"/ˈkɑːnflɪkt/", pos:"n.", zh:"冲突；矛盾", def:"a serious disagreement", example:"There was a ___ between the two sides.", level:2},
  {word:"consistent", ipa:"/kənˈsɪstənt/", pos:"adj.", zh:"一致的；始终如一的", def:"always behaving in the same way", example:"Her work is ___ and reliable.", level:2},
  {word:"constant", ipa:"/ˈkɑːnstənt/", pos:"adj.", zh:"持续不断的", def:"happening all the time", example:"He was in ___ pain.", level:2},
  {word:"construct", ipa:"/kənˈstrʌkt/", pos:"v.", zh:"建造；构建", def:"to build something", example:"They will ___ a new bridge.", level:2},
  {word:"consult", ipa:"/kənˈsʌlt/", pos:"v.", zh:"咨询；查阅", def:"to ask someone for advice", example:"You should ___ a doctor.", level:2},
  {word:"context", ipa:"/ˈkɑːntekst/", pos:"n.", zh:"上下文；背景", def:"the situation around something", example:"The word has a different meaning in this ___ .", level:2},
  {word:"contrast", ipa:"/ˈkɑːntræst/", pos:"n.", zh:"对比；反差", def:"a clear difference between things", example:"There is a sharp ___ between the two.", level:2},
  {word:"convert", ipa:"/kənˈvɜːrt/", pos:"v.", zh:"转换；转变", def:"to change into another form", example:"They will ___ the room into an office.", level:2},
  {word:"convey", ipa:"/kənˈveɪ/", pos:"v.", zh:"传达；表达", def:"to communicate an idea", example:"Words cannot ___ my thanks.", level:2},
  {word:"cooperate", ipa:"/koʊˈɑːpəreɪt/", pos:"v.", zh:"合作；协作", def:"to work together", example:"The two teams will ___ .", level:2},
  {word:"coordinate", ipa:"/koʊˈɔːrdɪneɪt/", pos:"v.", zh:"协调；配合", def:"to organize things so they work well", example:"She will ___ the event.", level:2},
  {word:"correspond", ipa:"/ˌkɔːrəˈspɑːnd/", pos:"v.", zh:"相符；一致", def:"to match or be similar", example:"His story doesn't ___ with the facts.", level:2},
  {word:"deduce", ipa:"/dɪˈduːs/", pos:"v.", zh:"推断；演绎", def:"to reach a conclusion from facts", example:"We can ___ the answer from the data.", level:2},
  {word:"defect", ipa:"/ˈdiːfekt/", pos:"n.", zh:"缺陷；瑕疵", def:"a fault or problem", example:"The product has a ___ .", level:2},
  {word:"depict", ipa:"/dɪˈpɪkt/", pos:"v.", zh:"描绘；描述", def:"to describe or show something", example:"The painting ___ a village scene.", level:2},
  {word:"despite", ipa:"/dɪˈspaɪt/", pos:"prep.", zh:"尽管", def:"without being affected by", example:"___ the rain, we went out.", level:2},
  {word:"detect", ipa:"/dɪˈtekt/", pos:"v.", zh:"察觉；检测", def:"to notice or discover something", example:"The machine can ___ small changes.", level:2},
  {word:"devote", ipa:"/dɪˈvoʊt/", pos:"v.", zh:"投入；奉献", def:"to give time or effort to something", example:"She ___ her life to teaching.", level:2},
  {word:"differentiate", ipa:"/ˌdɪfəˈrenʃieɪt/", pos:"v.", zh:"区分；区别", def:"to see the difference between things", example:"It's hard to ___ the twins.", level:2},
  {word:"distribute", ipa:"/dɪˈstrɪbjuːt/", pos:"v.", zh:"分配；分发", def:"to give something out", example:"They will ___ food to the poor.", level:2},
  {word:"dominate", ipa:"/ˈdɑːmɪneɪt/", pos:"v.", zh:"支配；主导", def:"to control something", example:"One company ___ the market.", level:2},
  {word:"encounter", ipa:"/ɪnˈkaʊntər/", pos:"v.", zh:"遇到；遭遇", def:"to meet something unexpectedly", example:"We may ___ problems.", level:2},
  {word:"ensure", ipa:"/ɪnˈʃʊr/", pos:"v.", zh:"确保；保证", def:"to make certain that something happens", example:"Please ___ the door is locked.", level:2},
  {word:"equivalent", ipa:"/ɪˈkwɪvələnt/", pos:"adj.", zh:"等同的；相当的", def:"equal in value or meaning", example:"One mile is ___ to 1.6 km.", level:2},
  {word:"expose", ipa:"/ɪkˈspoʊz/", pos:"v.", zh:"暴露；揭露", def:"to make something visible", example:"Don't ___ the film to light.", level:2},
  {word:"extensive", ipa:"/ɪkˈstensɪv/", pos:"adj.", zh:"广泛的；大量的", def:"covering a large area", example:"She has ___ knowledge of history.", level:2},
  {word:"extract", ipa:"/ɪkˈstrækt/", pos:"v.", zh:"提取；取出", def:"to take something out", example:"They ___ oil from the seeds.", level:2},
  {word:"facilitate", ipa:"/fəˈsɪlɪteɪt/", pos:"v.", zh:"促进；使便利", def:"to make something easier", example:"The app will ___ communication.", level:2},
  {word:"formulate", ipa:"/ˈfɔːrmjuleɪt/", pos:"v.", zh:"制定；构想", def:"to develop a plan or idea", example:"They will ___ a new policy.", level:2},
  {word:"framework", ipa:"/ˈfreɪmwɜːrk/", pos:"n.", zh:"框架；结构", def:"a basic structure", example:"We need a ___ for the project.", level:2},
  {word:"frequent", ipa:"/ˈfriːkwənt/", pos:"adj.", zh:"频繁的", def:"happening often", example:"He makes ___ trips abroad.", level:2},
  {word:"function", ipa:"/ˈfʌŋkʃn/", pos:"n.", zh:"功能；作用", def:"the purpose of something", example:"What is the ___ of this button?", level:2},
  {word:"gradual", ipa:"/ˈɡrædʒuəl/", pos:"adj.", zh:"逐渐的", def:"happening slowly over time", example:"There was a ___ improvement.", level:2},
  {word:"guarantee", ipa:"/ˌɡærənˈtiː/", pos:"v.", zh:"保证；担保", def:"to promise that something will happen", example:"We ___ the quality.", level:2},
  {word:"highlight", ipa:"/ˈhaɪlaɪt/", pos:"v.", zh:"强调；突出", def:"to emphasize something", example:"The report ___ the key issues.", level:2},
  {word:"implement", ipa:"/ˈɪmplɪment/", pos:"v.", zh:"实施；执行", def:"to put a plan into action", example:"They will ___ the new plan.", level:2},
  {word:"implication", ipa:"/ˌɪmplɪˈkeɪʃn/", pos:"n.", zh:"含义；影响", def:"a possible effect or meaning", example:"The law has serious ___ .", level:2},
  {word:"impose", ipa:"/ɪmˈpoʊz/", pos:"v.", zh:"强加；施加", def:"to force something on someone", example:"The government will ___ new taxes.", level:2},
  {word:"incentive", ipa:"/ɪnˈsentɪv/", pos:"n.", zh:"激励；刺激", def:"something that encourages you", example:"Bonuses are a good ___ .", level:2},
  {word:"incorporate", ipa:"/ɪnˈkɔːrpəreɪt/", pos:"v.", zh:"纳入；合并", def:"to include something", example:"We will ___ your ideas.", level:2},
  {word:"index", ipa:"/ˈɪndeks/", pos:"n.", zh:"索引；指标", def:"a list for finding information", example:"Check the ___ of the book.", level:2},
  {word:"infer", ipa:"/ɪnˈfɜːr/", pos:"v.", zh:"推断；推论", def:"to conclude from evidence", example:"We can ___ that he lied.", level:2},
  {word:"initial", ipa:"/ɪˈnɪʃl/", pos:"adj.", zh:"最初的；初始的", def:"at the beginning", example:"My ___ reaction was shock.", level:2},
  {word:"initiate", ipa:"/ɪˈnɪʃieɪt/", pos:"v.", zh:"发起；启动", def:"to start something", example:"They will ___ the project.", level:2},
  {word:"insight", ipa:"/ˈɪnsaɪt/", pos:"n.", zh:"洞察力；见解", def:"a deep understanding", example:"The book gives ___ into human nature.", level:2},
  {word:"instance", ipa:"/ˈɪnstəns/", pos:"n.", zh:"例子；实例", def:"an example", example:"For ___ , consider this case.", level:2},
  {word:"institute", ipa:"/ˈɪnstɪtuːt/", pos:"n.", zh:"机构；学院", def:"an organization for research or education", example:"She works at a research ___ .", level:2},
  {word:"interact", ipa:"/ˌɪntərˈækt/", pos:"v.", zh:"互动；相互作用", def:"to communicate with each other", example:"Children learn to ___ .", level:2},
  {word:"investigate", ipa:"/ɪnˈvestɪɡeɪt/", pos:"v.", zh:"调查；研究", def:"to examine something carefully", example:"Police will ___ the crime.", level:2},
  {word:"modify", ipa:"/ˈmɑːdɪfaɪ/", pos:"v.", zh:"修改；调整", def:"to change something slightly", example:"We need to ___ the design.", level:2},
  {word:"monitor", ipa:"/ˈmɑːnɪtər/", pos:"v.", zh:"监控；监测", def:"to watch something carefully", example:"Doctors ___ the patient's heart.", level:2},

  // ---------- Level 3 高阶（扩充） ----------
  {word:"alleviate", ipa:"/əˈliːvieɪt/", pos:"v.", zh:"减轻；缓解", def:"to make pain or a problem less severe", example:"The medicine will ___ the pain.", level:3},
  {word:"amend", ipa:"/əˈmend/", pos:"v.", zh:"修改；修订", def:"to change a law or text", example:"They will ___ the rule.", level:3},
  {word:"analogy", ipa:"/əˈnælədʒi/", pos:"n.", zh:"类比；比喻", def:"a comparison between two things", example:"He drew an ___ between the two.", level:3},
  {word:"articulate", ipa:"/ɑːrˈtɪkjuleɪt/", pos:"v.", zh:"清晰表达", def:"to express ideas clearly", example:"She can ___ her ideas well.", level:3},
  {word:"assert", ipa:"/əˈsɜːrt/", pos:"v.", zh:"断言；主张", def:"to state something firmly", example:"He ___ that he was right.", level:3},
  {word:"attain", ipa:"/əˈteɪn/", pos:"v.", zh:"达到；获得", def:"to achieve something", example:"She ___ her goal.", level:3},
  {word:"bias", ipa:"/ˈbaɪəs/", pos:"n.", zh:"偏见；偏向", def:"an unfair preference for something", example:"The report shows a clear ___ .", level:3},
  {word:"compatible", ipa:"/kəmˈpætəbl/", pos:"adj.", zh:"兼容的；相容的", def:"able to work or exist together", example:"The software is ___ with my phone.", level:3},
  {word:"compel", ipa:"/kəmˈpel/", pos:"v.", zh:"强迫；迫使", def:"to force someone to do something", example:"The law will ___ them to pay.", level:3},
  {word:"compile", ipa:"/kəmˈpaɪl/", pos:"v.", zh:"汇编；编译", def:"to gather things together into a list", example:"They will ___ the report.", level:3},
  {word:"complement", ipa:"/ˈkɑːmplɪment/", pos:"v.", zh:"补充；相配", def:"to add to something to make it complete", example:"The wine will ___ the meal.", level:3},
  {word:"comply", ipa:"/kəmˈplaɪ/", pos:"v.", zh:"遵守；服从", def:"to obey a rule or request", example:"We must ___ with the rules.", level:3},
  {word:"compound", ipa:"/ˈkɑːmpaʊnd/", pos:"v.", zh:"使恶化；加重", def:"to make a problem worse", example:"Lack of sleep can ___ the problem.", level:3},
  {word:"conceive", ipa:"/kənˈsiːv/", pos:"v.", zh:"构想；设想", def:"to think of an idea", example:"She ___ a brilliant plan.", level:3},
  {word:"condemn", ipa:"/kənˈdem/", pos:"v.", zh:"谴责", def:"to criticize something strongly", example:"Leaders ___ the attack.", level:3},
  {word:"confer", ipa:"/kənˈfɜːr/", pos:"v.", zh:"授予；商议", def:"to give an honor, or to discuss", example:"The title was ___ on him.", level:3},
  {word:"confine", ipa:"/kənˈfaɪn/", pos:"v.", zh:"限制；局限", def:"to keep something within limits", example:"Please ___ your remarks to the topic.", level:3},
  {word:"conform", ipa:"/kənˈfɔːrm/", pos:"v.", zh:"遵守；符合", def:"to obey rules or standards", example:"You must ___ to the standard.", level:3},
  {word:"consensus", ipa:"/kənˈsensəs/", pos:"n.", zh:"共识；一致意见", def:"a general agreement", example:"They reached a ___ .", level:3},
  {word:"consolidate", ipa:"/kənˈsɑːlɪdeɪt/", pos:"v.", zh:"巩固；合并", def:"to make something stronger", example:"We need to ___ our gains.", level:3},
  {word:"contend", ipa:"/kənˈtend/", pos:"v.", zh:"主张；争辩", def:"to argue that something is true", example:"He ___ that the plan is flawed.", level:3},
  {word:"credible", ipa:"/ˈkredəbl/", pos:"adj.", zh:"可信的；可靠的", def:"believable or trustworthy", example:"The story is hardly ___ .", level:3},
  {word:"culminate", ipa:"/ˈkʌlmɪneɪt/", pos:"v.", zh:"达到顶点；告终", def:"to reach the highest point", example:"The events ___ in a crisis.", level:3},
  {word:"cumulative", ipa:"/ˈkjuːmjəleɪtɪv/", pos:"adj.", zh:"累积的", def:"increasing gradually over time", example:"The ___ effect was huge.", level:3},
  {word:"deficiency", ipa:"/dɪˈfɪʃnsi/", pos:"n.", zh:"缺乏；不足", def:"a lack of something", example:"A vitamin ___ causes illness.", level:3},
  {word:"denote", ipa:"/dɪˈnoʊt/", pos:"v.", zh:"表示；意味着", def:"to be a sign of something", example:"The symbol ___ danger.", level:3},
  {word:"deteriorate", ipa:"/dɪˈtɪriəreɪt/", pos:"v.", zh:"恶化；变坏", def:"to become worse", example:"His health began to ___ .", level:3},
  {word:"deviate", ipa:"/ˈdiːvieɪt/", pos:"v.", zh:"偏离；背离", def:"to move away from a plan or standard", example:"Don't ___ from the plan.", level:3},
  {word:"dilemma", ipa:"/dɪˈlemə/", pos:"n.", zh:"困境；两难", def:"a difficult choice between options", example:"She faced a real ___ .", level:3},
  {word:"discrete", ipa:"/dɪˈskriːt/", pos:"adj.", zh:"分离的；独立的", def:"separate and distinct", example:"The process has ___ stages.", level:3},
  {word:"disparity", ipa:"/dɪˈspærəti/", pos:"n.", zh:"差异；悬殊", def:"a great difference", example:"There is a ___ in income.", level:3},
  {word:"disrupt", ipa:"/dɪsˈrʌpt/", pos:"v.", zh:"扰乱；打断", def:"to interrupt something", example:"The storm will ___ traffic.", level:3},
  {word:"dissolve", ipa:"/dɪˈzɑːlv/", pos:"v.", zh:"溶解；解散", def:"to mix into a liquid", example:"Sugar will ___ in water.", level:3},
  {word:"distort", ipa:"/dɪˈstɔːrt/", pos:"v.", zh:"歪曲；扭曲", def:"to change the truth", example:"The media ___ the facts.", level:3},
  {word:"dynamic", ipa:"/daɪˈnæmɪk/", pos:"adj.", zh:"动态的；有活力的", def:"constantly changing", example:"It's a ___ market.", level:3},
  {word:"elaborate", ipa:"/ɪˈlæbərət/", pos:"adj.", zh:"详尽的；精巧的", def:"detailed and complicated", example:"He gave an ___ explanation.", level:3},
  {word:"elicit", ipa:"/ɪˈlɪsɪt/", pos:"v.", zh:"引出；诱出", def:"to get a response or reaction", example:"The question ___ a laugh.", level:3},
  {word:"embed", ipa:"/ɪmˈbed/", pos:"v.", zh:"嵌入；植入", def:"to fix something deeply", example:"The idea is ___ in our culture.", level:3},
  {word:"encompass", ipa:"/ɪnˈkʌmpəs/", pos:"v.", zh:"包含；涵盖", def:"to include many things", example:"The course ___ many topics.", level:3},
  {word:"endeavor", ipa:"/ɪnˈdevər/", pos:"n.", zh:"努力；尝试", def:"a serious attempt", example:"It was a noble ___ .", level:3},
  {word:"endorse", ipa:"/ɪnˈdɔːrs/", pos:"v.", zh:"支持；背书", def:"to publicly support something", example:"They ___ the new policy.", level:3},
  {word:"entail", ipa:"/ɪnˈteɪl/", pos:"v.", zh:"需要；涉及", def:"to involve something as a result", example:"The job will ___ long hours.", level:3},
  {word:"evoke", ipa:"/ɪˈvoʊk/", pos:"v.", zh:"唤起；引起", def:"to bring a feeling to mind", example:"The song ___ memories.", level:3},
  {word:"exceed", ipa:"/ɪkˈsiːd/", pos:"v.", zh:"超过；超出", def:"to be greater than a limit", example:"Costs will ___ the budget.", level:3},
  {word:"foster", ipa:"/ˈfɔːstər/", pos:"v.", zh:"培养；促进", def:"to encourage something to develop", example:"The program will ___ creativity.", level:3},
  {word:"genuine", ipa:"/ˈdʒenjuɪn/", pos:"adj.", zh:"真正的；真诚的", def:"real and sincere", example:"She showed ___ concern.", level:3},
  {word:"imminent", ipa:"/ˈɪmɪnənt/", pos:"adj.", zh:"即将发生的", def:"about to happen", example:"A storm is ___ .", level:3},
  {word:"impair", ipa:"/ɪmˈper/", pos:"v.", zh:"损害；削弱", def:"to weaken or damage something", example:"Alcohol can ___ driving.", level:3},
  {word:"imperative", ipa:"/ɪmˈperətɪv/", pos:"adj.", zh:"必要的；紧迫的", def:"extremely important and urgent", example:"It is ___ to act now.", level:3},
  {word:"incline", ipa:"/ɪnˈklaɪn/", pos:"v.", zh:"倾向于", def:"to tend to do something", example:"I ___ to agree with you.", level:3},
  {word:"innovate", ipa:"/ˈɪnəveɪt/", pos:"v.", zh:"创新；革新", def:"to introduce new ideas", example:"Companies must ___ to survive.", level:3},
  {word:"intricate", ipa:"/ˈɪntrɪkət/", pos:"adj.", zh:"复杂的；错综的", def:"very complicated", example:"The watch has an ___ design.", level:3},
  {word:"intrinsic", ipa:"/ɪnˈtrɪnsɪk/", pos:"adj.", zh:"内在的；固有的", def:"belonging to the nature of something", example:"The work has ___ value.", level:3},
  {word:"invoke", ipa:"/ɪnˈvoʊk/", pos:"v.", zh:"援引；调用", def:"to use a law or rule", example:"They ___ an old law.", level:3},
  {word:"magnitude", ipa:"/ˈmæɡnɪtuːd/", pos:"n.", zh:"巨大；量级", def:"great size or importance", example:"The earthquake had a ___ of 7.", level:3},
  {word:"marginal", ipa:"/ˈmɑːrdʒɪnl/", pos:"adj.", zh:"微小的；边缘的", def:"very small or not important", example:"The change was ___ .", level:3},
  {word:"mediate", ipa:"/ˈmiːdieɪt/", pos:"v.", zh:"调解；斡旋", def:"to help settle a dispute", example:"The UN will ___ the conflict.", level:3},
  {word:"merge", ipa:"/mɜːrdʒ/", pos:"v.", zh:"合并；融合", def:"to combine into one", example:"The two companies will ___ .", level:3},
  {word:"mitigate", ipa:"/ˈmɪtɪɡeɪt/", pos:"v.", zh:"减轻；缓和", def:"to make something less severe", example:"We must ___ the risk.", level:3},
  {word:"momentum", ipa:"/moʊˈmentəm/", pos:"n.", zh:"势头；动力", def:"the force that keeps something moving", example:"The campaign gained ___ .", level:3},
  {word:"mutual", ipa:"/ˈmjuːtʃuəl/", pos:"adj.", zh:"相互的；共同的", def:"shared by two or more people", example:"They have ___ respect.", level:3},
  {word:"negligible", ipa:"/ˈneɡlɪdʒəbl/", pos:"adj.", zh:"微不足道的", def:"too small to matter", example:"The difference is ___ .", level:3},
  {word:"norm", ipa:"/nɔːrm/", pos:"n.", zh:"规范；常态", def:"a usual standard or pattern", example:"Working late is the ___ here.", level:3},
  {word:"notwithstanding", ipa:"/ˌnɑːtwɪθˈstændɪŋ/", pos:"prep.", zh:"尽管", def:"in spite of something", example:"___ the rain, we played.", level:3},
  {word:"objective", ipa:"/əbˈdʒektɪv/", pos:"adj.", zh:"客观的", def:"not influenced by personal feelings", example:"Try to stay ___ .", level:3},
  {word:"offset", ipa:"/ˈɔːfset/", pos:"v.", zh:"抵消；弥补", def:"to balance the effect of something", example:"The savings will ___ the cost.", level:3},
  {word:"ongoing", ipa:"/ˈɑːnɡoʊɪŋ/", pos:"adj.", zh:"持续的；进行中的", def:"continuing to happen", example:"It's an ___ project.", level:3},
  {word:"optimal", ipa:"/ˈɑːptɪməl/", pos:"adj.", zh:"最优的；最佳的", def:"the best possible", example:"This is the ___ solution.", level:3},
  {word:"overlap", ipa:"/ˌoʊvərˈlæp/", pos:"v.", zh:"重叠；部分相同", def:"to cover partly the same area", example:"The two courses ___ .", level:3},
  {word:"perceive", ipa:"/pərˈsiːv/", pos:"v.", zh:"感知；察觉", def:"to notice or understand something", example:"I ___ a change in him.", level:3},
  {word:"persist", ipa:"/pərˈsɪst/", pos:"v.", zh:"坚持；持续", def:"to continue despite difficulty", example:"The problem will ___ .", level:3},
  {word:"plausible", ipa:"/ˈplɔːzəbl/", pos:"adj.", zh:"貌似合理的", def:"seeming reasonable or true", example:"That's a ___ explanation.", level:3},
  {word:"precede", ipa:"/prɪˈsiːd/", pos:"v.", zh:"先于；在…之前", def:"to come before something", example:"A warning will ___ the event.", level:3},
  {word:"presume", ipa:"/prɪˈzuːm/", pos:"v.", zh:"假定；推测", def:"to suppose something is true", example:"I ___ you know the rules.", level:3},
  {word:"prevail", ipa:"/prɪˈveɪl/", pos:"v.", zh:"盛行；占优势", def:"to be common or win", example:"Justice will ___ .", level:3},
  {word:"proficient", ipa:"/prəˈfɪʃnt/", pos:"adj.", zh:"熟练的；精通的", def:"skilled at something", example:"She is ___ in English.", level:3},
  {word:"provoke", ipa:"/prəˈvoʊk/", pos:"v.", zh:"激起；激怒", def:"to cause a strong reaction", example:"His words ___ anger.", level:3},
  {word:"pursue", ipa:"/pərˈsuː/", pos:"v.", zh:"追求；从事", def:"to follow a goal", example:"She will ___ her dream.", level:3},
  {word:"restrain", ipa:"/rɪˈstreɪn/", pos:"v.", zh:"抑制；约束", def:"to hold back or control", example:"He couldn't ___ his anger.", level:3},
  {word:"retain", ipa:"/rɪˈteɪn/", pos:"v.", zh:"保留；保持", def:"to keep something", example:"The jar will ___ heat.", level:3},
  {word:"reveal", ipa:"/rɪˈviːl/", pos:"v.", zh:"揭示；透露", def:"to show something that was hidden", example:"The test will ___ the truth.", level:3},
  {word:"robust", ipa:"/roʊˈbʌst/", pos:"adj.", zh:"强健的；稳固的", def:"strong and reliable", example:"The system is ___ .", level:3},
  {word:"skeptical", ipa:"/ˈskeptɪkl/", pos:"adj.", zh:"怀疑的", def:"doubting that something is true", example:"I'm ___ about his claim.", level:3},
  {word:"stability", ipa:"/stəˈbɪləti/", pos:"n.", zh:"稳定；稳固", def:"the state of being steady", example:"The economy needs ___ .", level:3},
  {word:"subordinate", ipa:"/səˈbɔːrdɪnət/", pos:"adj.", zh:"从属的；下级的", def:"lower in rank or position", example:"He holds a ___ role.", level:3},

  // ---------- Level 4 学术（扩充，AWL） ----------
  {word:"abstract", ipa:"/ˈæbstrækt/", pos:"adj.", zh:"抽象的", def:"existing as an idea, not a physical thing", example:"It's an ___ concept.", level:4},
  {word:"accompany", ipa:"/əˈkʌmpəni/", pos:"v.", zh:"伴随；陪同", def:"to go with someone or something", example:"Fever may ___ the illness.", level:4},
  {word:"adjacent", ipa:"/əˈdʒeɪsnt/", pos:"adj.", zh:"相邻的；邻近的", def:"next to something", example:"The lab is ___ to the office.", level:4},
  {word:"aggregate", ipa:"/ˈæɡrɪɡət/", pos:"n.", zh:"总计；合计", def:"a total formed from parts", example:"The ___ of the data is huge.", level:4},
  {word:"albeit", ipa:"/ɔːlˈbiːɪt/", pos:"conj.", zh:"尽管；虽然", def:"although", example:"It was cheap, ___ low quality.", level:4},
  {word:"analogous", ipa:"/əˈnæləɡəs/", pos:"adj.", zh:"类似的；相似的", def:"similar in some way", example:"The two cases are ___ .", level:4},
  {word:"appendix", ipa:"/əˈpendɪks/", pos:"n.", zh:"附录；阑尾", def:"extra material at the end of a book", example:"See the ___ for details.", level:4},
  {word:"concurrent", ipa:"/kənˈkɜːrənt/", pos:"adj.", zh:"同时发生的；并发的", def:"happening at the same time", example:"The two events were ___ .", level:4},
  {word:"consequent", ipa:"/ˈkɑːnsɪkwənt/", pos:"adj.", zh:"随之发生的；作为结果的", def:"happening as a result", example:"The flood and its ___ damage.", level:4},
  {word:"controversy", ipa:"/ˈkɑːntrəvɜːrsi/", pos:"n.", zh:"争议；争论", def:"a strong public disagreement", example:"The decision caused ___ .", level:4},
  {word:"deficient", ipa:"/dɪˈfɪʃnt/", pos:"adj.", zh:"缺乏的；不足的", def:"not having enough of something", example:"The soil is ___ in iron.", level:4},
  {word:"discard", ipa:"/dɪsˈkɑːrd/", pos:"v.", zh:"丢弃；抛弃", def:"to throw something away", example:"You can ___ the old data.", level:4},
  {word:"discretion", ipa:"/dɪˈskreʃn/", pos:"n.", zh:"酌情决定权；谨慎", def:"the freedom to decide", example:"Use your own ___ .", level:4},
  {word:"distinct", ipa:"/dɪˈstɪŋkt/", pos:"adj.", zh:"不同的；清晰的", def:"clearly separate or different", example:"They are two ___ groups.", level:4},
  {word:"document", ipa:"/ˈdɑːkjumənt/", pos:"v.", zh:"记录；记载", def:"to record something in writing", example:"Please ___ the process.", level:4},
  {word:"domain", ipa:"/doʊˈmeɪn/", pos:"n.", zh:"领域；范围", def:"an area of activity or knowledge", example:"This is outside my ___ .", level:4},
  {word:"evolve", ipa:"/ɪˈvɑːlv/", pos:"v.", zh:"演变；进化", def:"to develop gradually", example:"The plan will ___ over time.", level:4},
  {word:"exclude", ipa:"/ɪkˈskluːd/", pos:"v.", zh:"排除；不包括", def:"to leave something out", example:"The price ___ tax.", level:4},
  {word:"incidence", ipa:"/ˈɪnsɪdəns/", pos:"n.", zh:"发生率", def:"the rate at which something happens", example:"The ___ of the disease is low.", level:4},
  {word:"induce", ipa:"/ɪnˈduːs/", pos:"v.", zh:"诱导；引起", def:"to cause something to happen", example:"The drug may ___ sleep.", level:4},
  {word:"integral", ipa:"/ˈɪntɪɡrəl/", pos:"adj.", zh:"不可或缺的", def:"necessary and important", example:"It's an ___ part of the system.", level:4},
  {word:"intervene", ipa:"/ˌɪntərˈviːn/", pos:"v.", zh:"干预；介入", def:"to get involved to change a situation", example:"The state will ___ .", level:4},
  {word:"isolate", ipa:"/ˈaɪsəleɪt/", pos:"v.", zh:"隔离；孤立", def:"to separate something from others", example:"They will ___ the cause.", level:4},
  {word:"minimal", ipa:"/ˈmɪnɪml/", pos:"adj.", zh:"最小的；极少的", def:"very small in amount", example:"The damage was ___ .", level:4},
  {word:"mutate", ipa:"/ˈmjuːteɪt/", pos:"v.", zh:"变异；突变", def:"to change in form or nature", example:"The virus can ___ quickly.", level:4},
  {word:"orient", ipa:"/ˈɔːrient/", pos:"v.", zh:"使适应；定位", def:"to adjust or aim at something", example:"The course is ___ toward beginners.", level:4},
  {word:"prospect", ipa:"/ˈprɑːspekt/", pos:"n.", zh:"前景；可能性", def:"the possibility of future success", example:"The job has good ___ .", level:4},
  {word:"protocol", ipa:"/ˈproʊtəkɔːl/", pos:"n.", zh:"协议；规程", def:"an official set of rules", example:"They follow a strict ___ .", level:4},
  {word:"proximity", ipa:"/prɑːkˈsɪməti/", pos:"n.", zh:"接近；邻近", def:"the state of being near", example:"The house's ___ to the school is a plus.", level:4},
  {word:"qualitative", ipa:"/ˈkwɑːləteɪtɪv/", pos:"adj.", zh:"定性的；性质的", def:"relating to quality, not quantity", example:"It's a ___ study.", level:4},
  {word:"quantitative", ipa:"/ˈkwɑːntəteɪtɪv/", pos:"adj.", zh:"定量的；数量的", def:"relating to amounts", example:"We need ___ data.", level:4},
  {word:"regime", ipa:"/reɪˈʒiːm/", pos:"n.", zh:"制度；政权", def:"a system of rules or government", example:"The new ___ brought change.", level:4},
  {word:"restore", ipa:"/rɪˈstɔːr/", pos:"v.", zh:"恢复；修复", def:"to bring something back", example:"They will ___ the old building.", level:4},
  {word:"revise", ipa:"/rɪˈvaɪz/", pos:"v.", zh:"修订；复习", def:"to change or review something", example:"Please ___ the draft.", level:4},
  {word:"sequence", ipa:"/ˈsiːkwəns/", pos:"n.", zh:"顺序；序列", def:"an order of things", example:"The steps must be done in ___ .", level:4},
  {word:"simulate", ipa:"/ˈsɪmjuleɪt/", pos:"v.", zh:"模拟；仿真", def:"to copy a real situation", example:"The software can ___ flight.", level:4},
  {word:"sole", ipa:"/soʊl/", pos:"adj.", zh:"唯一的；单独的", def:"only one", example:"He is the ___ owner.", level:4},
  {word:"sphere", ipa:"/sfɪr/", pos:"n.", zh:"领域；球体", def:"an area of activity, or a round shape", example:"It's outside his ___ of influence.", level:4},
  {word:"spontaneous", ipa:"/spɑːnˈteɪniəs/", pos:"adj.", zh:"自发的；自然的", def:"happening naturally without planning", example:"The crowd gave ___ applause.", level:4},
  {word:"supplement", ipa:"/ˈsʌplɪment/", pos:"v.", zh:"补充；增补", def:"to add something extra", example:"She will ___ her income.", level:4},
  {word:"suspend", ipa:"/səˈspend/", pos:"v.", zh:"暂停；悬挂", def:"to stop something temporarily", example:"They will ___ the service.", level:4},
  {word:"sustain", ipa:"/səˈsteɪn/", pos:"v.", zh:"维持；支撑", def:"to keep something going", example:"The land can ___ a large population.", level:4},
  {word:"terminate", ipa:"/ˈtɜːrmɪneɪt/", pos:"v.", zh:"终止；结束", def:"to end something", example:"They will ___ the contract.", level:4},
  {word:"theme", ipa:"/θiːm/", pos:"n.", zh:"主题；题目", def:"the main subject of something", example:"The ___ of the talk is change.", level:4},
  {word:"thereby", ipa:"/ˌðerˈbaɪ/", pos:"adv.", zh:"因此；从而", def:"by that means", example:"He saved money, ___ reducing debt.", level:4},
  {word:"trace", ipa:"/treɪs/", pos:"v.", zh:"追踪；追溯", def:"to find the origin of something", example:"They can ___ the source.", level:4},
  {word:"transform", ipa:"/trænsˈfɔːrm/", pos:"v.", zh:"转变；改造", def:"to change completely", example:"The internet will ___ education.", level:4},
  {word:"transition", ipa:"/trænˈzɪʃn/", pos:"n.", zh:"过渡；转变", def:"a change from one state to another", example:"The ___ was smooth.", level:4},
  {word:"transmit", ipa:"/trænsˈmɪt/", pos:"v.", zh:"传输；传播", def:"to send or pass something", example:"The device can ___ signals.", level:4},
  {word:"trigger", ipa:"/ˈtrɪɡər/", pos:"v.", zh:"触发；引起", def:"to cause something to start", example:"Stress can ___ the illness.", level:4},
  {word:"ultimate", ipa:"/ˈʌltɪmət/", pos:"adj.", zh:"最终的；根本的", def:"final or most important", example:"That's the ___ goal.", level:4},
  {word:"uniform", ipa:"/ˈjuːnɪfɔːrm/", pos:"adj.", zh:"统一的；一致的", def:"the same everywhere", example:"The standards are ___ .", level:4},
  {word:"unique", ipa:"/juˈniːk/", pos:"adj.", zh:"独特的；独一无二的", def:"being the only one of its kind", example:"Each person is ___ .", level:4},
  {word:"utility", ipa:"/juːˈtɪləti/", pos:"n.", zh:"效用；公用事业", def:"usefulness, or a public service", example:"The tool has little ___ .", level:4},
  {word:"utilize", ipa:"/ˈjuːtəlaɪz/", pos:"v.", zh:"利用；使用", def:"to use something effectively", example:"We should ___ the resources.", level:4},
  {word:"valid", ipa:"/ˈvælɪd/", pos:"adj.", zh:"有效的；合理的", def:"legally or logically acceptable", example:"Your ticket is still ___ .", level:4},
  {word:"variable", ipa:"/ˈveriəbl/", pos:"n.", zh:"变量；可变因素", def:"something that can change", example:"Price is the key ___ .", level:4},
  {word:"version", ipa:"/ˈvɜːrʒn/", pos:"n.", zh:"版本；说法", def:"a particular form of something", example:"This is the latest ___ .", level:4},
  {word:"virtual", ipa:"/ˈvɜːrtʃuəl/", pos:"adj.", zh:"虚拟的；实际上的", def:"existing online, or almost complete", example:"They held a ___ meeting.", level:4},
  {word:"visible", ipa:"/ˈvɪzəbl/", pos:"adj.", zh:"可见的；明显的", def:"able to be seen", example:"The stars are ___ tonight.", level:4},
  {word:"voluntary", ipa:"/ˈvɑːlənteri/", pos:"adj.", zh:"自愿的；志愿的", def:"done by choice, not forced", example:"It's a ___ activity.", level:4},
  {word:"whereas", ipa:"/ˌwerˈæz/", pos:"conj.", zh:"然而；鉴于", def:"in contrast to the fact that", example:"He likes tea, ___ she prefers coffee.", level:4},

  // ---------- 补足 500 词 ----------
  {word:"affirm", ipa:"/əˈfɜːrm/", pos:"v.", zh:"断言；确认", def:"to state something firmly as true", example:"She ___ her commitment.", level:2},
  {word:"ample", ipa:"/ˈæmpl/", pos:"adj.", zh:"充足的；丰富的", def:"more than enough", example:"We have ___ time.", level:2},
  {word:"anomaly", ipa:"/əˈnɑːməli/", pos:"n.", zh:"异常；反常", def:"something that is different from normal", example:"The result was an ___ .", level:2},
  {word:"assemble", ipa:"/əˈsembl/", pos:"v.", zh:"组装；集合", def:"to put parts together", example:"Workers ___ the cars.", level:2},
  {word:"cease", ipa:"/siːs/", pos:"v.", zh:"停止；终止", def:"to stop happening", example:"The rain will ___ soon.", level:2},
  {word:"decisive", ipa:"/dɪˈsaɪsɪv/", pos:"adj.", zh:"决定性的；果断的", def:"having a clear and strong effect", example:"It was a ___ victory.", level:2},
  {word:"designate", ipa:"/ˈdezɪɡneɪt/", pos:"v.", zh:"指定；任命", def:"to choose for a purpose", example:"They will ___ a leader.", level:2},
  {word:"dispose", ipa:"/dɪˈspoʊz/", pos:"v.", zh:"处理；丢弃", def:"to get rid of something", example:"Please ___ of the waste safely.", level:2},
  {word:"execute", ipa:"/ˈeksɪkjuːt/", pos:"v.", zh:"执行；实施", def:"to carry out a plan", example:"They will ___ the order.", level:2},
  {word:"illustrate", ipa:"/ˈɪləstreɪt/", pos:"v.", zh:"说明；举例", def:"to make something clear with examples", example:"The chart will ___ the trend.", level:2},
  {word:"preclude", ipa:"/prɪˈkluːd/", pos:"v.", zh:"排除；阻止", def:"to make something impossible", example:"The rule will ___ any doubt.", level:2},
  {word:"promote", ipa:"/prəˈmoʊt/", pos:"v.", zh:"促进；晋升", def:"to encourage or give a higher position", example:"The ads will ___ the product.", level:2},
  {word:"rational", ipa:"/ˈræʃnəl/", pos:"adj.", zh:"理性的；合理的", def:"based on reason, not emotion", example:"He made a ___ decision.", level:2},
  {word:"rely", ipa:"/rɪˈlaɪ/", pos:"v.", zh:"依赖；信赖", def:"to depend on something", example:"We ___ on technology.", level:2},
  {word:"restrict", ipa:"/rɪˈstrɪkt/", pos:"v.", zh:"限制；约束", def:"to limit something", example:"The law will ___ access.", level:2},
  {word:"specify", ipa:"/ˈspesɪfaɪ/", pos:"v.", zh:"明确说明；指定", def:"to state something clearly", example:"Please ___ your requirements.", level:2},
  {word:"submit", ipa:"/səbˈmɪt/", pos:"v.", zh:"提交；递交", def:"to give something for consideration", example:"Please ___ your report.", level:2},
  {word:"suppress", ipa:"/səˈpres/", pos:"v.", zh:"压制；抑制", def:"to stop something by force", example:"They tried to ___ the news.", level:2},
  {word:"undertake", ipa:"/ˌʌndərˈteɪk/", pos:"v.", zh:"承担；着手", def:"to accept a task", example:"She will ___ the project.", level:2},
  {word:"verify", ipa:"/ˈverɪfaɪ/", pos:"v.", zh:"核实；验证", def:"to check that something is true", example:"Please ___ the data.", level:2},
  {word:"adhere", ipa:"/ədˈhɪr/", pos:"v.", zh:"坚持；遵守", def:"to stick to a rule or belief", example:"We must ___ to the rules.", level:4},
  {word:"ambiguity", ipa:"/ˌæmbɪˈɡjuːəti/", pos:"n.", zh:"模棱两可；含糊", def:"a state of being unclear", example:"The ___ of the law caused problems.", level:4},
  {word:"consent", ipa:"/kənˈsent/", pos:"n.", zh:"同意；准许", def:"permission to do something", example:"You need their ___ first.", level:4},
  {word:"constraint", ipa:"/kənˈstreɪnt/", pos:"n.", zh:"约束；限制", def:"something that limits you", example:"Time is a big ___ .", level:4},
  {word:"displace", ipa:"/dɪsˈpleɪs/", pos:"v.", zh:"取代；使离开", def:"to force something out of place", example:"New tech will ___ old methods.", level:4},
  {word:"doctrine", ipa:"/ˈdɑːktrɪn/", pos:"n.", zh:"学说；教义", def:"a set of beliefs", example:"This is the core ___ .", level:4},
  {word:"duration", ipa:"/duˈreɪʃn/", pos:"n.", zh:"持续时间", def:"the length of time something lasts", example:"The ___ of the course is one year.", level:4},
  {word:"entity", ipa:"/ˈentəti/", pos:"n.", zh:"实体；独立存在物", def:"a thing that exists separately", example:"The company is a legal ___ .", level:4},
  {word:"erosion", ipa:"/ɪˈroʊʒn/", pos:"n.", zh:"侵蚀；削弱", def:"gradual wearing away", example:"Coastal ___ is a problem.", level:4},
  {word:"ideology", ipa:"/ˌaɪdiˈɑːlədʒi/", pos:"n.", zh:"意识形态", def:"a set of political beliefs", example:"The ___ shaped the policy.", level:4},
  {word:"integrity", ipa:"/ɪnˈteɡrəti/", pos:"n.", zh:"正直；完整", def:"honesty, or the state of being whole", example:"He is a man of ___ .", level:4},
  {word:"margin", ipa:"/ˈmɑːrdʒɪn/", pos:"n.", zh:"差额；边缘", def:"the difference or the edge", example:"They won by a small ___ .", level:4},
  {word:"migrate", ipa:"/ˈmaɪɡreɪt/", pos:"v.", zh:"迁移；移居", def:"to move to a new place", example:"Birds ___ south in winter.", level:4},
  {word:"philosophy", ipa:"/fəˈlɑːsəfi/", pos:"n.", zh:"哲学；理念", def:"a system of beliefs", example:"His ___ is simple.", level:4},
  {word:"prescribe", ipa:"/prɪˈskraɪb/", pos:"v.", zh:"规定；开处方", def:"to order a treatment or rule", example:"The doctor will ___ medicine.", level:4},
  {word:"principle", ipa:"/ˈprɪnsəpl/", pos:"n.", zh:"原则；原理", def:"a basic rule or belief", example:"He sticks to his ___ .", level:4},
  {word:"psychology", ipa:"/saɪˈkɑːlədʒi/", pos:"n.", zh:"心理学；心理", def:"the study of the mind", example:"She studies ___ .", level:4},
  {word:"reconcile", ipa:"/ˈrekənsaɪl/", pos:"v.", zh:"调和；使和解", def:"to make two things agree", example:"It's hard to ___ the two views.", level:4}
];
