// ============================================================
// 雅思核心词包 · 第2批（IELTS Batch 2）—— 主题/生活/高频扩展
// 字段与 words.js 一致；pack 标记词包名；level 标记难度/频率：
//   level 1 基础(日常)  level 2 进阶高频  level 3 高阶/中低频  level 4 学术
//   判词按 level 权重抽取：高频先遇到、先筛完；低频小比例混入。
// 加载方式：在 index.html 中排在 words_ielts1.js 之后引入。
// ============================================================
WORDS.push(
  // ---------- 健康 & 身体 ----------
  {word:"allergy", ipa:"/ˈælərdʒi/", pos:"n.", zh:"过敏", def:"a bad reaction of your body to some food or things", example:"He has an ___ to nuts, so he can't eat peanuts.", pack:"ielts2", level:2},
  {word:"disease", ipa:"/dɪˈziːz/", pos:"n.", zh:"疾病", def:"an illness that makes your body not work well", example:"Washing your hands can stop the ___ from spreading.", pack:"ielts2", level:2},
  {word:"symptom", ipa:"/ˈsɪmptəm/", pos:"n.", zh:"症状", def:"a sign that shows you are sick", example:"A high fever is a common ___ of this illness.", pack:"ielts2", level:2},
  {word:"injury", ipa:"/ˈɪndʒəri/", pos:"n.", zh:"受伤；伤害", def:"harm done to your body in an accident", example:"He missed the game because of a knee ___.", pack:"ielts2", level:2},
  {word:"treatment", ipa:"/ˈtriːtmənt/", pos:"n.", zh:"治疗；对待", def:"the way doctors help a sick person get better", example:"She is getting ___ for back pain.", pack:"ielts2", level:2},
  {word:"medicine", ipa:"/ˈmedɪsn/", pos:"n.", zh:"药；医学", def:"something you take to feel better when you are sick", example:"Take this ___ twice a day after meals.", pack:"ielts2", level:2},
  {word:"mental", ipa:"/ˈmentl/", pos:"adj.", zh:"精神的；心理的", def:"related to the mind, not the body", example:"Exercise is good for both ___ and physical health.", pack:"ielts2", level:2},
  {word:"physical", ipa:"/ˈfɪzɪkl/", pos:"adj.", zh:"身体的；体力的", def:"related to the body", example:"Playing sports keeps you in good ___ shape.", pack:"ielts2", level:2},
  {word:"cancer", ipa:"/ˈkænsər/", pos:"n.", zh:"癌症", def:"a very serious disease in which cells grow out of control", example:"Smoking increases the risk of lung ___.", pack:"ielts2", level:3},
  {word:"fitness", ipa:"/ˈfɪtnəs/", pos:"n.", zh:"健康；健壮", def:"the state of being strong and healthy", example:"She goes to the gym every day to keep her ___.", pack:"ielts2", level:2},

  // ---------- 环境 & 自然 ----------
  {word:"climate", ipa:"/ˈklaɪmət/", pos:"n.", zh:"气候", def:"the usual weather of a place over a long time", example:"The ___ in the north is cold and dry.", pack:"ielts2", level:2},
  {word:"atmosphere", ipa:"/ˈætməsfɪr/", pos:"n.", zh:"大气；气氛", def:"the air around the earth; the feeling of a place", example:"Gases are warming the ___ of the earth.", pack:"ielts2", level:3},
  {word:"species", ipa:"/ˈspiːʃiːz/", pos:"n.", zh:"物种", def:"a group of animals or plants of the same kind", example:"This rare ___ of bird lives only on that island.", pack:"ielts2", level:3},
  {word:"endangered", ipa:"/ɪnˈdeɪndʒərd/", pos:"adj.", zh:"濒危的", def:"in danger of disappearing from the world", example:"Tigers are an ___ animal in many countries.", pack:"ielts2", level:3},
  {word:"pollution", ipa:"/pəˈluːʃn/", pos:"n.", zh:"污染", def:"dirty air, water, or land that harms nature", example:"Air ___ is worse in big cities.", pack:"ielts2", level:2},
  {word:"flood", ipa:"/flʌd/", pos:"n./v.", zh:"洪水；淹没", def:"a large amount of water covering dry land", example:"The heavy rain caused a ___ in the village.", pack:"ielts2", level:2},
  {word:"earthquake", ipa:"/ˈɜːrθkweɪk/", pos:"n.", zh:"地震", def:"a sudden shaking of the ground", example:"The ___ destroyed many old buildings.", pack:"ielts2", level:3},
  {word:"volcano", ipa:"/vɑːlˈkeɪnoʊ/", pos:"n.", zh:"火山", def:"a mountain that can send out hot fire and rock", example:"The ___ last erupted fifty years ago.", pack:"ielts2", level:3},
  {word:"hurricane", ipa:"/ˈhɜːrəkeɪn/", pos:"n.", zh:"飓风", def:"a very strong storm with heavy rain and wind", example:"The ___ forced thousands of people to leave.", pack:"ielts2", level:3},
  {word:"storm", ipa:"/stɔːrm/", pos:"n.", zh:"暴风雨", def:"bad weather with strong wind and rain", example:"The ___ blew down several trees last night.", pack:"ielts2", level:2},
  {word:"glacier", ipa:"/ˈɡleɪʃər/", pos:"n.", zh:"冰川", def:"a very large, slow river of ice", example:"The ___ is melting because of warmer weather.", pack:"ielts2", level:3},
  {word:"soil", ipa:"/sɔɪl/", pos:"n.", zh:"土壤", def:"the top layer of earth where plants grow", example:"This ___ is good for growing rice.", pack:"ielts2", level:2},
  {word:"ocean", ipa:"/ˈoʊʃn/", pos:"n.", zh:"海洋", def:"the very large sea that covers most of the earth", example:"Plastic waste in the ___ harms sea animals.", pack:"ielts2", level:2},

  // ---------- 科技 & 数字 ----------
  {word:"technology", ipa:"/tekˈnɑːlədʒi/", pos:"n.", zh:"技术；科技", def:"new machines and ways of doing things using science", example:"Modern ___ makes our work much faster.", pack:"ielts2", level:2},
  {word:"data", ipa:"/ˈdeɪtə/", pos:"n.", zh:"数据", def:"facts and numbers collected for information", example:"The survey gives us ___ about people's habits.", pack:"ielts2", level:2},
  {word:"database", ipa:"/ˈdeɪtəbeɪs/", pos:"n.", zh:"数据库", def:"a large set of information stored in a computer", example:"The library has a ___ of all its books.", pack:"ielts2", level:3},
  {word:"network", ipa:"/ˈnetwɜːrk/", pos:"n.", zh:"网络", def:"a group of computers or people that are connected", example:"The whole building shares one computer ___.", pack:"ielts2", level:2},
  {word:"server", ipa:"/ˈsɜːrvər/", pos:"n.", zh:"服务器", def:"a computer that stores and sends data for other computers", example:"The website went down when the ___ stopped working.", pack:"ielts2", level:3},
  {word:"website", ipa:"/ˈwebsaɪt/", pos:"n.", zh:"网站", def:"a place on the Internet with information about a person or thing", example:"You can find the bus times on the city ___", pack:"ielts2", level:2},
  {word:"email", ipa:"/ˈiːmeɪl/", pos:"n./v.", zh:"电子邮件", def:"a message sent through the Internet", example:"Please send me the report by ___ today.", pack:"ielts2", level:2},
  {word:"password", ipa:"/ˈpæswɜːrd/", pos:"n.", zh:"密码", def:"a secret word that lets you use a computer or account", example:"Never tell your ___ to anyone.", pack:"ielts2", level:2},
  {word:"upload", ipa:"/ˌʌpˈloʊd/", pos:"v.", zh:"上传", def:"to send a file from your device to the Internet", example:"She ___ed the photos to her blog.", pack:"ielts2", level:2},
  {word:"gadget", ipa:"/ˈɡædʒɪt/", pos:"n.", zh:"小电子设备", def:"a small machine that does a useful thing", example:"This small ___ tells you how many steps you walk.", pack:"ielts2", level:3},
  {word:"robot", ipa:"/ˈroʊbɑːt/", pos:"n.", zh:"机器人", def:"a machine that can do work like a person", example:"A ___ now builds parts in the factory.", pack:"ielts2", level:2},
  {word:"screen", ipa:"/skriːn/", pos:"n.", zh:"屏幕", def:"the flat part of a computer or phone that shows pictures", example:"Looking at a small ___ for hours hurts your eyes.", pack:"ielts2", level:2},
  {word:"computer", ipa:"/kəmˈpjuːtər/", pos:"n.", zh:"电脑", def:"an electronic machine that stores and uses information", example:"He writes his code on a new ___.", pack:"ielts2", level:1},
  {word:"internet", ipa:"/ˈɪntərnet/", pos:"n.", zh:"互联网", def:"the system that connects computers around the world", example:"We use the ___ to search for information.", pack:"ielts2", level:1},
  {word:"machine", ipa:"/məˈʃiːn/", pos:"n.", zh:"机器", def:"a thing with parts that uses power to do work", example:"This ___ washes the dishes for us.", pack:"ielts2", level:2},
  {word:"laptop", ipa:"/ˈlæptɑːp/", pos:"n.", zh:"笔记本电脑", def:"a small computer you can carry and use anywhere", example:"She takes her ___ to work every day.", pack:"ielts2", level:2},
  {word:"smartphone", ipa:"/ˈsmɑːrtfoʊn/", pos:"n.", zh:"智能手机", def:"a mobile phone that can use the Internet and apps", example:"Most people check their ___ as soon as they wake up.", pack:"ielts2", level:2},
  {word:"hardware", ipa:"/ˈhɑːrdwer/", pos:"n.", zh:"硬件", def:"the physical parts of a computer, like the screen and keyboard", example:"The problem is in the ___ , not the software.", pack:"ielts2", level:3},
  {word:"keyword", ipa:"/ˈkiːwɜːrd/", pos:"n.", zh:"关键词", def:"a word you type to search for information", example:"Type the ___ in the search box to find it.", pack:"ielts2", level:3},
  {word:"browser", ipa:"/ˈbraʊzər/", pos:"n.", zh:"浏览器", def:"a program that lets you look at pages on the Internet", example:"Open your ___ and go to the news site.", pack:"ielts2", level:3},
  {word:"email account", ipa:"/ɪˈmeɪl əˈkaʊnt/", pos:"n.", zh:"电子邮箱账户", def:"an account that lets you send and get emails", example:"She opened a new ___ to separate work and home mail.", pack:"ielts2", level:3},

  // ---------- 社会 & 法律 & 政治 ----------
  {word:"society", ipa:"/səˈsaɪəti/", pos:"n.", zh:"社会", def:"people living together in a country or area", example:"In modern ___, people use phones all the time.", pack:"ielts2", level:2},
  {word:"population", ipa:"/ˌpɑːpjuˈleɪʃn/", pos:"n.", zh:"人口", def:"all the people who live in a place", example:"The ___ of this city is over one million.", pack:"ielts2", level:2},
  {word:"culture", ipa:"/ˈkʌltʃər/", pos:"n.", zh:"文化", def:"the way of life, food, and ideas of a group of people", example:"Traveling lets you learn about other ___.", pack:"ielts2", level:2},
  {word:"citizen", ipa:"/ˈsɪtɪzn/", pos:"n.", zh:"公民；市民", def:"a person who lives in and belongs to a country", example:"Every ___ has the right to vote.", pack:"ielts2", level:3},
  {word:"law", ipa:"/lɔː/", pos:"n.", zh:"法律", def:"a rule that everyone in a country must follow", example:"It is against the ___ to drive without a license.", pack:"ielts2", level:2},
  {word:"legal", ipa:"/ˈliːɡl/", pos:"adj.", zh:"合法的", def:"allowed by the law", example:"Is it ___ to ride a bike on the sidewalk here?", pack:"ielts2", level:2},
  {word:"court", ipa:"/kɔːrt/", pos:"n.", zh:"法庭", def:"the place where a judge decides if someone broke the law", example:"The case will be heard in ___ next month.", pack:"ielts2", level:3},
  {word:"judge", ipa:"/dʒʌdʒ/", pos:"n./v.", zh:"法官；判断", def:"a person who decides in a court; to decide or form an opinion", example:"The ___ asked the man to explain his story.", pack:"ielts2", level:3},
  {word:"justice", ipa:"/ˈdʒʌstɪs/", pos:"n.", zh:"公正；司法", def:"fair treatment; the system of law", example:"The family wants ___ for the lost worker.", pack:"ielts2", level:3},
  {word:"crime", ipa:"/kraɪm/", pos:"n.", zh:"犯罪", def:"an act that is against the law", example:"Stealing is a ___ in every country.", pack:"ielts2", level:2},
  {word:"criminal", ipa:"/ˈkrɪmɪnl/", pos:"n./adj.", zh:"罪犯；犯罪的", def:"a person who has done something against the law", example:"The ___ was caught by the police.", pack:"ielts2", level:3},
  {word:"election", ipa:"/ɪˈlekʃn/", pos:"n.", zh:"选举", def:"the event of choosing leaders by voting", example:"The next ___ will be held in May.", pack:"ielts2", level:3},
  {word:"parliament", ipa:"/ˈpɑːrləmənt/", pos:"n.", zh:"议会", def:"the group of people who make laws in a country", example:"The ___ passed a new law about traffic.", pack:"ielts2", level:3},
  {word:"government", ipa:"/ˈɡʌvərnmənt/", pos:"n.", zh:"政府", def:"the group of people who lead and rule a country", example:"The ___ plans to build more hospitals.", pack:"ielts2", level:2},
  {word:"protest", ipa:"/ˈproʊtest/", pos:"n./v.", zh:"抗议", def:"to show strongly that you do not agree", example:"Workers held a ___ about their low pay.", pack:"ielts2", level:3},
  {word:"constitution", ipa:"/ˌkɑːnstɪˈtuːʃn/", pos:"n.", zh:"宪法", def:"the set of most important rules of a country", example:"The ___ protects the rights of citizens.", pack:"ielts2", level:4},
  {word:"public", ipa:"/ˈpʌblɪk/", pos:"adj./n.", zh:"公共的；公众", def:"for everyone to use or see", example:"The park is open to the ___ all day.", pack:"ielts2", level:2},

  // ---------- 工作 & 经济 ----------
  {word:"economy", ipa:"/ɪˈkɑːnəmi/", pos:"n.", zh:"经济", def:"the system of making, buying, and selling goods in a country", example:"The ___ grows fast when people spend more.", pack:"ielts2", level:2},
  {word:"budget", ipa:"/ˈbʌdʒɪt/", pos:"n./v.", zh:"预算", def:"the money you plan to spend for something", example:"We have a small ___ for the trip.", pack:"ielts2", level:2},
  {word:"credit", ipa:"/ˈkredɪt/", pos:"n.", zh:"信用；赊账", def:"the ability to buy now and pay later", example:"He paid for the TV with his ___ card.", pack:"ielts2", level:3},
  {word:"debt", ipa:"/det/", pos:"n.", zh:"债务", def:"money that you owe to someone", example:"She worked hard to pay off her ___.", pack:"ielts2", level:3},
  {word:"cash", ipa:"/kæʃ/", pos:"n.", zh:"现金", def:"money in coins and paper notes", example:"Do you have ___ or do you pay by card?", pack:"ielts2", level:2},
  {word:"currency", ipa:"/ˈkɜːrənsi/", pos:"n.", zh:"货币", def:"the money used in a country", example:"The local ___ is the yuan.", pack:"ielts2", level:3},
  {word:"tax", ipa:"/tæks/", pos:"n.", zh:"税", def:"money people pay to the government", example:"Part of your salary goes to ___ every month.", pack:"ielts2", level:2},
  {word:"contract", ipa:"/ˈkɑːntrækt/", pos:"n.", zh:"合同", def:"a written agreement between people or companies", example:"Read the ___ carefully before you sign it.", pack:"ielts2", level:3},
  {word:"market", ipa:"/ˈmɑːrkɪt/", pos:"n.", zh:"市场", def:"a place where people buy and sell things; the demand for a product", example:"They sell fresh fruit at the morning ___.", pack:"ielts2", level:2},
  {word:"brand", ipa:"/brænd/", pos:"n.", zh:"品牌", def:"the name of a product made by one company", example:"People often buy the same ___ they trust.", pack:"ielts2", level:2},
  {word:"customer", ipa:"/ˈkʌstəmər/", pos:"n.", zh:"顾客", def:"a person who buys something from a shop", example:"The shop gives free coffee to its ___.", pack:"ielts2", level:2},
  {word:"advertising", ipa:"/ˈædvərtaɪzɪŋ/", pos:"n.", zh:"广告（业）", def:"the business of telling people about products", example:"Most of the website's money comes from ___.", pack:"ielts2", level:2},
  {word:"discount", ipa:"/ˈdɪskaʊnt/", pos:"n.", zh:"折扣", def:"money taken off the usual price", example:"Students get a 20% ___ at this shop.", pack:"ielts2", level:2},
  {word:"insurance", ipa:"/ɪnˈʃʊrəns/", pos:"n.", zh:"保险", def:"an agreement to pay for losses or accidents", example:"Health ___ helps pay for hospital costs.", pack:"ielts2", level:3},
  {word:"bonus", ipa:"/ˈboʊnəs/", pos:"n.", zh:"奖金；额外好处", def:"extra money or a good thing added to something", example:"Workers get a ___ at the end of the year.", pack:"ielts2", level:3},
  {word:"deadline", ipa:"/ˈdedlaɪn/", pos:"n.", zh:"截止日期", def:"the latest time by which you must finish something", example:"The ___ for the report is Friday.", pack:"ielts2", level:2},
  {word:"teamwork", ipa:"/ˈtiːmwɜːrk/", pos:"n.", zh:"团队合作", def:"working well together with other people", example:"Good ___ helps the group finish faster.", pack:"ielts2", level:2},
  {word:"workload", ipa:"/ˈwɜːrkloʊd/", pos:"n.", zh:"工作量", def:"the amount of work you must do", example:"Her ___ is too heavy this week.", pack:"ielts2", level:3},
  {word:"stock", ipa:"/stɑːk/", pos:"n.", zh:"股票；存货", def:"a share of a company you can buy; goods kept to sell", example:"He buys and sells ___ online.", pack:"ielts2", level:3},
  {word:"bank", ipa:"/bæŋk/", pos:"n.", zh:"银行", def:"a place that keeps and lends money", example:"I put some money in the ___ every month.", pack:"ielts2", level:2},
  {word:"job", ipa:"/dʒɑːb/", pos:"n.", zh:"工作", def:"the work you do to earn money", example:"She found a new ___ near her home.", pack:"ielts2", level:1},
  {word:"factory", ipa:"/ˈfæktəri/", pos:"n.", zh:"工厂", def:"a building where things are made in large numbers", example:"The ___ makes car parts.", pack:"ielts2", level:2},
  {word:"price", ipa:"/praɪs/", pos:"n.", zh:"价格", def:"the money you must pay to buy something", example:"The ___ of fruit goes up in winter.", pack:"ielts2", level:2},

  // ---------- 教育 & 学习 ----------
  {word:"exam", ipa:"/ɪɡˈzæm/", pos:"n.", zh:"考试", def:"a formal test of what you have learned", example:"She passed her final ___ with a high score.", pack:"ielts2", level:2},
  {word:"essay", ipa:"/ˈeseɪ/", pos:"n.", zh:"短文；论文", def:"a short piece of writing about one subject", example:"We have to write an ___ about the environment.", pack:"ielts2", level:2},
  {word:"lecture", ipa:"/ˈlektʃər/", pos:"n.", zh:"讲座；大课", def:"a talk given to a group to teach something", example:"The professor gave a ___ on history.", pack:"ielts2", level:2},
  {word:"semester", ipa:"/sɪˈmestər/", pos:"n.", zh:"学期", def:"one of the two halves of a school year", example:"The first ___ ends in January.", pack:"ielts2", level:3},
  {word:"research", ipa:"/ˈriːsɜːrtʃ/", pos:"n./v.", zh:"研究", def:"careful study to find new facts", example:"Her ___ shows that reading helps children's brains.", pack:"ielts2", level:2},
  {word:"subject", ipa:"/ˈsʌbdʒɪkt/", pos:"n.", zh:"科目；主题", def:"a thing you study, like math or history", example:"My favorite ___ in school was science.", pack:"ielts2", level:2},
  {word:"homework", ipa:"/ˈhoʊmwɜːrk/", pos:"n.", zh:"家庭作业", def:"work that teachers give students to do at home", example:"I finished my ___ before dinner.", pack:"ielts2", level:1},
  {word:"library", ipa:"/ˈlaɪbreri/", pos:"n.", zh:"图书馆", def:"a place with many books you can read or borrow", example:"She studies in the ___ every evening.", pack:"ielts2", level:2},
  {word:"knowledge", ipa:"/ˈnɑːlɪdʒ/", pos:"n.", zh:"知识", def:"the things you know and understand", example:"Reading widely increases your ___.", pack:"ielts2", level:2},
  {word:"skill", ipa:"/skɪl/", pos:"n.", zh:"技能", def:"the ability to do something well", example:"Cooking is a useful ___ to have.", pack:"ielts2", level:2},
  {word:"practice", ipa:"/ˈpræktɪs/", pos:"n./v.", zh:"练习；实践", def:"doing something many times to get better", example:"You need daily ___ to improve your English.", pack:"ielts2", level:2},
  {word:"progress", ipa:"/ˈprɑːɡres/", pos:"n.", zh:"进步", def:"moving forward or getting better", example:"She has made great ___ this year.", pack:"ielts2", level:2},

  // ---------- 旅行 & 交通 ----------
  {word:"tourism", ipa:"/ˈtʊrɪzəm/", pos:"n.", zh:"旅游业", def:"the business of helping and serving travelers", example:"The island depends on ___ for money.", pack:"ielts2", level:3},
  {word:"tourist", ipa:"/ˈtʊrɪst/", pos:"n.", zh:"游客", def:"a person who visits a place for fun", example:"Many ___ come to see the old town.", pack:"ielts2", level:2},
  {word:"destination", ipa:"/ˌdestɪˈneɪʃn/", pos:"n.", zh:"目的地", def:"the place you are going to", example:"Our ___ is a small beach town.", pack:"ielts2", level:3},
  {word:"journey", ipa:"/ˈdʒɜːrni/", pos:"n.", zh:"旅程", def:"the act of traveling from one place to another", example:"The ___ to the mountains takes three hours.", pack:"ielts2", level:2},
  {word:"luggage", ipa:"/ˈlʌɡɪdʒ/", pos:"n.", zh:"行李", def:"the bags you carry when you travel", example:"Please keep your ___ with you at all times.", pack:"ielts2", level:2},
  {word:"passenger", ipa:"/ˈpæsɪndʒər/", pos:"n.", zh:"乘客", def:"a person traveling in a car, bus, train, or plane", example:"All ___ must wear their seat belts.", pack:"ielts2", level:2},
  {word:"vehicle", ipa:"/ˈviːəkl/", pos:"n.", zh:"车辆", def:"a machine that carries people or things, like a car or bus", example:"This road is closed to all ___.", pack:"ielts2", level:3},
  {word:"flight", ipa:"/flaɪt/", pos:"n.", zh:"航班；飞行", def:"a trip in a plane", example:"Our ___ leaves at six in the morning.", pack:"ielts2", level:2},
  {word:"cruise", ipa:"/kruːz/", pos:"n.", zh:"乘船游览", def:"a holiday trip on a large ship", example:"They took a ___ around the islands.", pack:"ielts2", level:3},
  {word:"ticket", ipa:"/ˈtɪkɪt/", pos:"n.", zh:"票", def:"a small paper that lets you travel or enter a place", example:"You need a ___ to enter the museum.", pack:"ielts2", level:1},

  // ---------- 食物 & 购物 ----------
  {word:"ingredient", ipa:"/ɪnˈɡriːdiənt/", pos:"n.", zh:"（烹饪）原料", def:"one of the foods you use to make a dish", example:"Flour and eggs are the main ___ of the cake.", pack:"ielts2", level:3},
  {word:"recipe", ipa:"/ˈresəpi/", pos:"n.", zh:"食谱", def:"the instructions for cooking a dish", example:"This ___ tells you how to make noodles.", pack:"ielts2", level:2},
  {word:"cuisine", ipa:"/kwɪˈziːn/", pos:"n.", zh:"（某种风格的）菜肴", def:"a style of cooking from a country or region", example:"French ___ is famous around the world.", pack:"ielts2", level:3},
  {word:"grocery", ipa:"/ˈɡroʊsəri/", pos:"n.", zh:"食品杂货", def:"food and things you buy for the home", example:"I need to stop at the ___ store on my way home.", pack:"ielts2", level:3},
  {word:"snack", ipa:"/snæk/", pos:"n.", zh:"零食", def:"a small amount of food eaten between meals", example:"He had a ___ after school.", pack:"ielts2", level:2},
  {word:"meal", ipa:"/miːl/", pos:"n.", zh:"一餐", def:"food you eat at one time, like breakfast or dinner", example:"The hotel serves three ___ a day.", pack:"ielts2", level:1},
  {word:"flavor", ipa:"/ˈfleɪvər/", pos:"n.", zh:"味道", def:"the taste of food or drink", example:"This ice cream has a chocolate ___.", pack:"ielts2", level:2},
  {word:"shopping", ipa:"/ˈʃɑːpɪŋ/", pos:"n.", zh:"购物", def:"the activity of buying things in shops", example:"I like to do my ___ on the weekend.", pack:"ielts2", level:1},

  // ---------- 文化 & 媒体 & 娱乐 ----------
  {word:"entertainment", ipa:"/ˌentərˈteɪnmənt/", pos:"n.", zh:"娱乐", def:"things that amuse you, like films, music, and games", example:"The city offers many kinds of ___.", pack:"ielts2", level:3},
  {word:"celebrity", ipa:"/səˈlebrəti/", pos:"n.", zh:"名人", def:"a famous person, like an actor or singer", example:"The ___ waved to her fans.", pack:"ielts2", level:3},
  {word:"festival", ipa:"/ˈfestɪvl/", pos:"n.", zh:"节日", def:"a special day or period with music, food, and fun", example:"The Spring ___ is the biggest holiday here.", pack:"ielts2", level:2},
  {word:"tradition", ipa:"/trəˈdɪʃn/", pos:"n.", zh:"传统", def:"a way of doing things that is passed from parents to children", example:"Eating dumplings is a ___ in winter.", pack:"ielts2", level:2},
  {word:"custom", ipa:"/ˈkʌstəm/", pos:"n.", zh:"风俗；习惯", def:"the usual way of doing things in a place", example:"Shaking hands is a ___ when you meet someone here.", pack:"ielts2", level:3},
  {word:"religion", ipa:"/rɪˈlɪdʒən/", pos:"n.", zh:"宗教", def:"the belief in a god or gods and the ways of following it", example:"People of every ___ live in this city.", pack:"ielts2", level:3},
  {word:"audience", ipa:"/ˈɔːdiəns/", pos:"n.", zh:"观众；听众", def:"the people who watch or listen to a show", example:"The ___ clapped loudly at the end.", pack:"ielts2", level:3},
  {word:"media", ipa:"/ˈmiːdiə/", pos:"n.", zh:"媒体", def:"television, newspapers, and the Internet as a group", example:"The ___ reported the news within an hour.", pack:"ielts2", level:3},
  {word:"gallery", ipa:"/ˈɡæləri/", pos:"n.", zh:"美术馆；画廊", def:"a place where art is shown", example:"We saw some old paintings at the ___.", pack:"ielts2", level:3},
  {word:"performance", ipa:"/pərˈfɔːrməns/", pos:"n.", zh:"表演", def:"a show in front of people, like a play or concert", example:"The ___ lasted two hours.", pack:"ielts2", level:3},
  {word:"exhibition", ipa:"/ˌeksɪˈbɪʃn/", pos:"n.", zh:"展览", def:"a public show of art or interesting things", example:"There is a photo ___ at the museum this month.", pack:"ielts2", level:3},
  {word:"museum", ipa:"/mjuˈziːəm/", pos:"n.", zh:"博物馆", def:"a place that shows important old or interesting things", example:"The ___ has a collection of ancient coins.", pack:"ielts2", level:2},
  {word:"movie", ipa:"/ˈmuːvi/", pos:"n.", zh:"电影", def:"a story shown on a screen", example:"We watched a funny ___ last night.", pack:"ielts2", level:1},

  // ---------- 生活 & 人际关系 ----------
  {word:"lifestyle", ipa:"/ˈlaɪfstaɪl/", pos:"n.", zh:"生活方式", def:"the way a person lives", example:"A healthy ___ includes good food and exercise.", pack:"ielts2", level:2},
  {word:"relationship", ipa:"/rɪˈleɪʃnʃɪp/", pos:"n.", zh:"关系", def:"the way two people or groups feel and act with each other", example:"They have a close ___ with their neighbors.", pack:"ielts2", level:2},
  {word:"marriage", ipa:"/ˈmærɪdʒ/", pos:"n.", zh:"婚姻", def:"the state of being married", example:"They celebrated their tenth ___ anniversary.", pack:"ielts2", level:2},
  {word:"personality", ipa:"/ˌpɜːrsəˈnæləti/", pos:"n.", zh:"性格", def:"the character of a person, the way they behave", example:"She has a warm and friendly ___.", pack:"ielts2", level:3},
  {word:"childhood", ipa:"/ˈtʃaɪldhʊd/", pos:"n.", zh:"童年", def:"the time when you are a child", example:"He has happy memories of his ___.", pack:"ielts2", level:2},
  {word:"elderly", ipa:"/ˈeldərli/", pos:"adj.", zh:"年长的", def:"old, past middle age", example:"The ___ man walks slowly with a stick.", pack:"ielts2", level:2},
  {word:"generation", ipa:"/ˌdʒenəˈreɪʃn/", pos:"n.", zh:"一代人", def:"all the people born at about the same time", example:"My parents' ___ grew up without phones.", pack:"ielts2", level:3},
  {word:"habit", ipa:"/ˈhæbɪt/", pos:"n.", zh:"习惯", def:"something you do often without thinking", example:"Reading before bed is a good ___.", pack:"ielts2", level:2},
  {word:"hobby", ipa:"/ˈhɑːbi/", pos:"n.", zh:"爱好", def:"something you enjoy doing in your free time", example:"Her ___ is taking photos of birds.", pack:"ielts2", level:2},
  {word:"leisure", ipa:"/ˈliːʒər/", pos:"n.", zh:"闲暇", def:"free time when you are not working", example:"He spends his ___ time playing chess.", pack:"ielts2", level:3},
  {word:"neighbor", ipa:"/ˈneɪbər/", pos:"n.", zh:"邻居", def:"a person who lives near you", example:"Our ___ helped us carry the boxes.", pack:"ielts2", level:2},
  {word:"colleague", ipa:"/ˈkɑːliːɡ/", pos:"n.", zh:"同事", def:"a person you work with", example:"She has lunch with her ___ every day.", pack:"ielts2", level:2},
  {word:"friend", ipa:"/frend/", pos:"n.", zh:"朋友", def:"a person you like and trust", example:"He is an old ___ from school.", pack:"ielts2", level:1},
  {word:"family", ipa:"/ˈfæməli/", pos:"n.", zh:"家庭", def:"parents and children, or people related by blood", example:"My ___ has dinner together every Sunday.", pack:"ielts2", level:1},
  {word:"privacy", ipa:"/ˈpraɪvəsi/", pos:"n.", zh:"隐私", def:"the state of being alone and not watched", example:"Everyone needs some ___ from work.", pack:"ielts2", level:3},

  // ---------- 常用形容词/副词（写作口语通用） ----------
  {word:"enormous", ipa:"/ɪˈnɔːrməs/", pos:"adj.", zh:"巨大的", def:"very, very large", example:"They spent an ___ amount of money on the house.", pack:"ielts2", level:3},
  {word:"considerable", ipa:"/kənˈsɪdərəbl/", pos:"adj.", zh:"相当大的", def:"large enough to be important", example:"The new road caused a ___ drop in traffic.", pack:"ielts2", level:3},
  {word:"beneficial", ipa:"/ˌbenɪˈfɪʃl/", pos:"adj.", zh:"有益的", def:"good for you or for something", example:"Morning exercise is ___ for your health.", pack:"ielts2", level:3},
  {word:"valuable", ipa:"/ˈvæljuəbl/", pos:"adj.", zh:"宝贵的；值钱的", def:"worth a lot of money or very useful", example:"She gave me some ___ advice about my career.", pack:"ielts2", level:2},
  {word:"affordable", ipa:"/əˈfɔːrdəbl/", pos:"adj.", zh:"负担得起的", def:"cheap enough for most people to buy", example:"The city needs more ___ housing for young people.", pack:"ielts2", level:3},
  {word:"approximately", ipa:"/əˈprɑːksɪmətli/", pos:"adv.", zh:"大约", def:"almost but not exactly", example:"The trip takes ___ two hours.", pack:"ielts2", level:3},
  {word:"harmful", ipa:"/ˈhɑːrmfl/", pos:"adj.", zh:"有害的", def:"causing damage or danger", example:"Smoking is ___ to your health.", pack:"ielts2", level:2},
  {word:"useful", ipa:"/ˈjuːsfl/", pos:"adj.", zh:"有用的", def:"helping you do something", example:"This app is very ___ for learning words.", pack:"ielts2", level:1},
  {word:"popular", ipa:"/ˈpɑːpjələr/", pos:"adj.", zh:"受欢迎的", def:"liked by many people", example:"This song is ___ with young people.", pack:"ielts2", level:2},
  {word:"comfortable", ipa:"/ˈkʌmftəbl/", pos:"adj.", zh:"舒适的", def:"making you feel relaxed and nice", example:"This chair is soft and ___.", pack:"ielts2", level:2},
  {word:"expensive", ipa:"/ɪkˈspensɪv/", pos:"adj.", zh:"昂贵的", def:"costing a lot of money", example:"Eating out every day is ___.", pack:"ielts2", level:1},
  {word:"necessary", ipa:"/ˈnesəseri/", pos:"adj.", zh:"必要的", def:"needed, you cannot do without it", example:"A passport is ___ for travel abroad.", pack:"ielts2", level:2},
  {word:"responsible", ipa:"/rɪˈspɑːnsəbl/", pos:"adj.", zh:"负责的", def:"having the duty to take care of something", example:"She is ___ for training the new staff.", pack:"ielts2", level:2},
  {word:"reliable", ipa:"/rɪˈlaɪəbl/", pos:"adj.", zh:"可靠的", def:"able to be trusted to do what you expect", example:"We need a ___ car for long trips.", pack:"ielts2", level:3},
  {word:"flexible", ipa:"/ˈfleksəbl/", pos:"adj.", zh:"灵活的", def:"able to change easily to fit new needs", example:"My job has ___ working hours.", pack:"ielts2", level:3},
  {word:"suitable", ipa:"/ˈsuːtəbl/", pos:"adj.", zh:"合适的", def:"right for a purpose or person", example:"This film is not ___ for small children.", pack:"ielts2", level:3},
  {word:"independent", ipa:"/ˌɪndɪˈpendənt/", pos:"adj.", zh:"独立的", def:"not needing help from others", example:"She has been ___ since she moved out.", pack:"ielts2", level:3},
  {word:"confident", ipa:"/ˈkɑːnfɪdənt/", pos:"adj.", zh:"自信的", def:"sure that you can do something well", example:"He feels ___ about his English now.", pack:"ielts2", level:2},
  {word:"anxious", ipa:"/ˈæŋkʃəs/", pos:"adj.", zh:"焦虑的", def:"worried and nervous", example:"She felt ___ before the big test.", pack:"ielts2", level:3},
  {word:"proud", ipa:"/praʊd/", pos:"adj.", zh:"自豪的", def:"feeling happy about something you or others did well", example:"Her parents are ___ of her success.", pack:"ielts2", level:2},
  {word:"friendly", ipa:"/ˈfrendli/", pos:"adj.", zh:"友好的", def:"kind and pleasant to others", example:"The staff here are very ___.", pack:"ielts2", level:1},
  {word:"polite", ipa:"/pəˈlaɪt/", pos:"adj.", zh:"有礼貌的", def:"behaving in a kind and respectful way", example:"It is ___ to say thank you.", pack:"ielts2", level:2},
  {word:"honest", ipa:"/ˈɑːnɪst/", pos:"adj.", zh:"诚实的", def:"always telling the truth", example:"He is ___ and never lies.", pack:"ielts2", level:2},

  // ---------- 常用动词（进阶高频） ----------
  {word:"succeed", ipa:"/səkˈsiːd/", pos:"v.", zh:"成功", def:"to do what you tried to do", example:"She worked late to ___ in her project.", pack:"ielts2", level:2},
  {word:"protect", ipa:"/prəˈtekt/", pos:"v.", zh:"保护", def:"to keep someone or something safe", example:"We must ___ the forests from fire.", pack:"ielts2", level:2},
  {word:"prevent", ipa:"/prɪˈvent/", pos:"v.", zh:"阻止；预防", def:"to stop something from happening", example:"Washing hands can ___ many illnesses.", pack:"ielts2", level:2},
  {word:"manage", ipa:"/ˈmænɪdʒ/", pos:"v.", zh:"设法做到；管理", def:"to succeed in doing something hard; to be in charge of a business", example:"She ___s to study and work at the same time.", pack:"ielts2", level:2},
  {word:"remember", ipa:"/rɪˈmembər/", pos:"v.", zh:"记得", def:"to keep something in your mind", example:"I can't ___ where I put my keys.", pack:"ielts2", level:1},
  {word:"forget", ipa:"/fərˈɡet/", pos:"v.", zh:"忘记", def:"to not remember something", example:"Don't ___ to call your mother.", pack:"ielts2", level:1},
  {word:"believe", ipa:"/bɪˈliːv/", pos:"v.", zh:"相信", def:"to think something is true", example:"I ___ that hard work brings good results.", pack:"ielts2", level:1},
  {word:"expect", ipa:"/ɪkˈspekt/", pos:"v.", zh:"期待；预料", def:"to think something will happen", example:"We ___ the train to arrive on time.", pack:"ielts2", level:2},
  {word:"mention", ipa:"/ˈmenʃn/", pos:"v.", zh:"提到", def:"to say something briefly", example:"He ___ed that the meeting starts at nine.", pack:"ielts2", level:2},
  {word:"share", ipa:"/ʃer/", pos:"v.", zh:"分享", def:"to let others use or have part of something", example:"The two sisters ___ one bedroom.", pack:"ielts2", level:1},
  {word:"spend", ipa:"/spend/", pos:"v.", zh:"花费（时间/钱）", def:"to use money or time on something", example:"He ___s an hour reading every morning.", pack:"ielts2", level:1},
  {word:"return", ipa:"/rɪˈtɜːrn/", pos:"v.", zh:"返回；归还", def:"to come or go back; to give something back", example:"She will ___ home after the meeting.", pack:"ielts2", level:1},
);
