// =========================================================
// 雅思核心词包 · 第6批（IELTS Batch 6）—— 生活高频补全
// 目标：优先把 level1/2 的常用日常词补完整（动物/食物/居家/衣物/身体/学校/自然…）。
// =========================================================
WORDS.push(
  // ---------- 动物 ----------
  {word:"ant", ipa:"/ænt/", pos:"n.", zh:"蚂蚁", def:"a very small insect that lives in large groups", example:"An ___ can carry food bigger than itself.", pack:"ielts6", level:1},
  {word:"bat", ipa:"/bæt/", pos:"n.", zh:"蝙蝠；球拍", def:"a night animal that flies; a stick for some games", example:"A ___ sleeps during the day.", pack:"ielts6", level:1},
  {word:"bear", ipa:"/ber/", pos:"n.", zh:"熊", def:"a large, strong wild animal with thick fur", example:"The ___ caught a fish in the river.", pack:"ielts6", level:1},
  {word:"bee", ipa:"/biː/", pos:"n.", zh:"蜜蜂", def:"an insect that makes honey", example:"A ___ landed on the flower.", pack:"ielts6", level:1},
  {word:"bird", ipa:"/bɜːrd/", pos:"n.", zh:"鸟", def:"an animal with feathers and wings that can fly", example:"A ___ sang outside my window.", pack:"ielts6", level:1},
  {word:"butterfly", ipa:"/ˈbʌtərflaɪ/", pos:"n.", zh:"蝴蝶", def:"an insect with large, colorful wings", example:"A ___ rested on the flower.", pack:"ielts6", level:1},
  {word:"cat", ipa:"/kæt/", pos:"n.", zh:"猫", def:"a small animal that people keep as a pet", example:"The ___ is sleeping on the sofa.", pack:"ielts6", level:1},
  {word:"chicken", ipa:"/ˈtʃɪkɪn/", pos:"n.", zh:"鸡；鸡肉", def:"a farm bird kept for eggs and meat", example:"We have ___ for dinner.", pack:"ielts6", level:1},
  {word:"cow", ipa:"/kaʊ/", pos:"n.", zh:"奶牛", def:"a large farm animal that gives milk", example:"The ___ eats grass in the field.", pack:"ielts6", level:1},
  {word:"deer", ipa:"/dɪr/", pos:"n.", zh:"鹿", def:"a wild animal with long legs that runs fast", example:"We saw a ___ in the forest.", pack:"ielts6", level:1},
  {word:"dog", ipa:"/dɔːɡ/", pos:"n.", zh:"狗", def:"a pet animal that barks", example:"The ___ ran to greet me.", pack:"ielts6", level:1},
  {word:"duck", ipa:"/dʌk/", pos:"n.", zh:"鸭子", def:"a water bird with a flat mouth", example:"The ___ swam across the pond.", pack:"ielts6", level:1},
  {word:"eagle", ipa:"/ˈiːɡl/", pos:"n.", zh:"鹰", def:"a large bird that hunts other animals", example:"An ___ flew high above the mountain.", pack:"ielts6", level:1},
  {word:"elephant", ipa:"/ˈelɪfənt/", pos:"n.", zh:"大象", def:"a huge grey animal with a long nose", example:"The ___ lifted a log with its trunk.", pack:"ielts6", level:1},
  {word:"fish", ipa:"/fɪʃ/", pos:"n.", zh:"鱼", def:"an animal that lives in water and swims", example:"We cooked fresh ___ for lunch.", pack:"ielts6", level:1},
  {word:"fox", ipa:"/fɑːks/", pos:"n.", zh:"狐狸", def:"a wild animal like a small dog with a thick tail", example:"A ___ ran across the road.", pack:"ielts6", level:1},
  {word:"frog", ipa:"/frɔːɡ/", pos:"n.", zh:"青蛙", def:"a small green animal that jumps and lives near water", example:"A ___ jumped into the pond.", pack:"ielts6", level:1},
  {word:"goat", ipa:"/ɡoʊt/", pos:"n.", zh:"山羊", def:"a farm animal with horns that eats grass", example:"The ___ climbed the rocky hill.", pack:"ielts6", level:1},
  {word:"hen", ipa:"/hen/", pos:"n.", zh:"母鸡", def:"a female chicken that lays eggs", example:"The ___ laid an egg this morning.", pack:"ielts6", level:1},
  {word:"horse", ipa:"/hɔːrs/", pos:"n.", zh:"马", def:"a large animal that people ride", example:"She rides her ___ every weekend.", pack:"ielts6", level:1},
  {word:"lion", ipa:"/ˈlaɪən/", pos:"n.", zh:"狮子", def:"a large wild cat that lives in Africa", example:"The ___ is called the king of animals.", pack:"ielts6", level:1},
  {word:"monkey", ipa:"/ˈmʌŋki/", pos:"n.", zh:"猴子", def:"a smart animal with a long tail that climbs trees", example:"The ___ took a banana from my hand.", pack:"ielts6", level:1},
  {word:"mouse", ipa:"/maʊs/", pos:"n.", zh:"老鼠", def:"a small animal with a long tail", example:"A ___ ran across the kitchen floor.", pack:"ielts6", level:1},
  {word:"owl", ipa:"/aʊl/", pos:"n.", zh:"猫头鹰", def:"a night bird with big eyes", example:"The ___ hooted in the dark.", pack:"ielts6", level:1},
  {word:"pig", ipa:"/pɪɡ/", pos:"n.", zh:"猪", def:"a farm animal that is fat and eats a lot", example:"The ___ rolled in the mud.", pack:"ielts6", level:1},
  {word:"rabbit", ipa:"/ˈræbɪt/", pos:"n.", zh:"兔子", def:"a small animal with long ears that jumps", example:"The ___ ate a carrot.", pack:"ielts6", level:1},
  {word:"rat", ipa:"/ræt/", pos:"n.", zh:"大鼠", def:"a larger kind of mouse", example:"A ___ hid behind the boxes.", pack:"ielts6", level:1},
  {word:"seal", ipa:"/siːl/", pos:"n.", zh:"海豹", def:"a sea animal that lives on beaches too", example:"The ___ rested on the ice.", pack:"ielts6", level:2},
  {word:"sheep", ipa:"/ʃiːp/", pos:"n.", zh:"绵羊", def:"a farm animal that gives wool", example:"The farmer keeps two hundred ___.", pack:"ielts6", level:1},
  {word:"snake", ipa:"/sneɪk/", pos:"n.", zh:"蛇", def:"a long animal with no legs", example:"A ___ moved silently through the grass.", pack:"ielts6", level:1},
  {word:"spider", ipa:"/ˈspaɪdər/", pos:"n.", zh:"蜘蛛", def:"a small animal with eight legs that makes webs", example:"A ___ built a web in the corner.", pack:"ielts6", level:1},
  {word:"squirrel", ipa:"/ˈskwɜːrəl/", pos:"n.", zh:"松鼠", def:"a small animal with a big tail that climbs trees", example:"A ___ hid nuts for the winter.", pack:"ielts6", level:2},
  {word:"tiger", ipa:"/ˈtaɪɡər/", pos:"n.", zh:"老虎", def:"a large wild cat with black stripes", example:"The ___ is an endangered animal.", pack:"ielts6", level:1},
  {word:"turtle", ipa:"/ˈtɜːrtl/", pos:"n.", zh:"乌龟", def:"an animal with a hard shell that walks slowly", example:"A ___ crossed the beach slowly.", pack:"ielts6", level:1},
  {word:"whale", ipa:"/weɪl/", pos:"n.", zh:"鲸", def:"the largest sea animal", example:"We watched a ___ jump out of the water.", pack:"ielts6", level:1},
  {word:"wolf", ipa:"/wʊlf/", pos:"n.", zh:"狼", def:"a wild animal like a large dog", example:"The ___ howled at the moon.", pack:"ielts6", level:1},
  // ---------- 食物与饮品 ----------
  {word:"apple", ipa:"/ˈæpl/", pos:"n.", zh:"苹果", def:"a round red or green fruit", example:"She ate an ___ after lunch.", pack:"ielts6", level:1},
  {word:"banana", ipa:"/bəˈnænə/", pos:"n.", zh:"香蕉", def:"a long yellow fruit", example:"Monkeys love ___.", pack:"ielts6", level:1},
  {word:"bean", ipa:"/biːn/", pos:"n.", zh:"豆子", def:"a small seed eaten as food", example:"Green ___s are good for you.", pack:"ielts6", level:1},
  {word:"beef", ipa:"/biːf/", pos:"n.", zh:"牛肉", def:"the meat of a cow", example:"We had ___ noodles for dinner.", pack:"ielts6", level:1},
  {word:"bread", ipa:"/bred/", pos:"n.", zh:"面包", def:"a food made from flour, baked in an oven", example:"I bought a loaf of ___.", pack:"ielts6", level:1},
  {word:"butter", ipa:"/ˈbʌtər/", pos:"n.", zh:"黄油", def:"a soft yellow food made from milk", example:"She spread ___ on the toast.", pack:"ielts6", level:1},
  {word:"cake", ipa:"/keɪk/", pos:"n.", zh:"蛋糕", def:"a sweet baked food", example:"We ate a chocolate ___ at the party.", pack:"ielts6", level:1},
  {word:"candy", ipa:"/ˈkændi/", pos:"n.", zh:"糖果", def:"a sweet food made of sugar", example:"Children love ___.", pack:"ielts6", level:1},
  {word:"carrot", ipa:"/ˈkærət/", pos:"n.", zh:"胡萝卜", def:"a long orange vegetable", example:"Rabbits eat ___.", pack:"ielts6", level:1},
  {word:"cheese", ipa:"/tʃiːz/", pos:"n.", zh:"奶酪", def:"a solid food made from milk", example:"Pizza has ___ on top.", pack:"ielts6", level:1},
  {word:"coffee", ipa:"/ˈkɔːfi/", pos:"n.", zh:"咖啡", def:"a hot drink made from dark beans", example:"I drink ___ every morning.", pack:"ielts6", level:1},
  {word:"corn", ipa:"/kɔːrn/", pos:"n.", zh:"玉米", def:"a yellow grain grown on tall plants", example:"We ate ___ on the cob.", pack:"ielts6", level:1},
  {word:"cucumber", ipa:"/ˈkjuːkʌmbər/", pos:"n.", zh:"黄瓜", def:"a long green vegetable, cool to eat", example:"Add sliced ___ to the salad.", pack:"ielts6", level:1},
  {word:"egg", ipa:"/eɡ/", pos:"n.", zh:"鸡蛋", def:"a round food that comes from a hen", example:"I had boiled ___s for breakfast.", pack:"ielts6", level:1},
  {word:"grape", ipa:"/ɡreɪp/", pos:"n.", zh:"葡萄", def:"a small round fruit that grows in bunches", example:"These ___s are very sweet.", pack:"ielts6", level:1},
  {word:"honey", ipa:"/ˈhʌni/", pos:"n.", zh:"蜂蜜", def:"a sweet sticky food made by bees", example:"I put ___ in my tea.", pack:"ielts6", level:1},
  {word:"juice", ipa:"/dʒuːs/", pos:"n.", zh:"果汁", def:"the liquid from fruit or vegetables", example:"I drank a glass of orange ___.", pack:"ielts6", level:1},
  {word:"lemon", ipa:"/ˈlemən/", pos:"n.", zh:"柠檬", def:"a yellow fruit with a sour taste", example:"Add a slice of ___ to the water.", pack:"ielts6", level:1},
  {word:"meat", ipa:"/miːt/", pos:"n.", zh:"肉", def:"the flesh of animals used as food", example:"He doesn't eat ___.", pack:"ielts6", level:1},
  {word:"milk", ipa:"/mɪlk/", pos:"n.", zh:"牛奶", def:"the white drink that comes from cows", example:"Children should drink ___.", pack:"ielts6", level:1},
  {word:"noodle", ipa:"/ˈnuːdl/", pos:"n.", zh:"面条", def:"a long thin food made from flour", example:"We had ___ soup for lunch.", pack:"ielts6", level:1},
  {word:"nut", ipa:"/nʌt/", pos:"n.", zh:"坚果", def:"a dry fruit with a hard shell", example:"He is allergic to ___.", pack:"ielts6", level:1},
  {word:"oil", ipa:"/ɔɪl/", pos:"n.", zh:"油", def:"a liquid used for cooking or machines", example:"Fry the eggs in a little ___.", pack:"ielts6", level:1},
  {word:"onion", ipa:"/ˈʌnjən/", pos:"n.", zh:"洋葱", def:"a round vegetable with layers that makes you cry", example:"Chopping an ___ makes my eyes water.", pack:"ielts6", level:1},
  {word:"orange", ipa:"/ˈɔːrɪndʒ/", pos:"n.", zh:"橙子", def:"a round orange fruit", example:"I peeled an ___ for a snack.", pack:"ielts6", level:1},
  {word:"pepper", ipa:"/ˈpepər/", pos:"n.", zh:"胡椒；辣椒", def:"a hot or sharp seasoning; a green/red vegetable", example:"Add salt and ___ to taste.", pack:"ielts6", level:1},
  {word:"pie", ipa:"/paɪ/", pos:"n.", zh:"馅饼", def:"a baked food with fruit or meat inside", example:"My grandma makes the best apple ___.", pack:"ielts6", level:1},
  {word:"potato", ipa:"/pəˈteɪtoʊ/", pos:"n.", zh:"土豆", def:"a round brown vegetable grown under the ground", example:"I like mashed ___.", pack:"ielts6", level:1},
  {word:"rice", ipa:"/raɪs/", pos:"n.", zh:"米饭", def:"small white grains cooked and eaten as food", example:"We eat ___ with most meals.", pack:"ielts6", level:1},
  {word:"salt", ipa:"/sɔːlt/", pos:"n.", zh:"盐", def:"a white powder used to add taste", example:"The soup needs more ___.", pack:"ielts6", level:1},
  {word:"sandwich", ipa:"/ˈsænwɪtʃ/", pos:"n.", zh:"三明治", def:"bread with food between two pieces", example:"I took a ___ to work.", pack:"ielts6", level:1},
  {word:"soup", ipa:"/suːp/", pos:"n.", zh:"汤", def:"hot liquid food made from vegetables or meat", example:"Tomato ___ is my favorite.", pack:"ielts6", level:1},
  {word:"sugar", ipa:"/ˈʃʊɡər/", pos:"n.", zh:"糖", def:"a sweet white powder added to food", example:"Do you take ___ in your tea?", pack:"ielts6", level:1},
  {word:"tea", ipa:"/tiː/", pos:"n.", zh:"茶", def:"a hot drink made from leaves", example:"Let's have a cup of ___.", pack:"ielts6", level:1},
  {word:"tomato", ipa:"/təˈmeɪtoʊ/", pos:"n.", zh:"西红柿", def:"a round red vegetable", example:"___ soup is very tasty.", pack:"ielts6", level:1},
  {word:"vegetable", ipa:"/ˈvedʒtəbl/", pos:"n.", zh:"蔬菜", def:"a plant eaten as food, like a carrot", example:"Eat more fruit and ___.", pack:"ielts6", level:1},
  // ---------- 居家 & 物品 ----------
  {word:"bag", ipa:"/bæɡ/", pos:"n.", zh:"包", def:"a thing used for carrying things", example:"She put the books in her ___.", pack:"ielts6", level:1},
  {word:"basket", ipa:"/ˈbæskɪt/", pos:"n.", zh:"篮子", def:"a container made of thin material for carrying things", example:"The basket is full of fruit.", pack:"ielts6", level:1},
  {word:"bed", ipa:"/bed/", pos:"n.", zh:"床", def:"a piece of furniture you sleep on", example:"It is time to go to ___.", pack:"ielts6", level:1},
  {word:"blanket", ipa:"/ˈblæŋkɪt/", pos:"n.", zh:"毯子", def:"a thick cover to keep you warm", example:"She pulled the ___ over herself.", pack:"ielts6", level:1},
  {word:"bottle", ipa:"/ˈbɑːtl/", pos:"n.", zh:"瓶子", def:"a container for liquid with a narrow top", example:"Please fill the ___ with water.", pack:"ielts6", level:1},
  {word:"bowl", ipa:"/boʊl/", pos:"n.", zh:"碗", def:"a round dish for food like soup", example:"He ate a big ___ of rice.", pack:"ielts6", level:1},
  {word:"box", ipa:"/bɑːks/", pos:"n.", zh:"盒子", def:"a container with straight sides", example:"The shoes came in a white ___.", pack:"ielts6", level:1},
  {word:"brush", ipa:"/brʌʃ/", pos:"n.", zh:"刷子", def:"a tool with hairs used for cleaning or painting", example:"Clean your teeth with a tooth___.", pack:"ielts6", level:1},
  {word:"bucket", ipa:"/ˈbʌkɪt/", pos:"n.", zh:"水桶", def:"a container with a handle for carrying liquids", example:"Fill the ___ with soapy water.", pack:"ielts6", level:1},
  {word:"candle", ipa:"/ˈkændl/", pos:"n.", zh:"蜡烛", def:"wax with a string that gives light when burning", example:"We lit a ___ on the cake.", pack:"ielts6", level:1},
  {word:"chair", ipa:"/tʃer/", pos:"n.", zh:"椅子", def:"a seat for one person", example:"Pull up a ___ and sit down.", pack:"ielts6", level:1},
  {word:"clock", ipa:"/klɑːk/", pos:"n.", zh:"时钟", def:"a thing that shows the time", example:"The ___ on the wall says nine.", pack:"ielts6", level:1},
  {word:"comb", ipa:"/koʊm/", pos:"n.", zh:"梳子", def:"a tool used to make hair neat", example:"She keeps a ___ in her bag.", pack:"ielts6", level:1},
  {word:"cup", ipa:"/kʌp/", pos:"n.", zh:"杯子", def:"a small container to drink from", example:"May I have a ___ of tea?", pack:"ielts6", level:1},
  {word:"door", ipa:"/dɔːr/", pos:"n.", zh:"门", def:"the opening you use to enter a room", example:"Please close the ___ behind you.", pack:"ielts6", level:1},
  {word:"drawer", ipa:"/drɔːr/", pos:"n.", zh:"抽屉", def:"a box that slides in and out of furniture", example:"The keys are in the top ___.", pack:"ielts6", level:1},
  {word:"floor", ipa:"/flɔːr/", pos:"n.", zh:"地板；楼层", def:"the surface you walk on in a room", example:"The cat is lying on the ___.", pack:"ielts6", level:1},
  {word:"fork", ipa:"/fɔːrk/", pos:"n.", zh:"叉子", def:"a tool with points used to eat", example:"Eat the salad with a ___.", pack:"ielts6", level:1},
  {word:"fridge", ipa:"/frɪdʒ/", pos:"n.", zh:"冰箱", def:"a cold box that keeps food fresh", example:"Put the milk in the ___.", pack:"ielts6", level:1},
  {word:"glass", ipa:"/ɡlæs/", pos:"n.", zh:"玻璃杯；玻璃", def:"a cup made of glass; the hard clear material", example:"She drank a ___ of water.", pack:"ielts6", level:1},
  {word:"hammer", ipa:"/ˈhæmər/", pos:"n.", zh:"锤子", def:"a heavy tool for hitting nails", example:"He used a ___ to fix the shelf.", pack:"ielts6", level:1},
  {word:"key", ipa:"/kiː/", pos:"n.", zh:"钥匙", def:"a metal thing that opens a lock", example:"I lost my house ___.", pack:"ielts6", level:1},
  {word:"knife", ipa:"/naɪf/", pos:"n.", zh:"刀", def:"a sharp tool for cutting food", example:"Cut the bread with a ___.", pack:"ielts6", level:1},
  {word:"ladder", ipa:"/ˈlædər/", pos:"n.", zh:"梯子", def:"a thing with steps you climb", example:"He climbed the ___ to the roof.", pack:"ielts6", level:1},
  {word:"lamp", ipa:"/læmp/", pos:"n.", zh:"台灯", def:"a thing that gives light", example:"Read under the ___.", pack:"ielts6", level:1},
  {word:"lock", ipa:"/lɑːk/", pos:"n./v.", zh:"锁", def:"a metal thing that keeps a door closed", example:"Turn the key in the ___.", pack:"ielts6", level:1},
  {word:"mat", ipa:"/mæt/", pos:"n.", zh:"垫子", def:"a piece of material on the floor", example:"Wipe your shoes on the ___.", pack:"ielts6", level:1},
  {word:"mirror", ipa:"/ˈmɪrər/", pos:"n.", zh:"镜子", def:"glass that shows your face", example:"She looked at herself in the ___.", pack:"ielts6", level:1},
  {word:"pan", ipa:"/pæn/", pos:"n.", zh:"平底锅", def:"a metal container for cooking food", example:"Fry the fish in a ___.", pack:"ielts6", level:1},
  {word:"plate", ipa:"/pleɪt/", pos:"n.", zh:"盘子", def:"a flat dish for food", example:"Put the rice on a ___.", pack:"ielts6", level:1},
  {word:"rope", ipa:"/roʊp/", pos:"n.", zh:"绳子", def:"strong thick string", example:"Tie the box with a ___.", pack:"ielts6", level:1},
  {word:"soap", ipa:"/soʊp/", pos:"n.", zh:"肥皂", def:"a thing used with water to clean", example:"Wash your hands with ___.", pack:"ielts6", level:1},
  {word:"sofa", ipa:"/ˈsoʊfə/", pos:"n.", zh:"沙发", def:"a soft long seat for more than one person", example:"We watched TV on the ___.", pack:"ielts6", level:1},
  {word:"spoon", ipa:"/spuːn/", pos:"n.", zh:"勺子", def:"a tool with a bowl shape for eating soup", example:"Eat the soup with a ___.", pack:"ielts6", level:1},
  {word:"table", ipa:"/ˈteɪbl/", pos:"n.", zh:"桌子", def:"a piece of furniture with a flat top", example:"Dinner is on the ___.", pack:"ielts6", level:1},
  {word:"towel", ipa:"/ˈtaʊəl/", pos:"n.", zh:"毛巾", def:"a piece of cloth to dry yourself", example:"Dry your hands with a ___.", pack:"ielts6", level:1},
  {word:"wall", ipa:"/wɔːl/", pos:"n.", zh:"墙", def:"the side of a room or building", example:"There is a picture on the ___.", pack:"ielts6", level:1},
  {word:"window", ipa:"/ˈwɪndoʊ/", pos:"n.", zh:"窗户", def:"a glass opening in a wall", example:"Open the ___ for some air.", pack:"ielts6", level:1},
  {word:"wire", ipa:"/ˈwaɪər/", pos:"n.", zh:"电线", def:"thin metal thread that carries electricity", example:"Don't pull the ___.", pack:"ielts6", level:1},
  // ---------- 衣物 & 穿戴 ----------
  {word:"belt", ipa:"/belt/", pos:"n.", zh:"腰带", def:"a band you wear around your waist", example:"His pants need a ___.", pack:"ielts6", level:1},
  {word:"boot", ipa:"/buːt/", pos:"n.", zh:"靴子", def:"a shoe that covers the ankle", example:"Wear ___s in the snow.", pack:"ielts6", level:1},
  {word:"button", ipa:"/ˈbʌtn/", pos:"n.", zh:"纽扣", def:"a small round thing that closes clothes", example:"A ___ is missing from your shirt.", pack:"ielts6", level:1},
  {word:"cap", ipa:"/kæp/", pos:"n.", zh:"帽子（鸭舌）", def:"a soft hat with a front part", example:"He wore a baseball ___.", pack:"ielts6", level:1},
  {word:"coat", ipa:"/koʊt/", pos:"n.", zh:"外套", def:"a long warm piece of clothing", example:"Take your ___; it's cold outside.", pack:"ielts6", level:1},
  {word:"dress", ipa:"/dres/", pos:"n./v.", zh:"连衣裙；穿衣", def:"a piece of clothing for girls or women; to put on clothes", example:"She wore a red ___.", pack:"ielts6", level:1},
  {word:"glove", ipa:"/ɡlʌv/", pos:"n.", zh:"手套", def:"a cover for your hand", example:"Wear ___s in winter.", pack:"ielts6", level:1},
  {word:"hat", ipa:"/hæt/", pos:"n.", zh:"帽子", def:"a thing you wear on your head", example:"Put on a ___ in the sun.", pack:"ielts6", level:1},
  {word:"jacket", ipa:"/ˈdʒækɪt/", pos:"n.", zh:"夹克", def:"a short coat", example:"He hung his ___ by the door.", pack:"ielts6", level:1},
  {word:"jeans", ipa:"/dʒiːnz/", pos:"n.", zh:"牛仔裤", def:"strong blue pants", example:"She wore old ___ to the park.", pack:"ielts6", level:1},
  {word:"necklace", ipa:"/ˈnekləs/", pos:"n.", zh:"项链", def:"jewellery worn around the neck", example:"She wore a gold ___.", pack:"ielts6", level:2},
  {word:"pocket", ipa:"/ˈpɑːkɪt/", pos:"n.", zh:"口袋", def:"a small bag part of clothes", example:"He keeps his phone in his ___.", pack:"ielts6", level:1},
  {word:"scarf", ipa:"/skɑːrf/", pos:"n.", zh:"围巾", def:"a long cloth worn around the neck", example:"Wrap a ___ around your neck.", pack:"ielts6", level:1},
  {word:"shirt", ipa:"/ʃɜːrt/", pos:"n.", zh:"衬衫", def:"a piece of clothing for the upper body", example:"He wears a white ___ to work.", pack:"ielts6", level:1},
  {word:"shoe", ipa:"/ʃuː/", pos:"n.", zh:"鞋", def:"a thing you wear on your foot", example:"These ___ are too small.", pack:"ielts6", level:1},
  {word:"shorts", ipa:"/ʃɔːrts/", pos:"n.", zh:"短裤", def:"pants that end above the knee", example:"He wore ___ at the beach.", pack:"ielts6", level:1},
  {word:"sock", ipa:"/sɑːk/", pos:"n.", zh:"袜子", def:"a soft thing you wear on your foot", example:"This pair of ___s has a hole.", pack:"ielts6", level:1},
  {word:"suit", ipa:"/suːt/", pos:"n.", zh:"西装", def:"a formal set of jacket and pants", example:"He wore a black ___ to the interview.", pack:"ielts6", level:1},
  {word:"sweater", ipa:"/ˈswetər/", pos:"n.", zh:"毛衣", def:"a warm piece of clothing for the upper body", example:"This ___ is made of wool.", pack:"ielts6", level:1},
  {word:"tie", ipa:"/taɪ/", pos:"n./v.", zh:"领带；系", def:"a long cloth worn under a shirt collar; to fasten", example:"He wore a red ___.", pack:"ielts6", level:1},
  {word:"umbrella", ipa:"/ʌmˈbrelə/", pos:"n.", zh:"雨伞", def:"a thing that protects you from rain", example:"Take an ___; it may rain.", pack:"ielts6", level:1},
  {word:"vest", ipa:"/vest/", pos:"n.", zh:"背心", def:"a piece of clothing without sleeves", example:"He wore a ___ over his shirt.", pack:"ielts6", level:2},
  {word:"wallet", ipa:"/ˈwɑːlɪt/", pos:"n.", zh:"钱包", def:"a small case for money and cards", example:"He keeps his ___ in his pocket.", pack:"ielts6", level:1},
  // ---------- 身体 ----------
  {word:"ankle", ipa:"/ˈæŋkl/", pos:"n.", zh:"脚踝", def:"the joint between your leg and foot", example:"He twisted his ___ while running.", pack:"ielts6", level:1},
  {word:"arm", ipa:"/ɑːrm/", pos:"n.", zh:"手臂", def:"the part of your body from shoulder to hand", example:"She broke her ___ last year.", pack:"ielts6", level:1},
  {word:"back", ipa:"/bæk/", pos:"n.", zh:"背", def:"the part of the body behind you", example:"My ___ hurts from sitting too long.", pack:"ielts6", level:1},
  {word:"beard", ipa:"/bɪrd/", pos:"n.", zh:"胡子", def:"hair that grows on a man's face", example:"He grew a ___ in winter.", pack:"ielts6", level:1},
  {word:"blood", ipa:"/blʌd/", pos:"n.", zh:"血液", def:"the red liquid inside your body", example:"The doctor took a ___ test.", pack:"ielts6", level:1},
  {word:"bone", ipa:"/boʊn/", pos:"n.", zh:"骨头", def:"the hard part inside your body", example:"The dog buried a ___.", pack:"ielts6", level:1},
  {word:"chest", ipa:"/tʃest/", pos:"n.", zh:"胸口", def:"the front part of your body between neck and stomach", example:"He felt a pain in his ___.", pack:"ielts6", level:1},
  {word:"chin", ipa:"/tʃɪn/", pos:"n.", zh:"下巴", def:"the bottom part of your face", example:"She rested her hand on her ___.", pack:"ielts6", level:1},
  {word:"ear", ipa:"/ɪr/", pos:"n.", zh:"耳朵", def:"the part you hear with", example:"Keep your ___ close to the phone.", pack:"ielts6", level:1},
  {word:"elbow", ipa:"/ˈelboʊ/", pos:"n.", zh:"肘", def:"the joint in the middle of your arm", example:"He hurt his ___ in the fall.", pack:"ielts6", level:1},
  {word:"eye", ipa:"/aɪ/", pos:"n.", zh:"眼睛", def:"the part you see with", example:"Close your ___ and rest.", pack:"ielts6", level:1},
  {word:"face", ipa:"/feɪs/", pos:"n.", zh:"脸", def:"the front part of your head", example:"She washed her ___ with cold water.", pack:"ielts6", level:1},
  {word:"finger", ipa:"/ˈfɪŋɡər/", pos:"n.", zh:"手指", def:"one of the five parts at the end of your hand", example:"He pointed with his ___.", pack:"ielts6", level:1},
  {word:"foot", ipa:"/fʊt/", pos:"n.", zh:"脚", def:"the part at the end of your leg", example:"My left ___ is wet.", pack:"ielts6", level:1},
  {word:"hair", ipa:"/her/", pos:"n.", zh:"头发", def:"the thin things that grow on your head", example:"She has long black ___.", pack:"ielts6", level:1},
  {word:"hand", ipa:"/hænd/", pos:"n.", zh:"手", def:"the part at the end of your arm with fingers", example:"Raise your ___ if you know.", pack:"ielts6", level:1},
  {word:"head", ipa:"/hed/", pos:"n.", zh:"头", def:"the top part of your body", example:"Wear a hat to protect your ___.", pack:"ielts6", level:1},
  {word:"heart", ipa:"/hɑːrt/", pos:"n.", zh:"心脏", def:"the organ that pumps blood", example:"Running is good for your ___.", pack:"ielts6", level:1},
  {word:"knee", ipa:"/niː/", pos:"n.", zh:"膝盖", def:"the joint in the middle of your leg", example:"He went down on one ___.", pack:"ielts6", level:1},
  {word:"leg", ipa:"/leɡ/", pos:"n.", zh:"腿", def:"the part of your body you stand on", example:"The dog wagged its back ___.", pack:"ielts6", level:1},
  {word:"lip", ipa:"/lɪp/", pos:"n.", zh:"嘴唇", def:"the soft part around your mouth", example:"Her ___s were dry.", pack:"ielts6", level:1},
  {word:"lung", ipa:"/lʌŋ/", pos:"n.", zh:"肺", def:"the organ you breathe with", example:"Smoking harms your ___.", pack:"ielts6", level:1},
  {word:"mouth", ipa:"/maʊθ/", pos:"n.", zh:"嘴", def:"the part you eat and speak with", example:"Open your ___ and say ah.", pack:"ielts6", level:1},
  {word:"neck", ipa:"/nek/", pos:"n.", zh:"脖子", def:"the part between your head and body", example:"She wore a scarf around her ___.", pack:"ielts6", level:1},
  {word:"nose", ipa:"/noʊz/", pos:"n.", zh:"鼻子", def:"the part you smell with", example:"He has a cold and a runny ___.", pack:"ielts6", level:1},
  {word:"shoulder", ipa:"/ˈʃoʊldər/", pos:"n.", zh:"肩膀", def:"the part where your arm meets your body", example:"He carried the bag on his ___.", pack:"ielts6", level:1},
  {word:"skin", ipa:"/skɪn/", pos:"n.", zh:"皮肤", def:"the outer cover of your body", example:"Use cream to protect your ___.", pack:"ielts6", level:1},
  {word:"stomach", ipa:"/ˈstʌmək/", pos:"n.", zh:"胃", def:"the organ that digests food", example:"My ___ hurts after that meal.", pack:"ielts6", level:1},
  {word:"tooth", ipa:"/tuːθ/", pos:"n.", zh:"牙齿", def:"the white parts in your mouth for biting", example:"Brush your teeth twice a day.", pack:"ielts6", level:1},
  {word:"tongue", ipa:"/tʌŋ/", pos:"n.", zh:"舌头", def:"the soft part in your mouth you taste with", example:"The hot soup burned my ___.", pack:"ielts6", level:1},
  // ---------- 学校与文具 ----------
  {word:"blackboard", ipa:"/ˈblækbɔːrd/", pos:"n.", zh:"黑板", def:"a dark board written on with chalk", example:"The teacher wrote on the ___.", pack:"ielts6", level:1},
  {word:"chalk", ipa:"/tʃɔːk/", pos:"n.", zh:"粉笔", def:"a white stick used to write on a board", example:"The teacher used yellow ___.", pack:"ielts6", level:1},
  {word:"classroom", ipa:"/ˈklæsruːm/", pos:"n.", zh:"教室", def:"a room where lessons happen", example:"The ___ has twenty desks.", pack:"ielts6", level:1},
  {word:"dictionary", ipa:"/ˈdɪkʃəneri/", pos:"n.", zh:"词典", def:"a book that explains words", example:"Look the word up in a ___.", pack:"ielts6", level:1},
  {word:"eraser", ipa:"/ɪˈreɪsər/", pos:"n.", zh:"橡皮", def:"a thing that removes pencil marks", example:"Use an ___ to fix the mistake.", pack:"ielts6", level:1},
  {word:"notebook", ipa:"/ˈnoʊtbʊk/", pos:"n.", zh:"笔记本", def:"a book for writing notes", example:"Write the date in your ___.", pack:"ielts6", level:1},
  {word:"pen", ipa:"/pen/", pos:"n.", zh:"钢笔", def:"a tool that writes with ink", example:"Sign your name with this ___.", pack:"ielts6", level:1},
  {word:"pencil", ipa:"/ˈpensl/", pos:"n.", zh:"铅笔", def:"a tool that writes with lead", example:"Do the test in ___ or pen?", pack:"ielts6", level:1},
  {word:"ruler", ipa:"/ˈruːlər/", pos:"n.", zh:"尺子", def:"a straight tool for measuring", example:"Use a ___ to draw a straight line.", pack:"ielts6", level:1},
  {word:"school", ipa:"/skuːl/", pos:"n.", zh:"学校", def:"a place where children learn", example:"The kids go to ___ by bus.", pack:"ielts6", level:1},
  {word:"student", ipa:"/ˈstuːdnt/", pos:"n.", zh:"学生", def:"a person who studies at a school", example:"Every ___ has a book.", pack:"ielts6", level:1},
  {word:"teacher", ipa:"/ˈtiːtʃər/", pos:"n.", zh:"老师", def:"a person who teaches", example:"The ___ explained the lesson.", pack:"ielts6", level:1},
  {word:"textbook", ipa:"/ˈtekstbʊk/", pos:"n.", zh:"教科书", def:"a book used for study", example:"Open your ___ to page ten.", pack:"ielts6", level:1},
  {word:"class", ipa:"/klæs/", pos:"n.", zh:"班级；课", def:"a group of students; a lesson", example:"We have English ___ at nine.", pack:"ielts6", level:1},
  // ---------- 自然与天气 ----------
  {word:"air", ipa:"/er/", pos:"n.", zh:"空气", def:"the gas we breathe", example:"The mountain ___ is fresh.", pack:"ielts6", level:1},
  {word:"cloud", ipa:"/klaʊd/", pos:"n.", zh:"云", def:"a white shape in the sky", example:"Dark ___s mean rain.", pack:"ielts6", level:1},
  {word:"desert", ipa:"/ˈdezərt/", pos:"n.", zh:"沙漠", def:"a very dry place with little rain", example:"Camels live in the ___.", pack:"ielts6", level:1},
  {word:"dirt", ipa:"/dɜːrt/", pos:"n.", zh:"泥土；污垢", def:"loose earth; something that makes things dirty", example:"His shoes are covered in ___.", pack:"ielts6", level:1},
  {word:"dust", ipa:"/dʌst/", pos:"n.", zh:"灰尘", def:"very small dry pieces of dirt", example:"A layer of ___ covered the shelf.", pack:"ielts6", level:1},
  {word:"earth", ipa:"/ɜːrθ/", pos:"n.", zh:"地球；土壤", def:"the planet we live on; soil", example:"Plants grow in ___.", pack:"ielts6", level:1},
  {word:"fog", ipa:"/fɔːɡ/", pos:"n.", zh:"雾", def:"thick cloud near the ground", example:"Driving in ___ is dangerous.", pack:"ielts6", level:1},
  {word:"forest", ipa:"/ˈfɔːrɪst/", pos:"n.", zh:"森林", def:"a large area of trees", example:"We walked through the ___.", pack:"ielts6", level:1},
  {word:"ground", ipa:"/ɡraʊnd/", pos:"n.", zh:"地面", def:"the surface of the earth", example:"The ball fell to the ___.", pack:"ielts6", level:1},
  {word:"hill", ipa:"/hɪl/", pos:"n.", zh:"小山", def:"a small mountain", example:"They ran up the ___.", pack:"ielts6", level:1},
  {word:"ice", ipa:"/aɪs/", pos:"n.", zh:"冰", def:"frozen water", example:"Add some ___ to the drink.", pack:"ielts6", level:1},
  {word:"island", ipa:"/ˈaɪlənd/", pos:"n.", zh:"岛屿", def:"land with water around it", example:"They swam to the small ___.", pack:"ielts6", level:1},
  {word:"lake", ipa:"/leɪk/", pos:"n.", zh:"湖", def:"a large area of water with land around it", example:"We went fishing on the ___.", pack:"ielts6", level:1},
  {word:"leaf", ipa:"/liːf/", pos:"n.", zh:"树叶", def:"the green part of a plant", example:"A yellow ___ fell from the tree.", pack:"ielts6", level:1},
  {word:"lightning", ipa:"/ˈlaɪtnɪŋ/", pos:"n.", zh:"闪电", def:"a bright flash in the sky during a storm", example:"___ hit the tall tower.", pack:"ielts6", level:1},
  {word:"moon", ipa:"/muːn/", pos:"n.", zh:"月亮", def:"the round object that shines at night", example:"The ___ is full tonight.", pack:"ielts6", level:1},
  {word:"mountain", ipa:"/ˈmaʊntn/", pos:"n.", zh:"山", def:"a very high hill", example:"They climbed the high ___.", pack:"ielts6", level:1},
  {word:"rain", ipa:"/reɪn/", pos:"n.", zh:"雨", def:"water that falls from clouds", example:"The ___ lasted all night.", pack:"ielts6", level:1},
  {word:"rainbow", ipa:"/ˈreɪnboʊ/", pos:"n.", zh:"彩虹", def:"a colored arc in the sky after rain", example:"A ___ appeared after the storm.", pack:"ielts6", level:1},
  {word:"river", ipa:"/ˈrɪvər/", pos:"n.", zh:"河流", def:"a large stream of water to the sea", example:"The ___ runs through the city.", pack:"ielts6", level:1},
  {word:"rock", ipa:"/rɑːk/", pos:"n.", zh:"岩石", def:"a hard piece of stone", example:"He threw a ___ into the lake.", pack:"ielts6", level:1},
  {word:"sand", ipa:"/sænd/", pos:"n.", zh:"沙子", def:"the fine grains found on beaches", example:"The children played in the ___.", pack:"ielts6", level:1},
  {word:"sea", ipa:"/siː/", pos:"n.", zh:"海", def:"the large body of salt water", example:"We swam in the ___.", pack:"ielts6", level:1},
  {word:"sky", ipa:"/skaɪ/", pos:"n.", zh:"天空", def:"the space above the earth", example:"The ___ turned pink at sunset.", pack:"ielts6", level:1},
  {word:"snow", ipa:"/snoʊ/", pos:"n.", zh:"雪", def:"soft white ice that falls from clouds", example:"The children made a ___man.", pack:"ielts6", level:1},
  {word:"star", ipa:"/stɑːr/", pos:"n.", zh:"星星", def:"a bright point of light in the night sky", example:"We counted the ___s.", pack:"ielts6", level:1},
  {word:"stone", ipa:"/stoʊn/", pos:"n.", zh:"石头", def:"a small piece of rock", example:"She skipped a ___ across the water.", pack:"ielts6", level:1},
  {word:"sun", ipa:"/sʌn/", pos:"n.", zh:"太阳", def:"the hot bright star that gives us light", example:"The ___ rises in the east.", pack:"ielts6", level:1},
  {word:"thunder", ipa:"/ˈθʌndər/", pos:"n.", zh:"雷", def:"the loud sound after lightning", example:"We heard ___ in the distance.", pack:"ielts6", level:1},
  {word:"tree", ipa:"/triː/", pos:"n.", zh:"树", def:"a tall plant with a trunk", example:"Birds nest in the ___.", pack:"ielts6", level:1},
  {word:"valley", ipa:"/ˈvæli/", pos:"n.", zh:"山谷", def:"low land between hills or mountains", example:"A river runs through the ___.", pack:"ielts6", level:1},
  {word:"wind", ipa:"/wɪnd/", pos:"n.", zh:"风", def:"moving air", example:"The ___ blew the leaves away.", pack:"ielts6", level:1},
  // ---------- 城镇与交通 ----------
  {word:"airport", ipa:"/ˈerpɔːrt/", pos:"n.", zh:"机场", def:"a place where planes take off and land", example:"We arrived at the ___ early.", pack:"ielts6", level:1},
  {word:"bridge", ipa:"/brɪdʒ/", pos:"n.", zh:"桥", def:"a structure that crosses a river or road", example:"The ___ crosses the wide river.", pack:"ielts6", level:1},
  {word:"bus", ipa:"/bʌs/", pos:"n.", zh:"公交车", def:"a large vehicle that carries many people", example:"I take the ___ to school.", pack:"ielts6", level:1},
  {word:"car", ipa:"/kɑːr/", pos:"n.", zh:"汽车", def:"a road vehicle with four wheels", example:"He drives his ___ to work.", pack:"ielts6", level:1},
  {word:"church", ipa:"/tʃɜːrtʃ/", pos:"n.", zh:"教堂", def:"a building where people worship", example:"The ___ has a tall tower.", pack:"ielts6", level:1},
  {word:"cinema", ipa:"/ˈsɪnəmə/", pos:"n.", zh:"电影院", def:"a place where films are shown", example:"Let's go to the ___ tonight.", pack:"ielts6", level:1},
  {word:"city", ipa:"/ˈsɪti/", pos:"n.", zh:"城市", def:"a large town", example:"The ___ never sleeps.", pack:"ielts6", level:1},
  {word:"corner", ipa:"/ˈkɔːrnər/", pos:"n.", zh:"拐角", def:"the place where two roads or walls meet", example:"The shop is on the ___.", pack:"ielts6", level:1},
  {word:"country", ipa:"/ˈkʌntri/", pos:"n.", zh:"国家；乡村", def:"a nation; land away from cities", example:"China is a large ___.", pack:"ielts6", level:1},
  {word:"farm", ipa:"/fɑːrm/", pos:"n.", zh:"农场", def:"land used for growing crops and animals", example:"My uncle works on a ___.", pack:"ielts6", level:1},
  {word:"fire", ipa:"/ˈfaɪər/", pos:"n.", zh:"火", def:"the hot bright flames of burning", example:"Keep away from the ___.", pack:"ielts6", level:1},
  {word:"hospital", ipa:"/ˈhɑːspɪtl/", pos:"n.", zh:"医院", def:"a place where sick people are treated", example:"She works as a nurse in the ___.", pack:"ielts6", level:1},
  {word:"hotel", ipa:"/hoʊˈtel/", pos:"n.", zh:"酒店", def:"a place that rents rooms to travelers", example:"We stayed at a beach ___.", pack:"ielts6", level:1},
  {word:"park", ipa:"/pɑːrk/", pos:"n.", zh:"公园", def:"a public green place to relax", example:"The children played in the ___.", pack:"ielts6", level:1},
  {word:"police", ipa:"/pəˈliːs/", pos:"n.", zh:"警察", def:"the people who keep order and stop crime", example:"Call the ___ in an emergency.", pack:"ielts6", level:1},
  {word:"post", ipa:"/poʊst/", pos:"n.", zh:"邮政；邮件", def:"the system that sends letters; letters sent", example:"Did the ___ arrive today?", pack:"ielts6", level:1},
  {word:"restaurant", ipa:"/ˈrestərɑːnt/", pos:"n.", zh:"餐厅", def:"a place where you buy and eat meals", example:"This ___ serves great noodles.", pack:"ielts6", level:1},
  {word:"road", ipa:"/roʊd/", pos:"n.", zh:"道路", def:"a hard surface for cars to drive on", example:"The ___ is wet after the rain.", pack:"ielts6", level:1},
  {word:"shop", ipa:"/ʃɑːp/", pos:"n.", zh:"商店", def:"a place where things are sold", example:"The corner ___ sells milk.", pack:"ielts6", level:1},
  {word:"station", ipa:"/ˈsteɪʃn/", pos:"n.", zh:"车站", def:"a place where trains or buses stop", example:"Meet me at the train ___.", pack:"ielts6", level:1},
  {word:"street", ipa:"/striːt/", pos:"n.", zh:"街道", def:"a road in a city with buildings", example:"The ___ is busy at noon.", pack:"ielts6", level:1},
  {word:"supermarket", ipa:"/ˈsuːpərmɑːrkɪt/", pos:"n.", zh:"超市", def:"a large self-service shop for food", example:"I shop at the ___ once a week.", pack:"ielts6", level:1},
  {word:"taxi", ipa:"/ˈtæksi/", pos:"n.", zh:"出租车", def:"a car you pay to ride in", example:"We took a ___ to the airport.", pack:"ielts6", level:1},
  {word:"town", ipa:"/taʊn/", pos:"n.", zh:"城镇", def:"a place smaller than a city", example:"The ___ has one main street.", pack:"ielts6", level:1},
  {word:"train", ipa:"/treɪn/", pos:"n.", zh:"火车", def:"a line of connected cars on rails", example:"The ___ leaves at nine.", pack:"ielts6", level:1},
  {word:"village", ipa:"/ˈvɪlɪdʒ/", pos:"n.", zh:"村庄", def:"a small group of houses in the country", example:"She grew up in a quiet ___.", pack:"ielts6", level:1},
  {word:"zoo", ipa:"/zuː/", pos:"n.", zh:"动物园", def:"a place where animals are kept for viewing", example:"The kids love visiting the ___.", pack:"ielts6", level:1},
  // ---------- 生活动词（家务/动作） ----------
  {word:"catch", ipa:"/kætʃ/", pos:"v.", zh:"抓住", def:"to get hold of something moving", example:"Try to ___ the ball.", pack:"ielts6", level:1},
  {word:"climb", ipa:"/klaɪm/", pos:"v.", zh:"攀爬", def:"to go up something using your hands and feet", example:"The child ___ed the tree.", pack:"ielts6", level:1},
  {word:"cry", ipa:"/kraɪ/", pos:"v.", zh:"哭", def:"to have tears coming from your eyes", example:"The baby ___s when hungry.", pack:"ielts6", level:1},
  {word:"dance", ipa:"/dæns/", pos:"v.", zh:"跳舞", def:"to move your body to music", example:"They ___d at the party.", pack:"ielts6", level:1},
  {word:"drink", ipa:"/drɪŋk/", pos:"v.", zh:"喝", def:"to take liquid into your mouth", example:"___ more water in summer.", pack:"ielts6", level:1},
  {word:"drop", ipa:"/drɑːp/", pos:"v.", zh:"掉落", def:"to let something fall", example:"Don't ___ the glass.", pack:"ielts6", level:1},
  {word:"eat", ipa:"/iːt/", pos:"v.", zh:"吃", def:"to take food into your mouth", example:"We ___ dinner at seven.", pack:"ielts6", level:1},
  {word:"fly", ipa:"/flaɪ/", pos:"v.", zh:"飞", def:"to move through the air", example:"Birds ___ south in autumn.", pack:"ielts6", level:1},
  {word:"hear", ipa:"/hɪr/", pos:"v.", zh:"听见", def:"to notice sound with your ears", example:"Did you ___ that noise?", pack:"ielts6", level:1},
  {word:"jump", ipa:"/dʒʌmp/", pos:"v.", zh:"跳", def:"to push yourself into the air", example:"The frog ___ed into the water.", pack:"ielts6", level:1},
  {word:"laugh", ipa:"/læf/", pos:"v.", zh:"笑", def:"to make sounds when something is funny", example:"The joke made everyone ___.", pack:"ielts6", level:1},
  {word:"listen", ipa:"/ˈlɪsn/", pos:"v.", zh:"听", def:"to pay attention to a sound", example:"___ to the teacher carefully.", pack:"ielts6", level:1},
  {word:"run", ipa:"/rʌn/", pos:"v.", zh:"跑", def:"to move fast on your legs", example:"I ___ to catch the bus.", pack:"ielts6", level:1},
  {word:"sing", ipa:"/sɪŋ/", pos:"v.", zh:"唱歌", def:"to make music with your voice", example:"She loves to ___ in the shower.", pack:"ielts6", level:1},
  {word:"smell", ipa:"/smel/", pos:"v.", zh:"闻", def:"to notice with your nose", example:"I can ___ fresh bread.", pack:"ielts6", level:1},
  {word:"smile", ipa:"/smaɪl/", pos:"v.", zh:"微笑", def:"to make a happy look with your mouth", example:"She ___d at the camera.", pack:"ielts6", level:1},
  {word:"sweep", ipa:"/swiːp/", pos:"v.", zh:"扫地", def:"to clean the floor with a brush", example:"She ___s the floor daily.", pack:"ielts6", level:1},
  {word:"swim", ipa:"/swɪm/", pos:"v.", zh:"游泳", def:"to move through water", example:"We ___ in the sea.", pack:"ielts6", level:1},
  {word:"taste", ipa:"/teɪst/", pos:"v.", zh:"品尝", def:"to check food with your mouth", example:"___ the soup to check the salt.", pack:"ielts6", level:1},
  {word:"throw", ipa:"/θroʊ/", pos:"v.", zh:"扔", def:"to send something through the air with your hand", example:"___ the ball to me.", pack:"ielts6", level:1},
  {word:"walk", ipa:"/wɔːk/", pos:"v.", zh:"走路", def:"to move on your legs at a normal speed", example:"We ___ to the park.", pack:"ielts6", level:1},
  {word:"wash", ipa:"/wɑːʃ/", pos:"v.", zh:"洗", def:"to clean with water and soap", example:"___ your hands before eating.", pack:"ielts6", level:1},
  {word:"watch", ipa:"/wɑːtʃ/", pos:"v.", zh:"观看", def:"to look at something for a time", example:"We ___ed a movie last night.", pack:"ielts6", level:1},
  {word:"break", ipa:"/breɪk/", pos:"v.", zh:"打破", def:"to make something into pieces", example:"Be careful not to ___ the vase.", pack:"ielts6", level:1},
  {word:"cut", ipa:"/kʌt/", pos:"v.", zh:"切", def:"to divide with a knife", example:"___ the cake into eight pieces.", pack:"ielts6", level:1},
  // ---------- 颜色 & 形状 ----------
  {word:"black", ipa:"/blæk/", pos:"adj.", zh:"黑色的", def:"the darkest color, like night", example:"She wore a ___ dress.", pack:"ielts6", level:1},
  {word:"blue", ipa:"/bluː/", pos:"adj.", zh:"蓝色的", def:"the color of a clear sky", example:"The ___ sea is calm.", pack:"ielts6", level:1},
  {word:"brown", ipa:"/braʊn/", pos:"adj.", zh:"棕色的", def:"the color of coffee or wood", example:"He has ___ eyes.", pack:"ielts6", level:1},
  {word:"circle", ipa:"/ˈsɜːrkl/", pos:"n.", zh:"圆形", def:"a round shape", example:"Draw a ___ on the paper.", pack:"ielts6", level:1},
  {word:"color", ipa:"/ˈkʌlər/", pos:"n.", zh:"颜色", def:"how something looks, like red or blue", example:"What ___ is your car?", pack:"ielts6", level:1},
  {word:"green", ipa:"/ɡriːn/", pos:"adj.", zh:"绿色的", def:"the color of grass", example:"The ___ leaves moved in the wind.", pack:"ielts6", level:1},
  {word:"grey", ipa:"/ɡreɪ/", pos:"adj.", zh:"灰色的", def:"the color between black and white", example:"The sky was ___ all day.", pack:"ielts6", level:1},
  {word:"line", ipa:"/laɪn/", pos:"n.", zh:"线条；排队", def:"a long thin mark; people standing in order", example:"Draw a straight ___.", pack:"ielts6", level:1},
  {word:"pink", ipa:"/pɪŋk/", pos:"adj.", zh:"粉红色的", def:"a light red color", example:"The flowers are ___.", pack:"ielts6", level:1},
  {word:"purple", ipa:"/ˈpɜːrpl/", pos:"adj.", zh:"紫色的", def:"the color made by mixing red and blue", example:"She painted the wall ___.", pack:"ielts6", level:1},
  {word:"red", ipa:"/red/", pos:"adj.", zh:"红色的", def:"the color of blood", example:"The ___ apple is sweet.", pack:"ielts6", level:1},
  {word:"shape", ipa:"/ʃeɪp/", pos:"n.", zh:"形状", def:"the form of something, like a circle", example:"What ___ is the table?", pack:"ielts6", level:1},
  {word:"square", ipa:"/skwer/", pos:"n./adj.", zh:"正方形（的）", def:"a shape with four equal sides", example:"Fold the paper into a ___.", pack:"ielts6", level:1},
  {word:"triangle", ipa:"/ˈtraɪæŋɡl/", pos:"n.", zh:"三角形", def:"a shape with three sides", example:"The sign is a red ___.", pack:"ielts6", level:1},
  {word:"white", ipa:"/waɪt/", pos:"adj.", zh:"白色的", def:"the lightest color, like snow", example:"She wore a ___ coat.", pack:"ielts6", level:1},
  {word:"yellow", ipa:"/ˈjeloʊ/", pos:"adj.", zh:"黄色的", def:"the color of the sun", example:"The ___ bus is coming.", pack:"ielts6", level:1},
  // ---------- 时间 & 数量 ----------
  {word:"afternoon", ipa:"/ˌæftərˈnuːn/", pos:"n.", zh:"下午", def:"the time between noon and evening", example:"We met in the ___.", pack:"ielts6", level:1},
  {word:"autumn", ipa:"/ˈɔːtəm/", pos:"n.", zh:"秋天", def:"the season before winter", example:"Leaves fall in ___.", pack:"ielts6", level:1},
  {word:"evening", ipa:"/ˈiːvnɪŋ/", pos:"n.", zh:"傍晚", def:"the time between afternoon and night", example:"We watch TV in the ___.", pack:"ielts6", level:1},
  {word:"hour", ipa:"/ˈaʊər/", pos:"n.", zh:"小时", def:"a period of sixty minutes", example:"The film lasts two ___.", pack:"ielts6", level:1},
  {word:"minute", ipa:"/ˈmɪnɪt/", pos:"n.", zh:"分钟", def:"a period of sixty seconds", example:"The train leaves in ten ___.", pack:"ielts6", level:1},
  {word:"month", ipa:"/mʌnθ/", pos:"n.", zh:"月份", def:"one of the twelve parts of a year", example:"My birthday is next ___.", pack:"ielts6", level:1},
  {word:"morning", ipa:"/ˈmɔːrnɪŋ/", pos:"n.", zh:"早晨", def:"the early part of the day", example:"I run every ___.", pack:"ielts6", level:1},
  {word:"night", ipa:"/naɪt/", pos:"n.", zh:"夜晚", def:"the dark time when people sleep", example:"The stars shine at ___.", pack:"ielts6", level:1},
  {word:"season", ipa:"/ˈsiːzn/", pos:"n.", zh:"季节", def:"one of the four parts of the year", example:"My favorite ___ is spring.", pack:"ielts6", level:1},
  {word:"second", ipa:"/ˈsekənd/", pos:"n.", zh:"秒", def:"a very short unit of time", example:"Wait one ___.", pack:"ielts6", level:1},
  {word:"spring", ipa:"/sprɪŋ/", pos:"n.", zh:"春天", def:"the season after winter", example:"Flowers bloom in ___.", pack:"ielts6", level:1},
  {word:"summer", ipa:"/ˈsʌmər/", pos:"n.", zh:"夏天", def:"the hottest season", example:"We swim a lot in ___.", pack:"ielts6", level:1},
  {word:"time", ipa:"/taɪm/", pos:"n.", zh:"时间", def:"what clocks measure", example:"What ___ is it now?", pack:"ielts6", level:1},
  {word:"week", ipa:"/wiːk/", pos:"n.", zh:"周", def:"a period of seven days", example:"See you next ___.", pack:"ielts6", level:1},
  {word:"weekend", ipa:"/ˈwiːkend/", pos:"n.", zh:"周末", def:"Saturday and Sunday", example:"We go hiking on the ___.", pack:"ielts6", level:1},
  {word:"winter", ipa:"/ˈwɪntər/", pos:"n.", zh:"冬天", def:"the coldest season", example:"It snows in ___.", pack:"ielts6", level:1},
  {word:"year", ipa:"/jɪr/", pos:"n.", zh:"年", def:"a period of twelve months", example:"We moved here last ___.", pack:"ielts6", level:1},
  {word:"dozen", ipa:"/ˈdʌzn/", pos:"n.", zh:"一打（十二个）", def:"a group of twelve", example:"She bought a ___ of eggs.", pack:"ielts6", level:2},
  {word:"couple", ipa:"/ˈkʌpl/", pos:"n.", zh:"一对；几个", def:"two people together; a few", example:"I'll be back in a ___ of minutes.", pack:"ielts6", level:1},
  {word:"several", ipa:"/ˈsevrəl/", pos:"adj.", zh:"几个", def:"more than two but not many", example:"He tried ___ times.", pack:"ielts6", level:1},
  {word:"plenty", ipa:"/ˈplenti/", pos:"n.", zh:"大量", def:"a large amount that is enough", example:"There is ___ of food.", pack:"ielts6", level:1},
  // ---------- 家庭与人 ----------
  {word:"aunt", ipa:"/ænt/", pos:"n.", zh:"阿姨；姑妈", def:"the sister of your mother or father", example:"My ___ lives in Shanghai.", pack:"ielts6", level:1},
  {word:"baby", ipa:"/ˈbeɪbi/", pos:"n.", zh:"婴儿", def:"a very young child", example:"The ___ is crying.", pack:"ielts6", level:1},
  {word:"boy", ipa:"/bɔɪ/", pos:"n.", zh:"男孩", def:"a male child", example:"The ___ is playing football.", pack:"ielts6", level:1},
  {word:"brother", ipa:"/ˈbrʌðər/", pos:"n.", zh:"兄弟", def:"a male sibling", example:"My older ___ is tall.", pack:"ielts6", level:1},
  {word:"cousin", ipa:"/ˈkʌzn/", pos:"n.", zh:"表兄弟姐妹", def:"the child of your aunt or uncle", example:"My ___ visits every summer.", pack:"ielts6", level:1},
  {word:"daughter", ipa:"/ˈdɔːtər/", pos:"n.", zh:"女儿", def:"a female child", example:"Their ___ is five.", pack:"ielts6", level:1},
  {word:"father", ipa:"/ˈfɑːðər/", pos:"n.", zh:"父亲", def:"a male parent", example:"My ___ teaches history.", pack:"ielts6", level:1},
  {word:"girl", ipa:"/ɡɜːrl/", pos:"n.", zh:"女孩", def:"a female child", example:"The ___ reads under the tree.", pack:"ielts6", level:1},
  {word:"grandfather", ipa:"/ˈɡrænfɑːðər/", pos:"n.", zh:"祖父", def:"the father of your parent", example:"My ___ tells good stories.", pack:"ielts6", level:1},
  {word:"grandmother", ipa:"/ˈɡrænmʌðər/", pos:"n.", zh:"祖母", def:"the mother of your parent", example:"My ___ bakes great bread.", pack:"ielts6", level:1},
  {word:"husband", ipa:"/ˈhʌzbənd/", pos:"n.", zh:"丈夫", def:"a married man", example:"Her ___ cooks well.", pack:"ielts6", level:1},
  {word:"mother", ipa:"/ˈmʌðər/", pos:"n.", zh:"母亲", def:"a female parent", example:"My ___ is a nurse.", pack:"ielts6", level:1},
  {word:"parent", ipa:"/ˈperənt/", pos:"n.", zh:"父亲或母亲", def:"a mother or father", example:"Her ___s are teachers.", pack:"ielts6", level:1},
  {word:"person", ipa:"/ˈpɜːrsn/", pos:"n.", zh:"人", def:"a human being", example:"She is a kind ___.", pack:"ielts6", level:1},
  {word:"sister", ipa:"/ˈsɪstər/", pos:"n.", zh:"姐妹", def:"a female sibling", example:"My little ___ loves dolls.", pack:"ielts6", level:1},
  {word:"son", ipa:"/sʌn/", pos:"n.", zh:"儿子", def:"a male child of parents", example:"Their ___ goes to college.", pack:"ielts6", level:1},
  {word:"uncle", ipa:"/ˈʌŋkl/", pos:"n.", zh:"叔叔；舅舅", def:"the brother of your mother or father", example:"My ___ drives a taxi.", pack:"ielts6", level:1},
  {word:"wife", ipa:"/waɪf/", pos:"n.", zh:"妻子", def:"a married woman", example:"His ___ works in a bank.", pack:"ielts6", level:1},
  {word:"woman", ipa:"/ˈwʊmən/", pos:"n.", zh:"女人", def:"an adult female", example:"The ___ smiled at me.", pack:"ielts6", level:1},
  {word:"man", ipa:"/mæn/", pos:"n.", zh:"男人", def:"an adult male", example:"The ___ fixed my bike.", pack:"ielts6", level:1},
  // ---------- 职业与身份 ----------
  {word:"actor", ipa:"/ˈæktər/", pos:"n.", zh:"演员", def:"a person who acts in plays or films", example:"The ___ won an award.", pack:"ielts6", level:1},
  {word:"artist", ipa:"/ˈɑːrtɪst/", pos:"n.", zh:"艺术家", def:"a person who makes art", example:"The ___ paints with oil colors.", pack:"ielts6", level:1},
  {word:"boss", ipa:"/bɔːs/", pos:"n.", zh:"老板", def:"the person who leads your work", example:"My ___ gave me a day off.", pack:"ielts6", level:1},
  {word:"chef", ipa:"/ʃef/", pos:"n.", zh:"厨师", def:"a cook who works in a restaurant", example:"The ___ prepared a wonderful meal.", pack:"ielts6", level:1},
  {word:"driver", ipa:"/ˈdraɪvər/", pos:"n.", zh:"司机", def:"a person who drives a vehicle", example:"The bus ___ stopped at every stop.", pack:"ielts6", level:1},
  {word:"engineer", ipa:"/ˌendʒɪˈnɪr/", pos:"n.", zh:"工程师", def:"a person who designs machines or buildings", example:"The ___ checked the bridge.", pack:"ielts6", level:1},
  {word:"farmer", ipa:"/ˈfɑːrmər/", pos:"n.", zh:"农民", def:"a person who works on a farm", example:"The ___ grows rice.", pack:"ielts6", level:1},
  {word:"guide", ipa:"/ɡaɪd/", pos:"n.", zh:"导游；指南", def:"a person who shows tourists around", example:"The ___ showed us the old town.", pack:"ielts6", level:1},
  {word:"lawyer", ipa:"/ˈlɔːjər/", pos:"n.", zh:"律师", def:"a person who works with the law", example:"Her ___ spoke in court.", pack:"ielts6", level:1},
  {word:"manager", ipa:"/ˈmænɪdʒər/", pos:"n.", zh:"经理", def:"a person who manages a business", example:"The ___ hired two new staff.", pack:"ielts6", level:1},
  {word:"nurse", ipa:"/nɜːrs/", pos:"n.", zh:"护士", def:"a person who cares for sick people", example:"The ___ checked my temperature.", pack:"ielts6", level:1},
  {word:"pilot", ipa:"/ˈpaɪlət/", pos:"n.", zh:"飞行员", def:"a person who flies an airplane", example:"The ___ landed the plane safely.", pack:"ielts6", level:1},
  {word:"player", ipa:"/ˈpleɪər/", pos:"n.", zh:"运动员；选手", def:"a person who plays a sport or game", example:"He is a good football ___.", pack:"ielts6", level:1},
  {word:"policeman", ipa:"/pəˈliːsmən/", pos:"n.", zh:"警察（男）", def:"a male police officer", example:"The ___ stopped the traffic.", pack:"ielts6", level:1},
  {word:"reporter", ipa:"/rɪˈpɔːrtər/", pos:"n.", zh:"记者", def:"a person who writes news", example:"The ___ asked many questions.", pack:"ielts6", level:1},
  {word:"secretary", ipa:"/ˈsekrəteri/", pos:"n.", zh:"秘书", def:"a person who does office work for a boss", example:"The ___ answered the phone.", pack:"ielts6", level:1},
  {word:"singer", ipa:"/ˈsɪŋər/", pos:"n.", zh:"歌手", def:"a person who sings", example:"The ___ has a beautiful voice.", pack:"ielts6", level:1},
  {word:"waiter", ipa:"/ˈweɪtər/", pos:"n.", zh:"服务员", def:"a man who serves food in a restaurant", example:"The ___ brought our drinks.", pack:"ielts6", level:1},
  {word:"writer", ipa:"/ˈraɪtər/", pos:"n.", zh:"作家", def:"a person who writes books", example:"The ___ signed my copy.", pack:"ielts6", level:1},
  {word:"doctor", ipa:"/ˈdɑːktər/", pos:"n.", zh:"医生", def:"a person who treats sick people", example:"The ___ gave me some medicine.", pack:"ielts6", level:1},
  // ---------- 运动与休闲 ----------
  {word:"ball", ipa:"/bɔːl/", pos:"n.", zh:"球", def:"a round thing used in games", example:"Pass me the ___.", pack:"ielts6", level:1},
  {word:"basketball", ipa:"/ˈbæskɪtbɔːl/", pos:"n.", zh:"篮球", def:"a sport played with a large ball and hoops", example:"They play ___ after class.", pack:"ielts6", level:1},
  {word:"bicycle", ipa:"/ˈbaɪsɪkl/", pos:"n.", zh:"自行车", def:"a two-wheeled vehicle you pedal", example:"She rides her ___ to work.", pack:"ielts6", level:1},
  {word:"chess", ipa:"/tʃes/", pos:"n.", zh:"国际象棋", def:"a board game for two players", example:"He taught me how to play ___.", pack:"ielts6", level:1},
  {word:"football", ipa:"/ˈfʊtbɔːl/", pos:"n.", zh:"足球", def:"a sport played with a round ball and feet", example:"___ is popular worldwide.", pack:"ielts6", level:1},
  {word:"game", ipa:"/ɡeɪm/", pos:"n.", zh:"游戏；比赛", def:"an activity you play to have fun or win", example:"Let's play a ___.", pack:"ielts6", level:1},
  {word:"guitar", ipa:"/ɡɪˈtɑːr/", pos:"n.", zh:"吉他", def:"a musical instrument with strings", example:"He plays the ___ in a band.", pack:"ielts6", level:1},
  {word:"music", ipa:"/ˈmjuːzɪk/", pos:"n.", zh:"音乐", def:"sounds that are pleasant to hear", example:"I listen to ___ when studying.", pack:"ielts6", level:1},
  {word:"piano", ipa:"/piˈænoʊ/", pos:"n.", zh:"钢琴", def:"a large musical instrument with keys", example:"She practices the ___ daily.", pack:"ielts6", level:1},
  {word:"song", ipa:"/sɔːŋ/", pos:"n.", zh:"歌曲", def:"a short piece of music with words", example:"That ___ is my favorite.", pack:"ielts6", level:1},
  {word:"sport", ipa:"/spɔːrt/", pos:"n.", zh:"运动", def:"a game or activity done for exercise", example:"Swimming is my favorite ___.", pack:"ielts6", level:1},
  {word:"tennis", ipa:"/ˈtenɪs/", pos:"n.", zh:"网球", def:"a sport played with rackets and a ball", example:"They play ___ on weekends.", pack:"ielts6", level:1},
  {word:"toy", ipa:"/tɔɪ/", pos:"n.", zh:"玩具", def:"something children play with", example:"The child loves his new ___.", pack:"ielts6", level:1},
  // ---------- 常用形容词（更多） ----------
  {word:"alive", ipa:"/əˈlaɪv/", pos:"adj.", zh:"活着的", def:"living, not dead", example:"The fish is still ___.", pack:"ielts6", level:1},
  {word:"alone", ipa:"/əˈloʊn/", pos:"adj.", zh:"独自的", def:"without other people", example:"She lives ___.", pack:"ielts6", level:1},
  {word:"amazing", ipa:"/əˈmeɪzɪŋ/", pos:"adj.", zh:"惊人的", def:"very surprising and good", example:"The view was ___.", pack:"ielts6", level:1},
  {word:"bored", ipa:"/bɔːrd/", pos:"adj.", zh:"无聊的", def:"feeling tired because nothing is interesting", example:"I was ___ during the long talk.", pack:"ielts6", level:1},
  {word:"boring", ipa:"/ˈbɔːrɪŋ/", pos:"adj.", zh:"令人无聊的", def:"not interesting", example:"The lesson was ___.", pack:"ielts6", level:1},
  {word:"broken", ipa:"/ˈbroʊkən/", pos:"adj.", zh:"坏了的", def:"not working or in pieces", example:"The window is ___.", pack:"ielts6", level:1},
  {word:"clear", ipa:"/klɪr/", pos:"adj.", zh:"清晰的", def:"easy to see or understand", example:"The sky is ___ today.", pack:"ielts6", level:1},
  {word:"cold", ipa:"/koʊld/", pos:"adj.", zh:"冷的", def:"having low temperature", example:"The water is too ___.", pack:"ielts6", level:1},
  {word:"dark", ipa:"/dɑːrk/", pos:"adj.", zh:"黑暗的", def:"with little or no light", example:"The room is too ___.", pack:"ielts6", level:1},
  {word:"dead", ipa:"/ded/", pos:"adj.", zh:"死的", def:"not alive", example:"The old tree is ___.", pack:"ielts6", level:1},
  {word:"deep", ipa:"/diːp/", pos:"adj.", zh:"深的", def:"going far down", example:"The pool is very ___.", pack:"ielts6", level:1},
  {word:"delicious", ipa:"/dɪˈlɪʃəs/", pos:"adj.", zh:"美味的", def:"very tasty", example:"The soup is ___.", pack:"ielts6", level:1},
  {word:"dry", ipa:"/draɪ/", pos:"adj.", zh:"干的", def:"without water or wetness", example:"The clothes are ___.", pack:"ielts6", level:1},
  {word:"easy", ipa:"/ˈiːzi/", pos:"adj.", zh:"容易的", def:"not difficult", example:"The test was ___.", pack:"ielts6", level:1},
  {word:"exciting", ipa:"/ɪkˈsaɪtɪŋ/", pos:"adj.", zh:"令人兴奋的", def:"making you feel excited", example:"The match was ___.", pack:"ielts6", level:1},
  {word:"fat", ipa:"/fæt/", pos:"adj.", zh:"胖的", def:"having too much body weight", example:"The cat is getting ___.", pack:"ielts6", level:1},
  {word:"free", ipa:"/friː/", pos:"adj.", zh:"免费的；自由的", def:"not costing money; not busy", example:"Are you ___ this evening?", pack:"ielts6", level:1},
  {word:"fresh", ipa:"/freʃ/", pos:"adj.", zh:"新鲜的", def:"new and not old or tired", example:"I bought ___ bread.", pack:"ielts6", level:1},
  {word:"hot", ipa:"/hɑːt/", pos:"adj.", zh:"热的", def:"having high temperature", example:"The soup is very ___.", pack:"ielts6", level:1},
  {word:"hungry", ipa:"/ˈhʌŋɡri/", pos:"adj.", zh:"饿的", def:"wanting food", example:"I'm ___ after the run.", pack:"ielts6", level:1},
  {word:"low", ipa:"/loʊ/", pos:"adj.", zh:"低的", def:"not high", example:"The chair is too ___.", pack:"ielts6", level:1},
  {word:"narrow", ipa:"/ˈnæroʊ/", pos:"adj.", zh:"窄的", def:"small from side to side", example:"The road is very ___.", pack:"ielts6", level:1},
  {word:"noisy", ipa:"/ˈnɔɪzi/", pos:"adj.", zh:"吵闹的", def:"making a lot of noise", example:"The street is too ___.", pack:"ielts6", level:1},
  {word:"old", ipa:"/oʊld/", pos:"adj.", zh:"旧的；老的", def:"having existed for a long time", example:"He drives an ___ car.", pack:"ielts6", level:1},
  {word:"pretty", ipa:"/ˈprɪti/", pos:"adj.", zh:"漂亮的", def:"nice to look at", example:"What a ___ garden!", pack:"ielts6", level:1},
  {word:"sad", ipa:"/sæd/", pos:"adj.", zh:"悲伤的", def:"feeling unhappy", example:"She felt ___ at the goodbye.", pack:"ielts6", level:1},
  {word:"slow", ipa:"/sloʊ/", pos:"adj.", zh:"慢的", def:"not fast", example:"The old bus is ___.", pack:"ielts6", level:1},
  {word:"soft", ipa:"/sɔːft/", pos:"adj.", zh:"柔软的", def:"not hard, pleasant to touch", example:"The bed is ___.", pack:"ielts6", level:1},
  {word:"sweet", ipa:"/swiːt/", pos:"adj.", zh:"甜的", def:"tasting like sugar", example:"These grapes are ___.", pack:"ielts6", level:1},
  {word:"tall", ipa:"/tɔːl/", pos:"adj.", zh:"高的", def:"higher than average", example:"My brother is very ___.", pack:"ielts6", level:1},
  {word:"thick", ipa:"/θɪk/", pos:"adj.", zh:"厚的", def:"with a large distance between sides", example:"This book is ___.", pack:"ielts6", level:1},
  {word:"thin", ipa:"/θɪn/", pos:"adj.", zh:"薄的；瘦的", def:"with little distance between sides; slim", example:"The ice is too ___ to walk on.", pack:"ielts6", level:1},
  {word:"tired", ipa:"/ˈtaɪərd/", pos:"adj.", zh:"累的", def:"needing rest", example:"I feel ___ after work.", pack:"ielts6", level:1},
  {word:"wet", ipa:"/wet/", pos:"adj.", zh:"湿的", def:"covered with water", example:"My shoes are ___.", pack:"ielts6", level:1},
  {word:"wonderful", ipa:"/ˈwʌndərfl/", pos:"adj.", zh:"极好的", def:"very good; great", example:"We had a ___ holiday.", pack:"ielts6", level:1},
  // ===BATCH-C-END===
);
