// =========================================================
// 雅思核心词包 · 第3批（IELTS Batch 3）—— 扩容第一批（至 ~1040 词）
// 字段与 words.js 一致；pack:"ielts3"；level: 1基础/2进阶/3高阶/4学术。
// 后续批次按 words_ielts4.js … 继续，加载方式不变。
// =========================================================
WORDS.push(
  // ---------- 社会 & 政府 ----------
  {word:"abolish", ipa:"/əˈbɑːlɪʃ/", pos:"v.", zh:"废除；废止", def:"to officially end a law or system", example:"The government decided to ___ the old tax.", pack:"ielts3", level:3},
  {word:"legislation", ipa:"/ˌledʒɪsˈleɪʃn/", pos:"n.", zh:"立法；法律", def:"a law or set of laws", example:"New ___ about cars was passed last year.", pack:"ielts3", level:3},
  {word:"bureaucracy", ipa:"/bjʊˈrɑːkrəsi/", pos:"n.", zh:"官僚体制", def:"a system with many rules and slow processes", example:"The ___ made it hard to get a permit.", pack:"ielts3", level:4},
  {word:"govern", ipa:"/ˈɡʌvərn/", pos:"v.", zh:"统治；治理", def:"to officially control a country or city", example:"One party has ___ed this state for years.", pack:"ielts3", level:2},
  {word:"minister", ipa:"/ˈmɪnɪstər/", pos:"n.", zh:"部长；大臣", def:"an important government leader in charge of one area", example:"The health ___ gave a speech today.", pack:"ielts3", level:2},
  {word:"politics", ipa:"/ˈpɑːlətɪks/", pos:"n.", zh:"政治", def:"activities about running a country or government", example:"He studied ___ at university.", pack:"ielts3", level:2},
  {word:"opposition", ipa:"/ˌɑːpəˈzɪʃn/", pos:"n.", zh:"反对；对手", def:"people who disagree with or fight a plan or group", example:"The plan faced strong ___ from farmers.", pack:"ielts3", level:3},
  {word:"petition", ipa:"/pəˈtɪʃn/", pos:"n.", zh:"请愿书", def:"a paper signed by many people asking for change", example:"Thousands signed a ___ for cleaner air.", pack:"ielts3", level:3},
  // ---------- 环境 & 能源 ----------
  {word:"contaminate", ipa:"/kənˈtæmɪneɪt/", pos:"v.", zh:"污染；弄脏", def:"to make something dirty or unsafe", example:"Chemicals ___ed the river.", pack:"ielts3", level:3},
  {word:"extinction", ipa:"/ɪkˈstɪŋkʃn/", pos:"n.", zh:"灭绝", def:"the death of all members of a species", example:"Many animals face ___.", pack:"ielts3", level:3},
  {word:"landfill", ipa:"/ˈlændfɪl/", pos:"n.", zh:"垃圾填埋场", def:"a place where waste is buried in the ground", example:"Too much rubbish goes to the ___.", pack:"ielts3", level:3},
  {word:"disaster", ipa:"/dɪˈzæstər/", pos:"n.", zh:"灾难", def:"a sudden event that causes great damage", example:"The earthquake was a terrible ___.", pack:"ielts3", level:2},
  {word:"agriculture", ipa:"/ˈæɡrɪkʌltʃər/", pos:"n.", zh:"农业", def:"the science or work of growing crops and raising animals", example:"___ is important for food supply.", pack:"ielts3", level:3},
  {word:"fertilizer", ipa:"/ˈfɜːrtəlaɪzər/", pos:"n.", zh:"肥料", def:"a chemical or natural material that helps plants grow", example:"They added ___ to the soil.", pack:"ielts3", level:3},
  {word:"pesticide", ipa:"/ˈpestɪsaɪd/", pos:"n.", zh:"杀虫剂", def:"a chemical that kills insects that damage crops", example:"Too much ___ can harm bees.", pack:"ielts3", level:4},
  {word:"carbon", ipa:"/ˈkɑːrbən/", pos:"n.", zh:"碳", def:"a chemical element; part of greenhouse gas", example:"Burning fuel releases ___ dioxide.", pack:"ielts3", level:2},
  // ---------- 科学 & 技术 ----------
  {word:"automation", ipa:"/ˌɔːtəˈmeɪʃn/", pos:"n.", zh:"自动化", def:"the use of machines to do work without people", example:"___ has changed many factories.", pack:"ielts3", level:3},
  {word:"cyber", ipa:"/ˈsaɪbər/", pos:"adj.", zh:"网络的", def:"related to computers and the internet", example:"___ crime is growing quickly.", pack:"ielts3", level:3},
  {word:"encrypt", ipa:"/ɪnˈkrɪpt/", pos:"v.", zh:"加密", def:"to turn information into a secret code", example:"The app ___s your messages.", pack:"ielts3", level:4},
  {word:"algorithm", ipa:"/ˈælɡərɪðəm/", pos:"n.", zh:"算法", def:"a set of steps a computer follows to solve a problem", example:"The ___ sorts photos by date.", pack:"ielts3", level:4},
  {word:"engineering", ipa:"/ˌendʒɪˈnɪrɪŋ/", pos:"n.", zh:"工程学", example:"She studied ___ at university.", pack:"ielts3", level:2},
  {word:"scientist", ipa:"/ˈsaɪəntɪst/", pos:"n.", zh:"科学家", def:"a person who studies science", example:"The ___ discovered a new planet.", pack:"ielts3", level:1},
  {word:"laboratory", ipa:"/ˈlæbrətɔːri/", pos:"n.", zh:"实验室", def:"a room where scientists do experiments", example:"The team works in a modern ___.", pack:"ielts3", level:2},
  {word:"experiment", ipa:"/ɪkˈsperɪmənt/", pos:"n./v.", zh:"实验", def:"a test done to learn something", example:"They did an ___ to test the drug.", pack:"ielts3", level:2},
  // ---------- 健康 & 医学 ----------
  {word:"diet", ipa:"/ˈdaɪət/", pos:"n.", zh:"饮食", def:"the food and drink a person usually takes", example:"A healthy ___ has lots of vegetables.", pack:"ielts3", level:1},
  {word:"immunity", ipa:"/ɪˈmjuːnəti/", pos:"n.", zh:"免疫力", def:"the body's power to resist disease", example:"Exercise can improve your ___.", pack:"ielts3", level:4},
  {word:"physician", ipa:"/fɪˈzɪʃn/", pos:"n.", zh:"内科医生", def:"a doctor, especially one who treats illness", example:"Her ___ advised more rest.", pack:"ielts3", level:3},
  {word:"prescription", ipa:"/prɪˈskrɪpʃn/", pos:"n.", zh:"处方", def:"a doctor's written order for medicine", example:"You need a ___ for this drug.", pack:"ielts3", level:3},
  {word:"anxiety", ipa:"/æŋˈzaɪəti/", pos:"n.", zh:"焦虑", def:"a feeling of worry about something", example:"Exam time causes a lot of ___.", pack:"ielts3", level:3},
  {word:"depression", ipa:"/dɪˈpreʃn/", pos:"n.", zh:"抑郁；萧条", def:"a serious sad feeling; a bad economic period", example:"She talked to a doctor about her ___.", pack:"ielts3", level:3},
  {word:"fatigue", ipa:"/fəˈtiːɡ/", pos:"n.", zh:"疲劳", def:"great tiredness", example:"Long flights cause jet ___.", pack:"ielts3", level:3},
  {word:"organism", ipa:"/ˈɔːrɡənɪzəm/", pos:"n.", zh:"生物；有机体", def:"a living thing such as an animal or plant", example:"Germs are tiny ___ that cause disease.", pack:"ielts3", level:3},
  {word:"virus", ipa:"/ˈvaɪrəs/", pos:"n.", zh:"病毒", def:"a tiny thing that causes illness", example:"The ___ spreads through the air.", pack:"ielts3", level:2},
  {word:"bacteria", ipa:"/bækˈtɪriə/", pos:"n.", zh:"细菌", def:"very small living things, some of which cause disease", example:"Some ___ are good for the body.", pack:"ielts3", level:3},
  // ---------- 教育 & 学术 ----------
  {word:"assessment", ipa:"/əˈsesmənt/", pos:"n.", zh:"评估", def:"a test or judgment of progress", example:"Students take an ___ every term.", pack:"ielts3", level:3},
  {word:"seminar", ipa:"/ˈsemɪnɑːr/", pos:"n.", zh:"研讨课", def:"a small class where students discuss a topic", example:"We have a ___ on modern history every Friday.", pack:"ielts3", level:3},
  {word:"faculty", ipa:"/ˈfæklti/", pos:"n.", zh:"（大学）全体教员", def:"all the teachers in a university", example:"The ___ voted on the new policy.", pack:"ielts3", level:3},
  {word:"reasoning", ipa:"/ˈriːznɪŋ/", pos:"n.", zh:"推理", def:"the process of thinking logically", example:"Clear ___ helps solve problems.", pack:"ielts3", level:4},
  {word:"critical", ipa:"/ˈkrɪtɪkl/", pos:"adj.", zh:"批评的；关键的", def:"finding fault; very important", example:"___ thinking is a useful skill.", pack:"ielts3", level:3},
  {word:"methodology", ipa:"/ˌmeθəˈdɑːlədʒi/", pos:"n.", zh:"方法论", def:"the system of methods used in a study", example:"The paper explains its ___ clearly.", pack:"ielts3", level:4},
  {word:"percentage", ipa:"/pərˈsentɪdʒ/", pos:"n.", zh:"百分比", def:"an amount expressed out of one hundred", example:"A large ___ of students passed.", pack:"ielts3", level:2},
  {word:"attendance", ipa:"/əˈtendəns/", pos:"n.", zh:"出席；出勤", def:"the act of being present at a class or event", example:"___ at class is required.", pack:"ielts3", level:3},
  // ---------- 经济 & 商业 ----------
  {word:"recession", ipa:"/rɪˈseʃn/", pos:"n.", zh:"经济衰退", def:"a period when the economy becomes weaker", example:"Many shops closed during the ___.", pack:"ielts3", level:3},
  {word:"export", ipa:"/ɪkˈspɔːrt/", pos:"v./n.", zh:"出口", def:"to send goods to other countries; such goods", example:"This country ___s a lot of rice.", pack:"ielts3", level:2},
  {word:"import", ipa:"/ɪmˈpɔːrt/", pos:"v./n.", zh:"进口", def:"to bring goods in from other countries", example:"They ___ coffee from Brazil.", pack:"ielts3", level:2},
  {word:"competition", ipa:"/ˌkɑːmpəˈtɪʃn/", pos:"n.", zh:"竞争", def:"the activity of trying to win or be better than others", example:"There is strong ___ among phone makers.", pack:"ielts3", level:2},
  {word:"warehouse", ipa:"/ˈwerhaʊs/", pos:"n.", zh:"仓库", def:"a large building for storing goods", example:"The goods wait in a ___ before shipping.", pack:"ielts3", level:3},
  {word:"wholesale", ipa:"/ˈhoʊlseɪl/", pos:"n.", zh:"批发", def:"the sale of goods in large amounts to shops", example:"He buys fruit at ___ prices.", pack:"ielts3", level:4},
  {word:"trade", ipa:"/treɪd/", pos:"n./v.", zh:"贸易；交易", def:"the buying and selling of goods", example:"___ between the two countries is growing.", pack:"ielts3", level:2},
  // ---------- 法律 & 犯罪 ----------
  {word:"verdict", ipa:"/ˈvɜːrdɪkt/", pos:"n.", zh:"裁决", def:"the decision of a court", example:"The jury reached a guilty ___.", pack:"ielts3", level:4},
  {word:"trial", ipa:"/ˈtraɪəl/", pos:"n.", zh:"审判", def:"a court process to decide if someone is guilty", example:"The ___ lasted three weeks.", pack:"ielts3", level:2},
  {word:"witness", ipa:"/ˈwɪtnəs/", pos:"n.", zh:"目击者", def:"a person who saw a crime or event", example:"A ___ saw the car leave the scene.", pack:"ielts3", level:2},
  {word:"jury", ipa:"/ˈdʒʊri/", pos:"n.", zh:"陪审团", def:"a group of people who decide if someone is guilty", example:"The ___ found him guilty.", pack:"ielts3", level:3},
  {word:"accuse", ipa:"/əˈkjuːz/", pos:"v.", zh:"指控", def:"to say someone did something wrong", example:"They ___d him of stealing.", pack:"ielts3", level:2},
  {word:"guilty", ipa:"/ˈɡɪlti/", pos:"adj.", zh:"有罪的", def:"having broken the law", example:"The court said he was ___.", pack:"ielts3", level:2},
  {word:"offence", ipa:"/əˈfens/", pos:"n.", zh:"违法；冒犯", def:"an action that breaks the law", example:"Driving too fast is a minor ___.", pack:"ielts3", level:3},
  {word:"punishment", ipa:"/ˈpʌnɪʃmənt/", pos:"n.", zh:"惩罚", def:"something done to punish someone", example:"The ___ fits the crime.", pack:"ielts3", level:2},
  {word:"imprison", ipa:"/ɪmˈprɪzn/", pos:"v.", zh:"监禁", def:"to put someone in prison", example:"The court ___ed him for five years.", pack:"ielts3", level:3},
  {word:"fraud", ipa:"/frɔːd/", pos:"n.", zh:"欺诈", def:"the crime of cheating people for money", example:"He was arrested for ___.", pack:"ielts3", level:3},
  {word:"theft", ipa:"/θeft/", pos:"n.", zh:"偷窃", def:"the crime of stealing", example:"There was a ___ at the shop last night.", pack:"ielts3", level:3},
  {word:"smuggle", ipa:"/ˈsmʌɡl/", pos:"v.", zh:"走私", def:"to move goods into a country secretly and illegally", example:"They tried to ___ gold across the border.", pack:"ielts3", level:4},
  // ---------- 媒体 & 传播 ----------
  {word:"broadcast", ipa:"/ˈbrɔːdkæst/", pos:"v./n.", zh:"广播；播放", def:"to send out programs on TV or radio", example:"The match was ___ live.", pack:"ielts3", level:2},
  {word:"journalist", ipa:"/ˈdʒɜːrnəlɪst/", pos:"n.", zh:"记者", def:"a person who reports the news", example:"The ___ interviewed the mayor.", pack:"ielts3", level:2},
  {word:"coverage", ipa:"/ˈkʌvərɪdʒ/", pos:"n.", zh:"报道", def:"the reporting of news or events", example:"The event received wide media ___.", pack:"ielts3", level:3},
  {word:"censorship", ipa:"/ˈsensərʃɪp/", pos:"n.", zh:"审查", def:"the control of what people can see or read", example:"The government's ___ of books was criticized.", pack:"ielts3", level:4},
  {word:"advertise", ipa:"/ˈædvərtaɪz/", pos:"v.", zh:"做广告", def:"to tell people about a product to sell it", example:"They ___ the new drink on TV.", pack:"ielts3", level:2},
  {word:"publicity", ipa:"/pʌbˈlɪsəti/", pos:"n.", zh:"宣传", def:"attention from the media or public", example:"The film got a lot of ___.", pack:"ielts3", level:3},
  {word:"editorial", ipa:"/ˌedɪˈtɔːriəl/", pos:"n.", zh:"社论", def:"a newspaper article giving an opinion", example:"The ___ criticized the new tax.", pack:"ielts3", level:4},
  {word:"propaganda", ipa:"/ˌprɑːpəˈɡændə/", pos:"n.", zh:"宣传（贬义）", def:"information spread to influence people's opinions", example:"The posters were pure ___.", pack:"ielts3", level:4},
  // ---------- 情感 & 性格 ----------
  {word:"generous", ipa:"/ˈdʒenərəs/", pos:"adj.", zh:"慷慨的", def:"happy to give more than expected", example:"She is ___ with her time.", pack:"ielts3", level:2},
  {word:"stubborn", ipa:"/ˈstʌbərn/", pos:"adj.", zh:"固执的", def:"refusing to change your mind", example:"He is too ___ to listen.", pack:"ielts3", level:3},
  {word:"sensitive", ipa:"/ˈsensətɪv/", pos:"adj.", zh:"敏感的", def:"easily affected or upset by small things", example:"She is ___ to loud noises.", pack:"ielts3", level:2},
  {word:"optimistic", ipa:"/ˌɑːptɪˈmɪstɪk/", pos:"adj.", zh:"乐观的", def:"believing that good things will happen", example:"She is ___ about the future.", pack:"ielts3", level:3},
  {word:"pessimistic", ipa:"/ˌpesɪˈmɪstɪk/", pos:"adj.", zh:"悲观的", def:"expecting bad things to happen", example:"Don't be so ___; we can still win.", pack:"ielts3", level:3},
  {word:"ambitious", ipa:"/æmˈbɪʃəs/", pos:"adj.", zh:"有雄心的", def:"wanting to achieve a lot", example:"He has ___ plans for his career.", pack:"ielts3", level:3},
  {word:"cautious", ipa:"/ˈkɔːʃəs/", pos:"adj.", zh:"谨慎的", def:"careful to avoid danger or mistakes", example:"Be ___ when you cross the road.", pack:"ielts3", level:3},
  {word:"curious", ipa:"/ˈkjʊriəs/", pos:"adj.", zh:"好奇的", def:"wanting to know or learn", example:"Children are ___ about everything.", pack:"ielts3", level:2},
  {word:"jealous", ipa:"/ˈdʒeləs/", pos:"adj.", zh:"嫉妒的", def:"unhappy because someone has what you want", example:"He felt ___ of his brother's success.", pack:"ielts3", level:2},
  {word:"frustration", ipa:"/frʌˈstreɪʃn/", pos:"n.", zh:"沮丧；挫败", def:"the feeling of being annoyed because you cannot do something", example:"He shouted in ___.", pack:"ielts3", level:3},
  {word:"sympathy", ipa:"/ˈsɪmpəθi/", pos:"n.", zh:"同情", def:"the feeling of understanding someone's sadness", example:"She showed ___ for the sick child.", pack:"ielts3", level:3},
  {word:"compassion", ipa:"/kəmˈpæʃn/", pos:"n.", zh:"同情心", def:"strong kindness and care for others", example:"Nurses show great ___.", pack:"ielts3", level:4},
  {word:"patience", ipa:"/ˈpeɪʃns/", pos:"n.", zh:"耐心", def:"the ability to wait calmly", example:"Learning music needs ___.", pack:"ielts3", level:2},
  {word:"persistence", ipa:"/pərˈsɪstəns/", pos:"n.", zh:"坚持", def:"continuing to try even when it is hard", example:"Her ___ helped her finish the race.", pack:"ielts3", level:3},
  {word:"willpower", ipa:"/ˈwɪlpaʊər/", pos:"n.", zh:"意志力", def:"the strength to control your actions", example:"He quit smoking through ___.", pack:"ielts3", level:3},
  // ---------- 工作 & 职业 ----------
  {word:"interview", ipa:"/ˈɪntərvjuː/", pos:"n.", zh:"面试；采访", def:"a meeting to ask questions for a job or news", example:"She has a job ___ on Monday.", pack:"ielts3", level:2},
  {word:"resign", ipa:"/rɪˈzaɪn/", pos:"v.", zh:"辞职", def:"to officially leave your job", example:"He ___ed after the argument.", pack:"ielts3", level:3},
  {word:"overtime", ipa:"/ˈoʊvərtaɪm/", pos:"n.", zh:"加班", def:"extra work beyond the usual hours", example:"He worked ___ to finish the project.", pack:"ielts3", level:3},
  {word:"resume", ipa:"/rɪˈzuːm/", pos:"n.", zh:"简历", def:"a short list of your jobs and skills", example:"Send your ___ to the company.", pack:"ielts3", level:3},
  {word:"supervisor", ipa:"/ˈsuːpərvaɪzər/", pos:"n.", zh:"主管", def:"a person who watches over workers", example:"Ask your ___ before leaving early.", pack:"ielts3", level:3},
  // ---------- 旅行 & 文化 ----------
  {word:"heritage", ipa:"/ˈherɪtɪdʒ/", pos:"n.", zh:"遗产（文化）", def:"important buildings and traditions from the past", example:"The old town is a world ___.", pack:"ielts3", level:3},
  {word:"landmark", ipa:"/ˈlændmɑːrk/", pos:"n.", zh:"地标", def:"a famous building or place that is easy to see", example:"The tower is a famous ___.", pack:"ielts3", level:2},
  {word:"architecture", ipa:"/ˈɑːrkɪtektʃər/", pos:"n.", zh:"建筑（艺术）", def:"the art and design of buildings", example:"The city is known for its old ___.", pack:"ielts3", level:3},
  {word:"immigrant", ipa:"/ˈɪmɪɡrənt/", pos:"n.", zh:"移民", def:"a person who comes to live in another country", example:"Her grandparents were ___s.", pack:"ielts3", level:3},
  {word:"exotic", ipa:"/ɪɡˈzɑːtɪk/", pos:"adj.", zh:"异国情调的", def:"unusual and exciting because foreign", example:"They tried ___ fruits on the trip.", pack:"ielts3", level:3},
  {word:"scenery", ipa:"/ˈsiːnəri/", pos:"n.", zh:"风景", def:"the natural beauty of a place", example:"The ___ in the mountains is amazing.", pack:"ielts3", level:3},
  // ---------- 抽象动作 / 观点 ----------
  {word:"neglect", ipa:"/nɪˈɡlekt/", pos:"v.", zh:"忽视", def:"to fail to look after something", example:"He ___ed his health for years.", pack:"ielts3", level:3},
  {word:"recognize", ipa:"/ˈrekəɡnaɪz/", pos:"v.", zh:"认出；承认", def:"to know someone or something again", example:"I didn't ___ you with short hair.", pack:"ielts3", level:2},
  {word:"reflect", ipa:"/rɪˈflekt/", pos:"v.", zh:"反映；思考", def:"to show something; to think deeply", example:"The results ___ the hard work of the team.", pack:"ielts3", level:2},
  {word:"reject", ipa:"/rɪˈdʒekt/", pos:"v.", zh:"拒绝；否决", def:"to refuse to accept something", example:"The plan was ___ed by the board.", pack:"ielts3", level:2},
  {word:"substantial", ipa:"/səbˈstænʃl/", pos:"adj.", zh:"大量的；实质的", def:"large in size or importance", example:"They made a ___ improvement.", pack:"ielts3", level:4},
  {word:"evident", ipa:"/ˈevɪdənt/", pos:"adj.", zh:"显然的", def:"clear and obvious", example:"It is ___ that the team worked hard.", pack:"ielts3", level:3},
  {word:"frequency", ipa:"/ˈfriːkwənsi/", pos:"n.", zh:"频率", def:"how often something happens", example:"The ___ of earthquakes here is low.", pack:"ielts3", level:2},
  {word:"criterion", ipa:"/kraɪˈtɪriən/", pos:"n.", zh:"标准（单数）", def:"a standard used to judge something", example:"Price is not the only ___.", pack:"ielts3", level:4},
  {word:"underestimate", ipa:"/ˌʌndərˈestɪmeɪt/", pos:"v.", zh:"低估", def:"to think something is smaller or weaker than it is", example:"Never ___ the power of habit.", pack:"ielts3", level:3},
  {word:"exaggerate", ipa:"/ɪɡˈzædʒəreɪt/", pos:"v.", zh:"夸大", def:"to make something seem bigger or worse than it is", example:"Don't ___; the trip wasn't that bad.", pack:"ielts3", level:3},
  {word:"compromise", ipa:"/ˈkɑːmprəmaɪz/", pos:"n./v.", zh:"妥协", def:"an agreement where each side gives up something", example:"Both sides reached a ___.", pack:"ielts3", level:3},
  {word:"negotiate", ipa:"/nɪˈɡoʊʃieɪt/", pos:"v.", zh:"谈判", def:"to discuss to reach an agreement", example:"They ___d a better price.", pack:"ielts3", level:3},
);
