// =========================================================
// 雅思核心词包 · 第7批（IELTS Batch 7）—— 进阶高频补全（level2 为主）
// =========================================================
WORDS.push(
  // ---------- 家居与用品（进阶） ----------
  {word:"carpet", ipa:"/ˈkɑːrpɪt/", pos:"n.", zh:"地毯", def:"a floor covering made of thick cloth", example:"The ___ is soft and warm.", pack:"ielts7", level:2},
  {word:"curtain", ipa:"/ˈkɜːrtn/", pos:"n.", zh:"窗帘", def:"cloth that hangs over a window", example:"Open the ___s to let in light.", pack:"ielts7", level:2},
  {word:"cushion", ipa:"/ˈkʊʃn/", pos:"n.", zh:"坐垫", def:"a soft pillow for sitting on", example:"He sat on a soft ___.", pack:"ielts7", level:2},
  {word:"envelope", ipa:"/ˈenvəloʊp/", pos:"n.", zh:"信封", def:"a paper cover for letters", example:"She put the letter in an ___.", pack:"ielts7", level:2},
  {word:"faucet", ipa:"/ˈfɔːsɪt/", pos:"n.", zh:"水龙头", def:"a thing that controls water from a pipe", example:"Turn on the ___ to wash your hands.", pack:"ielts7", level:2},
  {word:"jar", ipa:"/dʒɑːr/", pos:"n.", zh:"罐子", def:"a glass container with a wide mouth", example:"There is honey in that ___.", pack:"ielts7", level:2},
  {word:"kettle", ipa:"/ˈketl/", pos:"n.", zh:"水壶", def:"a container for boiling water", example:"Boil some water in the ___.", pack:"ielts7", level:2},
  {word:"pillow", ipa:"/ˈpɪloʊ/", pos:"n.", zh:"枕头", def:"a soft thing you rest your head on", example:"My ___ is too flat.", pack:"ielts7", level:1},
  {word:"plug", ipa:"/plʌɡ/", pos:"n.", zh:"插头", def:"the part that connects to a wall socket", example:"Pull the ___ out of the socket.", pack:"ielts7", level:2},
  {word:"shelf", ipa:"/ʃelf/", pos:"n.", zh:"架子", def:"a flat board for holding things", example:"The books are on the top ___.", pack:"ielts7", level:1},
  {word:"stove", ipa:"/stoʊv/", pos:"n.", zh:"炉子", def:"a thing used for cooking or heating", example:"She cooked soup on the ___.", pack:"ielts7", level:1},
  {word:"tray", ipa:"/treɪ/", pos:"n.", zh:"托盘", def:"a flat holder for carrying cups or food", example:"The waiter carried drinks on a ___.", pack:"ielts7", level:2},
  {word:"vase", ipa:"/veɪs/", pos:"n.", zh:"花瓶", def:"a container for flowers", example:"She put roses in the ___.", pack:"ielts7", level:2},
  {word:"wicket", ipa:"/ˈwɪkɪt/", pos:"n.", zh:"小门；球门", def:"a small door; a target in cricket", example:"The cat slipped through the ___.", pack:"ielts7", level:3},
  // ---------- 出行与交通 ----------
  {word:"petrol", ipa:"/ˈpetrəl/", pos:"n.", zh:"汽油", def:"liquid fuel for cars", example:"The car needs more ___.", pack:"ielts7", level:2},
  {word:"platform", ipa:"/ˈplætfɔːrm/", pos:"n.", zh:"站台", def:"the raised place where you wait for a train", example:"The train leaves from ___ two.", pack:"ielts7", level:2},
  {word:"railway", ipa:"/ˈreɪlweɪ/", pos:"n.", zh:"铁路", def:"the track and system of trains", example:"The ___ crosses the whole country.", pack:"ielts7", level:2},
  {word:"sailor", ipa:"/ˈseɪlər/", pos:"n.", zh:"水手", def:"a person who works on a ship", example:"The ___ climbed the mast.", pack:"ielts7", level:2},
  {word:"voyage", ipa:"/ˈvɔɪɪdʒ/", pos:"n.", zh:"航行", def:"a long journey by sea or space", example:"The ship began its long ___.", pack:"ielts7", level:3},
  {word:"windscreen", ipa:"/ˈwɪndskriːn/", pos:"n.", zh:"挡风玻璃", def:"the glass at the front of a car", example:"Clean the ___ before driving.", pack:"ielts7", level:3},
  {word:"anchor", ipa:"/ˈæŋkər/", pos:"n.", zh:"锚", def:"a heavy metal thing that keeps a ship in place", example:"The ship dropped its ___ in the bay.", pack:"ielts7", level:3},
  {word:"compass", ipa:"/ˈkʌmpəs/", pos:"n.", zh:"指南针", def:"an instrument that shows north", example:"Hikers carry a ___.", pack:"ielts7", level:3},
  // ---------- 天气与自然（进阶） ----------
  {word:"breeze", ipa:"/briːz/", pos:"n.", zh:"微风", def:"a gentle, light wind", example:"A cool ___ came from the sea.", pack:"ielts7", level:2},
  {word:"cave", ipa:"/keɪv/", pos:"n.", zh:"洞穴", def:"a big hole in a hill or underground", example:"Bears sleep in a ___.", pack:"ielts7", level:2},
  {word:"cliff", ipa:"/klɪf/", pos:"n.", zh:"悬崖", def:"a high, steep rock face", example:"Birds nest on the ___.", pack:"ielts7", level:2},
  {word:"coast", ipa:"/koʊst/", pos:"n.", zh:"海岸", def:"the land next to the sea", example:"We drove along the ___.", pack:"ielts7", level:2},
  {word:"continent", ipa:"/ˈkɑːntɪnənt/", pos:"n.", zh:"大陆", def:"one of the large land areas of the world", example:"Asia is the biggest ___.", pack:"ielts7", level:2},
  {word:"dew", ipa:"/duː/", pos:"n.", zh:"露水", def:"small drops of water on grass in the morning", example:"The grass was wet with ___.", pack:"ielts7", level:3},
  {word:"equator", ipa:"/ɪˈkweɪtər/", pos:"n.", zh:"赤道", def:"the imaginary line around the middle of the earth", example:"It is hot near the ___.", pack:"ielts7", level:4},
  {word:"geography", ipa:"/dʒiˈɑːɡrəfi/", pos:"n.", zh:"地理", def:"the study of the earth and places", example:"She is good at ___.", pack:"ielts7", level:2},
  {word:"horizon", ipa:"/həˈraɪzn/", pos:"n.", zh:"地平线", def:"the line where the sky meets the land or sea", example:"The sun rose above the ___.", pack:"ielts7", level:3},
  {word:"jungle", ipa:"/ˈdʒʌŋɡl/", pos:"n.", zh:"丛林", def:"a thick tropical forest", example:"Many birds live in the ___.", pack:"ielts7", level:2},
  {word:"moisture", ipa:"/ˈmɔɪstʃər/", pos:"n.", zh:"潮气", def:"small drops of water in the air or on things", example:"___ in the air made the floor slippery.", pack:"ielts7", level:4},
  {word:"peninsula", ipa:"/pəˈnɪnsələ/", pos:"n.", zh:"半岛", def:"land mostly surrounded by water", example:"They live on a small ___.", pack:"ielts7", level:4},
  {word:"plain", ipa:"/pleɪn/", pos:"n.", zh:"平原", def:"a large flat area of land", example:"Wheat grows on the wide ___.", pack:"ielts7", level:2},
  {word:"shore", ipa:"/ʃɔːr/", pos:"n.", zh:"岸边", def:"the land at the edge of the sea or lake", example:"We walked along the ___.", pack:"ielts7", level:2},
  {word:"slope", ipa:"/sloʊp/", pos:"n.", zh:"斜坡", def:"a surface that goes up or down at an angle", example:"They skied down the ___.", pack:"ielts7", level:3},
  {word:"swamp", ipa:"/swɑːmp/", pos:"n.", zh:"沼泽", def:"very wet, soft land", example:"Frogs live in the ___.", pack:"ielts7", level:3},
  {word:"temperature", ipa:"/ˈtemprətʃər/", pos:"n.", zh:"温度", def:"how hot or cold something is", example:"The ___ dropped below zero.", pack:"ielts7", level:2},
  {word:"tide", ipa:"/taɪd/", pos:"n.", zh:"潮汐", def:"the regular rise and fall of the sea", example:"The ___ is coming in now.", pack:"ielts7", level:3},
  {word:"wave", ipa:"/weɪv/", pos:"n.", zh:"波浪", def:"a moving line of water on the sea", example:"The ___s crashed on the beach.", pack:"ielts7", level:1},
  // ---------- 身体与医疗（进阶） ----------
  {word:"ambulance", ipa:"/ˈæmbjələns/", pos:"n.", zh:"救护车", def:"a vehicle that takes sick people to hospital", example:"The ___ arrived very fast.", pack:"ielts7", level:2},
  {word:"bandage", ipa:"/ˈbændɪdʒ/", pos:"n.", zh:"绷带", def:"a long strip of cloth for a wound", example:"The nurse put a ___ on his arm.", pack:"ielts7", level:2},
  {word:"fever", ipa:"/ˈfiːvər/", pos:"n.", zh:"发烧", def:"a body temperature higher than normal", example:"She stayed home with a ___.", pack:"ielts7", level:2},
  {word:"germ", ipa:"/dʒɜːrm/", pos:"n.", zh:"细菌；病菌", def:"a tiny living thing that causes disease", example:"Wash your hands to kill ___.", pack:"ielts7", level:2},
  {word:"inject", ipa:"/ɪnˈdʒekt/", pos:"v.", zh:"注射", def:"to put medicine into the body with a needle", example:"The doctor ___ed the vaccine.", pack:"ielts7", level:4},
  {word:"muscle", ipa:"/ˈmʌsl/", pos:"n.", zh:"肌肉", def:"the body parts that move your bones", example:"Running builds your leg ___.", pack:"ielts7", level:2},
  {word:"nerve", ipa:"/nɜːrv/", pos:"n.", zh:"神经", def:"the body parts that carry messages", example:"The dentist hurt a ___ in my tooth.", pack:"ielts7", level:3},
  {word:"pill", ipa:"/pɪl/", pos:"n.", zh:"药片", def:"a small piece of medicine you swallow", example:"Take one ___ with water.", pack:"ielts7", level:1},
  {word:"swell", ipa:"/swel/", pos:"v.", zh:"肿胀", def:"to become bigger because of injury or illness", example:"My ankle ___ed after the fall.", pack:"ielts7", level:3},
  {word:"wound", ipa:"/wuːnd/", pos:"n.", zh:"伤口", def:"an injury where the skin is cut or broken", example:"The nurse cleaned the ___.", pack:"ielts7", level:2},
  {word:"pulse", ipa:"/pʌls/", pos:"n.", zh:"脉搏", def:"the regular beat of your heart you can feel", example:"The doctor checked my ___.", pack:"ielts7", level:3},
  {word:"sneeze", ipa:"/sniːz/", pos:"v.", zh:"打喷嚏", def:"to push air out of your nose suddenly", example:"He ___d three times in a row.", pack:"ielts7", level:2},
  {word:"cough", ipa:"/kɔːf/", pos:"v./n.", zh:"咳嗽", def:"to push air out suddenly with a sound", example:"She has a bad ___ today.", pack:"ielts7", level:1},
  // ---------- 情绪与性格（进阶） ----------
  {word:"annoy", ipa:"/əˈnɔɪ/", pos:"v.", zh:"使烦恼", def:"to make someone slightly angry", example:"The noise ___ed me all day.", pack:"ielts7", level:2},
  {word:"ashamed", ipa:"/əˈʃeɪmd/", pos:"adj.", zh:"羞愧的", def:"feeling bad about something you did", example:"He felt ___ of his lie.", pack:"ielts7", level:3},
  {word:"astonish", ipa:"/əˈstɑːnɪʃ/", pos:"v.", zh:"使惊讶", def:"to surprise someone very much", example:"The magic trick ___ed the children.", pack:"ielts7", level:3},
  {word:"desperate", ipa:"/ˈdespərət/", pos:"adj.", zh:"绝望的；急切的", def:"very worried or needing something very much", example:"He was ___ for a glass of water.", pack:"ielts7", level:3},
  {word:"embarrassed", ipa:"/ɪmˈbærəst/", pos:"adj.", zh:"尴尬的", def:"feeling shy and awkward", example:"I felt ___ when I forgot her name.", pack:"ielts7", level:3},
  {word:"humble", ipa:"/ˈhʌmbl/", pos:"adj.", zh:"谦虚的", def:"not proud; modest", example:"The star remained ___.", pack:"ielts7", level:3},
  {word:"impatient", ipa:"/ɪmˈpeɪʃnt/", pos:"adj.", zh:"不耐烦的", def:"not able to wait calmly", example:"He grew ___ with the slow line.", pack:"ielts7", level:3},
  {word:"lonely", ipa:"/ˈloʊnli/", pos:"adj.", zh:"孤独的", def:"unhappy because you are alone", example:"She felt ___ in the new city.", pack:"ielts7", level:2},
  {word:"nervous", ipa:"/ˈnɜːrvəs/", pos:"adj.", zh:"紧张的", def:"worried and a little afraid", example:"I felt ___ before the exam.", pack:"ielts7", level:2},
  {word:"relieved", ipa:"/rɪˈliːvd/", pos:"adj.", zh:"如释重负的", def:"happy because a worry is gone", example:"She felt ___ when the test ended.", pack:"ielts7", level:3},
  {word:"shy", ipa:"/ʃaɪ/", pos:"adj.", zh:"害羞的", def:"nervous about meeting people", example:"He is too ___ to speak in class.", pack:"ielts7", level:1},
  {word:"upset", ipa:"/ʌpˈset/", pos:"adj.", zh:"难过的", def:"unhappy or worried", example:"She was ___ about the bad news.", pack:"ielts7", level:1},
  {word:"grateful", ipa:"/ˈɡreɪtfl/", pos:"adj.", zh:"感激的", def:"feeling thanks to someone", example:"I'm ___ for your help.", pack:"ielts7", level:3},
  // ---------- 学习/生活杂项动词 ----------
  {word:"bake", ipa:"/beɪk/", pos:"v.", zh:"烘烤", def:"to cook food in an oven", example:"She ___d bread every Sunday.", pack:"ielts7", level:2},
  {word:"boil", ipa:"/bɔɪl/", pos:"v.", zh:"煮沸", def:"to heat water until it makes bubbles", example:"___ the eggs for five minutes.", pack:"ielts7", level:1},
  {word:"burn", ipa:"/bɜːrn/", pos:"v.", zh:"燃烧；烫伤", def:"to be on fire; to hurt with heat", example:"The toast ___t in the oven.", pack:"ielts7", level:1},
  {word:"fry", ipa:"/fraɪ/", pos:"v.", zh:"油炸", def:"to cook in hot oil", example:"Let's ___ some fish tonight.", pack:"ielts7", level:2},
  {word:"melt", ipa:"/melt/", pos:"v.", zh:"融化", def:"to change from solid to liquid with heat", example:"The ice cream ___t in the sun.", pack:"ielts7", level:2},
  {word:"pour", ipa:"/pɔːr/", pos:"v.", zh:"倒；倾泻", def:"to make liquid flow out", example:"___ the milk into the glass.", pack:"ielts7", level:1},
  {word:"roast", ipa:"/roʊst/", pos:"v.", zh:"烤（肉）", def:"to cook meat or vegetables in an oven", example:"We ___ed a chicken for dinner.", pack:"ielts7", level:2},
  {word:"slice", ipa:"/slaɪs/", pos:"v./n.", zh:"切片", def:"to cut into thin pieces; a thin piece", example:"Cut the bread into thin ___.", pack:"ielts7", level:2},
  {word:"steam", ipa:"/stiːm/", pos:"v./n.", zh:"蒸；蒸汽", def:"to cook with hot water vapor; the vapor itself", example:"___ the vegetables for ten minutes.", pack:"ielts7", level:2},
  {word:"stir", ipa:"/stɜːr/", pos:"v.", zh:"搅拌", def:"to mix with a spoon in circles", example:"___ the soup slowly.", pack:"ielts7", level:2},
  {word:"lend", ipa:"/lend/", pos:"v.", zh:"借出", def:"to give something that must be returned", example:"Can you ___ me ten dollars?", pack:"ielts7", level:2},
  {word:"lose", ipa:"/luːz/", pos:"v.", zh:"丢失", def:"to not be able to find something", example:"Don't ___ your ticket.", pack:"ielts7", level:1},
  {word:"pack", ipa:"/pæk/", pos:"v.", zh:"打包", def:"to put things into a bag or box", example:"I need to ___ my suitcase.", pack:"ielts7", level:1},
  {word:"remind", ipa:"/rɪˈmaɪnd/", pos:"v.", zh:"提醒", def:"to help someone remember something", example:"Please ___ me to call her.", pack:"ielts7", level:2},
  {word:"repair", ipa:"/rɪˈper/", pos:"v.", zh:"修理", def:"to fix something broken", example:"He ___ed the leaking pipe.", pack:"ielts7", level:2},
  {word:"steal", ipa:"/stiːl/", pos:"v.", zh:"偷", def:"to take something that is not yours", example:"Someone ___t my bike.", pack:"ielts7", level:1},
  {word:"store", ipa:"/stɔːr/", pos:"v.", zh:"储存", def:"to keep something for later use", example:"___ the apples in a cool place.", pack:"ielts7", level:2},
  {word:"visit", ipa:"/ˈvɪzɪt/", pos:"v.", zh:"拜访；参观", def:"to go to see a person or place", example:"We ___ed our grandparents.", pack:"ielts7", level:1},
  {word:"wait", ipa:"/weɪt/", pos:"v.", zh:"等待", def:"to stay until something happens", example:"Please ___ for the bus.", pack:"ielts7", level:1},
  // ===BATCH-A-END===
);
