// ============================================================
// 雅思核心词包 · 第1批（IELTS Batch 1）
// 加载方式：在 index.html 中排在 words.js 之后引入（WORDS 是同一个数组，直接 push）。
// 字段与 words.js 一致；pack 标记词包名，页面里可按词包筛选出词范围。
// 约定：def 尽量用 A2-B1 的简单英文写；example 里的 ___ 就是本词。
// ============================================================
WORDS.push(
  // ---------- 学术 & 抽象 ----------
  {word:"adopt", ipa:"/əˈdɑːpt/", pos:"v.", zh:"采用；收养", def:"to start to use a new idea, method, or plan", example:"The school decided to ___ a new teaching method.", pack:"ielts1"},
  {word:"applicant", ipa:"/ˈæplɪkənt/", pos:"n.", zh:"申请人", def:"a person who asks officially for a job or a place at a school", example:"There were over fifty ___ for the job.", pack:"ielts1"},
  {word:"appoint", ipa:"/əˈpɔɪnt/", pos:"v.", zh:"任命；指定", def:"to choose someone for an important job or position", example:"They will ___ a new manager next week.", pack:"ielts1"},
  {word:"argument", ipa:"/ˈɑːrɡjəmənt/", pos:"n.", zh:"论点；争吵", def:"a reason you give to show that something is true; a loud talk with someone who disagrees", example:"Her main ___ was that the plan costs too much.", pack:"ielts1"},
  {word:"assignment", ipa:"/əˈsaɪnmənt/", pos:"n.", zh:"作业；任务", def:"a piece of work that a teacher gives you to do", example:"I have to finish my history ___ by Friday.", pack:"ielts1"},
  {word:"attitude", ipa:"/ˈætɪtuːd/", pos:"n.", zh:"态度；看法", def:"the way you think or feel about someone or something", example:"His ___ toward work has changed a lot.", pack:"ielts1"},
  {word:"authority", ipa:"/əˈθɔːrəti/", pos:"n.", zh:"权威；官方机构", def:"the power to give orders and make decisions", example:"The local ___ closed the old bridge.", pack:"ielts1"},
  {word:"awareness", ipa:"/əˈwernəs/", pos:"n.", zh:"意识；认识", def:"knowledge of a situation or problem", example:"We need to raise ___ about air pollution.", pack:"ielts1"},
  {word:"barrier", ipa:"/ˈbæriər/", pos:"n.", zh:"障碍；屏障", def:"a thing that stops you from moving or doing something", example:"Language is often a ___ for new immigrants.", pack:"ielts1"},
  {word:"behalf", ipa:"/bɪˈhæf/", pos:"n.", zh:"代表（on behalf of）", def:"for someone else, as their helper or speaker", example:"He signed the letter on ___ of the whole team.", pack:"ielts1"},
  {word:"campaign", ipa:"/kæmˈpeɪn/", pos:"n.", zh:"（宣传）活动；运动", def:"a planned set of actions to reach a goal", example:"They started a ___ to save the old library.", pack:"ielts1"},
  {word:"civilization", ipa:"/ˌsɪvələˈzeɪʃn/", pos:"n.", zh:"文明", def:"a society with its own culture and way of life", example:"Ancient Egypt was a great ___ in history.", pack:"ielts1"},
  {word:"commitment", ipa:"/kəˈmɪtmənt/", pos:"n.", zh:"承诺；投入", def:"a promise to do something; strong care for something", example:"Learning a language takes time and ___.", pack:"ielts1"},
  {word:"conclusion", ipa:"/kənˈkluːʒn/", pos:"n.", zh:"结论", def:"the final idea you have after thinking or testing", example:"The report ends with a clear ___ about the results.", pack:"ielts1"},
  {word:"confidence", ipa:"/ˈkɑːnfɪdəns/", pos:"n.", zh:"信心；信任", def:"the feeling that you can do something well", example:"Speaking in front of people needs ___.", pack:"ielts1"},
  {word:"convention", ipa:"/kənˈvenʃn/", pos:"n.", zh:"惯例；大会", def:"a usual and accepted way of doing things; a large meeting", example:"Shaking hands is a social ___ in many countries.", pack:"ielts1"},
  {word:"criticism", ipa:"/ˈkrɪtɪsɪzəm/", pos:"n.", zh:"批评；评论", def:"the act of saying what is wrong or bad about something", example:"The movie got good ___ from most reviewers.", pack:"ielts1"},
  {word:"debate", ipa:"/dɪˈbeɪt/", pos:"n./v.", zh:"辩论", def:"a serious talk about two different ideas", example:"There was a long ___ about the new law.", pack:"ielts1"},
  {word:"decrease", ipa:"/dɪˈkriːs/", pos:"v./n.", zh:"减少", def:"to become smaller in number or amount", example:"Sales usually ___ in winter.", pack:"ielts1"},
  {word:"democracy", ipa:"/dɪˈmɑːkrəsi/", pos:"n.", zh:"民主（制度）", def:"a system in which the people choose their leaders by voting", example:"The country became a ___ after the war.", pack:"ielts1"},
  {word:"deposit", ipa:"/dɪˈpɑːzɪt/", pos:"n./v.", zh:"存款；押金；放下", def:"money you pay to keep something; to put money into a bank", example:"You must pay a ___ to rent the apartment.", pack:"ielts1"},
  {word:"discrimination", ipa:"/dɪˌskrɪmɪˈneɪʃn/", pos:"n.", zh:"歧视；区别对待", def:"treating some people worse because of their race, age, or sex", example:"The law protects people against ___.", pack:"ielts1"},
  {word:"discipline", ipa:"/ˈdɪsəplɪn/", pos:"n.", zh:"纪律；自制力；学科", def:"the ability to follow rules and control yourself", example:"Learning to play the piano takes ___.", pack:"ielts1"},
  {word:"enthusiasm", ipa:"/ɪnˈθuːziæzəm/", pos:"n.", zh:"热情；热衷", def:"a strong feeling of interest and excitement", example:"The students showed great ___ for the project.", pack:"ielts1"},
  {word:"equality", ipa:"/iˈkwɑːləti/", pos:"n.", zh:"平等", def:"the state of having the same rights as other people", example:"The school supports ___ between boys and girls.", pack:"ielts1"},
  {word:"expenditure", ipa:"/ɪkˈspendɪtʃər/", pos:"n.", zh:"支出；花费", def:"the total money that a person or government spends", example:"The government cut its ___ on new roads.", pack:"ielts1"},
  {word:"expertise", ipa:"/ˌekspɜːrˈtiːz/", pos:"n.", zh:"专门知识；专长", def:"special skill or knowledge in a certain area", example:"We need someone with ___ in computer safety.", pack:"ielts1"},
  {word:"exposure", ipa:"/ɪkˈspoʊʒər/", pos:"n.", zh:"接触；暴露", def:"the state of being in a situation or near something", example:"Too much ___ to the sun is bad for your skin.", pack:"ielts1"},
  {word:"illegal", ipa:"/ɪˈliːɡl/", pos:"adj.", zh:"非法的", def:"not allowed by the law", example:"It is ___ to park here after midnight.", pack:"ielts1"},
  {word:"individual", ipa:"/ˌɪndɪˈvɪdʒuəl/", pos:"n./adj.", zh:"个人（的）；单独的", def:"one person, not a group", example:"Each ___ has a different learning style.", pack:"ielts1"},
  {word:"institution", ipa:"/ˌɪnstɪˈtuːʃn/", pos:"n.", zh:"机构；制度", def:"an organization such as a bank, school, or hospital", example:"The university is a famous educational ___.", pack:"ielts1"},
  {word:"intellectual", ipa:"/ˌɪntəˈlektʃuəl/", pos:"adj./n.", zh:"智力的；知识分子", def:"related to the ability to think and understand", example:"Chess is an ___ game.", pack:"ielts1"},
  {word:"internal", ipa:"/ɪnˈtɜːrnl/", pos:"adj.", zh:"内部的；体内的", def:"inside a person, country, or organization", example:"The company has an ___ problem with its computers.", pack:"ielts1"},
  {word:"investment", ipa:"/ɪnˈvestmənt/", pos:"n.", zh:"投资", def:"money put into something to get more money later", example:"Buying a house is a big ___.", pack:"ielts1"},
  {word:"journal", ipa:"/ˈdʒɜːrnl/", pos:"n.", zh:"期刊；日记", def:"a magazine for a special subject; a daily record", example:"She published her research in a medical ___.", pack:"ielts1"},
  {word:"label", ipa:"/ˈleɪbl/", pos:"n./v.", zh:"标签；贴标签", def:"a small piece of paper that tells what something is", example:"Read the ___ on the bottle before you use it.", pack:"ielts1"},
  {word:"logical", ipa:"/ˈlɑːdʒɪkl/", pos:"adj.", zh:"合乎逻辑的", def:"based on clear and correct thinking", example:"There is a ___ reason for every rule.", pack:"ielts1"},
  {word:"majority", ipa:"/məˈdʒɔːrəti/", pos:"n.", zh:"大多数", def:"most of the people or things in a group", example:"The ___ of students live near the school.", pack:"ielts1"},
  {word:"maximize", ipa:"/ˈmæksɪmaɪz/", pos:"v.", zh:"最大化", def:"to make something as large or great as possible", example:"Farmers use new ways to ___ their crops.", pack:"ielts1"},
  {word:"minority", ipa:"/maɪˈnɔːrəti/", pos:"n.", zh:"少数（群体）", def:"a small part of a group; a group different from most people", example:"Only a ___ of workers agreed with the change.", pack:"ielts1"},
  {word:"moral", ipa:"/ˈmɔːrəl/", pos:"adj./n.", zh:"道德的；道德", def:"about what is right and wrong", example:"Parents are the first ___ teachers of their children.", pack:"ielts1"},
  {word:"nevertheless", ipa:"/ˌnevərðəˈles/", pos:"adv.", zh:"然而；尽管如此", def:"in spite of what was just said", example:"The weather was bad. ___, we went hiking.", pack:"ielts1"},
  {word:"obligation", ipa:"/ˌɑːblɪˈɡeɪʃn/", pos:"n.", zh:"义务；责任", def:"something you must do because of rules or duty", example:"We have an ___ to protect the environment.", pack:"ielts1"},
  {word:"occupation", ipa:"/ˌɑːkjuˈpeɪʃn/", pos:"n.", zh:"职业；占用", def:"the job that you do", example:"Please write your ___ on the form.", pack:"ielts1"},
  {word:"outcome", ipa:"/ˈaʊtkʌm/", pos:"n.", zh:"结果；后果", def:"the final result of an action or event", example:"The ___ of the meeting was very positive.", pack:"ielts1"},
  {word:"overall", ipa:"/ˌoʊvərˈɔːl/", pos:"adj./adv.", zh:"总体的（地）", def:"considering everything together", example:"The ___ quality of the food was good.", pack:"ielts1"},
  {word:"participate", ipa:"/pɑːrˈtɪsɪpeɪt/", pos:"v.", zh:"参加；参与", def:"to take part in an activity or event", example:"More girls now ___ in sports.", pack:"ielts1"},
  {word:"particular", ipa:"/pərˈtɪkjələr/", pos:"adj.", zh:"特定的；尤其的", def:"one specific thing, not any other", example:"Is there a ___ reason you asked that?", pack:"ielts1"},
  {word:"passive", ipa:"/ˈpæsɪv/", pos:"adj.", zh:"被动的", def:"accepting things without trying to change them", example:"She was not ___; she asked many questions.", pack:"ielts1"},
  {word:"permanent", ipa:"/ˈpɜːrmənənt/", pos:"adj.", zh:"永久的", def:"lasting for a long time or forever", example:"He found a ___ job in the city.", pack:"ielts1"},
  {word:"policy", ipa:"/ˈpɑːləsi/", pos:"n.", zh:"政策；方针", def:"a plan or rule that a government or company follows", example:"The new ___ allows workers to work from home.", pack:"ielts1"},
  {word:"poverty", ipa:"/ˈpɑːvərti/", pos:"n.", zh:"贫穷", def:"the state of not having enough money for basic needs", example:"Many children in that area live in ___.", pack:"ielts1"},
  {word:"precise", ipa:"/prɪˈsaɪs/", pos:"adj.", zh:"精确的", def:"exact and clear, with no mistakes", example:"Please give me the ___ time of the meeting.", pack:"ielts1"},
  {word:"predict", ipa:"/prɪˈdɪkt/", pos:"v.", zh:"预测", def:"to say what will happen in the future", example:"It is hard to ___ the weather in spring.", pack:"ielts1"},
  {word:"priority", ipa:"/praɪˈɔːrəti/", pos:"n.", zh:"优先（事项）", def:"something that is more important than other things", example:"Health should be the first ___ for everyone.", pack:"ielts1"},
  {word:"privilege", ipa:"/ˈprɪvəlɪdʒ/", pos:"n.", zh:"特权；荣幸", def:"a special right that only some people have", example:"Driving is a ___, not a right.", pack:"ielts1"},
  {word:"procedure", ipa:"/prəˈsiːdʒər/", pos:"n.", zh:"程序；步骤", def:"the official way of doing something", example:"Follow the safety ___ before you start.", pack:"ielts1"},
  {word:"proceed", ipa:"/proʊˈsiːd/", pos:"v.", zh:"继续进行", def:"to continue doing something after a stop", example:"The meeting will ___ after lunch.", pack:"ielts1"},
  {word:"profession", ipa:"/prəˈfeʃn/", pos:"n.", zh:"职业（尤指专业）", def:"a job that needs special study and training", example:"Teaching is a respected ___.", pack:"ielts1"},
  {word:"promotion", ipa:"/prəˈmoʊʃn/", pos:"n.", zh:"晋升；促销", def:"a move to a higher position; activity to sell more", example:"She got a ___ after two years of hard work.", pack:"ielts1"},
  {word:"property", ipa:"/ˈprɑːpərti/", pos:"n.", zh:"财产；房产", def:"something that you own, especially land or buildings", example:"Buying ___ in big cities is expensive.", pack:"ielts1"},
  {word:"prosperity", ipa:"/prɑːˈsperəti/", pos:"n.", zh:"繁荣；兴旺", def:"the state of being rich and successful", example:"The country enjoyed peace and ___ for many years.", pack:"ielts1"},
  {word:"purchase", ipa:"/ˈpɜːrtʃəs/", pos:"v./n.", zh:"购买", def:"to buy something", example:"You can ___ tickets online.", pack:"ielts1"},
  {word:"quantity", ipa:"/ˈkwɑːntəti/", pos:"n.", zh:"数量", def:"an amount or number of something", example:"The shop sells large ___ of rice.", pack:"ielts1"},
  {word:"realistic", ipa:"/ˌriːəˈlɪstɪk/", pos:"adj.", zh:"现实的；切实可行的", def:"accepting things as they really are; possible to do", example:"Set a ___ goal that you can reach.", pack:"ielts1"},
  {word:"reference", ipa:"/ˈrefrəns/", pos:"n.", zh:"参考；推荐信", def:"the act of looking at information; a letter about your ability", example:"Keep this book as a quick ___ for grammar.", pack:"ielts1"},
  {word:"reform", ipa:"/rɪˈfɔːrm/", pos:"n./v.", zh:"改革", def:"a change that makes a system better", example:"The new ___ changed the way schools are run.", pack:"ielts1"},
  {word:"region", ipa:"/ˈriːdʒən/", pos:"n.", zh:"地区；区域", def:"a large area of a country or the world", example:"This ___ is famous for its tea.", pack:"ielts1"},
  {word:"reluctant", ipa:"/rɪˈlʌktənt/", pos:"adj.", zh:"不情愿的", def:"not wanting to do something", example:"He was ___ to leave his hometown.", pack:"ielts1"},
  {word:"remark", ipa:"/rɪˈmɑːrk/", pos:"n./v.", zh:"评论；说起", def:"something you say about a person or thing", example:"Her ___ about the movie made us laugh.", pack:"ielts1"},
  {word:"reputation", ipa:"/ˌrepjuˈteɪʃn/", pos:"n.", zh:"名声；名誉", def:"the opinion people have about someone or something", example:"The hotel has a good ___ for service.", pack:"ielts1"},
  {word:"resource", ipa:"/ˈriːsɔːrs/", pos:"n.", zh:"资源", def:"things such as money, oil, or water that help you live or work", example:"The country is rich in natural ___.", pack:"ielts1"},
  {word:"responsibility", ipa:"/rɪˌspɑːnsəˈbɪləti/", pos:"n.", zh:"责任", def:"a duty to do something well", example:"Parents have a ___ to care for their children.", pack:"ielts1"},
  {word:"revenue", ipa:"/ˈrevənuː/", pos:"n.", zh:"（政府、公司的）收入", def:"the money that a government or business gets", example:"Tax ___ will pay for the new hospital.", pack:"ielts1"},
  {word:"revolution", ipa:"/ˌrevəˈluːʃn/", pos:"n.", zh:"革命；重大变革", def:"a complete change in a system or way of life", example:"The Internet caused a ___ in communication.", pack:"ielts1"},
  {word:"satisfaction", ipa:"/ˌsætɪsˈfækʃn/", pos:"n.", zh:"满意；满足", def:"the good feeling you get when something goes well", example:"He gets great ___ from helping others.", pack:"ielts1"},
  {word:"secure", ipa:"/sɪˈkjʊr/", pos:"adj./v.", zh:"安全的；使安全", def:"safe and protected; to make something safe", example:"Make sure your passwords are ___.", pack:"ielts1"},
  {word:"seek", ipa:"/siːk/", pos:"v.", zh:"寻求；寻找", def:"to try to find or get something", example:"Many people ___ advice before buying a house.", pack:"ielts1"},
  {word:"series", ipa:"/ˈsɪriːz/", pos:"n.", zh:"系列；连续", def:"several things of the same kind that come one after another", example:"She watched a ___ of talks about space.", pack:"ielts1"},
  {word:"session", ipa:"/ˈseʃn/", pos:"n.", zh:"一场（活动）；会议", def:"a period of time for a particular activity", example:"The training ___ lasts two hours.", pack:"ielts1"},
  {word:"statistics", ipa:"/stəˈtɪstɪks/", pos:"n.", zh:"统计（数字）；统计学", def:"numbers that show facts about something", example:"The ___ show that fewer people smoke now.", pack:"ielts1"},
  {word:"status", ipa:"/ˈsteɪtəs/", pos:"n.", zh:"地位；状态", def:"the position or situation of a person or thing", example:"Her ___ at work changed after the promotion.", pack:"ielts1"},
  {word:"survey", ipa:"/ˈsɜːrveɪ/", pos:"n./v.", zh:"调查；测量", def:"a set of questions to learn people's opinions", example:"The ___ found that most people cycle to work.", pack:"ielts1"},
  {word:"symbol", ipa:"/ˈsɪmbl/", pos:"n.", zh:"象征；符号", def:"a sign that means something else", example:"The dove is a ___ of peace.", pack:"ielts1"},
  {word:"target", ipa:"/ˈtɑːrɡɪt/", pos:"n./v.", zh:"目标；以…为目标", def:"a result that you try to reach", example:"Our ___ is to finish the work by Friday.", pack:"ielts1"},
  {word:"tendency", ipa:"/ˈtendənsi/", pos:"n.", zh:"倾向；趋势", def:"a way that someone often behaves", example:"He has a ___ to speak too quickly.", pack:"ielts1"},
  {word:"theory", ipa:"/ˈθɪri/", pos:"n.", zh:"理论", def:"an idea that explains why something happens", example:"The ___ of gravity explains falling objects.", pack:"ielts1"},
  {word:"tolerance", ipa:"/ˈtɑːlərəns/", pos:"n.", zh:"宽容；忍耐", def:"the ability to accept different ideas or people", example:"We should show ___ to people from other cultures.", pack:"ielts1"},
  {word:"trait", ipa:"/treɪt/", pos:"n.", zh:"特征；特点", def:"a quality that makes a person or thing different", example:"Patience is a useful ___ for teachers.", pack:"ielts1"},
  {word:"trend", ipa:"/trend/", pos:"n.", zh:"趋势；潮流", def:"the way something is changing or developing", example:"There is a ___ toward working from home.", pack:"ielts1"},
  {word:"venture", ipa:"/ˈventʃər/", pos:"n./v.", zh:"（有风险的）企业；冒险做", def:"a new business idea with some risk", example:"Starting a small shop is a risky ___.", pack:"ielts1"},
  {word:"victim", ipa:"/ˈvɪktɪm/", pos:"n.", zh:"受害者", def:"a person who is hurt by a crime or bad event", example:"The ___ of the fire lost everything.", pack:"ielts1"},
  {word:"volunteer", ipa:"/ˌvɑːlənˈtɪr/", pos:"n./v.", zh:"志愿者；自愿做", def:"a person who works without pay; to offer to do something", example:"She works as a ___ at the animal shelter.", pack:"ielts1"},
  {word:"welfare", ipa:"/ˈwelfer/", pos:"n.", zh:"福利；幸福", def:"the health and happiness of people; help from the state", example:"The government spends a lot on child ___.", pack:"ielts1"},
  {word:"withdraw", ipa:"/wɪðˈdrɔː/", pos:"v.", zh:"取（款）；撤回", def:"to take money out of a bank; to take back something you said", example:"I need to ___ some money from the bank.", pack:"ielts1"},
  {word:"zone", ipa:"/zoʊn/", pos:"n.", zh:"区域；地带", def:"an area that is used for a special purpose", example:"This is a no-parking ___.", pack:"ielts1"},

  // ---------- 环境 & 社会 ----------
  {word:"biodiversity", ipa:"/ˌbaɪoʊdaɪˈvɜːrsəti/", pos:"n.", zh:"生物多样性", def:"the number of different plants and animals in a place", example:"Cutting down forests reduces ___.", pack:"ielts1"},
  {word:"conservation", ipa:"/ˌkɑːnsərˈveɪʃn/", pos:"n.", zh:"（资源）保护", def:"the act of protecting nature and wild things", example:"The park works for the ___ of rare birds.", pack:"ielts1"},
  {word:"contamination", ipa:"/kənˌtæmɪˈneɪʃn/", pos:"n.", zh:"污染（有害物）", def:"the state of having harmful dirty or dangerous things mixed in", example:"Water ___ is a serious health problem.", pack:"ielts1"},
  {word:"deforestation", ipa:"/ˌdiːfɔːrɪˈsteɪʃn/", pos:"n.", zh:"滥伐森林", def:"the cutting down of forests on a large scale", example:"___ causes animals to lose their homes.", pack:"ielts1"},
  {word:"drought", ipa:"/draʊt/", pos:"n.", zh:"干旱", def:"a long time with no rain", example:"The ___ killed most of the crops.", pack:"ielts1"},
  {word:"ecosystem", ipa:"/ˈiːkoʊsɪstəm/", pos:"n.", zh:"生态系统", def:"all the living things in a place and how they work together", example:"Coral reefs are a fragile ___.", pack:"ielts1"},
  {word:"emission", ipa:"/ɪˈmɪʃn/", pos:"n.", zh:"（废气）排放", def:"gas or smoke that is sent into the air", example:"Cars must reduce their ___ of CO2.", pack:"ielts1"},
  {word:"fertile", ipa:"/ˈfɜːrtl/", pos:"adj.", zh:"肥沃的；能生育的", def:"(of land) able to grow many plants; able to have babies", example:"The valley has ___ soil for farming.", pack:"ielts1"},
  {word:"fossil", ipa:"/ˈfɑːsl/", pos:"n.", zh:"化石", def:"the shape of an old animal or plant in rock", example:"They found a dinosaur ___ near the river.", pack:"ielts1"},
  {word:"habitat", ipa:"/ˈhæbɪtæt/", pos:"n.", zh:"（动物的）栖息地", def:"the natural home of a plant or animal", example:"Pollution destroys the ___ of many fish.", pack:"ielts1"},
  {word:"harvest", ipa:"/ˈhɑːrvɪst/", pos:"n./v.", zh:"收获；收割", def:"the time when crops are collected", example:"Farmers work hard during the ___ season.", pack:"ielts1"},
  {word:"hazard", ipa:"/ˈhæzərd/", pos:"n.", zh:"危险；隐患", def:"something that can cause danger or harm", example:"Wet floors are a ___ in the kitchen.", pack:"ielts1"},
  {word:"irrigation", ipa:"/ˌɪrɪˈɡeɪʃn/", pos:"n.", zh:"灌溉", def:"the system of bringing water to dry land", example:"___ helps farmers grow crops in the desert.", pack:"ielts1"},
  {word:"marine", ipa:"/məˈriːn/", pos:"adj.", zh:"海洋的", def:"related to the sea and the life in it", example:"The ___ life near the coast is very rich.", pack:"ielts1"},
  {word:"nuclear", ipa:"/ˈnuːkliər/", pos:"adj.", zh:"核能的；核的", def:"related to the power made from atoms", example:"Some countries use ___ energy to make electricity.", pack:"ielts1"},
  {word:"organic", ipa:"/ɔːrˈɡænɪk/", pos:"adj.", zh:"有机的", def:"grown without artificial chemicals", example:"She only buys ___ vegetables.", pack:"ielts1"},
  {word:"pollutant", ipa:"/pəˈluːtənt/", pos:"n.", zh:"污染物", def:"a substance that makes air, water, or soil dirty", example:"Factories release ___ into the river.", pack:"ielts1"},
  {word:"recycle", ipa:"/ˌriːˈsaɪkl/", pos:"v.", zh:"回收利用", def:"to use old materials again to make new things", example:"We should ___ paper and glass.", pack:"ielts1"},
  {word:"renewable", ipa:"/rɪˈnuːəbl/", pos:"adj.", zh:"可再生的", def:"(of energy) able to be replaced naturally, like sun and wind", example:"Solar power is a clean and ___ energy.", pack:"ielts1"},
  {word:"sustainable", ipa:"/səˈsteɪnəbl/", pos:"adj.", zh:"可持续的", def:"able to continue without harming nature for the future", example:"We need ___ ways to grow food.", pack:"ielts1"},
  {word:"vegetation", ipa:"/ˌvedʒəˈteɪʃn/", pos:"n.", zh:"（总称）植被", def:"all the plants in a place", example:"The hills are covered with thick ___.", pack:"ielts1"},
  {word:"waste", ipa:"/weɪst/", pos:"n./v.", zh:"浪费；废物", def:"to use too much without care; things that are thrown away", example:"Please do not ___ food.", pack:"ielts1"},
  {word:"wildlife", ipa:"/ˈwaɪldlaɪf/", pos:"n.", zh:"野生动物", def:"animals and plants that live wild in nature", example:"The photo shows ___ in the national park.", pack:"ielts1"},

  // ---------- 城市 & 交通 & 居住 ----------
  {word:"accommodation", ipa:"/əˌkɑːməˈdeɪʃn/", pos:"n.", zh:"住宿；住处", def:"a place to live or stay", example:"The university helps students find ___.", pack:"ielts1"},
  {word:"campus", ipa:"/ˈkæmpəs/", pos:"n.", zh:"校园", def:"the land and buildings of a university or college", example:"The new library is in the center of the ___.", pack:"ielts1"},
  {word:"commute", ipa:"/kəˈmjuːt/", pos:"v./n.", zh:"通勤", def:"to travel regularly between home and work", example:"She ___s to the city by train every day.", pack:"ielts1"},
  {word:"congestion", ipa:"/kənˈdʒestʃən/", pos:"n.", zh:"（交通）拥堵", def:"too many cars on the road, so traffic moves slowly", example:"The morning ___ makes drivers late.", pack:"ielts1"},
  {word:"dense", ipa:"/dens/", pos:"adj.", zh:"密集的；稠密的", def:"with many things close together", example:"The city center has ___ traffic.", pack:"ielts1"},
  {word:"facility", ipa:"/fəˈsɪləti/", pos:"n.", zh:"设施", def:"a building or equipment for a special purpose", example:"The gym is a popular sports ___ on campus.", pack:"ielts1"},
  {word:"household", ipa:"/ˈhaʊshoʊld/", pos:"n.", zh:"家庭（户）", def:"all the people who live in one house", example:"The average ___ uses a lot of electricity.", pack:"ielts1"},
  {word:"housing", ipa:"/ˈhaʊzɪŋ/", pos:"n.", zh:"住房（总称）", def:"houses and apartments for people to live in", example:"The city needs more ___ for young workers.", pack:"ielts1"},
  {word:"inhabitant", ipa:"/ɪnˈhæbɪtənt/", pos:"n.", zh:"居民；栖居者", def:"a person or animal that lives in a place", example:"The town has about ten thousand ___.", pack:"ielts1"},
  {word:"infrastructure", ipa:"/ˈɪnfrəstrʌktʃər/", pos:"n.", zh:"基础设施", def:"basic systems such as roads, power, and water", example:"Good ___ is important for business.", pack:"ielts1"},
  {word:"metropolitan", ipa:"/ˌmetrəˈpɑːlɪtən/", pos:"adj.", zh:"大都市的", def:"related to a large city with its suburbs", example:"The ___ area has over ten million people.", pack:"ielts1"},
  {word:"pedestrian", ipa:"/pəˈdestriən/", pos:"n.", zh:"行人", def:"a person who walks on the street", example:"The bridge was built for ___ only.", pack:"ielts1"},
  {word:"resident", ipa:"/ˈrezɪdənt/", pos:"n.", zh:"居民", def:"a person who lives in a particular place", example:"The ___ of this street want more trees.", pack:"ielts1"},
  {word:"rural", ipa:"/ˈrʊrəl/", pos:"adj.", zh:"农村的", def:"related to the countryside, not the city", example:"He grew up in a small ___ village.", pack:"ielts1"},
  {word:"settlement", ipa:"/ˈsetlmənt/", pos:"n.", zh:"定居点；解决", def:"a small place where people live; an official end to a problem", example:"The first ___ in the area was near the river.", pack:"ielts1"},
  {word:"spacious", ipa:"/ˈspeɪʃəs/", pos:"adj.", zh:"宽敞的", def:"with a lot of space inside", example:"They moved to a more ___ apartment.", pack:"ielts1"},
  {word:"suburb", ipa:"/ˈsʌbɜːrb/", pos:"n.", zh:"郊区", def:"an area outside the center of a city where people live", example:"Many families live in the ___ and drive to work.", pack:"ielts1"},
  {word:"tenant", ipa:"/ˈtenənt/", pos:"n.", zh:"房客；租户", def:"a person who pays to live in or use a place", example:"The ___ pays rent at the start of each month.", pack:"ielts1"},
  {word:"transport", ipa:"/ˈtrænspɔːrt/", pos:"n./v.", zh:"交通；运输", def:"the moving of people or goods from one place to another", example:"Public ___ in the city is cheap and fast.", pack:"ielts1"},
  {word:"urban", ipa:"/ˈɜːrbən/", pos:"adj.", zh:"城市的", def:"related to a city or town", example:"___ life can be exciting but stressful.", pack:"ielts1"},

  // ---------- 工作 & 经济 ----------
  {word:"career", ipa:"/kəˈrɪr/", pos:"n.", zh:"职业；事业", def:"the job or work you do for many years", example:"She chose teaching as her ___.", pack:"ielts1"},
  {word:"commerce", ipa:"/ˈkɑːmɜːrs/", pos:"n.", zh:"商业；贸易", def:"the buying and selling of goods", example:"The Internet changed global ___.", pack:"ielts1"},
  {word:"consumer", ipa:"/kənˈsuːmər/", pos:"n.", zh:"消费者", def:"a person who buys things to use", example:"The new phone was popular with ___.", pack:"ielts1"},
  {word:"consumption", ipa:"/kənˈsʌmpʃn/", pos:"n.", zh:"消费；消耗", def:"the use of food, energy, or goods", example:"High energy ___ increases your bill.", pack:"ielts1"},
  {word:"corporation", ipa:"/ˌkɔːrpəˈreɪʃn/", pos:"n.", zh:"大公司", def:"a large company or group of companies", example:"She works for an international ___.", pack:"ielts1"},
  {word:"employee", ipa:"/ɪmˈplɔɪiː/", pos:"n.", zh:"雇员；员工", def:"a person who works for someone else", example:"Every ___ gets two weeks of holiday.", pack:"ielts1"},
  {word:"employer", ipa:"/ɪmˈplɔɪər/", pos:"n.", zh:"雇主", def:"a person or company that gives people work", example:"Her ___ lets her work from home.", pack:"ielts1"},
  {word:"employment", ipa:"/ɪmˈplɔɪmənt/", pos:"n.", zh:"就业；雇用", def:"the state of having a paid job", example:"The new factory will bring ___ to the town.", pack:"ielts1"},
  {word:"enterprise", ipa:"/ˈentərpraɪz/", pos:"n.", zh:"企业；事业", def:"a business or company", example:"Small ___ create most new jobs.", pack:"ielts1"},
  {word:"entrepreneur", ipa:"/ˌɑːntrəprəˈnɜːr/", pos:"n.", zh:"创业者", def:"a person who starts and runs their own business", example:"The young ___ built his first app at 20.", pack:"ielts1"},
  {word:"expense", ipa:"/ɪkˈspens/", pos:"n.", zh:"花费；开销", def:"money that you spend on something", example:"The trip was worth the ___.", pack:"ielts1"},
  {word:"finance", ipa:"/ˈfaɪnæns/", pos:"n./v.", zh:"金融；资金；为…提供资金", def:"money and how it is managed", example:"He studied ___ at university.", pack:"ielts1"},
  {word:"income", ipa:"/ˈɪnkʌm/", pos:"n.", zh:"收入", def:"money you get from work or investments", example:"Her ___ is higher than last year.", pack:"ielts1"},
  {word:"inflation", ipa:"/ɪnˈfleɪʃn/", pos:"n.", zh:"通货膨胀", def:"the rise in prices over time", example:"___ made food more expensive this year.", pack:"ielts1"},
  {word:"invest", ipa:"/ɪnˈvest/", pos:"v.", zh:"投资", def:"to put money into something to make more money later", example:"He plans to ___ in a small business.", pack:"ielts1"},
  {word:"labor", ipa:"/ˈleɪbər/", pos:"n.", zh:"劳动；劳动力", def:"work, especially physical work; all the workers", example:"The new machine saves a lot of ___.", pack:"ielts1"},
  {word:"loan", ipa:"/loʊn/", pos:"n.", zh:"贷款；借款", def:"money that you borrow and must pay back", example:"They took out a ___ to buy the car.", pack:"ielts1"},
  {word:"manufacture", ipa:"/ˌmænjuˈfæktʃər/", pos:"v./n.", zh:"制造", def:"to make goods in large numbers in a factory", example:"The company ___s parts for cars.", pack:"ielts1"},
  {word:"output", ipa:"/ˈaʊtpʊt/", pos:"n.", zh:"产量", def:"the amount that a person or machine produces", example:"The factory increased its ___ this year.", pack:"ielts1"},
  {word:"pension", ipa:"/ˈpenʃn/", pos:"n.", zh:"养老金", def:"money paid to someone after they stop working because of age", example:"He receives a small ___ every month.", pack:"ielts1"},
  {word:"profit", ipa:"/ˈprɑːfɪt/", pos:"n.", zh:"利润", def:"the money you keep after paying all costs", example:"The store made a big ___ last year.", pack:"ielts1"},
  {word:"recruit", ipa:"/rɪˈkruːt/", pos:"v./n.", zh:"招聘；招募；新成员", def:"to find new people to work for a company", example:"The company is trying to ___ more engineers.", pack:"ielts1"},
  {word:"retail", ipa:"/ˈriːteɪl/", pos:"n.", zh:"零售", def:"the selling of goods directly to people in shops", example:"Online ___ is growing fast.", pack:"ielts1"},
  {word:"retire", ipa:"/rɪˈtaɪər/", pos:"v.", zh:"退休", def:"to stop working because of age", example:"My father will ___ at sixty-five.", pack:"ielts1"},
  {word:"salary", ipa:"/ˈsæləri/", pos:"n.", zh:"薪水", def:"the money you get every month for your job", example:"The job offers a good ___ and health care.", pack:"ielts1"},
  {word:"staff", ipa:"/stæf/", pos:"n.", zh:"全体员工", def:"all the people who work in a place", example:"The ___ at this hotel are very friendly.", pack:"ielts1"},
  {word:"tariff", ipa:"/ˈtærɪf/", pos:"n.", zh:"关税", def:"a tax on goods coming into a country", example:"The new ___ made imports more expensive.", pack:"ielts1"},
  {word:"unemployment", ipa:"/ˌʌnɪmˈplɔɪmənt/", pos:"n.", zh:"失业（率）", def:"the state of having no job", example:"___ rose during the economic crisis.", pack:"ielts1"},
  {word:"wage", ipa:"/weɪdʒ/", pos:"n.", zh:"（按小时/周付的）工资", def:"money you get for work, paid by the hour or week", example:"The workers asked for a higher ___.", pack:"ielts1"},
  {word:"workforce", ipa:"/ˈwɜːrkfɔːrs/", pos:"n.", zh:"劳动力；员工总数", def:"all the people who work in a country or company", example:"The ___ in this area is getting older.", pack:"ielts1"},

  // ---------- 教育 & 健康 & 技术 ----------
  {word:"academic", ipa:"/ˌækəˈdemɪk/", pos:"adj.", zh:"学术的", def:"related to study, schools, or universities", example:"She has a strong ___ background in science.", pack:"ielts1"},
  {word:"compulsory", ipa:"/kəmˈpʌlsəri/", pos:"adj.", zh:"义务的；强制的", def:"that must be done by law or rule", example:"School is ___ for children until age sixteen.", pack:"ielts1"},
  {word:"curriculum", ipa:"/kəˈrɪkjələm/", pos:"n.", zh:"课程（体系）", def:"all the subjects taught at a school", example:"Sports are part of the school ___.", pack:"ielts1"},
  {word:"diploma", ipa:"/dɪˈploʊmə/", pos:"n.", zh:"文凭；毕业证书", def:"an official paper showing you finished a course", example:"She received a ___ in design.", pack:"ielts1"},
  {word:"graduate", ipa:"/ˈɡrædʒuət/", pos:"n./v.", zh:"毕业生；毕业", def:"a person who finished a course; to finish school", example:"He is a ___ of Oxford University.", pack:"ielts1"},
  {word:"literacy", ipa:"/ˈlɪtərəsi/", pos:"n.", zh:"读写能力", def:"the ability to read and write", example:"The program helps improve ___ in poor areas.", pack:"ielts1"},
  {word:"plagiarism", ipa:"/ˈpleɪdʒərɪzəm/", pos:"n.", zh:"剽窃；抄袭", def:"copying someone else's work as if it were yours", example:"Using AI to write your essay can be seen as ___.", pack:"ielts1"},
  {word:"qualification", ipa:"/ˌkwɑːlɪfɪˈkeɪʃn/", pos:"n.", zh:"资格；资历", def:"a degree or test result that shows you can do a job", example:"Good English is a ___ for this job.", pack:"ielts1"},
  {word:"scholarship", ipa:"/ˈskɑːlərʃɪp/", pos:"n.", zh:"奖学金", def:"money given to help a student pay for study", example:"She won a ___ to study abroad.", pack:"ielts1"},
  {word:"syllabus", ipa:"/ˈsɪləbəs/", pos:"n.", zh:"教学大纲", def:"a list of subjects to be studied in a course", example:"Grammar is on the first-year ___.", pack:"ielts1"},
  {word:"thesis", ipa:"/ˈθiːsɪs/", pos:"n.", zh:"论文", def:"a long piece of writing for a university degree", example:"She is writing her ___ on climate change.", pack:"ielts1"},
  {word:"tuition", ipa:"/tuˈɪʃn/", pos:"n.", zh:"学费；教学", def:"the money you pay for teaching", example:"University ___ has risen in recent years.", pack:"ielts1"},
  {word:"tutor", ipa:"/ˈtuːtər/", pos:"n.", zh:"导师；家教", def:"a teacher who helps one student or a small group", example:"He works as a ___ for math students.", pack:"ielts1"},
  {word:"undergraduate", ipa:"/ˌʌndərˈɡrædʒuət/", pos:"n.", zh:"本科生", def:"a student working for a first degree at university", example:"Most ___ live on campus in their first year.", pack:"ielts1"},
  {word:"vocational", ipa:"/voʊˈkeɪʃənl/", pos:"adj.", zh:"职业的；职业培训的", def:"teaching skills for a particular job", example:"___ training helps people find work quickly.", pack:"ielts1"},

  {word:"chronic", ipa:"/ˈkrɑːnɪk/", pos:"adj.", zh:"慢性的；长期的", def:"(of an illness) lasting a very long time", example:"He suffers from ___ back pain.", pack:"ielts1"},
  {word:"diagnosis", ipa:"/ˌdaɪəɡˈnoʊsɪs/", pos:"n.", zh:"诊断", def:"the process of finding what illness someone has", example:"Early ___ can save lives.", pack:"ielts1"},
  {word:"epidemic", ipa:"/ˌepɪˈdemɪk/", pos:"n.", zh:"流行病（大范围）", def:"a disease that spreads to many people quickly", example:"The city fought a flu ___ last winter.", pack:"ielts1"},
  {word:"hygiene", ipa:"/ˈhaɪdʒiːn/", pos:"n.", zh:"卫生", def:"the practice of keeping yourself and things clean", example:"Good ___ stops germs from spreading.", pack:"ielts1"},
  {word:"immune", ipa:"/ɪˈmjuːn/", pos:"adj.", zh:"免疫的", def:"safe from a disease because your body can fight it", example:"After the vaccine, she became ___ to the virus.", pack:"ielts1"},
  {word:"infection", ipa:"/ɪnˈfekʃn/", pos:"n.", zh:"感染；传染", def:"a disease caused by germs entering the body", example:"Wash your hands to prevent ___.", pack:"ielts1"},
  {word:"nutrition", ipa:"/nuˈtrɪʃn/", pos:"n.", zh:"营养", def:"the food you eat and how your body uses it", example:"Good ___ is important for growing children.", pack:"ielts1"},
  {word:"obesity", ipa:"/oʊˈbiːsəti/", pos:"n.", zh:"肥胖症", def:"the state of being too fat in an unhealthy way", example:"___ is a growing problem among young people.", pack:"ielts1"},
  {word:"surgery", ipa:"/ˈsɜːrdʒəri/", pos:"n.", zh:"外科手术", def:"a medical operation on the body", example:"The doctor performed ___ on her knee.", pack:"ielts1"},
  {word:"therapy", ipa:"/ˈθerəpi/", pos:"n.", zh:"治疗；疗法", def:"treatment that helps a person get better", example:"He goes to ___ for his injured arm.", pack:"ielts1"},
  {word:"vaccine", ipa:"/vækˈsiːn/", pos:"n.", zh:"疫苗", def:"a medicine that stops you from getting a disease", example:"Scientists developed a ___ for the virus.", pack:"ielts1"},

  {word:"artificial", ipa:"/ˌɑːrtɪˈfɪʃl/", pos:"adj.", zh:"人造的；人工的", def:"made by people, not natural", example:"___ intelligence can write simple reports.", pack:"ielts1"},
  {word:"device", ipa:"/dɪˈvaɪs/", pos:"n.", zh:"设备；装置", def:"a machine or tool made for a special purpose", example:"Turn off all electronic ___ on the plane.", pack:"ielts1"},
  {word:"digital", ipa:"/ˈdɪdʒɪtl/", pos:"adj.", zh:"数字的；数码的", def:"using or storing information as numbers, especially by computers", example:"The school moved to ___ books.", pack:"ielts1"},
  {word:"download", ipa:"/ˌdaʊnˈloʊd/", pos:"v./n.", zh:"下载", def:"to get a file from the Internet onto your device", example:"You can ___ the app for free.", pack:"ielts1"},
  {word:"innovation", ipa:"/ˌɪnəˈveɪʃn/", pos:"n.", zh:"创新", def:"a new idea, method, or invention", example:"The phone's camera is a real ___.", pack:"ielts1"},
  {word:"install", ipa:"/ɪnˈstɔːl/", pos:"v.", zh:"安装", def:"to put a machine or program in place for use", example:"We need to ___ new software on the computer.", pack:"ielts1"},
  {word:"online", ipa:"/ˌɑːnˈlaɪn/", pos:"adj./adv.", zh:"在线的", def:"connected to the Internet", example:"You can buy tickets ___ now.", pack:"ielts1"},
  {word:"patent", ipa:"/ˈpætnt/", pos:"n.", zh:"专利", def:"an official right to make or sell a new invention", example:"The company owns a ___ for the design.", pack:"ielts1"},
  {word:"software", ipa:"/ˈsɔːftwer/", pos:"n.", zh:"软件", def:"the programs that make a computer work", example:"You need special ___ to edit videos.", pack:"ielts1"},
);

// ============================================================
// 频率/难度分层（沿用 words.js 的 level 字段：1基础 / 2进阶 / 3高阶 / 4学术）
// words.js 已按 level 1–4 分好；本批雅思词统一补 level：
//   高频必背（能主动用，口语/写作常用）→ level 2
//   学术低频（6 分可缓，主要影响阅读）→ level 3
// 页面「设置 → 学习难度上限」默认 2：只背 level≤2 的高频词，学完再放开。
// ============================================================
const IELTS1_LEVEL3 = new Set([
  // 学术 & 抽象（低频）
  "applicant","appoint","assignment","authority","awareness","behalf",
  "civilization","commitment","convention","criticism","debate","democracy",
  "deposit","discrimination","discipline","enthusiasm","equality","expenditure",
  "expertise","exposure","institution","intellectual","internal","journal",
  "maximize","moral","nevertheless","obligation","occupation","outcome",
  "passive","precise","privilege","procedure","proceed","profession",
  "promotion","prosperity","quantity","realistic","reference","reform",
  "reluctant","remark","reputation","revenue","revolution","session",
  "statistics","tendency","tolerance","trait","venture","welfare","withdraw",
  // 环境 & 社会（低频）
  "biodiversity","conservation","contamination","deforestation","drought",
  "ecosystem","emission","fertile","fossil","habitat","harvest","hazard",
  "irrigation","marine","nuclear","organic","pollutant","renewable",
  "sustainable","vegetation","wildlife",
  // 城市 & 交通（低频）
  "commute","congestion","dense","household","inhabitant","infrastructure",
  "metropolitan","pedestrian","resident","settlement","spacious","suburb","tenant",
  // 工作 & 经济（低频）
  "commerce","consumption","corporation","enterprise","entrepreneur","inflation",
  "labor","manufacture","output","pension","recruit","retail","tariff",
  "unemployment","wage","workforce",
  // 教育（低频）
  "compulsory","curriculum","diploma","literacy","plagiarism","scholarship",
  "syllabus","thesis","tuition","tutor","undergraduate","vocational",
  // 健康（低频）
  "chronic","diagnosis","epidemic","hygiene","immune","infection","nutrition",
  "obesity","surgery","therapy","vaccine",
  // 技术（低频）
  "innovation","patent"
]);
WORDS.forEach(function(w){
  if(w.pack==='ielts1' && !w.level){
    w.level = IELTS1_LEVEL3.has(w.word) ? 3 : 2;
  }
});
